Repository AvaloniaUI/Avalonia, pull requests merged in 2019-09, with the labels that each got.

#2895 Animations subsystem perf fixes.
  src/Avalonia.Animation/Animatable.cs
Labels: perf

#2915 Perf set inheritance parent
  src/Avalonia.Base/AvaloniaObject.cs
  src/Avalonia.Base/AvaloniaPropertyRegistry.cs
Labels: dependent

#3010 Fix transitions since the last PR.
  src/Avalonia.Animation/Animatable.cs
Labels: regression
