Repository AvaloniaUI/Avalonia, pull requests merged in 2020-01, with the labels that each got.

#3464 Fix datagrid ascending multi-column sort
  Avalonia.sln
  nukebuild/Build.cs
  src/Avalonia.Controls.DataGrid/Collections/DataGridSortDescription.cs
  src/Avalonia.Controls.DataGrid/Properties/AssemblyInfo.cs
  tests/Avalonia.Controls.DataGrid.UnitTests/Avalonia.Controls.DataGrid.UnitTests.csproj
  tests/Avalonia.Controls.DataGrid.UnitTests/Collections/DataGridSortDescriptionTests.cs
Labels: backport

#3481 Respect background/border in ItemsControl.
  src/Avalonia.Themes.Default/ItemsControl.xaml
Labels: backport-candidate

#3480 Fix NRE in Menu
  src/Avalonia.Controls/Platform/DefaultMenuInteractionHandler.cs
  tests/Avalonia.Controls.UnitTests/Platform/DefaultMenuInteractionHandlerTests.cs
Labels: backport-candidate

#3346 Rename IStyleRoot to ILogicalRoot
  src/Avalonia.Controls/Application.cs
  src/Avalonia.Controls/Primitives/VisualLayerManager.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.Styling/LogicalTree/ILogicalRoot.cs
  src/Avalonia.Styling/LogicalTree/LogicalTreeAttachmentEventArgs.cs
  src/Avalonia.Styling/StyledElement.cs
  src/Avalonia.Styling/Styling/IGlobalStyles.cs
  src/Avalonia.Styling/Styling/IStyleRoot.cs
  tests/Avalonia.Controls.UnitTests/Presenters/ContentPresenterTests_Standalone.cs
  tests/Avalonia.Controls.UnitTests/Presenters/ItemsPresenterTests_Virtualization_Simple.cs
  tests/Avalonia.UnitTests/TestRoot.cs
  tests/Avalonia.UnitTests/TestTemplatedRoot.cs
Labels: dependent
