Repository AvaloniaUI/Avalonia, pull requests merged in 2020-06, with the labels that each got.

#4031 Implemented custom format support for clipboard
  native/Avalonia.Native/inc/avalonia-native.h
  native/Avalonia.Native/src/OSX/AvnString.h
  native/Avalonia.Native/src/OSX/AvnString.mm
  native/Avalonia.Native/src/OSX/clipboard.mm
  src/Android/Avalonia.Android/Platform/ClipboardImpl.cs
  src/Avalonia.DesignerSupport/Remote/Stubs.cs
  src/Avalonia.Input/Platform/IClipboard.cs
  src/Avalonia.Native/AvnString.cs
  src/Avalonia.Native/ClipboardImpl.cs
  src/Avalonia.X11/X11Atoms.cs
  src/Avalonia.X11/X11Clipboard.cs
  src/Avalonia.X11/XLib.cs
  src/Windows/Avalonia.Win32/ClipboardImpl.cs
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/iOS/Avalonia.iOS/Clipboard.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
Labels: backport-candidate

#4029 Hack-fix selecting nested nodes in TreeView.
  samples/ControlCatalog/Pages/TreeViewPage.xaml
  samples/ControlCatalog/ViewModels/TreeViewPageViewModel.cs
  src/Avalonia.Controls/IndexPath.cs
  src/Avalonia.Controls/IndexRange.cs
  src/Avalonia.Controls/SelectionModel.cs
  src/Avalonia.Controls/SelectionModelChangeSet.cs
  src/Avalonia.Controls/SelectionModelChildrenRequestedEventArgs.cs
  src/Avalonia.Controls/SelectionNode.cs
  src/Avalonia.Controls/TreeView.cs
  src/Avalonia.Controls/Utils/SelectionTreeHelper.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/MainViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/TreeNode.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/TreePageViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/TreePageView.xaml
  tests/Avalonia.Controls.UnitTests/IndexRangeTests.cs
  tests/Avalonia.Controls.UnitTests/SelectionModelTests.cs
  tests/Avalonia.Controls.UnitTests/TabControlTests.cs
  tests/Avalonia.Controls.UnitTests/TreeViewTests.cs
Labels: dependent

#4078 Try matching INPC properties before methods
  src/Avalonia.Base/Data/Core/Plugins/InpcPropertyAccessorPlugin.cs
  src/Avalonia.Base/Data/Core/PropertyAccessorNode.cs
  tests/Avalonia.Base.UnitTests/Data/Core/ExpressionObserverTests_Property.cs
  tests/Avalonia.Benchmarks/Data/AccessorTestObject.cs
  tests/Avalonia.Benchmarks/Data/PropertyAccessorBenchmarks.cs
  tests/Avalonia.Benchmarks/Data/PropertyAccessorPluginBenchmarks.cs
  tests/Avalonia.Markup.UnitTests/Parsers/ExpressionObserverBuilderTests_Property.cs
Labels: dependent, perf

#3970 Added additional positioning properties to Popup and ContextMenu.
  src/Avalonia.Controls/ContextMenu.cs
  src/Avalonia.Controls/Primitives/IPopupHost.cs
  src/Avalonia.Controls/Primitives/OverlayPopupHost.cs
  src/Avalonia.Controls/Primitives/Popup.cs
  src/Avalonia.Controls/Primitives/PopupPositioning/IPopupPositioner.cs
  src/Avalonia.Controls/Primitives/PopupPositioning/ManagedPopupPositioner.cs
  src/Avalonia.Controls/Primitives/PopupPositioning/ManagedPopupPositionerPopupImplHelper.cs
  src/Avalonia.Controls/Primitives/PopupRoot.cs
  src/Avalonia.Native/OsxManagedPopupPositionerPopupImplHelper.cs
Labels: backport-candidate

#4104 Remove duplicate code for MathUtilities
  src/Avalonia.Base/Properties/AssemblyInfo.cs
  src/Avalonia.Base/Utilities/MathUtilities.cs
  src/Avalonia.Controls.DataGrid/DataGrid.cs
  src/Avalonia.Controls.DataGrid/DataGridColumnHeader.cs
  src/Avalonia.Controls.DataGrid/DataGridColumns.cs
  src/Avalonia.Controls.DataGrid/DataGridLength.cs
  src/Avalonia.Controls.DataGrid/DataGridRow.cs
  src/Avalonia.Controls.DataGrid/DataGridRows.cs
  src/Avalonia.Controls.DataGrid/Primitives/DataGridCellsPresenter.cs
  src/Avalonia.Controls.DataGrid/Utils/DoubleUtil.cs
  tests/Avalonia.Base.UnitTests/Utilities/MathUtilitiesTests.cs
Labels: dependent

#4097 Restyle `ScrollViewer` in menus.
  src/Avalonia.Controls/Converters/MenuScrollingVisibilityConverter.cs
  src/Avalonia.Controls/ScrollViewer.cs
  src/Avalonia.Themes.Default/ContextMenu.xaml
  src/Avalonia.Themes.Default/MenuItem.xaml
  src/Avalonia.Themes.Default/ScrollViewer.xaml
Labels: backport-candidate

#4091 Itemsrepeater fixes and scroll anchoring
  samples/ControlCatalog/Pages/ItemsRepeaterPage.xaml
  samples/ControlCatalog/Pages/ItemsRepeaterPage.xaml.cs
  samples/ControlCatalog/ViewModels/ItemsRepeaterPageViewModel.cs
  src/Avalonia.Controls/IScrollAnchorProvider.cs
  src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
  src/Avalonia.Controls/Repeater/ItemsRepeater.cs
  src/Avalonia.Controls/Repeater/RepeaterLayoutContext.cs
  src/Avalonia.Controls/Repeater/ViewManager.cs
  src/Avalonia.Controls/Repeater/ViewportManager.cs
  src/Avalonia.Controls/Repeater/VirtualizationInfo.cs
  src/Avalonia.Controls/ScrollViewer.cs
  src/Avalonia.Layout/AttachedLayout.cs
  src/Avalonia.Layout/ElementManager.cs
  src/Avalonia.Layout/FlowLayoutAlgorithm.cs
  src/Avalonia.Layout/LayoutQueue.cs
  src/Avalonia.Layout/NonVirtualizingStackLayout.cs
  src/Avalonia.Layout/StackLayout.cs
  src/Avalonia.Layout/UniformGridLayout.cs
  tests/Avalonia.Controls.UnitTests/Presenters/ScrollContentPresenterTests.cs
  tests/Avalonia.Controls.UnitTests/Presenters/ScrollContentPresenterTests_ILogicalScrollable.cs
Labels: dependent

#4164 Disable render layers.
  src/Avalonia.Visuals/Rendering/SceneGraph/SceneBuilder.cs
  tests/Avalonia.Visuals.UnitTests/Rendering/DeferredRendererTests.cs
  tests/Avalonia.Visuals.UnitTests/Rendering/SceneGraph/SceneBuilderTests.cs
  tests/Avalonia.Visuals.UnitTests/Rendering/SceneGraph/SceneBuilderTests_Layers.cs
Labels: backport-candidate

#4093 .axaml file extension and msbuild metadata
  packages/Avalonia/Avalonia.csproj
  packages/Avalonia/AvaloniaBuildTasks.props
  packages/Avalonia/AvaloniaBuildTasks.targets
  packages/Avalonia/AvaloniaItemSchema.xaml
  src/Avalonia.Build.Tasks/GenerateAvaloniaResourcesTask.cs
  src/Avalonia.Build.Tasks/XamlCompilerTaskExecutor.cs
Labels: backport-candidate

#4191 Dispose the renderer before detaching visuals from the tree (perf)
  src/Avalonia.Controls/TopLevel.cs
Labels: backport-candidate
