Repository AvaloniaUI/Avalonia, pull requests merged in 2020-04, with the labels that each got.

#3712 [X11, FlyWM] Completely remove WM_TRANSIENT_FOR property
  src/Avalonia.X11/X11Window.cs
Labels: backport-candidate

#3711 Fixed InitialFileName for GTK-based file dialog
  samples/ControlCatalog/Pages/DialogsPage.xaml.cs
  src/Avalonia.X11/NativeDialogs/Gtk.cs
  src/Avalonia.X11/NativeDialogs/GtkNativeFileDialogs.cs
Labels: backport-candidate

#3713 Immediate rendering support for X11 platform via render loop
  src/Avalonia.X11/X11ImmediateRendererProxy.cs
  src/Avalonia.X11/X11Platform.cs
  src/Avalonia.X11/X11Window.cs
Labels: backport-candidate

#3693 Multibinding issue #3692 fixed
  src/Avalonia.Base/Data/Converters/FuncMultiValueConverter.cs
  tests/Avalonia.Base.UnitTests/AvaloniaObjectTests_MultiBinding.cs
Labels: backport-candidate

#3678 Fix XAML compiler handling of comma/or style selector.
  src/Markup/Avalonia.Markup.Xaml/XamlIl/CompilerExtensions/Transformers/AvaloniaXamlIlSelectorTransformer.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/StyleTests.cs
Labels: backport-candidate

#3783 [X11] Special handling for XI2 events when window is blocked by child dialog
  src/Avalonia.Input/Raw/RawPointerEventArgs.cs
  src/Avalonia.X11/X11Window.cs
  src/Avalonia.X11/XI2Manager.cs
Labels: backport-candidate, linux, x11

#3787 Fix Window/PopupRoot arrange.
  src/Avalonia.Controls/Primitives/PopupRoot.cs
  src/Avalonia.Controls/Window.cs
  src/Avalonia.Controls/WindowBase.cs
  tests/Avalonia.Controls.UnitTests/ContextMenuTests.cs
  tests/Avalonia.Controls.UnitTests/Primitives/PopupRootTests.cs
  tests/Avalonia.Controls.UnitTests/Primitives/PopupTests.cs
  tests/Avalonia.Controls.UnitTests/WindowTests.cs
  tests/Avalonia.Layout.UnitTests/FullLayoutTests.cs
  tests/Avalonia.UnitTests/MockWindowingPlatform.cs
Labels: backport-candidate

#3729 Implement ScrollViewer.ScrollChanged
  src/Avalonia.Controls/ScrollChangedEventArgs.cs
  src/Avalonia.Controls/ScrollViewer.cs
  tests/Avalonia.Controls.UnitTests/ScrollViewerTests.cs
Labels: dependent

#3773 [X11] Don't trigger Resized event on ConfigureEvent for popups
  src/Avalonia.X11/X11Window.cs
Labels: backport-candidate

#3819 macOS: Fix title not showing up in SelectFolderDialog, OpenFileDialog and SaveFileDialog
  native/Avalonia.Native/src/OSX/SystemDialogs.mm
Labels: backport-candidate

#3836 Fix KeyFrame's KeyTime conversion to Cue
  src/Avalonia.Animation/Animation.cs
  tests/Avalonia.Animation.UnitTests/AnimationIterationTests.cs
Labels: backport-candidate
