Repository AvaloniaUI/Avalonia, pull requests merged in 2021-07, with the labels that each got.

#6093 ScrollContentPresenter, fix order of operations, set Offset before setting Extent
  src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
Labels: backport-candidate

#6151 Fixes issue 6100
  src/Avalonia.Controls/ComboBox.cs
  tests/Avalonia.Controls.UnitTests/ComboBoxTests.cs
Labels: backport-candidate

#6187 Allow moving items in ItemsRepeater
  src/Avalonia.Layout/ElementManager.cs
Labels: backport-candidate

#6212 OSX: Fix initial keyboard input
  native/Avalonia.Native/src/OSX/window.mm
Labels: backport-candidate

#6133 Add Arc shape control 2: Electric Boogaloo
  src/Avalonia.Controls/Shapes/Arc.cs
Labels: backport-candidate

#6198 Validate parent/owner when showing windows.
  src/Avalonia.Controls/Window.cs
  tests/Avalonia.Controls.UnitTests/WindowTests.cs
Labels: backport-candidate

#6031 Solid color brush changes and compile time parsing
  src/Avalonia.Visuals/ApiCompatBaseline.txt
  src/Avalonia.Visuals/Media/Brush.cs
  src/Avalonia.Visuals/Media/Immutable/ImmutableSolidColorBrush.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlLanguageParseIntrinsics.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/DynamicResourceExtensionTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/ResourceIncludeTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/StaticResourceExtensionTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/BasicTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/StyleTests.cs
Labels: breaking-change, wont-backport

#5981 NumericUpDown control changes
  samples/ControlCatalog/Pages/NumericUpDownPage.xaml
  samples/ControlCatalog/Pages/NumericUpDownPage.xaml.cs
  src/Avalonia.Base/Utilities/MathUtilities.cs
  src/Avalonia.Controls/ApiCompatBaseline.txt
  src/Avalonia.Controls/NumericUpDown/NumericUpDown.cs
  src/Avalonia.Controls/NumericUpDown/NumericUpDownValueChangedEventArgs.cs
Labels: breaking-change

#6245 OSX - window state - keep field in sync.
  native/Avalonia.Native/src/OSX/window.mm
Labels: backport-candidate

#6244 Fix: Thumb should handle pointer capture loss
  src/Avalonia.Controls/Primitives/Thumb.cs
Labels: backport-candidate

#6246 Fix "." (empty) paths with compiled bindings.
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlBindingPathParser.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/CompiledBindingExtensionTests.cs
Labels: backport-candidate

#6251 Fix DataGrid column sorting with inherited interface property
  src/Avalonia.Controls.DataGrid/Utils/ReflectionHelper.cs
Labels: backport-candidate, bug

#6250 Fixes/osx flicker
  native/Avalonia.Native/src/OSX/window.mm
Labels: backport-candidate

#6258 Fix light dismiss overlay intercepting titlebar hit tests for OSX.
  src/Avalonia.Native/WindowImpl.cs
Labels: backport-candidate

#6213 Fixes/textbox crash when focused but not visible
  src/Avalonia.Controls/TextBox.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
Labels: backport-candidate

#6270 Disable text search by default.
  src/Avalonia.Controls/ComboBox.cs
  src/Avalonia.Controls/Primitives/SelectingItemsControl.cs
Labels: backport-candidate

#6275 [DataGrid] Invert ascending/descending arrows for Fluent Theme and match their behaviour with Simple Theme
  src/Avalonia.Controls.DataGrid/Themes/Fluent.xaml
Labels: backport-candidate

#6283 fixes(DataGrid): Fixes DataGridColumn IsVisible binding
  samples/ControlCatalog/Pages/DataGridPage.xaml
  src/Avalonia.Controls.DataGrid/DataGridColumn.cs
Labels: backport-candidate

#6174 OSX: Handle applicationShouldTerminate
  native/Avalonia.Native/src/OSX/app.mm
  native/Avalonia.Native/src/OSX/window.mm
  src/Avalonia.Controls/ApiCompatBaseline.txt
  src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs
  src/Avalonia.Controls/ApplicationLifetimes/IClassicDesktopStyleApplicationLifetime.cs
  src/Avalonia.Controls/Platform/IPlatformLifetimeEventsImpl.cs
  src/Avalonia.Native/AvaloniaNativeApplicationPlatform.cs
  src/Avalonia.Native/AvaloniaNativePlatform.cs
  src/Avalonia.Native/avn.idl
  tests/Avalonia.Controls.UnitTests/DesktopStyleApplicationLifetimeTests.cs
Labels: backport-candidate

#6285 Remove TextBox margin hack
  src/Avalonia.Themes.Fluent/Controls/TextBox.xaml
Labels: backport-candidate

#6183 Gradient animations
  samples/RenderDemo/Pages/AnimationsPage.xaml
  samples/RenderDemo/Pages/TransitionsPage.xaml
  src/Avalonia.Visuals/Animation/Animators/BaseBrushAnimator.cs
  src/Avalonia.Visuals/Animation/Animators/GradientBrushAnimator.cs
  src/Avalonia.Visuals/Animation/Animators/RelativePointAnimator.cs
  src/Avalonia.Visuals/Animation/Animators/SolidColorBrushAnimator.cs
  src/Avalonia.Visuals/Animation/Transitions/BrushTransition.cs
  src/Avalonia.Visuals/Animation/Transitions/RelativePointTransition.cs
  src/Avalonia.Visuals/Media/GradientBrush.cs
  src/Avalonia.Visuals/Media/SolidColorBrush.cs
  src/Avalonia.Visuals/RelativePoint.cs
Labels: backport-candidate

#6266 OSX: Fix showing window with no specified size.
  native/Avalonia.Native/src/OSX/window.mm
Labels: backport-candidate

#6313 Add ClipGeometry and OpacityMask properties to DrawingGroup
  src/Avalonia.Visuals/Media/DrawingGroup.cs
Labels: backport-candidate

#6188 OSX: Fix child window activation
  native/Avalonia.Native/src/OSX/window.h
  native/Avalonia.Native/src/OSX/window.mm
  src/Avalonia.Controls/ApiCompatBaseline.txt
  src/Avalonia.Controls/Platform/IWindowBaseImpl.cs
  src/Avalonia.Controls/Window.cs
  src/Avalonia.Controls/WindowBase.cs
  src/Avalonia.DesignerSupport/Remote/PreviewerWindowImpl.cs
  src/Avalonia.DesignerSupport/Remote/Stubs.cs
  src/Avalonia.Headless/HeadlessWindowImpl.cs
  src/Avalonia.Native/PopupImpl.cs
  src/Avalonia.Native/WindowImplBase.cs
  src/Avalonia.Native/avn.idl
  src/Avalonia.X11/X11Window.cs
  src/Windows/Avalonia.Win32/PopupImpl.cs
  src/Windows/Avalonia.Win32/Win32Platform.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
  tests/Avalonia.Controls.UnitTests/ContextMenuTests.cs
  tests/Avalonia.Controls.UnitTests/WindowBaseTests.cs
  tests/Avalonia.UnitTests/MockWindowingPlatform.cs
Labels: backport-candidate

#6052 Fix dialogs crashing on X11 when Title is set to null
  src/Avalonia.X11/X11Window.cs
Labels: backport-candidate

#6322 Properties of PointerEventArgs in TappedEventArgs
  src/Avalonia.Input/TappedEventArgs.cs
Labels: backport-candidate

#6254 Fix autosizing when DPI changed
  native/Avalonia.Native/src/OSX/window.h
  native/Avalonia.Native/src/OSX/window.mm
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
  src/Avalonia.Controls/ApiCompatBaseline.txt
  src/Avalonia.Controls/Embedding/Offscreen/OffscreenTopLevelImpl.cs
  src/Avalonia.Controls/Platform/ITopLevelImpl.cs
  src/Avalonia.Controls/Platform/IWindowImpl.cs
  src/Avalonia.Controls/Primitives/PopupRoot.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.Controls/Window.cs
  src/Avalonia.Controls/WindowBase.cs
  src/Avalonia.DesignerSupport/Remote/PreviewerWindowImpl.cs
  src/Avalonia.DesignerSupport/Remote/Stubs.cs
  src/Avalonia.Headless/HeadlessWindowImpl.cs
  src/Avalonia.Native/PopupImpl.cs
  src/Avalonia.Native/WindowImplBase.cs
  src/Avalonia.Native/avn.idl
  src/Avalonia.X11/X11Window.cs
  src/Linux/Avalonia.LinuxFramebuffer/FramebufferToplevelImpl.cs
  src/Windows/Avalonia.Win32.Interop/Wpf/WpfTopLevelImpl.cs
  src/Windows/Avalonia.Win32/PopupImpl.cs
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
  src/iOS/Avalonia.iOS/AvaloniaView.cs
  tests/Avalonia.Controls.UnitTests/TopLevelTests.cs
  tests/Avalonia.Controls.UnitTests/WindowTests.cs
  tests/Avalonia.UnitTests/MockWindowingPlatform.cs
Labels: backport-candidate
