Repository AvaloniaUI/Avalonia, pull requests merged in 2021-08, with the labels that each got.

#6340 Fix DataGrid wheel scroll calculation
  src/Avalonia.Controls.DataGrid/DataGrid.cs
Labels: backport-candidate

#6341 Win32 WindowImpl: Don't change z-order when Position is set
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: backport-candidate

#5996 Port tab navigation algorithm from WPF (including TabIndex support)
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.Input/Avalonia.Input.csproj
  src/Avalonia.Input/FocusManager.cs
  src/Avalonia.Input/ICustomKeyboardNavigation.cs
  src/Avalonia.Input/InputElement.cs
  src/Avalonia.Input/KeyboardNavigation.cs
  src/Avalonia.Input/KeyboardNavigationHandler.cs
  src/Avalonia.Input/KeyboardNavigationMode.cs
  src/Avalonia.Input/Navigation/TabNavigation.cs
  tests/Avalonia.Input.UnitTests/KeyboardNavigationTests_Custom.cs
  tests/Avalonia.Input.UnitTests/KeyboardNavigationTests_Tab.cs
  tests/Avalonia.UnitTests/TestRoot.cs
Labels: backport-candidate

#6351 Add comments about OSX,Linux, Windows platform options
  src/Avalonia.Native/AvaloniaNativePlatformExtensions.cs
  src/Avalonia.X11/X11Platform.cs
  src/Windows/Avalonia.Win32/Win32Platform.cs
Labels: backport-candidate

#6362 Respect CancellationToken in InternalPlatformThreadingInterface.RunLoop.
  src/Avalonia.Controls/Platform/InternalPlatformThreadingInterface.cs
Labels: backport-candidate

#6268 Fix existing and add missing osx-specific key shortcuts
  src/Avalonia.Native/AvaloniaNativePlatform.cs
Labels: osx, backport-candidate

#6191 DevTools: Support for inspecting Popup visual tree
  src/Avalonia.Controls/ContextMenu.cs
  src/Avalonia.Controls/Diagnostics/IPopupHostProvider.cs
  src/Avalonia.Controls/Diagnostics/ToolTipDiagnostics.cs
  src/Avalonia.Controls/Flyouts/FlyoutBase.cs
  src/Avalonia.Controls/Primitives/Popup.cs
  src/Avalonia.Controls/ToolTip.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/MainViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/TreeNode.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/VisualTreeNode.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/MainView.xaml
  src/Avalonia.Diagnostics/Diagnostics/Views/MainWindow.xaml.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/TreePageView.xaml
  src/Avalonia.Visuals/VisualTree/IVisualTreeHost.cs
Labels: backport-candidate, dev-tools

#6342 Improve datagrid scrolling
  samples/ControlCatalog/Pages/DataGridPage.xaml
  src/Avalonia.Controls.DataGrid/DataGrid.cs
  src/Avalonia.Controls.DataGrid/DataGridCell.cs
  src/Avalonia.Controls.DataGrid/Primitives/DataGridRowsPresenter.cs
  src/Avalonia.Controls.DataGrid/Themes/Default.xaml
  src/Avalonia.Controls.DataGrid/Themes/Fluent.xaml
Labels: backport-candidate

#6407 OSX: Fix a couple of minimized WindowState bugs
  native/Avalonia.Native/src/OSX/window.mm
Labels: backport-candidate

#6425 [OSX] [Native] fix tab shortcuts in NativeMenu
  native/Avalonia.Native/src/OSX/KeyTransform.mm
Labels: backport-candidate

#6373 Fix skia OpacityMask push and pop methods
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
Labels: backport-candidate

#6374 Enable antialiasing for PushGeometryClip
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
  src/Windows/Avalonia.Direct2D1/Media/DrawingContextImpl.cs
  tests/TestFiles/Skia/Controls/CustomRender/GeometryClip.expected.png
  tests/TestFiles/Skia/GeometryClipping/Geometry_Clip_Clips_Path.expected.png
Labels: backport-candidate

#6429 Check if TextBox.Text is null in AutoCompleteBox
  src/Avalonia.Controls/AutoCompleteBox.cs
Labels: backport-candidate

#6430 Add Not value converter to BoolConverters
  src/Avalonia.Base/Data/Converters/BoolConverters.cs
Labels: backport-candidate

#6242 Invalidating measure on TransformedBounds update
  src/Avalonia.Controls/Primitives/AdornerLayer.cs
Labels: backport-candidate

#6457 Don't display warning when WinUICompositorConnection succeeds.
  src/Windows/Avalonia.Win32/WinRT/Composition/WinUICompositorConnection.cs
Labels: backport-candidate

#6256 Fix TextLayout rendering with transform applied.
  src/Avalonia.Visuals/Media/TextFormatting/ShapedTextCharacters.cs
  tests/Avalonia.RenderTests/Media/TextFormatting/TextLayoutTests.cs
  tests/TestFiles/Direct2D1/Media/TextFormatting/TextLayout/TextLayout_Basic.expected.png
  tests/TestFiles/Direct2D1/Media/TextFormatting/TextLayout/TextLayout_Rotated.expected.png
  tests/TestFiles/Skia/Media/TextFormatting/TextLayout/TextLayout_Basic.expected.png
  tests/TestFiles/Skia/Media/TextFormatting/TextLayout/TextLayout_Rotated.expected.png
Labels: bug, backport-candidate

#6226 ContentPresenter should create child without content, if template was set
  samples/ControlCatalog/Pages/ComboBoxPage.xaml
  src/Avalonia.Base/Utilities/TypeUtilities.cs
  src/Avalonia.Controls/Presenters/ContentPresenter.cs
  src/Avalonia.Controls/Templates/FuncDataTemplate`1.cs
  src/Markup/Avalonia.Markup.Xaml/Templates/DataTemplate.cs
  tests/Avalonia.Controls.UnitTests/Presenters/ContentPresenterTests_Standalone.cs
Labels: bug, backport-candidate

#6392 [Menu] [Interaction] Allow end user to change menu show delay globally
  src/Avalonia.Controls/Platform/DefaultMenuInteractionHandler.cs
Labels: API, backport-candidate

#6404 Close popup if combobox is not visible
  src/Avalonia.Controls/ComboBox.cs
  src/Avalonia.Controls/Mixins/DisposableMixin.cs
  src/Avalonia.Controls/Primitives/Popup.cs
Labels: bug, backport-candidate

#6499 fixes(Doc): fixes AvaloniaList XML Comments
  src/Avalonia.Base/Collections/AvaloniaList.cs
Labels: backport-candidate

#6492 Add text box clipboard events
  src/Avalonia.Controls/TextBox.cs
Labels: API, backport-candidate

#6491 Fix alt down shortcuts and allow alt down handling for end users
  src/Avalonia.Input/AccessKeyHandler.cs
Labels: bug, backport-candidate
