Repository AvaloniaUI/Avalonia, pull requests merged in 2021-12, with the labels that each got.

#7071 Fix issues with positioning of non-overlay popups
  src/Avalonia.Controls/Primitives/Popup.cs
  tests/Avalonia.Controls.UnitTests/Primitives/PopupTests.cs
  tests/Avalonia.UnitTests/MockWindowingPlatform.cs
Labels: bug, backport-candidate

#7029 Avalonia.Web (wasm)
  .gitignore
  Avalonia.sln
  NuGet.Config
  build/ApiDiff.props
  build/HarfBuzzSharp.props
  build/SkiaSharp.props
  samples/ControlCatalog.Web/App.razor
  samples/ControlCatalog.Web/App.razor.cs
  samples/ControlCatalog.Web/ControlCatalog.Web.csproj
  samples/ControlCatalog.Web/LinkerConfig.xml
  samples/ControlCatalog.Web/Pages/Index.razor
  samples/ControlCatalog.Web/Program.cs
  samples/ControlCatalog.Web/Properties/launchSettings.json
  samples/ControlCatalog.Web/Shared/MainLayout.razor
  samples/ControlCatalog.Web/Shared/MainLayout.razor.css
  samples/ControlCatalog.Web/_Imports.razor
  samples/ControlCatalog.Web/wwwroot/css/app.css
  samples/ControlCatalog.Web/wwwroot/favicon.ico
  samples/ControlCatalog.Web/wwwroot/index.html
  samples/ControlCatalog.Web/wwwroot/js/app.js
  src/Skia/Avalonia.Skia/Avalonia.Skia.csproj
  src/Skia/Avalonia.Skia/SKTypefaceCollection.cs
  src/Skia/Avalonia.Skia/SKTypefaceCollectionCache.cs
  src/Web/Avalonia.Web.Blazor/Assets/NotoMono-Regular.ttf
  src/Web/Avalonia.Web.Blazor/Assets/NotoSans-Italic.ttf
  src/Web/Avalonia.Web.Blazor/Avalonia.Web.Blazor.csproj
  src/Web/Avalonia.Web.Blazor/Avalonia.Web.Blazor.targets
  src/Web/Avalonia.Web.Blazor/AvaloniaBlazorAppBuilder.cs
  src/Web/Avalonia.Web.Blazor/AvaloniaView.razor
  src/Web/Avalonia.Web.Blazor/AvaloniaView.razor.cs
  src/Web/Avalonia.Web.Blazor/BlazorRuntimePlatform.cs
  src/Web/Avalonia.Web.Blazor/BlazorSingleViewLifetime.cs
  src/Web/Avalonia.Web.Blazor/BlazorSkiaGpu.cs
  src/Web/Avalonia.Web.Blazor/BlazorSkiaGpuRenderSession.cs
  src/Web/Avalonia.Web.Blazor/BlazorSkiaGpuRenderTarget.cs
  src/Web/Avalonia.Web.Blazor/BlazorSkiaSurface.cs
  src/Web/Avalonia.Web.Blazor/CustomFontManagerImpl.cs
  src/Web/Avalonia.Web.Blazor/Interop/ActionHelper.cs
  src/Web/Avalonia.Web.Blazor/Interop/DpiWatcherInterop.cs
  src/Web/Avalonia.Web.Blazor/Interop/FloatFloatActionHelper.cs
  src/Web/Avalonia.Web.Blazor/Interop/InputHelperInterop.cs
  src/Web/Avalonia.Web.Blazor/Interop/JSModuleInterop.cs
  src/Web/Avalonia.Web.Blazor/Interop/SKHtmlCanvasInterop.cs
  src/Web/Avalonia.Web.Blazor/Interop/SizeWatcherInterop.cs
  src/Web/Avalonia.Web.Blazor/Interop/Typescript/DpiWatcher.ts
  src/Web/Avalonia.Web.Blazor/Interop/Typescript/InputHelper.ts
  src/Web/Avalonia.Web.Blazor/Interop/Typescript/SKHtmlCanvas.ts
  src/Web/Avalonia.Web.Blazor/Interop/Typescript/SizeWatcher.ts
  src/Web/Avalonia.Web.Blazor/Interop/Typescript/types/dotnet/extras.d.ts
  src/Web/Avalonia.Web.Blazor/Interop/Typescript/types/dotnet/index.d.ts
  src/Web/Avalonia.Web.Blazor/Interop/Typescript/types/emscripten/index.d.ts
  src/Web/Avalonia.Web.Blazor/Keycodes.cs
  src/Web/Avalonia.Web.Blazor/ManualTriggerRenderTimer.cs
  src/Web/Avalonia.Web.Blazor/RazorViewTopLevelImpl.cs
  src/Web/Avalonia.Web.Blazor/WinStubs.cs
  src/Web/Avalonia.Web.Blazor/WindowingPlatform.cs
  src/Web/Avalonia.Web.Blazor/_Imports.razor
  src/Web/Avalonia.Web.Blazor/tsconfig.json
Labels: backport-candidate

#7015 OSX do not enforce DND copy effect
  native/Avalonia.Native/src/OSX/dnd.mm
  samples/ControlCatalog/Pages/DragAndDropPage.xaml
  samples/ControlCatalog/Pages/DragAndDropPage.xaml.cs
Labels: backport-candidate

#6854 type of the TreeView's items can be customized
  src/Avalonia.Controls/TreeView.cs
  src/Avalonia.Controls/TreeViewItem.cs
  tests/Avalonia.Controls.UnitTests/TreeViewTests.cs
Labels: enhancement, backport-candidate

#7044 Handle TabStopps
  src/Skia/Avalonia.Skia/FormattedTextImpl.cs
Labels: enhancement, skia, backport-candidate

#6836 Border StrokeDashArray
  src/Avalonia.Controls/Border.cs
  src/Avalonia.Controls/Utils/BorderRenderHelper.cs
Labels: API, api-review-required

#7028 Use MicroCOM for Win32 dialogs implementation + minor fixes
  samples/ControlCatalog/Pages/DialogsPage.xaml
  samples/ControlCatalog/Pages/DialogsPage.xaml.cs
  src/Avalonia.Controls/Platform/ISystemDialogImpl.cs
  src/Windows/Avalonia.Win32/Avalonia.Win32.csproj
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/Windows/Avalonia.Win32/SystemDialogImpl.cs
  src/Windows/Avalonia.Win32/Win32Com/win32.idl
  src/tools/MicroComGenerator/ParseException.cs
Labels: backport-candidate

#6860 DataGridColumn - fix LayoutRoundedWidth with DPI scaling applied
  src/Avalonia.Controls.DataGrid/DataGridColumn.cs
Labels: bug, datagrid, backport-candidate

#7094 fix: Make DataGridColumn.Header and .HeaderTemplate a DirectProperty
  src/Avalonia.Controls.DataGrid/DataGridColumn.cs
Labels: API, backport-candidate

#7111 [Win32] Use WS_EX_LAYERED style for native control holders with winui composition
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/Windows/Avalonia.Win32/Win32NativeControlHost.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: backport-candidate

#7110 [OSX] bring window to front when Activate() is called.
  native/Avalonia.Native/src/OSX/window.mm
Labels: bug, osx, backport-candidate

#7112 Don't forget to add SplitView.Pane to the logical tree
  src/Avalonia.Controls/SplitView.cs
Labels: bug, backport-candidate

#6909 [OSX] Refactor Native App Menu. Move default menu initialization code from ObjC to C#.
  native/Avalonia.Native/src/OSX/app.mm
  native/Avalonia.Native/src/OSX/common.h
  native/Avalonia.Native/src/OSX/main.mm
  native/Avalonia.Native/src/OSX/menu.mm
  src/Avalonia.Controls/Platform/INativeApplicationCommands.cs
  src/Avalonia.Native/AvaloniaNativeMenuExporter.cs
  src/Avalonia.Native/AvaloniaNativePlatform.cs
  src/Avalonia.Native/IAvnMenuItem.cs
  src/Avalonia.Native/MacOSNativeMenuCommands.cs
  src/Avalonia.Native/avn.idl
Labels: backport-candidate

#6438 [Menu] [Performance] Improve Menu item can execute logic. Make it work like in WPF
  src/Avalonia.Controls/MenuItem.cs
  src/Avalonia.Controls/Platform/DefaultMenuInteractionHandler.cs
  tests/Avalonia.Controls.UnitTests/MenuItemTests.cs
Labels: bug, perf

#7007 Windows IME
  samples/ControlCatalog/Pages/TextBoxPage.xaml
  src/Avalonia.Controls/TextBox.cs
  src/Avalonia.Controls/TextBoxTextInputMethodClient.cs
  src/Avalonia.Input/InputMethod.cs
  src/Avalonia.Input/TextInput/InputMethodManager.cs
  src/Windows/Avalonia.Win32/Input/Imm32CaretManager.cs
  src/Windows/Avalonia.Win32/Input/Imm32InputMethod.cs
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: enhancement, backport-candidate

#7138 fix incorrect extension of props file for Avalonia.Web.Blazor
  src/Web/Avalonia.Web.Blazor/Avalonia.Web.Blazor.props
Labels: backport-candidate

#7089 Introduce FontManagerOptions
  src/Avalonia.Visuals/Media/FontFallback.cs
  src/Avalonia.Visuals/Media/FontManager.cs
  src/Avalonia.Visuals/Media/FontManagerOptions.cs
  src/Avalonia.Visuals/Media/UnicodeRange.cs
  src/Web/Avalonia.Web.Blazor/Assets/NotoMono-Regular.ttf
  src/Web/Avalonia.Web.Blazor/Assets/NotoSans-Italic.ttf
  src/Web/Avalonia.Web.Blazor/Avalonia.Web.Blazor.csproj
  src/Web/Avalonia.Web.Blazor/BlazorSingleViewLifetime.cs
  src/Web/Avalonia.Web.Blazor/CustomFontManagerImpl.cs
  tests/Avalonia.UnitTests/MockGlyphTypeface.cs
  tests/Avalonia.Visuals.UnitTests/Media/FontManagerTests.cs
  tests/Avalonia.Visuals.UnitTests/Media/UnicodeRangeSegmentTests.cs
  tests/Avalonia.Visuals.UnitTests/Media/UnicodeRangeTests.cs
Labels: enhancement, backport-candidate

#7122 Multitarget net6.0 and netstandard2.0.
  build/ApiDiff.props
  build/MicroCom.targets
  packages/Avalonia/Avalonia.csproj
  src/Avalonia.Animation/Avalonia.Animation.csproj
  src/Avalonia.Base/Avalonia.Base.csproj
  src/Avalonia.Build.Tasks/Avalonia.Build.Tasks.csproj
  src/Avalonia.Build.Tasks/SpanCompat.cs
  src/Avalonia.Controls.DataGrid/Avalonia.Controls.DataGrid.csproj
  src/Avalonia.Controls/Avalonia.Controls.csproj
  src/Avalonia.DesignerSupport/Avalonia.DesignerSupport.csproj
  src/Avalonia.Desktop/Avalonia.Desktop.csproj
  src/Avalonia.DesktopRuntime/Avalonia.DesktopRuntime.csproj
  src/Avalonia.Diagnostics/Avalonia.Diagnostics.csproj
  src/Avalonia.Dialogs/Avalonia.Dialogs.csproj
  src/Avalonia.FreeDesktop/Avalonia.FreeDesktop.csproj
  src/Avalonia.Headless.Vnc/Avalonia.Headless.Vnc.csproj
  src/Avalonia.Headless/Avalonia.Headless.csproj
  src/Avalonia.Input/Avalonia.Input.csproj
  src/Avalonia.Interactivity/Avalonia.Interactivity.csproj
  src/Avalonia.Layout/Avalonia.Layout.csproj
  src/Avalonia.Native/Avalonia.Native.csproj
  src/Avalonia.OpenGL/Avalonia.OpenGL.csproj
  src/Avalonia.ReactiveUI/Avalonia.ReactiveUI.csproj
  src/Avalonia.Remote.Protocol/Avalonia.Remote.Protocol.csproj
  src/Avalonia.Styling/Avalonia.Styling.csproj
  src/Avalonia.Themes.Default/Avalonia.Themes.Default.csproj
  src/Avalonia.Themes.Fluent/Avalonia.Themes.Fluent.csproj
  src/Avalonia.Visuals/Avalonia.Visuals.csproj
  src/Avalonia.X11/Avalonia.X11.csproj
  src/Linux/Avalonia.LinuxFramebuffer/Avalonia.LinuxFramebuffer.csproj
  src/Markup/Avalonia.Markup.Xaml.Loader/Avalonia.Markup.Xaml.Loader.csproj
  src/Markup/Avalonia.Markup.Xaml/Avalonia.Markup.Xaml.csproj
  src/Markup/Avalonia.Markup/Avalonia.Markup.csproj
  src/Markup/Avalonia.Markup/Markup/Data/DelayedBinding.cs
  src/Markup/Avalonia.Markup/Markup/Parsers/Nodes/StringIndexerNode.cs
  src/Skia/Avalonia.Skia/Avalonia.Skia.csproj
  src/Windows/Avalonia.Direct2D1/Avalonia.Direct2D1.csproj
  src/Windows/Avalonia.Win32/Avalonia.Win32.csproj
  src/Windows/Avalonia.Win32/WinRT/NativeWinRTMethods.cs
Labels: breaking-change

#7163 [X11] Dispose transparency helper
  src/Avalonia.X11/X11Window.cs
Labels: backport-candidate

#7183 Do not copy UWP behavior with ListBoxItem horizontal alignment
  src/Avalonia.Themes.Fluent/Controls/ListBoxItem.xaml
Labels: breaking-change

#7187 osx: Fixes red flicker on Catalina when resizing
  native/Avalonia.Native/src/OSX/window.mm
Labels: backport-candidate

#7031 Add support for drawing ellipses directly via DrawingContext
  samples/ControlCatalog/Pages/PointersPage.cs
  src/Avalonia.Headless/HeadlessPlatformRenderInterface.cs
  src/Avalonia.Visuals/ApiCompatBaseline.txt
  src/Avalonia.Visuals/Media/DrawingContext.cs
  src/Avalonia.Visuals/Platform/IDrawingContextImpl.cs
  src/Avalonia.Visuals/Rendering/SceneGraph/DeferredDrawingContextImpl.cs
  src/Avalonia.Visuals/Rendering/SceneGraph/EllipseNode.cs
  src/Avalonia.Visuals/Rendering/SceneGraph/RectangleNode.cs
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
  src/Windows/Avalonia.Direct2D1/Media/DrawingContextImpl.cs
  tests/Avalonia.Benchmarks/NullDrawingContextImpl.cs
  tests/Avalonia.Visuals.UnitTests/Rendering/SceneGraph/EllipseNodeTests.cs
Labels: backport-candidate

#7201 Support RelativeSource-based bindings without requiring an x:DataType property.
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlBindingPathTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlDataContextTypeTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/XamlIlBindingPathHelper.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/CompiledBindingExtensionTests.cs
Labels: xaml-compiler

#7219 Use pointer position relative to the scroll gesture recognizer target
  src/Avalonia.Input/GestureRecognizers/ScrollGestureRecognizer.cs
Labels: backport-candidate

#7240 Added nullable annotations to Avalonia.Styling.
  src/Avalonia.Styling/Avalonia.Styling.csproj
  src/Avalonia.Styling/Controls/ChildNameScope.cs
  src/Avalonia.Styling/Controls/INameScope.cs
  src/Avalonia.Styling/Controls/NameScope.cs
  src/Avalonia.Styling/Controls/NameScopeExtensions.cs
  src/Avalonia.Styling/Controls/NameScopeLocator.cs
  src/Avalonia.Styling/Controls/PseudoClassesExtensions.cs
  src/Avalonia.Styling/Controls/ResourceDictionary.cs
  src/Avalonia.Styling/Controls/ResourceNodeExtensions.cs
  src/Avalonia.Styling/INamed.cs
  src/Avalonia.Styling/LogicalTree/ControlLocator.cs
  src/Avalonia.Styling/LogicalTree/ILogical.cs
  src/Avalonia.Styling/LogicalTree/LogicalExtensions.cs
  src/Avalonia.Styling/LogicalTree/LogicalTreeAttachmentEventArgs.cs
  src/Avalonia.Styling/StyledElement.cs
  src/Avalonia.Styling/Styling/Activators/NthChildActivator.cs
  src/Avalonia.Styling/Styling/Activators/StyleClassActivator.cs
  src/Avalonia.Styling/Styling/ChildSelector.cs
  src/Avalonia.Styling/Styling/OrSelector.cs
  src/Avalonia.Styling/Styling/PropertyEqualsSelector.cs
  src/Avalonia.Styling/Styling/Selectors.cs
  src/Avalonia.Styling/Styling/Styles.cs
  src/Avalonia.Styling/Styling/TemplateSelector.cs
  src/Avalonia.Visuals/Visual.cs
  src/Markup/Avalonia.Markup/Markup/Parsers/SelectorParser.cs
Labels: backport-candidate

#7213 Fix DoubleTapped on touch
  src/Avalonia.Input/Gestures.cs
  src/Avalonia.Input/PointerEventArgs.cs
  src/Avalonia.Input/TouchDevice.cs
  tests/Avalonia.Input.UnitTests/TouchDeviceTests.cs
Labels: bug, enhancement, backport-candidate

#7248 Add a DataType property on CompiledBindingExtension to enable specifying the start type explicitly on a binding.
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlBindingPathTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlDataContextTypeTransformer.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindingExtension.cs
Labels: xaml-compiler

#7251 Stopgap measure to fix #7245
  src/Avalonia.X11/X11Window.cs
Labels: backport-candidate

#7243 Fix touch device tests
  src/Avalonia.Input/TouchDevice.cs
  tests/Avalonia.Input.UnitTests/TouchDeviceTests.cs
Labels: bug, backport-candidate

#7256 Fast Fluent theme switching
  samples/ControlCatalog/App.xaml.cs
  samples/ControlCatalog/MainView.xaml.cs
  src/Avalonia.Themes.Fluent/FluentTheme.cs
Labels: enhancement, backport-candidate

#6280 feat(DevTools): Allow to display the type of property in ControlDettails
  src/Avalonia.Diagnostics/Diagnostics/Converters/GetTypeNameConverter.cs
  src/Avalonia.Diagnostics/Diagnostics/TypeExtesnions.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/AvaloniaPropertyViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ClrPropertyViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ControlDetailsViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/MainViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/PropertyViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/ControlDetailsView.xaml
  src/Avalonia.Diagnostics/Diagnostics/Views/MainView.xaml
Labels: enhancement, dev-tools

#7280 TextBox selection with shift key and left click
  src/Avalonia.Controls/TextBox.cs
Labels: enhancement, backport-candidate

#6527 Features Dispatcher.Post<T>(Action<T>, T arg, DispatcherPriority priority = DispatcherPriority.Normal)
  src/Avalonia.Base/ApiCompatBaseline.txt
  src/Avalonia.Base/Threading/Dispatcher.cs
  src/Avalonia.Base/Threading/IDispatcher.cs
  src/Avalonia.Base/Threading/JobRunner.cs
  tests/Avalonia.UnitTests/ImmediateDispatcher.cs
Labels: enhancement, breaking-change

#7274 Add properties to IPlatformSettings to define double-click Size\Time for Touch input.
  src/Android/Avalonia.Android/AndroidPlatform.cs
  src/Avalonia.DesignerSupport/Remote/PreviewerWindowingPlatform.cs
  src/Avalonia.Headless/HeadlessPlatformStubs.cs
  src/Avalonia.Input/TouchDevice.cs
  src/Avalonia.Native/AvaloniaNativePlatform.cs
  src/Avalonia.Visuals/ApiCompatBaseline.txt
  src/Avalonia.Visuals/Platform/IPlatformSettings.cs
  src/Avalonia.X11/Stubs.cs
  src/Avalonia.X11/X11Platform.cs
  src/Linux/Avalonia.LinuxFramebuffer/Stubs.cs
  src/Web/Avalonia.Web.Blazor/WindowingPlatform.cs
  src/Windows/Avalonia.Win32/Win32Platform.cs
  src/iOS/Avalonia.iOS/Platform.cs
  tests/Avalonia.Input.UnitTests/TouchDeviceTests.cs
Labels: breaking-change, wont-backport

#6769 feat(DevTools): Allow to Show/Hide implemented interfaces on Control Details
  src/Avalonia.Diagnostics/Diagnostics/DevToolsOptions.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ControlDetailsViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/MainViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/TreePageViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/MainView.xaml
Labels: enhancement, backport-candidate, dev-tools
