Repository AvaloniaUI/Avalonia, pull requests merged in 2021-09, with the labels that each got.

#6536 Fix AutoCompleteBox NRE
  src/Avalonia.Controls/AutoCompleteBox.cs
  tests/Avalonia.Controls.UnitTests/AutoCompleteBoxTests.cs
Labels: bug, backport-candidate

#6484 [OSX] Fix middle click
  native/Avalonia.Native/src/OSX/window.mm
Labels: bug, backport-candidate

#6464 Update AvaloniaSynchronizationContext to don't wrap exceptions
  src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs
Labels: bug, backport-candidate

#6533 Compiler intrinsic based type nullability check
  src/Avalonia.Base/Data/Converters/FuncValueConverter.cs
  src/Avalonia.Base/Utilities/TypeUtilities.cs
Labels: backport-candidate

#6555 win32 - dont loose window state when hide and show are called program…
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: backport-candidate

#6453 Implement MaskedTextBox
  samples/ControlCatalog/Pages/TextBoxPage.xaml
  src/Avalonia.Controls/MaskedTextBox.cs
  tests/Avalonia.Controls.UnitTests/MaskedTextBoxTests.cs
Labels: enhancement, backport-candidate, api-review-required

#6524 Revert "ScrollContentPresenter, fix order of operations, set Offset before setting Extent"
  src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
Labels: bug, backport-candidate

#6566 CompiledBinding correctly locates IDataContextProvider as anchor.
  src/Markup/Avalonia.Markup.Xaml/Extensions.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindingExtension.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/ReflectionBindingExtension.cs
Labels: backport-candidate

#6570 fixes(DataGrid): Issue #6567 New line in Editable DataGrid, Not editable
  src/Avalonia.Controls.DataGrid/DataGridDataConnection.cs
Labels: bug, datagrid, backport-candidate

#6507 Don't log $parent binding errors when control detached from logical tree
  src/Avalonia.Visuals/Visual.cs
  tests/Avalonia.Base.UnitTests/Avalonia.Base.UnitTests.csproj
  tests/Avalonia.Base.UnitTests/Logging/LoggingTests.cs
Labels: bug, backport-candidate

#6394 Fix Datagrid right click selection
  src/Avalonia.Controls.DataGrid/DataGrid.cs
  src/Avalonia.Controls.DataGrid/DataGridCell.cs
  src/Avalonia.Controls.DataGrid/DataGridRowGroupHeader.cs
  src/Avalonia.Controls.DataGrid/DataGridRowHeader.cs
Labels: enhancement

#5638 Fix DataGridTemplateColumn Recycled Issue
  src/Avalonia.Controls.DataGrid/DataGridRow.cs
Labels: bug, datagrid, backport-candidate

#6575 Allow popups to move using horizontal or vertical offsets like in WPF
  src/Avalonia.Controls/Primitives/Popup.cs
Labels: backport-candidate

#6572 Set MenuItem icon presenter size from style
  src/Avalonia.Themes.Fluent/Controls/MenuItem.xaml
Labels: backport-candidate

#6522 Revert "Fixed gradient brush target rectangles."
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
  src/Skia/Avalonia.Skia/FormattedTextImpl.cs
  src/Windows/Avalonia.Direct2D1/Media/AvaloniaTextRenderer.cs
  src/Windows/Avalonia.Direct2D1/Media/DrawingContextImpl.cs
  src/Windows/Avalonia.Direct2D1/Media/LinearGradientBrushImpl.cs
  src/Windows/Avalonia.Direct2D1/Media/RadialGradientBrushImpl.cs
  tests/Avalonia.RenderTests/Media/ConicGradientBrushTests.cs
  tests/Avalonia.RenderTests/Media/LinearGradientBrushTests.cs
  tests/Avalonia.RenderTests/Media/RadialGradientBrushTests.cs
Labels: regression, backport-candidate

#6604 [X11] Fixed potential freezes/segfaults on window close
  src/Avalonia.Visuals/Rendering/DeferredRenderer.cs
  src/Avalonia.X11/X11Window.cs
Labels: bug, backport-candidate, x11

#6569 Fix avalonia resource generation on resource deletion
  packages/Avalonia/AvaloniaBuildTasks.targets
Labels: bug, xaml, backport-candidate

#6619 ProgressBar missed TemplateBinding.CornerRadius
  src/Avalonia.Themes.Fluent/Controls/ProgressBar.xaml
Labels: backport-candidate

#6620 NotificationCard missed TemplateBinding.CornerRadius
  src/Avalonia.Themes.Fluent/Controls/NotificationCard.xaml
Labels: backport-candidate

#6597 Win32: Fix handling of subsequent keypress after Alt/F10
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
Labels: bug, windows, backport-candidate

#6616 Fix opening submenu popup for menus without subitems
  src/Avalonia.Controls/Platform/DefaultMenuInteractionHandler.cs
Labels: backport-candidate

#6581 Fixes PathMarkupParser flag parsing when no separator is used
  src/Avalonia.Visuals/Media/PathMarkupParser.cs
  tests/Avalonia.Visuals.UnitTests/Media/PathMarkupParserTests.cs
Labels: backport-candidate

#6576 Add GeometryGroup and CombinedGeometry
  src/Avalonia.Headless/HeadlessPlatformRenderInterface.cs
  src/Avalonia.Visuals/ApiCompatBaseline.txt
  src/Avalonia.Visuals/Media/CombinedGeometry.cs
  src/Avalonia.Visuals/Media/GeometryCollection.cs
  src/Avalonia.Visuals/Media/GeometryGroup.cs
  src/Avalonia.Visuals/Media/RotateTransform.cs
  src/Avalonia.Visuals/Platform/IPlatformRenderInterface.cs
  src/Skia/Avalonia.Skia/CombinedGeometryImpl.cs
  src/Skia/Avalonia.Skia/GeometryGroupImpl.cs
  src/Skia/Avalonia.Skia/PlatformRenderInterface.cs
  src/Windows/Avalonia.Direct2D1/Direct2D1Platform.cs
  src/Windows/Avalonia.Direct2D1/Media/CombinedGeometryImpl.cs
  src/Windows/Avalonia.Direct2D1/Media/GeometryGroupImpl.cs
  tests/Avalonia.Benchmarks/NullRenderingPlatform.cs
  tests/Avalonia.RenderTests/Media/CombinedGeometryTests.cs
  tests/Avalonia.RenderTests/Media/GeometryGroupTests.cs
  tests/Avalonia.UnitTests/MockPlatformRenderInterface.cs
  tests/Avalonia.Visuals.UnitTests/Media/GeometryGroupTests.cs
  tests/Avalonia.Visuals.UnitTests/VisualTree/MockRenderInterface.cs
  tests/TestFiles/Direct2D1/Media/CombinedGeometry/Geometry1_Transform.expected.png
  tests/TestFiles/Direct2D1/Media/CombinedGeometry/GeometryCombineMode_Exclude.expected.png
  tests/TestFiles/Direct2D1/Media/CombinedGeometry/GeometryCombineMode_Intersect.expected.png
  tests/TestFiles/Direct2D1/Media/CombinedGeometry/GeometryCombineMode_Union.expected.png
  tests/TestFiles/Direct2D1/Media/CombinedGeometry/GeometryCombineMode_Xor.expected.png
  tests/TestFiles/Direct2D1/Media/GeometryGroup/Child_Transform.expected.png
  tests/TestFiles/Direct2D1/Media/GeometryGroup/FillRule_Stroke_EvenOdd.expected.png
  tests/TestFiles/Direct2D1/Media/GeometryGroup/FillRule_Stroke_NonZero.expected.png
  tests/TestFiles/Skia/Media/CombinedGeometry/Geometry1_Transform.expected.png
  tests/TestFiles/Skia/Media/CombinedGeometry/GeometryCombineMode_Exclude.expected.png
  tests/TestFiles/Skia/Media/CombinedGeometry/GeometryCombineMode_Intersect.expected.png
  tests/TestFiles/Skia/Media/CombinedGeometry/GeometryCombineMode_Union.expected.png
  tests/TestFiles/Skia/Media/CombinedGeometry/GeometryCombineMode_Xor.expected.png
  tests/TestFiles/Skia/Media/GeometryGroup/Child_Transform.expected.png
  tests/TestFiles/Skia/Media/GeometryGroup/FillRule_Stroke_EvenOdd.expected.png
  tests/TestFiles/Skia/Media/GeometryGroup/FillRule_Stroke_NonZero.expected.png
Labels: enhancement, backport-candidate

#6639 Fix Expander HeaderTemplate for Simple Theme
  src/Avalonia.Themes.Default/Expander.xaml
Labels: bug, backport-candidate

#6638 FlyoutBase create presenter before calling Opening event
  src/Avalonia.Controls/Flyouts/FlyoutBase.cs
Labels: backport-candidate

#6652 Add a few customization points to Linux Framebuffer backend.
  src/Linux/Avalonia.LinuxFramebuffer/FramebufferToplevelImpl.cs
  src/Linux/Avalonia.LinuxFramebuffer/LinuxFramebufferPlatform.cs
  src/Linux/Avalonia.LinuxFramebuffer/LinuxFramebufferPlatformOptions.cs
Labels: enhancement, backport-candidate

#6646 Used EqualityComparer<T>.Default to check values for equality
  src/Avalonia.Visuals/Media/FormattedText.cs
Labels: backport-candidate

#6632 Fix opening disabled menu with accelerator key
  src/Avalonia.Controls/Platform/DefaultMenuInteractionHandler.cs
Labels: bug, backport-candidate

#6657 Fix ICustomDrawOperation HitTest coordinate space.
  src/Avalonia.Visuals/Rendering/SceneGraph/CustomDrawOperation.cs
Labels: backport-candidate

#6485 Tweaks to ItemsSourceView
  src/Avalonia.Controls/ItemsSourceView.cs
  tests/Avalonia.Controls.UnitTests/ItemsSourceViewTests.cs
Labels: backport-candidate
