Repository AvaloniaUI/Avalonia, pull requests merged in 2021-05, with the labels that each got.

#4615 Lookless file dialogs
  src/Avalonia.Dialogs/Avalonia.Dialogs.csproj
  src/Avalonia.Dialogs/ChildFitter.cs
  src/Avalonia.Dialogs/FileSizeStringConverter.cs
  src/Avalonia.Dialogs/ManagedFileChooser.cs
  src/Avalonia.Dialogs/ManagedFileChooser.xaml
  src/Avalonia.Dialogs/ResourceSelectorConverter.cs
  src/Avalonia.Themes.Default/Avalonia.Themes.Default.csproj
  src/Avalonia.Themes.Default/DefaultTheme.xaml
  src/Avalonia.Themes.Default/ManagedFileChooser.xaml
  src/Avalonia.Themes.Fluent/Avalonia.Themes.Fluent.csproj
  src/Avalonia.Themes.Fluent/Controls/FluentControls.xaml
  src/Avalonia.Themes.Fluent/Controls/ManagedFileChooser.xaml
Labels: breaking-change

#5423 Remove Avalonia.ReactiveUI.Events
  Avalonia.sln
  nukebuild/Build.cs
  nukebuild/_build.csproj
  src/Avalonia.ReactiveUI.Events/Avalonia.ReactiveUI.Events.csproj
Labels: breaking-change

#5861 Port CornerRadiusFilterConverter from WinUI
  src/Avalonia.Controls/Converters/CornerRadiusFilterConverter.cs
  src/Avalonia.Controls/Converters/CornerRadiusFilterKind.cs
Labels: backport-candidate

#5860 Optional tooltip DataValidationError template
  src/Avalonia.Controls.DataGrid/Themes/Fluent.xaml
  src/Avalonia.Themes.Fluent/Controls/DataValidationErrors.xaml
Labels: backport-candidate

#5896 Fix NRE in Skia DrawingContextImpl.
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
  tests/Avalonia.Skia.UnitTests/DrawingContextImplTests.cs
Labels: backport-candidate

#5909 add contentattribute to image.
  src/Avalonia.Controls/Image.cs
Labels: backport-candidate

#5910 dont use datatemplate in datavalidationerrors.
  src/Avalonia.Themes.Fluent/Controls/DataValidationErrors.xaml
Labels: backport-candidate

#5917 `StretchDirection` for `Viewbox`
  samples/ControlCatalog/Pages/ViewboxPage.xaml
  samples/ControlCatalog/Pages/ViewboxPage.xaml.cs
  src/Avalonia.Controls/Image.cs
  src/Avalonia.Controls/Viewbox.cs
  tests/Avalonia.Controls.UnitTests/ViewboxTests.cs
Labels: backport-candidate

#5918 Fix property type for `Viewbox.Stretch.`
  samples/ControlCatalog/Pages/ViewboxPage.xaml
  samples/ControlCatalog/Pages/ViewboxPage.xaml.cs
  src/Avalonia.Controls/Viewbox.cs
Labels: backport-candidate

#5573 New Fluent expander style
  samples/ControlCatalog/App.xaml.cs
  src/Avalonia.Themes.Fluent/Accents/Base.xaml
  src/Avalonia.Themes.Fluent/Controls/Expander.xaml
Labels: backport-candidate

#5925 Change Viewbox.Stretch to a styled property
  src/Avalonia.Controls/ApiCompatBaseline.txt
  src/Avalonia.Controls/Viewbox.cs
Labels: breaking-change

#5929 Reuse animators in Transitions code + add missing BoxShadowsTransition + fix NRE in ISolidColorBrushAnimator
  samples/RenderDemo/Pages/AnimationsPage.xaml
  samples/RenderDemo/Pages/TransitionsPage.xaml
  src/Avalonia.Animation/Transitions/DoubleTransition.cs
  src/Avalonia.Animation/Transitions/FloatTransition.cs
  src/Avalonia.Animation/Transitions/IntegerTransition.cs
  src/Avalonia.Visuals/Animation/Animators/SolidColorBrushAnimator.cs
  src/Avalonia.Visuals/Animation/Transitions/BoxShadowsTransition.cs
  src/Avalonia.Visuals/Animation/Transitions/CornerRadiusTransition.cs
  src/Avalonia.Visuals/Animation/Transitions/PointTransition.cs
  src/Avalonia.Visuals/Animation/Transitions/SizeTransition.cs
  src/Avalonia.Visuals/Animation/Transitions/ThicknessTransition.cs
  src/Avalonia.Visuals/Animation/Transitions/VectorTransition.cs
Labels: backport-candidate

#5800 Api to allow loading WriteableBitmap from File / Stream
  src/Avalonia.Headless/HeadlessPlatformRenderInterface.cs
  src/Avalonia.Visuals/ApiCompatBaseline.txt
  src/Avalonia.Visuals/Media/Imaging/WriteableBitmap.cs
  src/Avalonia.Visuals/Platform/IPlatformRenderInterface.cs
  src/Skia/Avalonia.Skia/PlatformRenderInterface.cs
  src/Skia/Avalonia.Skia/WriteableBitmapImpl.cs
  src/Windows/Avalonia.Direct2D1/Direct2D1Platform.cs
  src/Windows/Avalonia.Direct2D1/Media/Imaging/WriteableWicBitmapImpl.cs
  tests/Avalonia.Benchmarks/NullRenderingPlatform.cs
  tests/Avalonia.UnitTests/MockPlatformRenderInterface.cs
  tests/Avalonia.Visuals.UnitTests/VisualTree/MockRenderInterface.cs
Labels: backport-candidate

#5927 Avoid allocating lists in `Classes`.
  src/Avalonia.Styling/Controls/Classes.cs
Labels: backport-candidate, perf

#5926 Cleanup layout visualizer and improve UX.
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ControlLayoutViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/ControlDetailsView.xaml
  src/Avalonia.Diagnostics/Diagnostics/Views/ThicknessEditor.cs
Labels: backport-candidate, dev-tools

#5913 fixes from upstream, wraplayout.
  src/Avalonia.Layout/WrapLayout/WrapLayout.cs
Labels: backport-candidate

#5923 Fix ICustomHitTest
  src/Avalonia.Visuals/Rendering/ICustomSimpleHitTest.cs
  src/Avalonia.Visuals/Rendering/ImmediateRenderer.cs
  src/Avalonia.Visuals/Rendering/SceneGraph/Scene.cs
  tests/Avalonia.Visuals.UnitTests/Rendering/CustomHitTestBorder.cs
  tests/Avalonia.Visuals.UnitTests/Rendering/DeferredRendererTests_HitTesting.cs
  tests/Avalonia.Visuals.UnitTests/Rendering/ImmediateRendererTests_HitTesting.cs
Labels: backport-candidate, rendering

#5944 Class level docs for basic controls.
  src/Avalonia.Controls/DateTimePickers/TimePicker.cs
  src/Avalonia.Controls/Expander.cs
  src/Avalonia.Controls/Grid.cs
  src/Avalonia.Controls/Primitives/ScrollBarVisibility.cs
  src/Avalonia.Controls/RadioButton.cs
  src/Avalonia.Controls/RelativePanel.cs
  src/Avalonia.Controls/RepeatButton.cs
  src/Avalonia.Controls/TextBox.cs
Labels: backport-candidate

#5943 trick to make OSX invalidate the shadow.
  native/Avalonia.Native/src/OSX/window.h
  native/Avalonia.Native/src/OSX/window.mm
Labels: backport-candidate

#5948 fix implementation of ScalingChanged property.
  src/Avalonia.Native/WindowImplBase.cs
Labels: backport-candidate

#5935 TextBox: update command states on selection changes
  src/Avalonia.Controls/TextBox.cs
Labels: backport-candidate

#5950 Allow for easily changing layout alignment
  src/Avalonia.Diagnostics/Diagnostics/Controls/ThicknessEditor.axaml
  src/Avalonia.Diagnostics/Diagnostics/Controls/ThicknessEditor.cs
  src/Avalonia.Diagnostics/Diagnostics/Converters/EnumToCheckedConverter.cs
  src/Avalonia.Diagnostics/Diagnostics/DevToolsOptions.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ControlLayoutViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/ControlDetailsView.xaml
  src/Avalonia.Diagnostics/Diagnostics/Views/ControlDetailsView.xaml.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/LayoutExplorerView.axaml
  src/Avalonia.Diagnostics/Diagnostics/Views/LayoutExplorerView.axaml.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/MainWindow.xaml
  src/Avalonia.Diagnostics/Diagnostics/Views/TreePageView.xaml
Labels: backport-candidate, dev-tools

#5894 Added support for single-touch screens directly via evdev
  src/Linux/Avalonia.LinuxFramebuffer/Input/EvDev/EvDevBackend.cs
  src/Linux/Avalonia.LinuxFramebuffer/Input/EvDev/EvDevDevice.cs
  src/Linux/Avalonia.LinuxFramebuffer/Input/EvDev/EvDevDeviceDescription.cs
  src/Linux/Avalonia.LinuxFramebuffer/Input/EvDev/EvDevTouchScreen.cs
  src/Linux/Avalonia.LinuxFramebuffer/Input/EvDev/EvDevTouchScreenDeviceDescription.cs
  src/Linux/Avalonia.LinuxFramebuffer/LinuxFramebufferPlatform.cs
  src/Linux/Avalonia.LinuxFramebuffer/NativeUnsafeMethods.cs
Labels: backport-candidate

#5955 Enable InputElement, Interactive, Visual and AvaloniaObject nullablity
  src/Avalonia.Base/AvaloniaObject.cs
  src/Avalonia.Base/Diagnostics/IAvaloniaObjectDebug.cs
  src/Avalonia.Base/IAvaloniaObject.cs
  src/Avalonia.Controls/Control.cs
  src/Avalonia.Controls/IControl.cs
  src/Avalonia.Input/IInputElement.cs
  src/Avalonia.Input/InputElement.cs
  src/Avalonia.Input/KeyboardDevice.cs
  src/Avalonia.Input/MouseDevice.cs
  src/Avalonia.Interactivity/IInteractive.cs
  src/Avalonia.Interactivity/Interactive.cs
  src/Avalonia.Layout/Layoutable.cs
  src/Avalonia.Styling/Controls/ISetInheritanceParent.cs
  src/Avalonia.Styling/Controls/ISetLogicalParent.cs
  src/Avalonia.Styling/IDataContextProvider.cs
  src/Avalonia.Styling/IStyledElement.cs
  src/Avalonia.Styling/StyledElement.cs
  src/Avalonia.Styling/Styling/ISetterValue.cs
  src/Avalonia.Styling/Styling/PropertySetterInstance.cs
  src/Avalonia.Styling/Styling/PropertySetterLazyInstance.cs
  src/Avalonia.Visuals/Visual.cs
  src/Avalonia.Visuals/VisualTree/IVisual.cs
Labels: backport-candidate

#5987 Fix a memory leak in StreamNode.
  src/Avalonia.Base/Data/Core/StreamNode.cs
Labels: backport-candidate

#5991 Feature/devtools filter text box
  src/Avalonia.Diagnostics/Diagnostics/Controls/FilterTextBox.axaml
  src/Avalonia.Diagnostics/Diagnostics/Controls/FilterTextBox.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ControlDetailsViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/EventsPageViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/FilterViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/TreePageViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/ControlDetailsView.xaml
  src/Avalonia.Diagnostics/Diagnostics/Views/EventsPageView.xaml
  src/Avalonia.Diagnostics/Diagnostics/Views/MainWindow.xaml
  src/Avalonia.Themes.Default/TextBox.xaml
Labels: backport-candidate, dev-tools

#5953 Specialized observables for transitions
  src/Avalonia.Animation/AnimatorDrivenTransition.cs
  src/Avalonia.Animation/AnimatorTransitionObservable.cs
  src/Avalonia.Animation/Clock.cs
  src/Avalonia.Animation/ClockBase.cs
  src/Avalonia.Animation/Transition.cs
  src/Avalonia.Animation/TransitionInstance.cs
  src/Avalonia.Animation/TransitionObservableBase.cs
  src/Avalonia.Animation/Transitions/DoubleTransition.cs
  src/Avalonia.Animation/Transitions/FloatTransition.cs
  src/Avalonia.Animation/Transitions/IntegerTransition.cs
  src/Avalonia.Visuals/Animation/Transitions/BoxShadowsTransition.cs
  src/Avalonia.Visuals/Animation/Transitions/ColorTransition.cs
  src/Avalonia.Visuals/Animation/Transitions/CornerRadiusTransition.cs
  src/Avalonia.Visuals/Animation/Transitions/PointTransition.cs
  src/Avalonia.Visuals/Animation/Transitions/SizeTransition.cs
  src/Avalonia.Visuals/Animation/Transitions/ThicknessTransition.cs
  src/Avalonia.Visuals/Animation/Transitions/TransformOperationsTransition.cs
  src/Avalonia.Visuals/Animation/Transitions/VectorTransition.cs
  tests/Avalonia.Benchmarks/Animations/TransitionBenchmark.cs
Labels: backport-candidate, perf

#5968 Fix custom hit testing
  src/Avalonia.Controls/Primitives/LightDismissOverlayLayer.cs
  src/Avalonia.Visuals/Rendering/SceneGraph/Scene.cs
Labels: backport-candidate
