Repository AvaloniaUI/Avalonia, pull requests merged in 2021-06, with the labels that each got.

#5997 Optimize shape rendering (pen creation mostly).
  src/Avalonia.Controls/Shapes/Shape.cs
  src/Avalonia.Visuals/Media/Immutable/ImmutableDashStyle.cs
  src/Avalonia.Visuals/Media/Immutable/ImmutablePen.cs
  src/Avalonia.Visuals/Rendering/SceneGraph/SceneBuilder.cs
  src/Avalonia.Visuals/Rendering/SceneGraph/VisualNode.cs
  tests/Avalonia.Benchmarks/NullDrawingContextImpl.cs
  tests/Avalonia.Benchmarks/NullRenderingPlatform.cs
  tests/Avalonia.Benchmarks/Rendering/ShapeRendering.cs
Labels: backport-candidate

#6014 Implemented ImageDrawing.
  src/Avalonia.Visuals/Media/ImageDrawing.cs
  tests/Avalonia.RenderTests/Media/ImageDrawingTests.cs
  tests/TestFiles/Direct2D1/Media/ImageDrawing/ImageDrawing_BottomRight.expected.png
  tests/TestFiles/Direct2D1/Media/ImageDrawing/ImageDrawing_Fill.expected.png
  tests/TestFiles/Direct2D1/Media/ImageDrawing/github_icon.png
  tests/TestFiles/Skia/Media/ImageDrawing/ImageDrawing_BottomRight.expected.png
  tests/TestFiles/Skia/Media/ImageDrawing/ImageDrawing_Fill.expected.png
  tests/TestFiles/Skia/Media/ImageDrawing/github_icon.png
Labels: backport-candidate

#6016 Fix light dismiss overlay intercepting titlebar hit tests.
  src/Windows/Avalonia.Win32/WindowImpl.CustomCaptionProc.cs
Labels: backport-candidate

#6022 SelectedDate and SelectedTime => TwoWay by default
  src/Avalonia.Controls/DateTimePickers/DatePicker.cs
  src/Avalonia.Controls/DateTimePickers/TimePicker.cs
Labels: backport-candidate

#6023 TextBox: Add IsUndoEnabled and UndoLimit
  src/Avalonia.Controls/TextBox.cs
  src/Avalonia.Controls/Utils/UndoRedoHelper.cs
Labels: backport-candidate

#5998 Enable nullable on Avalonia.Diagnostics project
  src/Avalonia.Base/Metadata/NullableAttributes.cs
  src/Avalonia.Diagnostics/Avalonia.Diagnostics.csproj
  src/Avalonia.Diagnostics/Diagnostics/Controls/ThicknessEditor.cs
  src/Avalonia.Diagnostics/Diagnostics/Converters/BoolToOpacityConverter.cs
  src/Avalonia.Diagnostics/Diagnostics/Converters/EnumToCheckedConverter.cs
  src/Avalonia.Diagnostics/Diagnostics/DevTools.cs
  src/Avalonia.Diagnostics/Diagnostics/Models/ConsoleContext.cs
  src/Avalonia.Diagnostics/Diagnostics/Models/EventChainLink.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewLocator.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/AvaloniaPropertyViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ClrPropertyViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ConsoleViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ControlDetailsViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ControlLayoutViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/EventOwnerTreeNode.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/EventTreeNode.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/EventTreeNodeBase.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/EventsPageViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/FilterViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/FiredEvent.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/LogicalTreeNode.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/MainViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/PropertyViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ResourceSetterViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/SetterViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/TreeNode.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/TreeNodeCollection.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/TreePageViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ViewModelBase.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/VisualTreeNode.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/ConsoleView.xaml.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/EventsPageView.xaml.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/MainView.xaml.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/MainWindow.xaml.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/TreePageView.xaml.cs
  src/Avalonia.Diagnostics/Diagnostics/VisualTreeDebug.cs
Labels: backport-candidate, dev-tools

#6029 Transitions for solid color brushes.
  samples/RenderDemo/Pages/TransitionsPage.xaml
  src/Avalonia.Visuals/Animation/Transitions/BrushTransition.cs
Labels: backport-candidate

#6046 fixes(DevTools): Issue #5882
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/AvaloniaPropertyViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ClrPropertyViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/PropertyViewModel.cs
Labels: backport-candidate, dev-tools

#6049 fixes(DevTools): Issue #6047
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ControlDetailsViewModel.cs
Labels: backport-candidate, dev-tools

#6064 Fix fetching neutral value in animations.
  src/Avalonia.Animation/AnimationInstance`1.cs
Labels: backport-candidate

#5055 Fix crash when KeyBindings change while they are being handled
  src/Avalonia.Input/KeyboardDevice.cs
  tests/Avalonia.Input.UnitTests/KeyboardDeviceTests.cs
Labels: backport-candidate

#6083 fix osx window state logic.
  native/Avalonia.Native/src/OSX/window.mm
Labels: backport-candidate

#6054 Allow for using ScrollViewer.AllowAutoHide as an attached property.
  src/Avalonia.Base/AvaloniaObjectExtensions.cs
  src/Avalonia.Controls/ApiCompatBaseline.txt
  src/Avalonia.Controls/ScrollViewer.cs
  src/Avalonia.Themes.Default/ListBox.xaml
  src/Avalonia.Themes.Default/TextBox.xaml
  src/Avalonia.Themes.Default/TreeView.xaml
  src/Avalonia.Themes.Fluent/Controls/ListBox.xaml
  src/Avalonia.Themes.Fluent/Controls/TextBox.xaml
  src/Avalonia.Themes.Fluent/Controls/TreeView.xaml
Labels: breaking-change, wont-backport

#6072 Ensure we unsubscribe from PropertyChanged.
  src/Avalonia.Animation/AnimationInstance`1.cs
Labels: backport-candidate

#6091 scale flyout transient area.
  src/Avalonia.Controls/Flyouts/FlyoutBase.cs
Labels: backport-candidate

#6105 ComboBox: Let Data and Stretch be overridden
  src/Avalonia.Themes.Fluent/Controls/ComboBox.xaml
Labels: backport-candidate

#6018 Cancellable animations (for async methods) + Expander fix
  src/Avalonia.Animation/Animation.cs
  src/Avalonia.Animation/ApiCompatBaseline.txt
  src/Avalonia.Animation/IAnimation.cs
  src/Avalonia.Controls/Expander.cs
  src/Avalonia.Controls/Presenters/CarouselPresenter.cs
  src/Avalonia.ReactiveUI/TransitioningContentControl.cs
  src/Avalonia.Visuals/Animation/CompositePageTransition.cs
  src/Avalonia.Visuals/Animation/CrossFade.cs
  src/Avalonia.Visuals/Animation/IPageTransition.cs
  src/Avalonia.Visuals/Animation/PageSlide.cs
  src/Avalonia.Visuals/ApiCompatBaseline.txt
  tests/Avalonia.Animation.UnitTests/AnimationIterationTests.cs
Labels: breaking-change

#6135 Use IsNullOrEmpty instead of IsNullOrWhiteSpace for :empty pseudoclass
  src/Avalonia.Controls/TextBox.cs
Labels: backport-candidate
