Repository AvaloniaUI/Avalonia, pull requests merged in 2021-11, with the labels that each got.

#6790 DevTools - allow to navigate to children (especially DataContext)
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ControlDetailsViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/ControlDetailsView.xaml
  src/Avalonia.Diagnostics/Diagnostics/Views/ControlDetailsView.xaml.cs
Labels: enhancement, backport-candidate, dev-tools

#6809 fixes: Warnings CS0219 and CS0168
  src/Avalonia.DesignerSupport/Remote/HtmlTransport/HtmlTransport.cs
  src/Avalonia.X11/X11Window.Ime.cs
  src/Skia/Avalonia.Skia/Gpu/OpenGl/GlSkiaGpu.cs
Labels: backport-candidate

#6830 Update NumericUpDown template MinWidth
  src/Avalonia.Themes.Fluent/Controls/NumericUpDown.xaml
Labels: bug, backport-candidate

#6818 Filter pointer pressed events from disabled sub-menu items
  src/Avalonia.Controls/Platform/DefaultMenuInteractionHandler.cs
  tests/Avalonia.Controls.UnitTests/Platform/DefaultMenuInteractionHandlerTests.cs
Labels: bug, backport-candidate

#6900 Don't update TransformedBounds from RenderTargetBitmap.
  src/Avalonia.Visuals/Rendering/ImmediateRenderer.cs
  tests/Avalonia.Visuals.UnitTests/Rendering/ImmediateRendererTests.cs
  tests/Avalonia.Visuals.UnitTests/VisualTree/TransformedBoundsTests.cs
Labels: bug, backport-candidate

#6902 net6.0 sdk
  azure-pipelines.yml
  build/HarfBuzzSharp.props
  build/MicroCom.targets
  build/SkiaSharp.props
  global.json
  src/tools/MicroComGenerator/MicroComGenerator.csproj
Labels: backport-candidate

#6896 Fixes/clipping rendering issues osx
  src/Skia/Avalonia.Skia/Gpu/OpenGl/GlSkiaGpu.cs
Labels: backport-candidate

#6907 Use event args to get value instead of field
  src/Avalonia.Input/InputElement.cs
Labels: backport-candidate

#6913 Fix TrayIcon commands executes twice
  src/Avalonia.Controls/MenuItem.cs
Labels: bug, windows, backport-candidate

#6925 Fix copy-pasta
  src/Avalonia.Controls/Platform/PlatformManager.cs
Labels: backport-candidate

#6926 macOS: Only raise non-client click when outside view client area.
  native/Avalonia.Native/src/OSX/window.mm
Labels: bug, backport-candidate

#6970 Investigation of animation system failure issue #6969
  src/Avalonia.Animation/Animators/Animator`1.cs
  tests/Avalonia.Animation.UnitTests/AnimatableTests.cs
Labels: backport-candidate

#6941 add the old Animation.RunAsync api back for backporting
  src/Avalonia.Animation/Animation.cs
  src/Avalonia.Animation/ApiCompatBaseline.txt
Labels: backport-candidate

#6972 feat: Allow to debug XamlIl Compilation
  packages/Avalonia/AvaloniaBuildTasks.targets
  src/Avalonia.Build.Tasks/CompileAvaloniaXamlTask.cs
  src/Avalonia.Build.Tasks/XamlCompilerTaskExecutor.cs
Labels: backport-candidate

#6867 [OSX] allow child windows to be shown on top of fullscreen windows.
  native/Avalonia.Native/src/OSX/window.mm
Labels: backport-candidate

#6868 [win32] only take focus on button down events.
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
Labels: backport-candidate

#6811 allow window to clear focus manager when it closes, preventing memory…
  src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs
  src/Avalonia.Controls/WindowBase.cs
  src/Avalonia.Input/ApiCompatBaseline.txt
  src/Avalonia.Input/FocusManager.cs
  src/Avalonia.Input/IFocusManager.cs
Labels: backport-candidate

#6815 Fixes/static resource brush converter
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/StaticResourceExtension.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/StaticResourceExtensionTests.cs
Labels: backport-candidate

#6754 fixes: some null annotation
  src/Avalonia.Base/Data/BindingValue.cs
  src/Avalonia.Base/Data/Converters/MethodToCommandConverter.cs
  src/Avalonia.Controls/Application.cs
  src/Avalonia.Controls/Flyouts/FlyoutBase.cs
  src/Avalonia.Controls/Primitives/Popup.cs
  src/Avalonia.Controls/SplitView.cs
  src/Avalonia.Controls/TrayIcon.cs
  src/Avalonia.Input/ICommandSource.cs
  src/Avalonia.Styling/Styling/PropertySetterInstance.cs
  src/Avalonia.Styling/Styling/Setter.cs
  src/tools/MicroComGenerator/CSharpGen.Utils.cs
Labels: backport-candidate

#6883 Implement IPlatformLifetimeEvents for X11/Linux
  src/Avalonia.X11/ICELib.cs
  src/Avalonia.X11/SMLib.cs
  src/Avalonia.X11/X11Platform.cs
  src/Avalonia.X11/X11PlatformLifetimeEvents.cs
Labels: backport-candidate

#7006 fix stuck tooltips on macOS
  native/Avalonia.Native/src/OSX/window.mm
Labels: backport-candidate

#7043 make IsOpenProperty on flyoutbase public.
  src/Avalonia.Controls/Flyouts/FlyoutBase.cs
Labels: backport-candidate
