Repository AvaloniaUI/Avalonia, pull requests merged in 2022-12, with the labels that each got.

#9581 bugfix: If the slider is disabled while sliding, prevent the track sliding
  src/Avalonia.Controls/Slider.cs
  src/Avalonia.Themes.Fluent/Controls/Slider.xaml
Labels: bug

#9609 Throw an exception on unit test assertion fail.
  tests/Avalonia.UnitTests/ModuleInitializer.cs
Labels: infrastructure

#9566 MacOS: Only bring windows to front if they're on the active space.
  native/Avalonia.Native/src/OSX/WindowImpl.mm
  samples/IntegrationTestApp/MainWindow.axaml
  samples/IntegrationTestApp/MainWindow.axaml.cs
  samples/IntegrationTestApp/ShowWindowTest.axaml
  tests/Avalonia.IntegrationTests.Appium/WindowTests.cs
  tests/Avalonia.IntegrationTests.Appium/WindowTests_MacOS.cs
Labels: bug, os-macos

#9625 Fix Theme Re-Attach and Animations in Styles Without Activators
  src/Avalonia.Base/StyledElement.cs
  src/Avalonia.Base/Styling/StyleInstance.cs
  tests/Avalonia.Base.UnitTests/Styling/StyleTests.cs
  tests/Avalonia.Base.UnitTests/Styling/StyledElementTests_Theming.cs
Labels: bug

#9642 Fix canceling animations.
  .ncrunch/ReactiveUIDemo.v3.ncrunchproject
  Avalonia.Desktop.slnf
  Avalonia.sln
  samples/ReactiveUIDemo/App.axaml
  samples/ReactiveUIDemo/App.axaml.cs
  samples/ReactiveUIDemo/MainWindow.axaml
  samples/ReactiveUIDemo/MainWindow.axaml.cs
  samples/ReactiveUIDemo/ReactiveUIDemo.csproj
  samples/ReactiveUIDemo/ViewModels/BarViewModel.cs
  samples/ReactiveUIDemo/ViewModels/FooViewModel.cs
  samples/ReactiveUIDemo/ViewModels/MainWindowViewModel.cs
  samples/ReactiveUIDemo/ViewModels/RoutedViewHostPageViewModel.cs
  samples/ReactiveUIDemo/Views/BarView.axaml
  samples/ReactiveUIDemo/Views/BarView.axaml.cs
  samples/ReactiveUIDemo/Views/FooView.axaml
  samples/ReactiveUIDemo/Views/FooView.axaml.cs
  src/Avalonia.Base/Animation/Animators/Animator`1.cs
  tests/Avalonia.Base.UnitTests/Animation/AnimationIterationTests.cs
Labels: bug

#9562 IsVisible can control window show and hide.
  src/Avalonia.Controls/Window.cs
  src/Avalonia.Controls/WindowBase.cs
  tests/Avalonia.Controls.UnitTests/WindowTests.cs
Labels: backport-candidate

#9577 Implement compile time MergedDictionaties
  src/Avalonia.Controls.ColorPicker/Themes/Fluent/ColorPicker.xaml
  src/Avalonia.Controls.ColorPicker/Themes/Fluent/Fluent.xaml
  src/Avalonia.Controls.ColorPicker/Themes/Simple/ColorPicker.xaml
  src/Avalonia.Controls.ColorPicker/Themes/Simple/Simple.xaml
  src/Avalonia.Themes.Fluent/Accents/Base.xaml
  src/Avalonia.Themes.Fluent/Controls/Button.xaml
  src/Avalonia.Themes.Fluent/Controls/FluentControls.xaml
  src/Avalonia.Themes.Fluent/Controls/RepeatButton.xaml
  src/Avalonia.Themes.Fluent/Controls/ToggleButton.xaml
  src/Avalonia.Themes.Fluent/FluentTheme.xaml
  src/Avalonia.Themes.Fluent/FluentTheme.xaml.cs
  src/Avalonia.Themes.Simple/Controls/SimpleControls.xaml
  src/Avalonia.Themes.Simple/SimpleTheme.xaml
  src/Avalonia.Themes.Simple/SimpleTheme.xaml.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaRuntimeXamlLoader.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlCompiler.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/GroupTransformers/IXamlAstGroupTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/GroupTransformers/XamlIncludeGroupTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/GroupTransformers/XamlMergeResourceGroupTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/XamlDocumentParseException.cs
  src/Markup/Avalonia.Markup.Xaml/Avalonia.Markup.Xaml.csproj
  src/Markup/Avalonia.Markup.Xaml/Styling/MergeResourceInclude.cs
  src/Markup/Avalonia.Markup.Xaml/Styling/ResourceInclude.cs
  src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs
  tests/Avalonia.Benchmarks/Themes/ThemeBenchmark.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/MergeResourceIncludeTests.cs
Labels: perf, area-xaml

#9699 Fix SelectionModelSelectionChangedEventArgs.SelectedItems indexer.
  src/Avalonia.Controls/Selection/SelectedItems.cs
  tests/Avalonia.Controls.UnitTests/Selection/SelectionModelTests_Single.cs
Labels: bug, backport-candidate

#9722 Marshal StyledProperty bindings to UI thread.
  src/Avalonia.Base/PropertyStore/BindingEntryBase.cs
  src/Avalonia.Base/PropertyStore/LocalValueBindingObserver.cs
  src/Avalonia.Base/PropertyStore/LocalValueUntypedBindingObserver.cs
  tests/Avalonia.Base.UnitTests/Avalonia.Base.UnitTests.csproj
  tests/Avalonia.Base.UnitTests/AvaloniaObjectTests_Binding.cs
  tests/Avalonia.Base.UnitTests/AvaloniaObjectTests_Direct.cs
Labels: bug

#9727 DataGridColumn: make OwningGrid protected internal
  src/Avalonia.Controls.DataGrid/DataGridColumn.cs
Labels: api, area-datagrid

#9715 Added WindowClosingEventArgs.
  src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs
  src/Avalonia.Controls/Platform/IWindowImpl.cs
  src/Avalonia.Controls/Window.cs
  src/Avalonia.Controls/WindowClosingEventArgs.cs
  src/Avalonia.DesignerSupport/Remote/PreviewerWindowImpl.cs
  src/Avalonia.DesignerSupport/Remote/Stubs.cs
  src/Avalonia.Headless/HeadlessWindowImpl.cs
  src/Avalonia.Native/WindowImpl.cs
  src/Avalonia.X11/X11Window.cs
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
  tests/Avalonia.Controls.UnitTests/WindowTests.cs
Labels: enhancement

#9760 Remove IRuntimePlatform.OperatingSystem API and replace with trimmable OperatingSystem API
  samples/ControlCatalog/Pages/PlatformInfoPage.xaml.cs
  samples/ControlCatalog/ViewModels/PlatformInformationViewModel.cs
  src/Avalonia.Base/Avalonia.Base.csproj
  src/Avalonia.Base/Compatibility/OperatingSystem.cs
  src/Avalonia.Base/Logging/LogArea.cs
  src/Avalonia.Base/Platform/IRuntimePlatform.cs
  src/Avalonia.Base/Platform/StandardRuntimePlatform.cs
  src/Avalonia.Base/Platform/StandardRuntimePlatformServices.cs
  src/Avalonia.Desktop/AppBuilderDesktopExtensions.cs
  src/Avalonia.OpenGL/Egl/EglInterface.cs
  src/Browser/Avalonia.Browser/BrowserRuntimePlatform.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlOptionMarkupExtensionTransformer.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/OnFormFactorExtension.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/OnPlatformExtension.cs
  src/Skia/Avalonia.Skia/Helpers/PixelFormatHelper.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/OnPlatformExtensionTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/OptionsMarkupExtensionTests.cs
Labels: perf, breaking-change, area-trimming
