Repository AvaloniaUI/Avalonia, pull requests merged in 2022-04, with the labels that each got.

#7911 Add Template Part Attributes to Controls
  src/Avalonia.Controls/AutoCompleteBox.cs
  src/Avalonia.Controls/ButtonSpinner.cs
  src/Avalonia.Controls/Calendar/Calendar.cs
  src/Avalonia.Controls/Calendar/CalendarDatePicker.cs
  src/Avalonia.Controls/Calendar/CalendarItem.cs
  src/Avalonia.Controls/Chrome/CaptionButtons.cs
  src/Avalonia.Controls/Chrome/TitleBar.cs
  src/Avalonia.Controls/ComboBox.cs
  src/Avalonia.Controls/ContentControl.cs
  src/Avalonia.Controls/DateTimePickers/DatePicker.cs
  src/Avalonia.Controls/DateTimePickers/DatePickerPresenter.cs
  src/Avalonia.Controls/DateTimePickers/TimePicker.cs
  src/Avalonia.Controls/DateTimePickers/TimePickerPresenter.cs
  src/Avalonia.Controls/ListBox.cs
  src/Avalonia.Controls/MenuItem.cs
  src/Avalonia.Controls/Notifications/WindowNotificationManager.cs
  src/Avalonia.Controls/NumericUpDown/NumericUpDown.cs
  src/Avalonia.Controls/Primitives/ScrollBar.cs
  src/Avalonia.Controls/ProgressBar.cs
  src/Avalonia.Controls/ScrollViewer.cs
  src/Avalonia.Controls/Slider.cs
  src/Avalonia.Controls/SplitButton/SplitButton.cs
  src/Avalonia.Controls/SplitView.cs
  src/Avalonia.Controls/TabControl.cs
  src/Avalonia.Controls/TextBox.cs
  src/Avalonia.Controls/ToggleSwitch.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.Controls/TreeViewItem.cs
  src/Avalonia.Dialogs/ManagedFileChooser.cs
Labels: backport-candidate

#7921 Add missing context.Transform = Transform in EllipseNode
  src/Avalonia.Visuals/Rendering/SceneGraph/EllipseNode.cs
Labels: backport-candidate

#7914 Add Rectangle RadiusX/RadiusY Properties for Rounded Corners
  samples/ControlCatalog/Pages/CanvasPage.xaml
  src/Avalonia.Controls/Shapes/Rectangle.cs
  src/Avalonia.Visuals/Media/StreamGeometryContext.cs
  src/Avalonia.Visuals/Platform/IGeometryContext.cs
  src/Avalonia.Visuals/Platform/IPlatformRenderInterface.cs
Labels: API

#7931 Delete DropDown.cs
  src/Avalonia.Controls/ApiCompatBaseline.txt
  src/Avalonia.Controls/DropDown.cs
Labels: breaking-change

#7810 Implement FlowDirection - Bidirectional layout
  samples/ControlCatalog/MainView.xaml
  samples/ControlCatalog/MainView.xaml.cs
  samples/ControlCatalog/Pages/ScreenPage.cs
  src/Avalonia.Controls/ComboBox.cs
  src/Avalonia.Controls/Control.cs
  src/Avalonia.Controls/Image.cs
  src/Avalonia.Controls/Presenters/TextPresenter.cs
  src/Avalonia.Controls/Primitives/OverlayPopupHost.cs
  src/Avalonia.Controls/Primitives/PopupPositioning/IPopupPositioner.cs
  src/Avalonia.Controls/Primitives/PopupRoot.cs
  src/Avalonia.Controls/TextBlock.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.Themes.Default/Controls/CheckBox.xaml
  src/Avalonia.Themes.Fluent/Controls/CheckBox.xaml
  src/Avalonia.Visuals/ApiCompatBaseline.txt
  src/Avalonia.Visuals/Rendering/ImmediateRenderer.cs
  src/Avalonia.Visuals/Rendering/SceneGraph/SceneBuilder.cs
  src/Avalonia.Visuals/Visual.cs
  src/Avalonia.Visuals/VisualExtensions.cs
  src/Avalonia.Visuals/VisualTree/IVisual.cs
Labels: API

#7954 Fix NativeMenuBar exception.
  src/Avalonia.Themes.Fluent/Controls/NativeMenuBar.xaml
Labels: bug, backport-candidate

#7965 Fix ScrollGestureEndedEvent type.
  src/Avalonia.Input/ApiCompatBaseline.txt
  src/Avalonia.Input/Gestures.cs
Labels: API, wont-backport

#7953 Some menu fixes and integration tests.
  samples/IntegrationTestApp/MainWindow.axaml
  samples/IntegrationTestApp/MainWindow.axaml.cs
  src/Avalonia.Controls/MenuItem.cs
  src/Avalonia.Controls/Platform/DefaultMenuInteractionHandler.cs
  tests/Avalonia.Controls.UnitTests/Platform/DefaultMenuInteractionHandlerTests.cs
  tests/Avalonia.IntegrationTests.Appium/ElementExtensions.cs
  tests/Avalonia.IntegrationTests.Appium/MenuTests.cs
Labels: bug, backport-candidate

#7968 add win32 egl gpu blacklist.
  src/Windows/Avalonia.Win32/Win32GlManager.cs
  src/Windows/Avalonia.Win32/Win32Platform.cs
Labels: backport-candidate

#7292 Upgrade DataGrid
  samples/ControlCatalog/Pages/DataGridPage.xaml
  src/Avalonia.Base/LogicalTree/ChildIndexChangedEventArgs.cs
  src/Avalonia.Controls.DataGrid/DataGrid.cs
  src/Avalonia.Controls.DataGrid/DataGridColumn.cs
  src/Avalonia.Controls.DataGrid/DataGridColumnCollection.cs
  src/Avalonia.Controls.DataGrid/DataGridColumns.cs
  src/Avalonia.Controls.DataGrid/DataGridDataConnection.cs
  src/Avalonia.Controls.DataGrid/DataGridRow.cs
  src/Avalonia.Controls.DataGrid/DataGridRows.cs
  src/Avalonia.Controls.DataGrid/DataGridTextColumn.cs
  src/Avalonia.Controls.DataGrid/Primitives/DataGridCellsPresenter.cs
  src/Avalonia.Controls.DataGrid/Primitives/DataGridColumnHeadersPresenter.cs
  src/Avalonia.Controls.DataGrid/Primitives/DataGridRowsPresenter.cs
  src/Avalonia.Controls.DataGrid/Themes/Default.xaml
  src/Avalonia.Controls.DataGrid/Themes/Fluent.xaml
  src/Avalonia.Controls/ItemsControl.cs
  src/Avalonia.Controls/Panel.cs
  src/Avalonia.Controls/Presenters/ItemsPresenterBase.cs
Labels: enhancement, datagrid, wont-backport

#7191 OSX handle CMD+key up combinations in Avalonia
  native/Avalonia.Native/src/OSX/app.mm
Labels: backport-candidate, inactive

#7905 "PointerOver" refactoring, moved shared code from (Pen)MouseDevice to the top level
  src/Avalonia.Base/Input/IInputRoot.cs
  src/Avalonia.Base/Input/IKeyboardDevice.cs
  src/Avalonia.Base/Input/IMouseDevice.cs
  src/Avalonia.Base/Input/IPointerDevice.cs
  src/Avalonia.Base/Input/KeyboardDevice.cs
  src/Avalonia.Base/Input/MouseDevice.cs
  src/Avalonia.Base/Input/PointerEventArgs.cs
  src/Avalonia.Base/Input/PointerOverPreProcessor.cs
  src/Avalonia.Base/Input/Raw/RawDragEvent.cs
  src/Avalonia.Base/Input/Raw/RawInputHelpers.cs
  src/Avalonia.Base/Input/Raw/RawPointerEventArgs.cs
  src/Avalonia.Base/Input/TouchDevice.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/MainViewModel.cs
  tests/Avalonia.Base.UnitTests/Input/MouseDeviceTests.cs
  tests/Avalonia.Base.UnitTests/Input/PointerOverTests.cs
  tests/Avalonia.Controls.UnitTests/TopLevelTests.cs
Labels: bug

#7517 Make DispatcherPriority to be a struct with static readonly field values
  src/Avalonia.Base/ApiCompatBaseline.txt
  src/Avalonia.Base/Threading/AvaloniaScheduler.cs
  src/Avalonia.Base/Threading/Dispatcher.cs
  src/Avalonia.Base/Threading/DispatcherPriority.cs
  src/Avalonia.Base/Threading/DispatcherTimer.cs
  src/Avalonia.Base/Threading/IDispatcher.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/MainViewModel.cs
  tests/Avalonia.UnitTests/ImmediateDispatcher.cs
Labels: wont-backport

#8022 Remove IAvaloniaPropertyVisitor due to generic virtual methods.
  src/Avalonia.Base/AvaloniaObject.cs
  src/Avalonia.Base/AvaloniaProperty.cs
  src/Avalonia.Base/DirectPropertyBase.cs
  src/Avalonia.Base/Interactivity/IInteractive.cs
  src/Avalonia.Base/StyledPropertyBase.cs
  src/Avalonia.Base/Styling/Setter.cs
  src/Avalonia.Base/Threading/IDispatcher.cs
  src/Avalonia.Base/Utilities/IAvaloniaPropertyVisitor.cs
  src/Avalonia.Controls/AutoCompleteBox.cs
  src/Avalonia.Controls/Button.cs
  src/Avalonia.Controls/Calendar/CalendarDatePicker.cs
  src/Avalonia.Controls/MenuItem.cs
  src/Avalonia.Controls/NumericUpDown/NumericUpDown.cs
  src/Avalonia.Controls/Primitives/SelectingItemsControl.cs
  src/Avalonia.Controls/Slider.cs
  src/Avalonia.Controls/TextBox.cs
  src/Avalonia.Controls/TreeView.cs
  src/Avalonia.Controls/TreeViewItem.cs
  tests/Avalonia.Base.UnitTests/AvaloniaObjectTests_DataValidation.cs
  tests/Avalonia.Base.UnitTests/AvaloniaPropertyTests.cs
Labels: API, wont-backport

#8034 Fix ContextMenu freeze.
  src/Avalonia.Controls/ItemsControl.cs
  src/Avalonia.Controls/Platform/DefaultMenuInteractionHandler.cs
  tests/Avalonia.Controls.UnitTests/Primitives/SelectingItemsControlTests.cs
Labels: bug, backport-candidate

#6982 fixes: TrayIcon should be re-added when the Explorer is restarted
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/Windows/Avalonia.Win32/TrayIconImpl.cs
Labels: backport-candidate
