Repository AvaloniaUI/Avalonia, pull requests merged in 2022-10, with the labels that each got.

#9088 Update flags for XSetWMNormalHints
  src/Avalonia.X11/X11Window.cs
Labels: backport-candidate

#9157 Add TextBox.TextChanged and TextBox.TextChanging Events
  src/Avalonia.Controls/TextBox.cs
  src/Avalonia.Controls/TextBoxTextInputMethodClient.cs
  src/Avalonia.Controls/TextChangedEventArgs.cs
  src/Avalonia.Controls/TextChangingEventArgs.cs
Labels: api, api-suggestion

#9167 Remove HeaderContentPresenter of several controls.
  samples/ControlCatalog/Pages/DateTimePickerPage.xaml
  src/Avalonia.Controls/DateTimePickers/DatePicker.cs
  src/Avalonia.Controls/DateTimePickers/TimePicker.cs
  src/Avalonia.Themes.Fluent/Accents/FluentControlResourcesDark.xaml
  src/Avalonia.Themes.Fluent/Accents/FluentControlResourcesLight.xaml
  src/Avalonia.Themes.Fluent/Controls/DatePicker.xaml
  src/Avalonia.Themes.Fluent/Controls/Slider.xaml
  src/Avalonia.Themes.Fluent/Controls/TimePicker.xaml
  src/Avalonia.Themes.Simple/Controls/DatePicker.xaml
  src/Avalonia.Themes.Simple/Controls/TimePicker.xaml
Labels: breaking-change

#9135 Addresses #8970, Fixes DataGrid not processing all new items on change.
  src/Avalonia.Controls.DataGrid/Collections/DataGridCollectionView.cs
Labels: bug, area-datagrid

#9147 [RichTextBlock] Properly arrange embedded controls during ArrangeOverride
  src/Avalonia.Controls/Documents/IInlineHost.cs
  src/Avalonia.Controls/Documents/InlineRun.cs
  src/Avalonia.Controls/Documents/InlineUIContainer.cs
  src/Avalonia.Controls/RichTextBlock.cs
  tests/Avalonia.Controls.UnitTests/RichTextBlockTests.cs
Labels: release-blocker

#9133 Comment and update the Screen class
  native/Avalonia.Native/src/OSX/Screens.mm
  samples/ControlCatalog/Pages/ScreenPage.cs
  src/Avalonia.Controls/Platform/IScreenImpl.cs
  src/Avalonia.Controls/Platform/Screen.cs
  src/Avalonia.Controls/Screens.cs
  src/Avalonia.Native/ScreenImpl.cs
  src/Avalonia.Native/WindowImplBase.cs
  src/Avalonia.Native/avn.idl
  src/Avalonia.X11/X11Screens.cs
  src/Avalonia.X11/X11Window.cs
  src/Windows/Avalonia.Win32/TrayIconImpl.cs
  src/Windows/Avalonia.Win32/WinScreen.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: api, breaking-change

#9278 wasm: re-implement touch.
  src/Web/Avalonia.Web/Avalonia.Web.csproj
  src/Web/Avalonia.Web/AvaloniaView.cs
  src/Web/Avalonia.Web/BrowserTopLevelImpl.cs
  src/Web/Avalonia.Web/Interop/InputHelper.cs
  src/Web/Avalonia.Web/webapp/modules/avalonia/input.ts
Labels: os-browser

#9144 Prevent SelectingItemsControl's selection from being updated on focus when toggle is enabled
  src/Avalonia.Controls/ListBox.cs
  src/Avalonia.Controls/Primitives/SelectingItemsControl.cs
  tests/Avalonia.Controls.UnitTests/ListBoxTests_Multiple.cs
  tests/Avalonia.Controls.UnitTests/ListBoxTests_Single.cs
Labels: bug

#9301 backport: osx re-entrancy fix.
  native/Avalonia.Native/src/OSX/AvnWindow.mm
Labels: os-macos
