Repository AvaloniaUI/Avalonia, pull requests merged in 2022-09, with the labels that each got.

#8895 Fix DashStyle not applying values correctly.
  src/Avalonia.Base/Media/DashStyle.cs
  tests/Avalonia.Base.UnitTests/Media/PenTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/ControlTemplateTests.cs
Labels: breaking-change, wont-backport

#8905 Fix unpredictable choice between methods when using method binding.
  src/Avalonia.Base/Data/Core/Plugins/MethodAccessorPlugin.cs
  tests/Avalonia.Markup.UnitTests/Parsers/ExpressionObserverBuilderTests_Method.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Data/BindingTests_Method.cs
Labels: breaking-change, wont-backport

#8934 Replace webpack with esbuild
  src/Avalonia.DesignerSupport/Remote/HtmlTransport/webapp/build.js
  src/Avalonia.DesignerSupport/Remote/HtmlTransport/webapp/package-lock.json
  src/Avalonia.DesignerSupport/Remote/HtmlTransport/webapp/package.json
  src/Avalonia.DesignerSupport/Remote/HtmlTransport/webapp/src/index.html
  src/Avalonia.DesignerSupport/Remote/HtmlTransport/webapp/tsconfig.json
  src/Avalonia.DesignerSupport/Remote/HtmlTransport/webapp/webpack.config.js
  src/Web/Avalonia.Web.Blazor/Avalonia.Web.Blazor.csproj
  src/Web/Avalonia.Web.Blazor/Interop/AvaloniaModule.cs
  src/Web/Avalonia.Web.Blazor/Interop/Storage/StorageProviderInterop.cs
  src/Web/Avalonia.Web.Blazor/webapp/build.js
  src/Web/Avalonia.Web.Blazor/webapp/modules/Avalonia.ts
  src/Web/Avalonia.Web.Blazor/webapp/modules/Avalonia/Avalonia.ts
  src/Web/Avalonia.Web.Blazor/webapp/modules/Storage.ts
  src/Web/Avalonia.Web.Blazor/webapp/package.json
  src/Web/Avalonia.Web.Blazor/webapp/tsconfig.json
  src/Web/Avalonia.Web.Blazor/webapp/webpack.config.js
Labels: os-browser

#8460 feat: StringBuilderCache
  src/Avalonia.Base/Avalonia.Base.csproj
  src/Avalonia.Base/Input/KeyGesture.cs
  src/Avalonia.Base/Logging/TraceLogSink.cs
  src/Avalonia.Base/Media/BoxShadow.cs
  src/Avalonia.Base/Media/BoxShadows.cs
  src/Avalonia.Base/Media/Fonts/FamilyNameCollection.cs
  src/Avalonia.Base/Media/HslColor.cs
  src/Avalonia.Base/Media/HsvColor.cs
  src/Avalonia.Base/Styling/NthChildSelector.cs
  src/Avalonia.Base/Styling/PropertyEqualsSelector.cs
  src/Avalonia.Base/Styling/TypeNameAndClassSelector.cs
  src/Avalonia.Base/Utilities/StringBuilderCache.cs
  src/Avalonia.Build.Tasks/Avalonia.Build.Tasks.csproj
  src/Avalonia.Controls.ColorPicker/Helpers/ColorHelper.cs
  src/Avalonia.Controls.DataGrid/DataGrid.cs
  src/Avalonia.Controls/Converters/PlatformKeyGestureConverter.cs
  src/Avalonia.Controls/Documents/InlineCollection.cs
  src/Avalonia.Diagnostics/Diagnostics/VisualTreeDebug.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/Avalonia.Markup.Xaml.Loader.csproj
  src/Windows/Avalonia.Win32/ClipboardFormats.cs
  src/Windows/Avalonia.Win32/Input/WindowsKeyboardDevice.cs
  src/Windows/Avalonia.Win32/OleDataObject.cs
  src/tools/Avalonia.Designer.HostApp/Avalonia.Designer.HostApp.csproj
Labels: perf, inactive

#8992 Add spring animation support
  samples/RenderDemo/MainWindow.xaml
  samples/RenderDemo/Pages/SpringAnimationsPage.xaml
  samples/RenderDemo/Pages/SpringAnimationsPage.xaml.cs
  src/Avalonia.Base/Animation/Easings/SpringEasing.cs
  src/Avalonia.Base/Animation/Spring.cs
  src/Avalonia.Base/Animation/SpringTypeConverter.cs
  src/Avalonia.Base/Utilities/SpringSolver.cs
  tests/Avalonia.Base.UnitTests/Animation/SpringTests.cs
Labels: api, backport-candidate

#9012 Set control adorner from xaml
  samples/ControlCatalog/MainView.xaml
  samples/ControlCatalog/Pages/AdornerLayerPage.xaml
  samples/ControlCatalog/Pages/AdornerLayerPage.xaml.cs
  src/Avalonia.Controls/Primitives/AdornerLayer.cs
Labels: api, backport-candidate
