Repository AvaloniaUI/Avalonia, pull requests merged in 2022-02, with the labels that each got.

#6286 ItemsControl: WrapSelection
  samples/ControlCatalog/Pages/ComboBoxPage.xaml
  samples/ControlCatalog/Pages/ComboBoxPage.xaml.cs
  samples/ControlCatalog/Pages/ListBoxPage.xaml
  samples/ControlCatalog/ViewModels/ComboBoxPageViewModel.cs
  samples/ControlCatalog/ViewModels/ListBoxPageViewModel.cs
  src/Avalonia.Controls/ComboBox.cs
  src/Avalonia.Controls/ItemsControl.cs
  src/Avalonia.Controls/Presenters/ItemVirtualizerSimple.cs
  src/Avalonia.Controls/Primitives/SelectingItemsControl.cs
  src/Avalonia.Controls/VirtualizingStackPanel.cs
  tests/Avalonia.Controls.UnitTests/ListBoxTests.cs
Labels: enhancement, backport-candidate

#7548 fix 32 bit raspberry pi session manager seg fault
  src/Avalonia.X11/SMLib.cs
  src/Avalonia.X11/X11PlatformLifetimeEvents.cs
Labels: backport-candidate

#7537 Minimization bugfix on Windows
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: backport-candidate

#7581 Introduced RawPointerPoint for usage with IntermediatePoints
  src/Avalonia.Input/MouseDevice.cs
  src/Avalonia.Input/PointerEventArgs.cs
  src/Avalonia.Input/Raw/RawPointerEventArgs.cs
  src/Shared/RawEventGrouping.cs
Labels: backport-candidate

#7605 Add Skia Helper Methods to allow applying Skia Filter Effects (Blur, DropShadow, Lighting) to DC content
  src/Skia/Avalonia.Skia/Helpers/DrawingContextHelper.cs
Labels: backport-candidate

#7594 Implement `TextSearch.Text`
  src/Avalonia.Controls/Primitives/SelectingItemsControl.cs
  src/Avalonia.Controls/Primitives/TextSearch.cs
  tests/Avalonia.Controls.UnitTests/Primitives/SelectingItemsControlTests.cs
Labels: enhancement, API

#7634 Fix Date/Time picker popups
  src/Avalonia.Controls/DateTimePickers/DatePicker.cs
  src/Avalonia.Controls/DateTimePickers/DatePickerPresenter.cs
  src/Avalonia.Controls/DateTimePickers/TimePicker.cs
  src/Avalonia.Controls/DateTimePickers/TimePickerPresenter.cs
Labels: backport-candidate

#7506 MicroCOM Drag'n'Drop
  samples/ControlCatalog/MainView.xaml
  samples/ControlCatalog/Pages/ClipboardPage.xaml
  samples/ControlCatalog/Pages/ClipboardPage.xaml.cs
  samples/ControlCatalog/Pages/DragAndDropPage.xaml
  samples/ControlCatalog/Pages/DragAndDropPage.xaml.cs
  src/Avalonia.MicroCom/CallbackBase.cs
  src/Avalonia.MicroCom/MicroComRuntime.cs
  src/Avalonia.MicroCom/MicroComShadow.cs
  src/Avalonia.Native/AvaloniaNativeApplicationPlatform.cs
  src/Avalonia.Native/AvaloniaNativeDragSource.cs
  src/Avalonia.Native/AvaloniaNativePlatform.cs
  src/Avalonia.Native/CallbackBase.cs
  src/Avalonia.Native/DeferredFramebuffer.cs
  src/Avalonia.Native/IAvnMenu.cs
  src/Avalonia.Native/MenuActionCallback.cs
  src/Avalonia.Native/PlatformThreadingInterface.cs
  src/Avalonia.Native/PredicateCallback.cs
  src/Avalonia.Native/SystemDialogs.cs
  src/Avalonia.Native/WindowImplBase.cs
  src/Windows/Avalonia.Win32/ClipboardFormats.cs
  src/Windows/Avalonia.Win32/ClipboardImpl.cs
  src/Windows/Avalonia.Win32/DataObject.cs
  src/Windows/Avalonia.Win32/DragSource.cs
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/Windows/Avalonia.Win32/OleContext.cs
  src/Windows/Avalonia.Win32/OleDataObject.cs
  src/Windows/Avalonia.Win32/OleDragSource.cs
  src/Windows/Avalonia.Win32/OleDropTarget.cs
  src/Windows/Avalonia.Win32/Win32Com/win32.idl
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: bug, wont-backport

#7622 Exposing `Window.ChildWindows` collection
  src/Avalonia.Controls/Window.cs
Labels: backport-candidate

#7677 Remove DesktopRuntime project and move AppBuilder to PlatformSupport project
  Avalonia.sln
  build/CoreLibraries.props
  nukebuild/numerge.config
  src/Avalonia.Controls/ApiCompatBaseline.txt
  src/Avalonia.Controls/Platform/ExportWindowingSubsystemAttribute.cs
  src/Avalonia.DesktopRuntime/ApiCompatBaseline.txt
  src/Avalonia.DesktopRuntime/AppBuilder.cs
  src/Avalonia.DesktopRuntime/Avalonia.DesktopRuntime.csproj
  src/Avalonia.Native/Properties/AssemblyInfo.cs
  src/Avalonia.PlatformSupport/AppBuilder.cs
  src/Avalonia.PlatformSupport/Avalonia.PlatformSupport.csproj
  src/Avalonia.Visuals/ApiCompatBaseline.txt
  src/Avalonia.Visuals/Platform/ExportRenderingSubsystemAttribute.cs
  src/Windows/Avalonia.Direct2D1/Properties/AssemblyInfo.cs
  src/Windows/Avalonia.Win32/Properties/AssemblyInfo.cs
  tests/Avalonia.DesignerSupport.TestApp/Avalonia.DesignerSupport.TestApp.csproj
  tests/Avalonia.Direct2D1.RenderTests/Avalonia.Direct2D1.RenderTests.csproj
  tests/Avalonia.Skia.RenderTests/Avalonia.Skia.RenderTests.csproj
Labels: breaking-change, wont-backport

#6800 Introduce Typeface.Stretch and rework Typeface fallback selection
  src/Avalonia.Controls/Presenters/TextPresenter.cs
  src/Avalonia.Controls/TextBlock.cs
  src/Avalonia.Headless/HeadlessPlatformStubs.cs
  src/Avalonia.Visuals/ApiCompatBaseline.txt
  src/Avalonia.Visuals/Media/FontManager.cs
  src/Avalonia.Visuals/Media/FontStretch.cs
  src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs
  src/Avalonia.Visuals/Media/Typeface.cs
  src/Avalonia.Visuals/Platform/IFontManagerImpl.cs
  src/Skia/Avalonia.Skia/FontManagerImpl.cs
  src/Skia/Avalonia.Skia/SKTypefaceCollection.cs
  src/Skia/Avalonia.Skia/SKTypefaceCollectionCache.cs
  src/Windows/Avalonia.Direct2D1/Media/Direct2D1FontCollectionCache.cs
  src/Windows/Avalonia.Direct2D1/Media/FontManagerImpl.cs
  tests/Avalonia.Skia.UnitTests/Media/CustomFontManagerImpl.cs
  tests/Avalonia.UnitTests/HarfBuzzFontManagerImpl.cs
  tests/Avalonia.UnitTests/MockFontManagerImpl.cs
  tests/Avalonia.Visuals.UnitTests/Media/FontManagerTests.cs
Labels: wont-backport

#6953 Add TextBlock inlines support
  samples/ControlCatalog/Pages/TextBlockPage.xaml
  src/Avalonia.Base/Metadata/TrimSurroundingWhitespaceAttribute.cs
  src/Avalonia.Base/Metadata/WhitespaceSignificantCollectionAttribute.cs
  src/Avalonia.Controls/Documents/Bold.cs
  src/Avalonia.Controls/Documents/Inline.cs
  src/Avalonia.Controls/Documents/InlineCollection.cs
  src/Avalonia.Controls/Documents/Italic.cs
  src/Avalonia.Controls/Documents/LineBreak.cs
  src/Avalonia.Controls/Documents/Run.cs
  src/Avalonia.Controls/Documents/Span.cs
  src/Avalonia.Controls/Documents/TextElement.cs
  src/Avalonia.Controls/Documents/Underline.cs
  src/Avalonia.Controls/Properties/AssemblyInfo.cs
  src/Avalonia.Controls/TextBlock.cs
  src/Avalonia.Visuals/Avalonia.Visuals.csproj
  src/Avalonia.Visuals/Media/TextFormatting/FormattedTextSource.cs
  src/Avalonia.Visuals/Media/TextFormatting/TextCharacters.cs
  src/Avalonia.Visuals/Media/TextFormatting/TextRunProperties.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlLanguage.cs
  tests/Avalonia.Controls.UnitTests/TextBlockTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/BasicTests.cs
  tests/Avalonia.UnitTests/MockTextShaperImpl.cs
Labels: enhancement
