Repository AvaloniaUI/Avalonia, pull requests merged in 2022-08, with the labels that each got.

#8458 IStorageFolder.GetItemsAsync() + use Async suffix in storage provider methods
  samples/ControlCatalog/Pages/DialogsPage.xaml.cs
  src/Android/Avalonia.Android/Platform/Storage/AndroidStorageItem.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFile.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFolder.cs
  src/Avalonia.Base/Platform/Storage/IStorageBookmarkItem.cs
  src/Avalonia.Base/Platform/Storage/IStorageFile.cs
  src/Avalonia.Base/Platform/Storage/IStorageFolder.cs
  src/Avalonia.Base/Platform/Storage/IStorageItem.cs
  src/Web/Avalonia.Web.Blazor/Interop/Storage/StorageProviderInterop.cs
  src/Web/Avalonia.Web.Blazor/Interop/Typescript/StorageProvider.ts
  src/iOS/Avalonia.iOS/Storage/IOSStorageItem.cs
Labels: api, os-browser, os-ios, os-android

#8637 Use correct ToggleModifier in ListBox multiselection on MacOS.
  src/Avalonia.Controls/ListBox.cs
  tests/Avalonia.Controls.UnitTests/ListBoxTests_Single.cs
  tests/Avalonia.Controls.UnitTests/Primitives/SelectingItemsControlTests.cs
  tests/Avalonia.Controls.UnitTests/Primitives/SelectingItemsControlTests_Multiple.cs
Labels: bug, os-macos, backport-candidate

#8655 Use correct ToggleModifier in TreeView multiselection on MacOS
  src/Avalonia.Controls/TreeView.cs
  tests/Avalonia.Controls.UnitTests/TreeViewTests.cs
Labels: bug, os-macos, backport-candidate

#8670 Fix and test for #8669
  src/Avalonia.Controls/Presenters/ItemVirtualizerSimple.cs
  tests/Avalonia.Controls.UnitTests/ListBoxTests.cs
Labels: bug

#8676 Tweak TemplateBinding Initialization
  src/Markup/Avalonia.Markup/Data/TemplateBinding.cs
  tests/Avalonia.Markup.UnitTests/Data/TemplateBindingTests.cs
Labels: bug

#8663 Fix and optimize StringFormatConverter.
  src/Avalonia.Controls/Converters/StringFormatConverter.cs
Labels: bug, backport-candidate

#8656 Use GetFeature + API lease approach for accessing SKCanvas
  samples/RenderDemo/Pages/CustomSkiaPage.cs
  src/Avalonia.Base/Media/DrawingGroup.cs
  src/Avalonia.Base/Platform/IDrawingContextImpl.cs
  src/Avalonia.Base/Rendering/Composition/Drawing/CompositionDrawingContext.cs
  src/Avalonia.Base/Rendering/Composition/Server/DrawingContextProxy.cs
  src/Avalonia.Base/Rendering/SceneGraph/DeferredDrawingContextImpl.cs
  src/Avalonia.Headless/HeadlessPlatformRenderInterface.cs
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
  src/Skia/Avalonia.Skia/Helpers/DrawingContextHelper.cs
  src/Skia/Avalonia.Skia/ISkiaDrawingContextImpl.cs
  src/Skia/Avalonia.Skia/ISkiaSharpApiLeaseFeature.cs
  src/Windows/Avalonia.Direct2D1/Media/DrawingContextImpl.cs
  tests/Avalonia.Benchmarks/NullDrawingContextImpl.cs
Labels: api, breaking-change

#8686 Enable android composition renderer
  src/Android/Avalonia.Android/AndroidPlatform.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
Labels: os-android

#8683 Stop TransitioningContentControl if it was cancelled
  src/Avalonia.Controls/TransitioningContentControl.cs
Labels: bug, backport-candidate

#8685 Delete legacy ReactiveUI.TransitioningContentControl
  src/Avalonia.ReactiveUI/RoutedViewHost.cs
  src/Avalonia.ReactiveUI/TransitioningContentControl.cs
  src/Avalonia.ReactiveUI/ViewModelViewHost.cs
  tests/Avalonia.ReactiveUI.UnitTests/TransitioningContentControlTest.cs
Labels: breaking-change

#8691 Optimize CurrentThreadIsLoopThread on android backend
  src/Android/Avalonia.Android/AndroidThreadingInterface.cs
Labels: perf, os-android

#8692 Disable hardcoded FPS
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
Labels: os-android

#8699 Backport PR 7778
  src/Avalonia.Visuals/Rendering/SceneGraph/GeometryBoundsHelper.cs
  src/Avalonia.Visuals/Rendering/SceneGraph/GeometryNode.cs
Labels: bug, backport-candidate

#8706 Fix composition rendering after render target was corrupted
  src/Android/Avalonia.Android/AndroidPlatform.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionTarget.cs
Labels: bug, area-ncomp

#8618 macos: Don't reopen hidden window when parent clicked.
  native/Avalonia.Native/src/OSX/WindowImpl.mm
  samples/IntegrationTestApp/MainWindow.axaml.cs
  samples/IntegrationTestApp/ShowWindowTest.axaml
  tests/Avalonia.IntegrationTests.Appium/WindowTests_MacOS.cs
Labels: bug, os-macos, backport-candidate

#8725 Simplify class creation for BclStorageFile\BclStorageFolder
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFile.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFolder.cs
Labels: enhancement

#8734 Fixed glActiveTexture calls
  src/Avalonia.OpenGL/Controls/OpenGlControlBase.cs
  src/Skia/Avalonia.Skia/Gpu/OpenGl/OpenGlBitmapImpl.cs
Labels: backport-candidate

#8668 Implement DataContext update notifications on the DataGrid
  src/Avalonia.Controls.DataGrid/DataGrid.cs
Labels: bug, area-datagrid

#8739 Update SkiaSharp
  build/HarfBuzzSharp.props
  build/SkiaSharp.props
Labels: backport-candidate

#8707 Remove obsolete members from Avalonia.Base namespace
  src/Avalonia.Base/Animation/Animation.cs
  src/Avalonia.Base/Animation/Animators/SolidColorBrushAnimator.cs
  src/Avalonia.Base/AvaloniaObjectExtensions.cs
  src/Avalonia.Base/AvaloniaProperty`1.cs
  src/Avalonia.Base/Collections/AvaloniaListExtensions.cs
  src/Avalonia.Base/DirectPropertyBase.cs
  src/Avalonia.Base/EnumExtensions.cs
  src/Avalonia.Base/Interactivity/RoutedEvent.cs
  src/Avalonia.Base/Layout/ILayoutManager.cs
  src/Avalonia.Base/Layout/LayoutManager.cs
  src/Avalonia.Base/Layout/Layoutable.cs
  src/Avalonia.Base/Media/Imaging/Bitmap.cs
  src/Avalonia.Base/Media/Imaging/WriteableBitmap.cs
  src/Avalonia.Base/Utilities/WeakObservable.cs
  src/Avalonia.Base/Utilities/WeakSubscriptionManager.cs
  src/Avalonia.Base/Visual.cs
  src/Avalonia.Base/VisualTree/IVisualTreeHost.cs
  src/Avalonia.Controls/Primitives/Popup.cs
  src/Avalonia.Controls/Remote/RemoteWidget.cs
  src/Avalonia.X11/X11IconLoader.cs
  tests/Avalonia.Base.UnitTests/Collections/AvaloniaListExtenionsTests.cs
  tests/Avalonia.Base.UnitTests/WeakSubscriptionManagerTests.cs
  tests/Avalonia.RenderTests/Media/BitmapTests.cs
Labels: breaking-change, wont-backport

#8738 Update and fix ReactiveUI on master branch + ios
  build/ReactiveUI.props
  src/Avalonia.Controls/Control.cs
  src/Avalonia.ReactiveUI/AvaloniaActivationForViewFetcher.cs
  src/Avalonia.ReactiveUI/RoutedViewHost.cs
  src/Avalonia.ReactiveUI/ViewModelViewHost.cs
  tests/Avalonia.Controls.UnitTests/LoadedTests.cs
  tests/Avalonia.ReactiveUI.UnitTests/AutoSuspendHelperTest.cs
  tests/Avalonia.ReactiveUI.UnitTests/AvaloniaActivationForViewFetcherTest.cs
  tests/Avalonia.ReactiveUI.UnitTests/ReactiveUserControlTest.cs
  tests/Avalonia.ReactiveUI.UnitTests/ReactiveWindowTest.cs
  tests/Avalonia.ReactiveUI.UnitTests/RoutedViewHostTest.cs
  tests/Avalonia.ReactiveUI.UnitTests/ViewModelViewHostTest.cs
Labels: bug, bug-in-dependency

#8732 Remove obsolete members from Avalonia.Controls assembly.
  samples/ControlCatalog/DecoratedWindow.xaml
  samples/ControlCatalog/MainWindow.xaml
  samples/ControlCatalog/Pages/NumericUpDownPage.xaml
  samples/ControlCatalog/ViewModels/ContextPageViewModel.cs
  samples/ControlCatalog/ViewModels/MenuPageViewModel.cs
  samples/RenderDemo/Pages/DrawingPage.xaml
  src/Avalonia.Controls.ColorPicker/Themes/Fluent/Fluent.xaml
  src/Avalonia.Controls.ColorPicker/Themes/Simple/Simple.xaml
  src/Avalonia.Controls/DesktopApplicationExtensions.cs
  src/Avalonia.Controls/DrawingPresenter.cs
  src/Avalonia.Controls/LoggingExtensions.cs
  src/Avalonia.Controls/NativeMenuItem.cs
  src/Avalonia.Controls/NativeMenuItemSeparator.cs
  src/Avalonia.Controls/NumericUpDown/NumericUpDown.cs
  src/Avalonia.Controls/Primitives/Popup.cs
  src/Avalonia.Controls/Primitives/TemplatedControl.cs
  src/Avalonia.Controls/ProgressBar.cs
  src/Avalonia.Controls/RichTextBlock.cs
  src/Avalonia.Controls/SystemDialog.cs
  src/Avalonia.Controls/TextBox.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.Controls/Window.cs
  src/Avalonia.Controls/WindowBase.cs
  src/Avalonia.Diagnostics/Diagnostics/Screenshots/FilePickerHandler.cs
  src/Avalonia.Dialogs/AboutAvaloniaDialog.xaml
  src/Avalonia.Themes.Fluent/Controls/ManagedFileChooser.xaml
  src/Avalonia.Themes.Simple/Controls/CalendarDatePicker.xaml
Labels: breaking-change, wont-backport

#8755 Remove obsolete members from remaining assemblies
  samples/ControlCatalog.NetCore/Program.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/InvalidationAwareSurfaceView.cs
  src/Avalonia.Controls.DataGrid/Collections/DataGridSortDescription.cs
  src/Avalonia.Dialogs/ManagedFileChooser.cs
  src/Markup/Avalonia.Markup.Xaml/XamlIl/Runtime/XamlIlRuntimeHelpers.cs
  src/Skia/Avalonia.Skia/Helpers/DrawingContextHelper.cs
  src/Windows/Avalonia.Win32/Win32Platform.cs
Labels: breaking-change, wont-backport

#8698 Revamp android input handling to support mouse, pen and historical points
  samples/ControlCatalog/Pages/PointersPage.xaml.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
  src/Android/Avalonia.Android/Platform/Specific/Helpers/AndroidMotionEventsHelper.cs
  src/Android/Avalonia.Android/Platform/Specific/Helpers/AndroidTouchEventsHelper.cs
  src/Avalonia.Base/Input/Raw/RawPointerEventArgs.cs
Labels: enhancement, os-android

#8817 Fix Fluent theme port bugs
  src/Avalonia.Controls.DataGrid/Themes/Fluent.xaml
  src/Avalonia.Themes.Fluent/Controls/ButtonSpinner.xaml
  src/Avalonia.Themes.Fluent/Controls/DatePicker.xaml
  src/Avalonia.Themes.Fluent/Controls/TimePicker.xaml
Labels: bug, wont-backport

#8850 [Blazor] Disable auto-capitalization of input element text in AvaloniaView
  src/Web/Avalonia.Web.Blazor/AvaloniaView.razor
Labels: bug, os-browser
