Repository AvaloniaUI/Avalonia, pull requests merged in 2022-07, with the labels that each got.

#7412 [Win] WM_Pointer pen support
  .editorconfig
  samples/ControlCatalog.NetCore/Program.cs
  samples/ControlCatalog/MainView.xaml
  samples/ControlCatalog/Pages/PointerCanvas.cs
  samples/ControlCatalog/Pages/PointerContactsTab.cs
  samples/ControlCatalog/Pages/PointersPage.cs
  samples/ControlCatalog/Pages/PointersPage.xaml
  samples/ControlCatalog/Pages/PointersPage.xaml.cs
  src/Avalonia.Base/Input/GestureRecognizers/ScrollGestureRecognizer.cs
  src/Avalonia.Base/Input/IKeyboardDevice.cs
  src/Avalonia.Base/Input/IPenDevice.cs
  src/Avalonia.Base/Input/IPointer.cs
  src/Avalonia.Base/Input/PenDevice.cs
  src/Avalonia.Base/Input/PointerEventArgs.cs
  src/Avalonia.Base/Input/PointerPoint.cs
  src/Avalonia.Base/Input/Raw/RawPointerEventArgs.cs
  src/Avalonia.Base/Input/Raw/RawTouchEventArgs.cs
  src/Avalonia.Base/Input/TouchDevice.cs
  src/Avalonia.Controls.DataGrid/DataGridCell.cs
  src/Shared/RawEventGrouping.cs
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/Windows/Avalonia.Win32/Win32Platform.cs
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
  tests/Avalonia.Base.UnitTests/Input/TouchDeviceTests.cs
Labels: enhancement, api, os-windows, wont-backport, inactive

#8409 Don't promote layout property values to local values in DevTools.
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ControlLayoutViewModel.cs
Labels: bug, backport-candidate

#8427 Fix crash in deferred renderer when reparenting a control.
  src/Avalonia.Base/Rendering/SceneGraph/SceneBuilder.cs
  tests/Avalonia.Base.UnitTests/Rendering/SceneGraph/SceneBuilderTests.cs
Labels: bug, area-rendering, backport-candidate

#8431 Remove perf-expensive DottedLineFocusAdorner style
  src/Avalonia.Themes.Fluent/Controls/FocusAdorner.xaml
Labels: enhancement, perf, backport-candidate, area-fluent

#8416 [Blazor] Prevent input focus leaving the TextBox after first click
  src/Web/Avalonia.Web.Blazor/AvaloniaView.razor
  src/Web/Avalonia.Web.Blazor/AvaloniaView.razor.cs
Labels: bug, os-browser

#8412 Apply target's TemplatedParent to a Flyout and Tooltip, when it's opened
  src/Avalonia.Controls/Flyouts/FlyoutBase.cs
  src/Avalonia.Controls/Primitives/Popup.cs
  src/Avalonia.Controls/Primitives/TemplatedControl.cs
  src/Avalonia.Controls/ToolTip.cs
  tests/Avalonia.LeakTests/ControlTests.cs
  tests/Avalonia.Markup.UnitTests/Data/TemplateBindingTests.cs
Labels: bug

#8442 Fix empty batch nested updates.
  src/Avalonia.Base/ValueStore.cs
  tests/Avalonia.Base.UnitTests/AvaloniaObjectTests_BatchUpdate.cs
Labels: bug, backport-candidate

#8417 [Blazor] Implement Skia Raster backend for rendering to HTML canvas
  samples/ControlCatalog.Web/App.razor.cs
  src/Web/Avalonia.Web.Blazor/AvaloniaView.razor.cs
  src/Web/Avalonia.Web.Blazor/BlazorSkiaRasterSurface.cs
  src/Web/Avalonia.Web.Blazor/BlazorSkiaSurface.cs
  src/Web/Avalonia.Web.Blazor/IBlazorSkiaSurface.cs
  src/Web/Avalonia.Web.Blazor/RazorViewTopLevelImpl.cs
Labels: enhancement, area-rendering, os-browser

#8456 make splitview not culture sensitive.
  src/Avalonia.Controls/SplitView.cs
Labels: backport-candidate

#8452 fix(DataGrid): CS8073 The result of the expression is always 'true'
  src/Avalonia.Controls.DataGrid/DataGrid.cs
Labels: bug, area-datagrid

#8433 Improve performance of style class selector subscriptions
  src/Avalonia.Base/Controls/Classes.cs
  src/Avalonia.Base/Controls/IClassesChangedListener.cs
  src/Avalonia.Base/Styling/Activators/StyleClassActivator.cs
  src/Avalonia.Base/Styling/TypeNameAndClassSelector.cs
  tests/Avalonia.Base.UnitTests/Styling/SelectorTests_Template.cs
  tests/Avalonia.Benchmarks/Styling/Style_ClassSelector.cs
  tests/Avalonia.LeakTests/ControlTests.cs
Labels: perf, backport-candidate

#8466 More compiled binding fixes
  src/Avalonia.Diagnostics/Diagnostics/Controls/FilterTextBox.axaml
  src/Avalonia.Themes.Fluent/Controls/MenuItem.xaml
  src/Avalonia.Themes.Fluent/Controls/ProgressBar.xaml
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlCompiler.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlBindingPathParser.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlBindingPathTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/XamlIlBindingPathHelper.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindings/CompiledBindingPath.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/CompiledBindingExtensionTests.cs
Labels: bug, area-xaml

#8474 Fix overwriting TemplatedParent when opening a Popup.
  src/Avalonia.Controls/Primitives/TemplatedControl.cs
  tests/Avalonia.Controls.UnitTests/MenuItemTests.cs
  tests/Avalonia.Controls.UnitTests/Primitives/PopupTests.cs
Labels: bug

#8451 fix: DBus Null annotations
  Avalonia.sln
  src/Avalonia.FreeDesktop/Avalonia.FreeDesktop.csproj
  src/Avalonia.FreeDesktop/DBusCallQueue.cs
  src/Avalonia.FreeDesktop/DBusHelper.cs
  src/Avalonia.FreeDesktop/DBusIme/DBusTextInputMethodBase.cs
  src/Avalonia.FreeDesktop/DBusIme/Fcitx/FcitxDBus.cs
  src/Avalonia.FreeDesktop/DBusIme/Fcitx/FcitxICWrapper.cs
  src/Avalonia.FreeDesktop/DBusIme/Fcitx/FcitxX11TextInputMethod.cs
  src/Avalonia.FreeDesktop/DBusIme/IBus/IBusDBus.cs
  src/Avalonia.FreeDesktop/DBusIme/IBus/IBusX11TextInputMethod.cs
  src/Avalonia.FreeDesktop/DBusIme/X11DBusImeHelper.cs
  src/Avalonia.FreeDesktop/DBusMenu.cs
  src/Avalonia.FreeDesktop/DBusMenuExporter.cs
  src/Avalonia.FreeDesktop/DBusRequest.cs
  src/Avalonia.FreeDesktop/LinuxMountedVolumeInfoProvider.cs
  src/Avalonia.SourceGenerator/Avalonia.SourceGenerator.csproj
  src/Linux/Avalonia.LinuxFramebuffer/Output/DrmOutput.cs
  src/Shared/IsExternalInit.cs
Labels: os-linux

#8483 Fix initial window size on osx
  native/Avalonia.Native/src/OSX/AvnView.mm
Labels: backport-candidate

#8482 window centering edge case
  src/Avalonia.Controls/Window.cs
  tests/Avalonia.Controls.UnitTests/WindowTests.cs
  tests/Avalonia.UnitTests/MockWindowingPlatform.cs
Labels: backport-candidate

#8492 Fix reentrancy problem in Classes listeners.
  .ncrunch/ControlCatalog.net6.0.v3.ncrunchproject
  .ncrunch/ControlCatalog.netstandard2.0.v3.ncrunchproject
  src/Avalonia.Base/Controls/Classes.cs
  src/Avalonia.Base/Utilities/SafeEnumerableList.cs
  tests/Avalonia.Controls.UnitTests/ClassesTests.cs
  tests/Avalonia.Controls.UnitTests/Utils/SafeEnumerableListTests.cs
Labels: backport-candidate

#8518 Backport native control host handle validation
  src/Windows/Avalonia.Win32/Win32NativeControlHost.cs
Labels: os-windows, backport-candidate, backported-0.10.x

#8520 fix: RowDesiredWidth was missing the RowHeaderWidth
  src/Avalonia.Controls.DataGrid/Primitives/DataGridRowsPresenter.cs
Labels: backport-candidate

#8523 Allow to pass custom `IMenuInteractionHandler` to `MenuFlyoutPresenter`
  src/Avalonia.Controls/Flyouts/MenuFlyoutPresenter.cs
  src/Avalonia.Controls/MenuBase.cs
Labels: api

#8531 `ComboBoxMinHeight` should be of Type `double`, not `Thickness`
  src/Avalonia.Themes.Fluent/DensityStyles/Compact.xaml
Labels: bug, area-fluent

#8538 Introduced GtkInteropHelper.RunOnGlibThread, fixed demos
  samples/ControlCatalog.NetCore/NativeControls/Gtk/EmbedSample.Gtk.cs
  samples/ControlCatalog.NetCore/NativeControls/Gtk/GtkHelper.cs
  src/Avalonia.X11/Interop/GtkInteropHelper.cs
  src/Avalonia.X11/NativeDialogs/Gtk.cs
Labels: backport-candidate

#8540 Fix typo in DataGrid
  src/Avalonia.Controls.DataGrid/Collections/DataGridSortDescription.cs
  src/Avalonia.Controls.DataGrid/DataGridColumn.cs
Labels: area-datagrid, breaking-change

#8547 Tray icon fixes
  samples/ControlCatalog/App.xaml
  src/Avalonia.Controls/TrayIcon.cs
  src/Avalonia.Themes.Default/Controls/NativeMenuBar.xaml
  src/Avalonia.Themes.Fluent/Controls/NativeMenuBar.xaml
  src/Windows/Avalonia.Win32/IconImpl.cs
  src/Windows/Avalonia.Win32/TrayIconImpl.cs
  src/Windows/Avalonia.Win32/Win32NativeToManagedMenuExporter.cs
  src/Windows/Avalonia.Win32/Win32Platform.cs
Labels: bug, os-windows, backport-candidate

#8548 Abstract linux DBus and GTK storage providers, use async initialization
  Avalonia.sln
  src/Avalonia.FreeDesktop/DBusHelper.cs
  src/Avalonia.FreeDesktop/DBusSystemDialog.cs
  src/Avalonia.X11/NativeDialogs/CompositeStorageProvider.cs
  src/Avalonia.X11/NativeDialogs/Gtk.cs
  src/Avalonia.X11/NativeDialogs/GtkNativeFileDialogs.cs
  src/Avalonia.X11/X11Platform.cs
  src/Avalonia.X11/X11Window.cs
Labels: bug, os-linux

#8577 Remove all obsolete members from Input namespace
  src/Avalonia.Base/Input/Cursor.cs
  src/Avalonia.Base/Input/DragEventArgs.cs
  src/Avalonia.Base/Input/GotFocusEventArgs.cs
  src/Avalonia.Base/Input/IInputRoot.cs
  src/Avalonia.Base/Input/IKeyboardDevice.cs
  src/Avalonia.Base/Input/IMouseDevice.cs
  src/Avalonia.Base/Input/IPointerDevice.cs
  src/Avalonia.Base/Input/KeyEventArgs.cs
  src/Avalonia.Base/Input/KeyGesture.cs
  src/Avalonia.Base/Input/MouseDevice.cs
  src/Avalonia.Base/Input/PenDevice.cs
  src/Avalonia.Base/Input/PointerEventArgs.cs
  src/Avalonia.Base/Input/PointerOverPreProcessor.cs
  src/Avalonia.Base/Input/Raw/RawDragEvent.cs
  src/Avalonia.Base/Input/Raw/RawTouchEventArgs.cs
  src/Avalonia.Base/Input/TouchDevice.cs
  src/Avalonia.Controls/Platform/ITopLevelImpl.cs
  src/Avalonia.Controls/Primitives/PopupPositioning/IPopupPositioner.cs
  src/Avalonia.Controls/Remote/Server/RemoteServerTopLevelImpl.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/MainWindow.xaml.cs
  src/Windows/Avalonia.Win32.Interop/Wpf/WpfTopLevelImpl.cs
  src/Windows/Avalonia.Win32/Input/WindowsMouseDevice.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
  tests/Avalonia.Base.UnitTests/Input/MouseDeviceTests.cs
  tests/Avalonia.Base.UnitTests/Input/PointerOverTests.cs
  tests/Avalonia.Base.UnitTests/Input/PointerTestsBase.cs
  tests/Avalonia.UnitTests/MockWindowingPlatform.cs
  tests/Avalonia.UnitTests/TestRoot.cs
Labels: breaking-change

#8597 Set WM_CLASS property according to ICCCM spec
  src/Avalonia.X11/X11Platform.cs
  src/Avalonia.X11/X11Window.cs
  src/Avalonia.X11/XLib.cs
Labels: backport-candidate, area-x11

#8601 Workaround for SkiaSharp broken image decoding.
  src/Skia/Avalonia.Skia/ImmutableBitmap.cs
  src/Skia/Avalonia.Skia/WriteableBitmapImpl.cs
Labels: bug, bug-in-dependency, backport-candidate

#8604 Don't throw exceptions for missing windowing platform since it's actually not mandatory for TrayIcon
  src/Avalonia.Controls/Platform/PlatformManager.cs
Labels: bug, os-linux, backport-candidate

#8599 Scene hittest now uses exclusive `Rect.Contains`. Fixes https://githu…
  src/Avalonia.Base/Rendering/SceneGraph/ExperimentalAcrylicNode.cs
  src/Avalonia.Base/Rendering/SceneGraph/GlyphRunNode.cs
  src/Avalonia.Base/Rendering/SceneGraph/ImageNode.cs
  src/Avalonia.Base/Rendering/SceneGraph/RectangleNode.cs
  src/Avalonia.Base/Rendering/SceneGraph/Scene.cs
  tests/Avalonia.Base.UnitTests/Rendering/CompositorHitTestingTests.cs
  tests/Avalonia.Base.UnitTests/Rendering/DeferredRendererTests_HitTesting.cs
Labels: bug, backport-candidate
