Repository AvaloniaUI/Avalonia, pull requests merged in 2022-05, with the labels that each got.

#8042 Make ComboBox dropdown respect scale transform
  samples/ControlCatalog/Pages/ComboBoxPage.xaml
  src/Avalonia.Controls/Primitives/IPopupHost.cs
  src/Avalonia.Controls/Primitives/OverlayPopupHost.cs
  src/Avalonia.Controls/Primitives/Popup.cs
  src/Avalonia.Controls/Primitives/PopupRoot.cs
  src/Avalonia.Themes.Default/Controls/OverlayPopupHost.xaml
  src/Avalonia.Themes.Default/Controls/PopupRoot.xaml
  src/Avalonia.Themes.Fluent/Controls/ComboBox.xaml
  src/Avalonia.Themes.Fluent/Controls/OverlayPopupHost.xaml
  src/Avalonia.Themes.Fluent/Controls/PopupRoot.xaml
  tests/Avalonia.Controls.UnitTests/Primitives/PopupRootTests.cs
  tests/Avalonia.Controls.UnitTests/Primitives/PopupTests.cs
Labels: rendering, wont-backport

#8084 Use top level to inform about pointer input
  src/iOS/Avalonia.iOS/TouchHandler.cs
Labels: bug, ios

#8089 OSX: use content min/max size for minsize.
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
Labels: backport-candidate

#8106 Make ThreadSafeObjectPool actually thread safe
  src/Avalonia.Base/Threading/ThreadSafeObjectPool.cs
Labels: backport-candidate

#8114 Fix property registrations
  src/Avalonia.Base/Layout/UniformGridLayout.cs
  src/Avalonia.Base/Media/ConicGradientBrush.cs
  src/Avalonia.Controls/ContextMenu.cs
  src/Avalonia.Controls/DockPanel.cs
  src/Avalonia.Controls/MaskedTextBox.cs
  src/Avalonia.Controls/Presenters/TextPresenter.cs
  src/Avalonia.Controls/Primitives/Popup.cs
  src/Avalonia.Controls/Primitives/SelectingItemsControl.cs
  src/Avalonia.Controls/Primitives/Track.cs
  src/Avalonia.Controls/Slider.cs
  src/Avalonia.Controls/SplitView.cs
  src/Avalonia.Controls/TextBox.cs
Labels: backport-candidate

#8126 Fix property owner type registrations
  src/Avalonia.Controls/DateTimePickers/TimePicker.cs
  src/Avalonia.Controls/Primitives/SelectingItemsControl.cs
Labels: backport-candidate

#8141 Fix PointerMovedEvent name registration
  src/Avalonia.Base/Input/InputElement.cs
  tests/Avalonia.Base.UnitTests/Input/PointerOverTests.cs
Labels: backport-candidate

#8148 Move Fluent/Default themes out of main package
  build/CoreLibraries.props
  samples/BindingDemo/BindingDemo.csproj
  samples/ControlCatalog/ControlCatalog.csproj
  samples/IntegrationTestApp/IntegrationTestApp.csproj
  samples/PlatformSanityChecks/PlatformSanityChecks.csproj
  samples/Previewer/Previewer.csproj
  samples/RenderDemo/RenderDemo.csproj
  samples/Sandbox/Sandbox.csproj
  samples/VirtualizationDemo/VirtualizationDemo.csproj
  samples/interop/Direct3DInteropSample/Direct3DInteropSample.csproj
  samples/interop/NativeEmbedSample/NativeEmbedSample.csproj
Labels: enhancement, breaking-change, fluent

#8147 Routing event fixes
  src/Avalonia.Base/Input/InputElement.cs
  src/Avalonia.Controls/Primitives/SelectingItemsControl.cs
  src/Avalonia.Controls/Primitives/TemplatedControl.cs
  src/Avalonia.Controls/TextBox.cs
  src/Avalonia.Controls/Window.cs
Labels: backport-candidate

#8095 Respect Window MaxWidth and MaxHeight when using any SizeToContent to Auto
  src/Avalonia.Controls/Window.cs
  tests/Avalonia.Controls.UnitTests/WindowTests.cs
Labels: bug, backport-candidate

#7555 Fix visibility layout invalidation
  src/Avalonia.Base/Layout/Layoutable.cs
  tests/Avalonia.Base.UnitTests/Layout/LayoutableTests.cs
Labels: bug, backport-candidate

#8163 Avoid static references in DataGrid fluent theme
  src/Avalonia.Controls.DataGrid/Themes/Fluent.xaml
Labels: bug, datagrid

#8180 Fixes/osx popup flyout fixes
  native/Avalonia.Native/src/OSX/AvnWindow.mm
  native/Avalonia.Native/src/OSX/PopupImpl.mm
  native/Avalonia.Native/src/OSX/WindowBaseImpl.h
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
  native/Avalonia.Native/src/OSX/WindowImpl.h
  native/Avalonia.Native/src/OSX/WindowImpl.mm
  native/Avalonia.Native/src/OSX/WindowProtocol.h
Labels: backport-candidate

#8172 Fix Menu selection to match UWP.
  src/Avalonia.Controls/Platform/DefaultMenuInteractionHandler.cs
Labels: bug, backport-candidate

#8176 Don't cast android scaling from double to int
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
Labels: bug, android

#8188 Fix osx dialog style mask
  native/Avalonia.Native/src/OSX/WindowImpl.mm
Labels: backport-candidate

#8187 OSX: fix file dialog filter nullable annotation, and osx platform.
  samples/ControlCatalog/ControlCatalog.csproj
  samples/ControlCatalog/Pages/DialogsPage.xaml.cs
  src/Avalonia.Controls/SystemDialog.cs
  src/Avalonia.Native/SystemDialogs.cs
Labels: backport-candidate

#8036 Add `TransformOrigin` to Brushes
  src/Avalonia.Base/Animation/Animators/GradientBrushAnimator.cs
  src/Avalonia.Base/Media/Brush.cs
  src/Avalonia.Base/Media/IBrush.cs
  src/Avalonia.Base/Media/Immutable/ImmutableConicGradientBrush.cs
  src/Avalonia.Base/Media/Immutable/ImmutableGradientBrush.cs
  src/Avalonia.Base/Media/Immutable/ImmutableImageBrush.cs
  src/Avalonia.Base/Media/Immutable/ImmutableLinearGradientBrush.cs
  src/Avalonia.Base/Media/Immutable/ImmutableRadialGradientBrush.cs
  src/Avalonia.Base/Media/Immutable/ImmutableSolidColorBrush.cs
  src/Avalonia.Base/Media/Immutable/ImmutableTileBrush.cs
  src/Avalonia.Base/Media/Immutable/ImmutableVisualBrush.cs
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
Labels: enhancement, API

#8189 Make AvaloniaPropertyAccessorPlugin use weak events.
  src/Avalonia.Base/Collections/Pooled/PooledList.cs
  src/Avalonia.Base/Data/Core/Plugins/AvaloniaPropertyAccessorPlugin.cs
  src/Avalonia.Base/Utilities/WeakEvents.cs
  tests/Avalonia.LeakTests/ControlTests.cs
Labels: backport-candidate

#8228 Don't allow bindings to private methods
  src/Avalonia.Base/Data/Converters/DefaultValueConverter.cs
  tests/Avalonia.Markup.UnitTests/Data/BindingTests_Method.cs
Labels: bug, wont-backport
