Repository AvaloniaUI/Avalonia, pull requests merged in 2022-01, with the labels that each got.

#7298 Check for null visual parent.
  src/Avalonia.Visuals/Rendering/SceneGraph/SceneBuilder.cs
Labels: bug, backport-candidate

#7302 [MacOS] fix quit menu item copy paste mistake
  src/Avalonia.Native/AvaloniaNativeMenuExporter.cs
Labels: backport-candidate

#7300 [WASM] Fix cursors in macOS, fix default cursor set logic
  src/Web/Avalonia.Web.Blazor/AvaloniaView.razor.cs
  src/Web/Avalonia.Web.Blazor/RazorViewTopLevelImpl.cs
Labels: backport-candidate

#7299 Add additional null checks to Avalonia.Native.WindowBaseImpl.
  src/Avalonia.Native/WindowImplBase.cs
Labels: bug, osx, backport-candidate

#7320 ListBox should respect ClipToBounds
  src/Avalonia.Themes.Fluent/Controls/ListBox.xaml
Labels: enhancement, backport-candidate

#6948 Fix DataGrid SelectionChanged event not raised after 3 right clicks
  src/Avalonia.Controls.DataGrid/DataGrid.cs
Labels: bug, datagrid, backport-candidate

#7341 Fixes/standard osx item generation
  samples/ControlCatalog/App.xaml
  src/Avalonia.Dialogs/AboutAvaloniaDialog.xaml
  src/Avalonia.Dialogs/Avalonia.Dialogs.csproj
  src/Avalonia.Native/AvaloniaNativeMenuExporter.cs
Labels: backport-candidate

#7350 Fix Skia FormattedTextImpl text alignment
  src/Skia/Avalonia.Skia/FormattedTextImpl.cs
Labels: backport-candidate

#7370 Another workaround for broken TopLevel.cs causing crash on X11
  src/Avalonia.X11/X11Window.cs
Labels: backport-candidate

#7373 Fix NRE on window close with opened menu
  src/Avalonia.Controls/Platform/DefaultMenuInteractionHandler.cs
Labels: bug, backport-candidate

#7368 Set antialias to true when calling ClipRoundRect
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
Labels: backport-candidate

#7336 Enable ClearType on Windows
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
  src/Skia/Avalonia.Skia/PlatformRenderInterface.cs
Labels: backport-candidate

#7236 Better fix for #6830
  src/Avalonia.Themes.Fluent/Controls/NumericUpDown.xaml
Labels: bug, regression, backport-candidate

#7385 Use the new syntax for a simple theme in DevTools and fix the crash.
  src/Avalonia.Diagnostics/Diagnostics/Views/MainWindow.xaml
Labels: wont-backport

#7374 win32: Don't raise TextInput event when KeyDown was handled (Attempt #2)
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: bug, backport-candidate

#7388 Use CompiledBindings for Fluent theme
  src/Avalonia.Themes.Fluent/Controls/ButtonSpinner.xaml
  src/Avalonia.Themes.Fluent/Controls/CalendarDatePicker.xaml
  src/Avalonia.Themes.Fluent/Controls/CalendarItem.xaml
  src/Avalonia.Themes.Fluent/Controls/DataValidationErrors.xaml
  src/Avalonia.Themes.Fluent/Controls/DatePicker.xaml
  src/Avalonia.Themes.Fluent/Controls/Expander.xaml
  src/Avalonia.Themes.Fluent/Controls/ManagedFileChooser.xaml
  src/Avalonia.Themes.Fluent/Controls/MenuItem.xaml
  src/Avalonia.Themes.Fluent/Controls/NativeMenuBar.xaml
  src/Avalonia.Themes.Fluent/Controls/ProgressBar.xaml
  src/Avalonia.Themes.Fluent/Controls/TabItem.xaml
  src/Avalonia.Themes.Fluent/Controls/TabStripItem.xaml
  src/Avalonia.Themes.Fluent/Controls/TextBox.xaml
  src/Avalonia.Themes.Fluent/Controls/TimePicker.xaml
  src/Avalonia.Themes.Fluent/Controls/ToolTip.xaml
  src/Avalonia.Themes.Fluent/Controls/WindowNotificationManager.xaml
Labels: enhancement, backport-candidate, fluent

#7405 Fix UseRenderTransformProperty registration typo
  src/Avalonia.Controls/LayoutTransformControl.cs
Labels: bug, backport-candidate

#7397 Fix text wrapping behavior
  src/Avalonia.Visuals/Media/TextFormatting/TextFormatterImpl.cs
  src/Avalonia.Visuals/Media/TextFormatting/TextLayout.cs
Labels: backport-candidate

#7409 Butter Smooth resizing in Browser
  src/Avalonia.Visuals/Properties/AssemblyInfo.cs
  src/Avalonia.Visuals/Rendering/DeferredRenderer.cs
  src/Web/Avalonia.Web.Blazor/AvaloniaView.razor.cs
  src/Web/Avalonia.Web.Blazor/Interop/SKHtmlCanvasInterop.cs
  src/Web/Avalonia.Web.Blazor/Interop/Typescript/SKHtmlCanvas.ts
Labels: enhancement, browser

#7321 [macOS] DataGrid - handle OSX key modifiers (ctrl vs cmd)
  src/Avalonia.Controls.DataGrid/DataGridColumn.cs
  src/Avalonia.Controls.DataGrid/Utils/KeyboardHelper.cs
Labels: enhancement, datagrid, backport-candidate

#6564 [OSX] Trackpad gestures - Magnify (Pitch to zoom), Rotate and Swipe
  native/Avalonia.Native/src/OSX/window.mm
  src/Avalonia.Input/Gestures.cs
  src/Avalonia.Input/InputElement.cs
  src/Avalonia.Input/MouseDevice.cs
  src/Avalonia.Input/PointerDeltaEventArgs.cs
  src/Avalonia.Input/Raw/RawPointerEventArgs.cs
  src/Avalonia.Input/Raw/RawPointerGestureEventArgs.cs
  src/Avalonia.Native/WindowImplBase.cs
  src/Avalonia.Native/avn.idl
Labels: enhancement, API, osx

#7411 fix deadlock from X11Window on close
  src/Avalonia.X11/X11Window.cs
Labels: backport-candidate

#7413 Added GetIntermediatePoints support for X11, libinput and evdev
  samples/ControlCatalog/Pages/PointersPage.cs
  src/Avalonia.Base/Threading/Dispatcher.cs
  src/Avalonia.Base/Threading/JobRunner.cs
  src/Avalonia.Input/MouseDevice.cs
  src/Avalonia.Input/PointerEventArgs.cs
  src/Avalonia.Input/Raw/RawInputEventArgs.cs
  src/Avalonia.Input/Raw/RawPointerEventArgs.cs
  src/Avalonia.Input/TouchDevice.cs
  src/Avalonia.X11/Avalonia.X11.csproj
  src/Avalonia.X11/X11Window.cs
  src/Linux/Avalonia.LinuxFramebuffer/Avalonia.LinuxFramebuffer.csproj
  src/Linux/Avalonia.LinuxFramebuffer/Input/EvDev/EvDevBackend.cs
  src/Linux/Avalonia.LinuxFramebuffer/Input/LibInput/LibInputBackend.cs
  src/Linux/Avalonia.LinuxFramebuffer/Input/RawEventGroupingThreadingHelper.cs
  src/Shared/RawEventGrouping.cs
Labels: enhancement, API, x11

#7250 Fix pointer popup positioning for overlay popups
  src/Avalonia.Controls/Primitives/Popup.cs
  tests/Avalonia.Controls.UnitTests/Primitives/PopupTests.cs
Labels: bug, regression, backport-candidate

#7424 fix stability of wasm init.
  src/Web/Avalonia.Web.Blazor/AvaloniaView.razor.cs
Labels: backport-candidate, backported 0.10.x

#7430 Fix AvaloniaDictionary Remove method
  src/Avalonia.Base/Collections/AvaloniaDictionary.cs
  tests/Avalonia.Base.UnitTests/Collections/AvaloniaDictionaryTests.cs
Labels: bug, backport-candidate

#7436 Ensure menu children are closed on menu flyout presenter detached
  src/Avalonia.Controls/Flyouts/MenuFlyoutPresenter.cs
Labels: backport-candidate

#7455 [Deadlock] Fix Monitor.Enter in finally
  src/Avalonia.OpenGL/Egl/EglContext.cs
Labels: backport-candidate

#7279 ScrollViewer add property to bubble up the scroll event if not handled by nested ScrollViewer
  src/Avalonia.Controls.DataGrid/DataGrid.cs
  src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
  src/Avalonia.Controls/ScrollViewer.cs
  src/Avalonia.Themes.Default/Controls/ListBox.xaml
  src/Avalonia.Themes.Default/Controls/ScrollViewer.xaml
  src/Avalonia.Themes.Default/Controls/TextBox.xaml
  src/Avalonia.Themes.Default/Controls/TreeView.xaml
  src/Avalonia.Themes.Fluent/Controls/ListBox.xaml
  src/Avalonia.Themes.Fluent/Controls/ScrollViewer.xaml
  src/Avalonia.Themes.Fluent/Controls/TextBox.xaml
  src/Avalonia.Themes.Fluent/Controls/TreeView.xaml
Labels: enhancement, API

#7449 Add DensityStyle property in Fluent Theme provider
  src/Avalonia.Themes.Fluent/FluentTheme.cs
Labels: enhancement, backport-candidate

#7476 Nullability tweaks in lower-level libraries.
  src/Avalonia.Input/ICloseable.cs
  src/Avalonia.Input/IInputElement.cs
  src/Avalonia.Input/IMainMenu.cs
  src/Avalonia.Input/INavigableContainer.cs
  src/Avalonia.Input/InputElement.cs
  src/Avalonia.Input/TextInput/ITextInputMethodClient.cs
  src/Avalonia.Input/TextInput/ITextInputMethodImpl.cs
  src/Avalonia.Interactivity/Interactive.cs
  src/Avalonia.Layout/ElementManager.cs
  src/Avalonia.Layout/FlowLayoutAlgorithm.cs
  src/Avalonia.Layout/LayoutHelper.cs
  src/Avalonia.Layout/StackLayout.cs
  src/Avalonia.Layout/UniformGridLayout.cs
  src/Avalonia.Layout/VirtualizingLayout.cs
  src/Avalonia.Layout/WrapLayout/WrapLayout.cs
  src/Avalonia.Styling/Controls/IResourceHost.cs
  src/Avalonia.Styling/Controls/IResourceProvider.cs
  src/Avalonia.Styling/LogicalTree/LogicalTreeAttachmentEventArgs.cs
  src/Avalonia.Styling/Styling/IGlobalStyles.cs
  src/Avalonia.Visuals/Media/DrawingContext.cs
  src/Avalonia.Visuals/Platform/LockedFramebuffer.cs
  src/Avalonia.Visuals/VisualTree/IHostedVisualTreeRoot.cs
  src/Avalonia.Visuals/VisualTree/IVisualTreeHost.cs
Labels: API, wont-backport
