Repository AvaloniaUI/Avalonia, pull requests merged in 2022-06, with the labels that each got.

#8211 [OSX] dialogs stay ontop of main window when another app is displayed.
  native/Avalonia.Native/src/OSX/AvnPanelWindow.mm
  native/Avalonia.Native/src/OSX/AvnView.mm
  native/Avalonia.Native/src/OSX/AvnWindow.mm
  native/Avalonia.Native/src/OSX/INSWindowHolder.h
  native/Avalonia.Native/src/OSX/WindowBaseImpl.h
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
  native/Avalonia.Native/src/OSX/WindowImpl.h
  native/Avalonia.Native/src/OSX/WindowImpl.mm
  native/Avalonia.Native/src/OSX/WindowProtocol.h
Labels: backport-candidate

#8239 OSX Shadow invalidation when window sized
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
  native/Avalonia.Native/src/OSX/WindowImpl.mm
Labels: backport-candidate

#8246 re-set popup.Parent if its no longer set.
  src/Avalonia.Controls/Flyouts/FlyoutBase.cs
  tests/Avalonia.Controls.UnitTests/FlyoutTests.cs
Labels: backport-candidate

#8249 prevent segfault when closing app with child windows open.
  native/Avalonia.Native/src/OSX/WindowImpl.mm
Labels: backport-candidate

#8257 Fixes/osx toolbar hint
  native/Avalonia.Native/src/OSX/AvnWindow.mm
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
  native/Avalonia.Native/src/OSX/WindowImpl.mm
  samples/ControlCatalog/MainWindow.xaml.cs
Labels: backport-candidate

#8258 OSX: fix call to virtual method from ctor.
  native/Avalonia.Native/src/OSX/PopupImpl.mm
  native/Avalonia.Native/src/OSX/WindowBaseImpl.h
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
  native/Avalonia.Native/src/OSX/WindowImpl.h
  native/Avalonia.Native/src/OSX/WindowImpl.mm
Labels: backport-candidate

#8265 whenever we become key... dispatch invalidateShadow
  native/Avalonia.Native/src/OSX/AvnWindow.mm
Labels: backport-candidate

#8253 Stop listening for IsCancel on button detached
  src/Avalonia.Controls/Button.cs
  tests/Avalonia.Controls.UnitTests/ButtonTests.cs
Labels: bug, backport-candidate

#8268 [X11] Added support for the basic version of _NET_WM_SYNC_REQUEST protocol
  src/Avalonia.X11/X11Atoms.cs
  src/Avalonia.X11/X11Info.cs
  src/Avalonia.X11/X11Window.cs
  src/Avalonia.X11/XLib.cs
Labels: backport-candidate, x11

#8259 Make NumericUpDown's Value nullable
  samples/ControlCatalog/Pages/NumericUpDownPage.xaml
  src/Avalonia.Controls/NumericUpDown/NumericUpDown.cs
  src/Avalonia.Controls/NumericUpDown/NumericUpDownValueChangedEventArgs.cs
Labels: API, breaking-change

#8291 Fix FluentTheme density style
  src/Avalonia.Themes.Fluent/FluentTheme.cs
Labels: bug, backport-candidate, fluent

#8270 [X11] Improve _NET_WM_SYNC_REQUEST handling
  src/Avalonia.X11/X11Window.cs
Labels: backport-candidate, x11

#8272 Fix android initialization order
  samples/ControlCatalog.Android/ControlCatalog.Android.csproj
  src/Android/Avalonia.Android/AndroidPlatform.cs
  src/Android/Avalonia.Android/AvaloniaActivity.cs
Labels: bug, android

#8305 Fixes/reduce excessive layout passes
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
  src/Avalonia.Base/Layout/LayoutManager.cs
  tests/Avalonia.Base.UnitTests/Layout/LayoutManagerTests.cs
Labels: backport-candidate

#8313 Feature GlyphRun.BuildGeometry
  samples/RenderDemo/Pages/GlyphRunPage.xaml
  samples/RenderDemo/Pages/GlyphRunPage.xaml.cs
  src/Avalonia.Base/Media/GlyphRun.cs
  src/Avalonia.Base/Media/PlatformGeometry.cs
  src/Avalonia.Base/Platform/IPlatformRenderInterface.cs
  src/Avalonia.Headless/HeadlessPlatformRenderInterface.cs
  src/Skia/Avalonia.Skia/PlatformRenderInterface.cs
  src/Windows/Avalonia.Direct2D1/Direct2D1Platform.cs
  tests/Avalonia.Base.UnitTests/VisualTree/MockRenderInterface.cs
  tests/Avalonia.Benchmarks/NullRenderingPlatform.cs
  tests/Avalonia.RenderTests/Media/GlyphRunTests.cs
  tests/Avalonia.UnitTests/MockPlatformRenderInterface.cs
  tests/TestFiles/Direct2D1/Media/GlyphRun/Should_Render_GlyphRun_Geometry.expected.png
  tests/TestFiles/Skia/Media/GlyphRun/Should_Render_GlyphRun_Geometry.expected.png
Labels: API

#8315 Make GridSplitter scaling aware.
  src/Avalonia.Controls/GridSplitter.cs
Labels: bug, backport-candidate

#8245 Use own Pen (if set) in GeometryDrawing.GetBounds
  src/Avalonia.Visuals/Media/GeometryDrawing.cs
  tests/Avalonia.RenderTests/Media/GeometryDrawingTests.cs
Labels: bug

#5169 fix #4996
  native/Avalonia.Native/src/OSX/AvnView.mm
Labels: inactive

#8391 Fix DirectBindingSubscription NRE
  src/Avalonia.Base/AvaloniaObject.cs
Labels: bug, backport-candidate

#8347 Port windows.ui.xaml.textalignment to Avalonia
  src/Avalonia.Base/Media/GlyphRun.cs
  src/Avalonia.Base/Media/TextAlignment.cs
  src/Avalonia.Base/Media/TextFormatting/InterWordJustification.cs
  src/Avalonia.Base/Media/TextFormatting/JustificationProperties.cs
  src/Avalonia.Base/Media/TextFormatting/TextFormatterImpl.cs
  src/Avalonia.Base/Media/TextFormatting/TextLayout.cs
  src/Avalonia.Base/Media/TextFormatting/TextLine.cs
  src/Avalonia.Base/Media/TextFormatting/TextLineImpl.cs
  src/Avalonia.Controls/TextBlock.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextFormatterTests.cs
Labels: breaking-change

#8393 Set window margin to 0 WinUiComp is used - issue #8316
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: bug, wont-backport

#8396 Rename to PointerEntered and PointerExited
  src/Avalonia.Base/Input/IInputElement.cs
  src/Avalonia.Base/Input/InputElement.cs
  src/Avalonia.Base/Input/PointerOverPreProcessor.cs
  src/Avalonia.Controls.ColorPicker/ColorSpectrum/ColorSpectrum.cs
  src/Avalonia.Controls.DataGrid/DataGridCell.cs
  src/Avalonia.Controls.DataGrid/DataGridColumnHeader.cs
  src/Avalonia.Controls.DataGrid/DataGridRow.cs
  src/Avalonia.Controls.DataGrid/DataGridRowGroupHeader.cs
  src/Avalonia.Controls.DataGrid/DataGridRowHeader.cs
  src/Avalonia.Controls/Calendar/CalendarItem.cs
  src/Avalonia.Controls/GridSplitter.cs
  src/Avalonia.Controls/MenuItem.cs
  src/Avalonia.Controls/Platform/DefaultMenuInteractionHandler.cs
  src/Avalonia.Controls/Primitives/ScrollBar.cs
  src/Avalonia.Controls/ToolTipService.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/TreePageView.xaml.cs
  tests/Avalonia.Base.UnitTests/Input/PointerOverTests.cs
  tests/Avalonia.Controls.UnitTests/ButtonTests.cs
  tests/Avalonia.Controls.UnitTests/Platform/DefaultMenuInteractionHandlerTests.cs
  tests/Avalonia.UnitTests/MouseTestHelper.cs
Labels: api, breaking-change

#7450 Fix offset window position
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: bug, os-windows

#8365 OffScreenMargin calculation with different DPI monitors calculation
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: bug, os-windows

#8405 Fix more macos window issues and add more integration tests.
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
  native/Avalonia.Native/src/OSX/WindowImpl.mm
  samples/IntegrationTestApp/MainWindow.axaml
  samples/IntegrationTestApp/MainWindow.axaml.cs
  samples/IntegrationTestApp/ShowWindowTest.axaml
  samples/IntegrationTestApp/ShowWindowTest.axaml.cs
  src/Avalonia.Controls/Window.cs
  tests/Avalonia.IntegrationTests.Appium/ElementExtensions.cs
  tests/Avalonia.IntegrationTests.Appium/PlatformTheoryAttribute.cs
  tests/Avalonia.IntegrationTests.Appium/WindowTests.cs
  tests/Avalonia.IntegrationTests.Appium/WindowTests_MacOS.cs
  tests/Avalonia.IntegrationTests.Appium/macos-clean-build-test.sh
Labels: bug, os-macos, wont-backport

#8421 Don't make ResourceDictionary inherit from `AvaloniaDictionary`
  src/Avalonia.Base/Controls/ResourceDictionary.cs
Labels: api, breaking-change
