Repository AvaloniaUI/Avalonia, pull requests merged in 2022-03, with the labels that each got.

#7730 Fall back from CenterOwner to CenterScreen when owner window is minimized.
  src/Avalonia.Controls/Window.cs
Labels: backport-candidate

#7723 Fix expander header stretching
  src/Avalonia.Themes.Default/Controls/Expander.xaml
  src/Avalonia.Themes.Fluent/Controls/Expander.xaml
Labels: bug, backport-candidate

#7736 allow setting the window title to null on osx.
  src/Avalonia.Native/WindowImpl.cs
Labels: backport-candidate

#7783 RoutedViewHost: Fix property registration
  src/Avalonia.ReactiveUI/RoutedViewHost.cs
Labels: backport-candidate

#6344 Add Transform property for Brush class
  samples/RenderDemo/MainWindow.xaml
  samples/RenderDemo/Pages/BrushesPage.axaml
  samples/RenderDemo/Pages/BrushesPage.axaml.cs
  src/Avalonia.Visuals/Animation/Animators/GradientBrushAnimator.cs
  src/Avalonia.Visuals/ApiCompatBaseline.txt
  src/Avalonia.Visuals/Media/Brush.cs
  src/Avalonia.Visuals/Media/IBrush.cs
  src/Avalonia.Visuals/Media/Immutable/ImmutableConicGradientBrush.cs
  src/Avalonia.Visuals/Media/Immutable/ImmutableGradientBrush.cs
  src/Avalonia.Visuals/Media/Immutable/ImmutableImageBrush.cs
  src/Avalonia.Visuals/Media/Immutable/ImmutableLinearGradientBrush.cs
  src/Avalonia.Visuals/Media/Immutable/ImmutableRadialGradientBrush.cs
  src/Avalonia.Visuals/Media/Immutable/ImmutableSolidColorBrush.cs
  src/Avalonia.Visuals/Media/Immutable/ImmutableTileBrush.cs
  src/Avalonia.Visuals/Media/Immutable/ImmutableTransform.cs
  src/Avalonia.Visuals/Media/Immutable/ImmutableVisualBrush.cs
  src/Avalonia.Visuals/Media/Transform.cs
  src/Avalonia.Visuals/Media/TransformExtensions.cs
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
Labels: breaking-change

#7774 fix pinvoke signature for smc and ice error handlers for 32 bit
  src/Avalonia.X11/ICELib.cs
  src/Avalonia.X11/SMLib.cs
  src/Avalonia.X11/X11PlatformLifetimeEvents.cs
Labels: backport-candidate

#7787 make mica fallback to acrylic on compatible windows 10
  src/Avalonia.Controls/WindowTransparencyLevel.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: backport-candidate

#7804 Invalid Mouse Over events on NC raw events
  src/Avalonia.Input/MouseDevice.cs
Labels: backport-candidate

#7830 Use CompiledBindings with bindings to methods
  src/Avalonia.Themes.Fluent/Controls/TextBox.xaml
Labels: enhancement, fluent, wont-backport

#7786 Fix: DataGrid copying data clears DataGridCells
  src/Avalonia.Base/Data/BindingOperations.cs
  tests/Avalonia.Base.UnitTests/AvaloniaObjectTests_Binding.cs
Labels: bug, datagrid, backport-candidate

#7827 Add support for showing binding paths in DevTools.
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/BindingSetterViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ControlDetailsViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/SetterViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/ControlDetailsView.xaml
Labels: dev-tools

#7832 Measure overlay layer children to constraint.
  src/Avalonia.Controls/Primitives/OverlayLayer.cs
Labels: backport-candidate

#7008 feat(ContentPresenter): Content of ContentPresenter should become DataContext of the subtree whenever ContentTemplate is not null
  src/Avalonia.Controls/Presenters/ContentPresenter.cs
  tests/Avalonia.Controls.UnitTests/Presenters/ContentPresenterTests_InTemplate.cs
Labels: enhancement, wont-backport, inactive

#6534 fixes(OSX): convertBaseToScreen:' is deprecated: first deprecated in macOS 10.7
  native/Avalonia.Native/src/OSX/controlhost.mm
  native/Avalonia.Native/src/OSX/window.mm
Labels: inactive

#7883 Remove CornerRadius from MenuFlyoutPresenter
  src/Avalonia.Controls/Flyouts/MenuFlyoutPresenter.cs
Labels: wont-backport
