Repository AvaloniaUI/Avalonia, pull requests merged in 2023-04, with the labels that each got.

#10923 Proper implementation of DispatcherImpl for iOS
  src/iOS/Avalonia.iOS/DispatcherImpl.cs
  src/iOS/Avalonia.iOS/Interop.cs
  src/iOS/Avalonia.iOS/Platform.cs
  src/iOS/Avalonia.iOS/PlatformSettings.cs
  src/iOS/Avalonia.iOS/PlatformThreadingInterface.cs
Labels: os-ios

#10851 Don't allow window zoom when CanResize=false and custom window chrome
  src/Avalonia.Controls/Automation/Peers/ControlAutomationPeer.cs
  src/Avalonia.Controls/Chrome/CaptionButtons.cs
  src/Avalonia.Native/WindowImpl.cs
  src/Avalonia.Themes.Fluent/Controls/CaptionButtons.xaml
  src/Avalonia.Themes.Simple/Controls/CaptionButtons.xaml
  tests/Avalonia.IntegrationTests.Appium/WindowTests.cs
  tests/Avalonia.IntegrationTests.Appium/WindowTests_MacOS.cs
Labels: bug, os-macos, os-windows, backport-candidate

#11002 Update browser WindowingPlatform exception message
  src/Browser/Avalonia.Browser/WindowingPlatform.cs
Labels: os-browser

#11010 Add "readClipboardText" workaround for Mozilla
  src/Browser/Avalonia.Browser/AvaloniaView.cs
  src/Browser/Avalonia.Browser/Interop/InputHelper.cs
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/input.ts
Labels: os-browser

#11012 Backport WCT fix for editing DataGrid
  src/Avalonia.Controls.DataGrid/DataGrid.cs
Labels: area-datagrid

#10999 Removed unreferenced resources from TextBox
  src/Avalonia.Themes.Fluent/Controls/TextBox.xaml
  src/Avalonia.Themes.Simple/Controls/TextBox.xaml
Labels: breaking-change

#10473 Avalonia.Headless.XUnit extensions and attempt to make Avalonia.Headless easier to use
  Avalonia.sln
  nukebuild/Build.cs
  samples/ControlCatalog.NetCore/ControlCatalog.NetCore.csproj
  samples/ControlCatalog.NetCore/Properties/launchSettings.json
  samples/MobileSandbox.Desktop/MobileSandbox.Desktop.csproj
  src/Avalonia.Base/Platform/Storage/NoopStorageProvider.cs
  src/Avalonia.Controls/AppBuilder.cs
  src/Avalonia.Controls/Avalonia.Controls.csproj
  src/Avalonia.Controls/Platform/ScreenHelper.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs
  src/Avalonia.Headless/Avalonia.Headless.csproj
  src/Avalonia.Native/Avalonia.Native.csproj
  src/Headless/Avalonia.Headless.Vnc/Avalonia.Headless.Vnc.csproj
  src/Headless/Avalonia.Headless.Vnc/HeadlessVncFramebufferSource.cs
  src/Headless/Avalonia.Headless.Vnc/HeadlessVncPlatformExtensions.cs
  src/Headless/Avalonia.Headless.XUnit/Avalonia.Headless.XUnit.csproj
  src/Headless/Avalonia.Headless.XUnit/AvaloniaTestFramework.cs
  src/Headless/Avalonia.Headless.XUnit/AvaloniaTestFrameworkAttribute.cs
  src/Headless/Avalonia.Headless.XUnit/AvaloniaTestRunner.cs
  src/Headless/Avalonia.Headless/Avalonia.Headless.csproj
  src/Headless/Avalonia.Headless/AvaloniaHeadlessPlatform.cs
  src/Headless/Avalonia.Headless/HeadlessPlatformRenderInterface.cs
  src/Headless/Avalonia.Headless/HeadlessPlatformStubs.cs
  src/Headless/Avalonia.Headless/HeadlessWindowExtensions.cs
  src/Headless/Avalonia.Headless/HeadlessWindowImpl.cs
  src/Headless/Avalonia.Headless/IHeadlessWindow.cs
  tests/Avalonia.Headless.UnitTests/Avalonia.Headless.UnitTests.csproj
  tests/Avalonia.Headless.UnitTests/InputTests.cs
  tests/Avalonia.Headless.UnitTests/RenderingTests.cs
  tests/Avalonia.Headless.UnitTests/TestApplication.cs
  tests/Avalonia.Headless.UnitTests/ThreadingTests.cs
Labels: api, area-headless

#11086 DevTools visual/logical tree context flyout
  src/Avalonia.Base/Input/Cursor.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/TreePageViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/TreePageView.xaml
  src/Avalonia.Diagnostics/Diagnostics/Views/TreePageView.xaml.cs
Labels: area-dev-tools

#11138 Don't clear ItemIsOwnContainer containers in PanelContainerGenerator.
  src/Avalonia.Controls/Presenters/PanelContainerGenerator.cs
  tests/Avalonia.Controls.UnitTests/ItemsControlTests.cs
  tests/Avalonia.Controls.UnitTests/Primitives/SelectingItemsControlTests.cs
Labels: bug

#11168 Fix selection being clearing when recycling containers.
  src/Avalonia.Controls/Generators/ItemContainerGenerator.cs
  src/Avalonia.Controls/Utils/RealizedStackElements.cs
  tests/Avalonia.Controls.UnitTests/Primitives/SelectingItemsControlTests_Multiple.cs
Labels: bug

#11127 Fix layout invalidation when controls made effectively visible.
  src/Avalonia.Base/Layout/LayoutManager.cs
  src/Avalonia.Base/Layout/LayoutQueue.cs
  src/Avalonia.Base/Layout/Layoutable.cs
  src/Avalonia.Controls/VirtualizingStackPanel.cs
  tests/Avalonia.Base.UnitTests/Layout/LayoutManagerTests.cs
Labels: bug

#11029 Include analyzers in the main package
  .editorconfig
  Avalonia.sln
  build/DevAnalyzers.props
  nukebuild/numerge.config
  packages/Avalonia/Avalonia.csproj
  samples/ControlCatalog/Pages/CustomDrawingExampleControl.cs
  samples/IntegrationTestApp/IntegrationTestApp.csproj
  src/Avalonia.Base/ClassBindingManager.cs
  src/Avalonia.Base/Media/DashStyle.cs
  src/Avalonia.Base/Media/GradientBrush.cs
  src/Avalonia.Base/Media/PolyLineSegment.cs
  src/Avalonia.Base/Media/TransformGroup.cs
  src/Avalonia.Base/StyledElement.cs
  src/Avalonia.Base/Styling/ThemeVariant.cs
  src/Avalonia.Base/Visual.cs
  src/Avalonia.Controls/Application.cs
  src/Avalonia.Controls/AutoCompleteBox/AutoCompleteBox.cs
  src/Avalonia.Controls/AutoCompleteBox/AutoCompleteFilterMode.cs
  src/Avalonia.Controls/ColumnDefinition.cs
  src/Avalonia.Controls/ContextMenu.cs
  src/Avalonia.Controls/DefinitionBase.cs
  src/Avalonia.Controls/Documents/Span.cs
  src/Avalonia.Controls/Flyouts/PopupFlyoutBase.cs
  src/Avalonia.Controls/LayoutTransformControl.cs
  src/Avalonia.Controls/ListBox.cs
  src/Avalonia.Controls/MenuItem.cs
  src/Avalonia.Controls/Primitives/UniformGrid.cs
  src/Avalonia.Controls/Primitives/VisualLayerManager.cs
  src/Avalonia.Controls/PullToRefresh/RefreshVisualizer.cs
  src/Avalonia.Controls/RowDefinition.cs
  src/Avalonia.Controls/SplitView/SplitViewTemplateSettings.cs
  src/Avalonia.Controls/TabControl.cs
  src/Avalonia.Controls/TabItem.cs
  src/Avalonia.Controls/ToggleSwitch.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.Diagnostics/Diagnostics/Controls/Application.cs
  src/Avalonia.ReactiveUI/Avalonia.ReactiveUI.csproj
  src/Avalonia.ReactiveUI/ReactiveUserControl.cs
  src/Avalonia.ReactiveUI/ReactiveWindow.cs
  src/Avalonia.Themes.Fluent/Avalonia.Themes.Fluent.csproj
  src/Avalonia.Themes.Fluent/Controls/AutoCompleteBox.xaml
  src/Avalonia.Themes.Simple/Avalonia.Themes.Simple.csproj
  src/tools/Avalonia.Analyzers/Avalonia.Analyzers.csproj
  src/tools/Avalonia.Analyzers/AvaloniaPropertyAnalyzer.CompileAnalyzer.cs
  src/tools/Avalonia.Analyzers/AvaloniaPropertyAnalyzer.cs
  src/tools/Avalonia.Analyzers/GlobalSuppressions.cs
  src/tools/Avalonia.Analyzers/OnPropertyChangedOverrideAnalyzer.cs
  src/tools/Avalonia.Generators/GeneratorContextExtensions.cs
  src/tools/PublicAnalyzers/Avalonia.Analyzers.csproj
Labels: area-analyzers

#11190 Introduce static AssetLoader
  src/Avalonia.Base/Platform/AssetLoader.cs
  src/Avalonia.Base/Platform/StandardAssetLoader.cs
  src/Avalonia.Base/Platform/StandardRuntimePlatformServices.cs
  tests/Avalonia.Base.UnitTests/AssetLoaderTests.cs
  tests/Avalonia.Benchmarks/Styling/ResourceBenchmarks.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/StyleIncludeTests.cs
  tests/Avalonia.RenderTests/TestBase.cs
  tests/Avalonia.UnitTests/TestServices.cs
Labels: breaking-change

#11189 Make ICustomDrawOperation to use ImmediateDrawingContext
  samples/RenderDemo/Pages/CustomSkiaPage.cs
  src/Avalonia.Base/Media/ImmediateDrawingContext.cs
  src/Avalonia.Base/Media/PlatformDrawingContext.cs
  src/Avalonia.Base/Platform/IDrawingContextImpl.cs
  src/Avalonia.Base/Rendering/Composition/Server/DrawingContextProxy.cs
  src/Avalonia.Base/Rendering/SceneGraph/CustomDrawOperation.cs
  src/Browser/Avalonia.Browser/WebEmbeddableControlRoot.cs
  src/Headless/Avalonia.Headless/HeadlessPlatformRenderInterface.cs
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
  src/Windows/Avalonia.Direct2D1/Media/DrawingContextImpl.cs
Labels: breaking-change

#11195 Progressbar Updates
  src/Avalonia.Controls/ProgressBar.cs
  src/Avalonia.Controls/SplitView/SplitView.cs
  src/Avalonia.Controls/SplitView/SplitViewTemplateSettings.cs
  src/Avalonia.Themes.Fluent/Controls/ProgressBar.xaml
  src/Avalonia.Themes.Simple/Controls/ProgressBar.xaml
Labels: breaking-change
