Repository AvaloniaUI/Avalonia, pull requests merged in 2023-12, with the labels that each got.

#13538 Avoid Adreno DXGI adapter on Win-ARM devices
  src/Windows/Avalonia.Win32/OpenGl/Angle/AngleWin32EglDisplay.cs
Labels: backport-candidate-11.0.x

#13775 Fix Animation.FillMode when cue isn't 0% or 100%
  src/Avalonia.Base/Animation/Animatable.cs
  src/Avalonia.Base/Animation/Animation.cs
  src/Avalonia.Base/Animation/AnimatorKeyFrame.cs
  src/Avalonia.Base/Animation/Animators/Animator`1.cs
  src/Avalonia.Base/Animation/Animators/BaseBrushAnimator.cs
  src/Avalonia.Base/Media/Effects/EffectAnimator.cs
  tests/Avalonia.Base.UnitTests/Animation/AnimatableTests.cs
  tests/Avalonia.Base.UnitTests/Animation/AnimationIterationTests.cs
  tests/Avalonia.Base.UnitTests/Animation/SpringTests.cs
Labels: backport-candidate-11.0.x

#13724 Ignore mouse move when left window
  src/Avalonia.Base/Input/PointerOverPreProcessor.cs
Labels: backport-candidate-11.0.x

#13788 release Context
  src/Avalonia.OpenGL/Controls/OpenGlControlResources.cs
Labels: backport-candidate-11.0.x

#13795 Fix Some Virtualizing List Update Bugs
  src/Avalonia.Controls/Utils/RealizedStackElements.cs
  src/Avalonia.Controls/VirtualizingStackPanel.cs
  tests/Avalonia.Controls.UnitTests/VirtualizingStackPanelTests.cs
Labels: bug, backport-candidate-11.0.x

#13820 Update Avalonia.Browser.props
  src/Browser/Avalonia.Browser/Avalonia.Browser.props
Labels: backport-candidate-11.0.x

#11918 Fix: RangeBase should not write coerced values back when DataContext is changing
  src/Avalonia.Controls/Primitives/RangeBase.cs
  tests/Avalonia.Controls.UnitTests/Primitives/RangeBaseTests.cs
Labels: backport-candidate-11.0.x

#13797 Updated RenderDataRectangleNode.HitTest to properly hit-test rounded rectangles
  src/Avalonia.Base/Rendering/Composition/Drawing/Nodes/RenderDataRectangleNode.cs
  src/Avalonia.Base/RoundedRect.cs
  tests/Avalonia.Base.UnitTests/RoundedRectTests.cs
Labels: backport-candidate-11.0.x

#13831 Unsubscribe android back handler when toplevel is disposed
  src/Android/Avalonia.Android/Platform/AndroidSystemNavigationManager.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
Labels: backport-candidate-11.0.x

#13845 Fix DataGrid IList editing issue
  src/Avalonia.Controls.DataGrid/Collections/DataGridCollectionView.cs
  src/Avalonia.Controls.DataGrid/DataGridDataConnection.cs
Labels: bug, area-datagrid, backport-candidate-11.0.x

#13847 Fixes TextLine run bounds union calculation
  src/Avalonia.Base/Media/TextFormatting/TextLineImpl.cs
Labels: backport-candidate-11.0.x

#13849 Fix: TabItem.TabStripPlacement is not set for new tab items
  src/Avalonia.Controls/TabControl.cs
  tests/Avalonia.Controls.UnitTests/TabControlTests.cs
Labels: backport-candidate-11.0.x

#13868 Hackfix for calling SelectAll with SelectedItem binding
  src/Avalonia.Controls/Selection/SelectionModel.cs
  tests/Avalonia.Controls.UnitTests/ListBoxTests_Multiple.cs
Labels: bug, backport-candidate-11.0.x

#13893 Fix ToggleSwitch dragging
  src/Avalonia.Controls/ToggleSwitch.cs
Labels: backport-candidate-11.0.x

#13920 Remove Console support in DevTools
  api/Avalonia.Diagnostics.nupkg.xml
  src/Avalonia.Diagnostics/Avalonia.Diagnostics.csproj
  src/Avalonia.Diagnostics/Diagnostics/Models/ConsoleContext.cs
  src/Avalonia.Diagnostics/Diagnostics/Models/ConsoleHistoryItem.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ConsoleViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/MainViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/ConsoleView.xaml
  src/Avalonia.Diagnostics/Diagnostics/Views/ConsoleView.xaml.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/MainView.xaml
  src/Avalonia.Diagnostics/Diagnostics/Views/MainView.xaml.cs
Labels: breaking-change, area-dev-tools

#13937 feat: Allow treat Avalonia Access Unstable Private Apis Warning as Error
  packages/Avalonia/AvaloniaPrivateApis.targets
Labels: backport-candidate-11.0.x

#13905 Ensure extended title bar height is set on platform implementation
  src/Avalonia.Controls/Window.cs
Labels: backport-candidate-11.0.x

#13948 Fix double context request from hold gesture
  src/Avalonia.Controls/Control.cs
Labels: backport-candidate-11.0.x

#13966 Use ShowNoActivate in Win32NativeControlHost.
  src/Windows/Avalonia.Win32/Win32NativeControlHost.cs
Labels: backport-candidate-11.0.x

#13870 Add transition leak tests
  tests/Avalonia.LeakTests/TransitionTests.cs
Labels: backport-candidate-11.0.x

#13942 Fix iOS Dispatcher
  src/iOS/Avalonia.iOS/Avalonia.iOS.csproj
  src/iOS/Avalonia.iOS/DispatcherImpl.cs
  src/iOS/Avalonia.iOS/Interop.cs
Labels: bug, os-ios, backport-candidate-11.0.x

#13997 Fix DBus Exception on window close
  src/Avalonia.FreeDesktop/DBusIme/DBusTextInputMethodBase.cs
Labels: backport-candidate-11.0.x

#13800 Fix SelectedItemsControl initialization property order
  src/Avalonia.Controls/Primitives/SelectingItemsControl.cs
  tests/Avalonia.Controls.UnitTests/EnumerableExtensions.cs
  tests/Avalonia.Controls.UnitTests/Primitives/SelectingItemsControlTests.cs
  tests/Avalonia.UnitTests/NotifyingBase.cs
Labels: backport-candidate-11.0.x

#13976 Fix IOSStorageFolder permission problem
  src/iOS/Avalonia.iOS/Storage/IOSSecurityScopedStream.cs
  src/iOS/Avalonia.iOS/Storage/IOSStorageItem.cs
Labels: backport-candidate-11.0.x

#13818 Implement helper OutputApiDiff target
  .gitignore
  .nuke/build.schema.json
  Avalonia.sln
  nukebuild/ApiDiffHelper.cs
  nukebuild/Build.cs
  nukebuild/_build.csproj
Labels: backport-candidate-11.0.x

#14010 Update Tmds.DBus.SourceGenerator to 0.0.13
  src/Avalonia.FreeDesktop/Avalonia.FreeDesktop.csproj
Labels: backport-candidate-11.0.x

#14014 Remove missing MVID warning on XAML compilation
  packages/Avalonia/AvaloniaBuildTasks.targets
Labels: backport-candidate-11.0.x

#14026 Fixed color of selected DataGridRow
  src/Avalonia.Controls.DataGrid/Themes/Fluent.xaml
Labels: backport-candidate-11.0.x

#13980 Fixes Border and Shape border re-rendering when changing Brush value
  src/Avalonia.Base/Media/Pen.cs
  src/Avalonia.Controls/Shapes/Shape.cs
  src/Avalonia.Controls/Utils/BorderRenderHelper.cs
  tests/Avalonia.Base.UnitTests/Media/PenTests.cs
Labels: backport-candidate-11.0.x
