Repository AvaloniaUI/Avalonia, pull requests merged in 2023-03, with the labels that each got.

#10523 feat: AvaloniaVS defered loading
  packages/Avalonia/Avalonia.props
Labels: backport-candidate

#10497 Fix `SetCurrent` value in combination with certain styles
  src/Avalonia.Base/PropertyStore/ValueStore.cs
  tests/Avalonia.Base.UnitTests/AvaloniaObjectTests_SetCurrentValue.cs
Labels: bug

#10531 Add LabelAutomationPeer
  src/Avalonia.Controls/Automation/Peers/LabelAutomationPeer.cs
  src/Avalonia.Controls/Label.cs
Labels: wont-backport

#10545 Fix integration tests by disambiguating controls.
  samples/IntegrationTestApp/ShowWindowTest.axaml
  samples/IntegrationTestApp/ShowWindowTest.axaml.cs
  tests/Avalonia.IntegrationTests.Appium/WindowTests.cs
  tests/Avalonia.IntegrationTests.Appium/WindowTests_MacOS.cs
Labels: infrastructure

#10511 Fix TreeView data template handling
  src/Avalonia.Controls/ItemsControl.cs
  src/Avalonia.Controls/Primitives/HeaderedItemsControl.cs
  tests/Avalonia.Controls.UnitTests/TreeViewTests.cs
Labels: bug

#10532 Fixes/mac os constrain window size
  native/Avalonia.Native/src/OSX/AvnView.mm
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
  native/Avalonia.Native/src/OSX/WindowImpl.mm
  samples/IntegrationTestApp/ShowWindowTest.axaml
  samples/IntegrationTestApp/ShowWindowTest.axaml.cs
  tests/Avalonia.IntegrationTests.Appium/WindowTests.cs
Labels: backport-candidate

#9526 [macOS] - Input method integration
  native/Avalonia.Native/src/OSX/Avalonia.Native.OSX.xcodeproj/project.pbxproj
  native/Avalonia.Native/src/OSX/AvnTextInputMethod.h
  native/Avalonia.Native/src/OSX/AvnTextInputMethod.mm
  native/Avalonia.Native/src/OSX/AvnTextInputMethodDelegate.h
  native/Avalonia.Native/src/OSX/AvnView.h
  native/Avalonia.Native/src/OSX/AvnView.mm
  native/Avalonia.Native/src/OSX/WindowBaseImpl.h
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
  src/Avalonia.Controls/Presenters/TextPresenter.cs
  src/Avalonia.Controls/TextBox.cs
  src/Avalonia.Controls/TextBoxTextInputMethodClient.cs
  src/Avalonia.Native/AvaloniaNativeTextInputMethod.cs
  src/Avalonia.Native/WindowImpl.cs
  src/Avalonia.Native/avn.idl
  src/Windows/Avalonia.Win32/Input/Imm32InputMethod.cs
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
Labels: os-macos

#10492 Update Flyout and Popup APIs to make gap between them smaller
  samples/ControlCatalog/Pages/ContextFlyoutPage.xaml.cs
  samples/ControlCatalog/Pages/FlyoutsPage.axaml
  src/Avalonia.Base/Input/MouseDevice.cs
  src/Avalonia.Base/Input/PenDevice.cs
  src/Avalonia.Base/Input/PointerEventArgs.cs
  src/Avalonia.Base/Input/PointerOverPreProcessor.cs
  src/Avalonia.Base/Input/TouchDevice.cs
  src/Avalonia.Controls/Flyouts/Flyout.cs
  src/Avalonia.Controls/Flyouts/FlyoutBase.cs
  src/Avalonia.Controls/Flyouts/FlyoutPlacementMode.cs
  src/Avalonia.Controls/Flyouts/MenuFlyout.cs
  src/Avalonia.Controls/Flyouts/PopupFlyoutBase.cs
  src/Avalonia.Controls/PlacementMode.cs
  src/Avalonia.Controls/Primitives/PopupPositioning/IPopupPositioner.cs
  src/Avalonia.Controls/SplitButton/SplitButton.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/VisualTreeNode.cs
Labels: api

#10575 macOS: Don't allow window zoom when CanResize=false.
  native/Avalonia.Native/src/OSX/AvnWindow.mm
  native/Avalonia.Native/src/OSX/WindowBaseImpl.h
  native/Avalonia.Native/src/OSX/WindowImpl.h
  native/Avalonia.Native/src/OSX/WindowImpl.mm
Labels: bug, os-macos, backport-candidate

#10603 Change StorageFolder.GetItemsAsync to return IAsyncEnumerable
  samples/ControlCatalog/Pages/DialogsPage.xaml.cs
  samples/ControlCatalog/Pages/DragAndDropPage.xaml.cs
  src/Android/Avalonia.Android/Platform/Storage/AndroidStorageItem.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFolder.cs
  src/Avalonia.Base/Platform/Storage/IStorageFolder.cs
  src/Browser/Avalonia.Browser/Interop/GeneralHelpers.cs
  src/Browser/Avalonia.Browser/Interop/StorageHelper.cs
  src/Browser/Avalonia.Browser/Storage/BrowserStorageProvider.cs
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/generalHelpers.ts
  src/Browser/Avalonia.Browser/webapp/modules/storage/storageItem.ts
  src/iOS/Avalonia.iOS/Storage/IOSStorageItem.cs
Labels: os-browser

#10541 Add ScrollBarAutomationPeer
  samples/IntegrationTestApp/MainWindow.axaml
  src/Avalonia.Controls/Automation/Peers/ScrollBarAutomationPeer.cs
  src/Avalonia.Controls/Primitives/ScrollBar.cs
  tests/Avalonia.IntegrationTests.Appium/ScrollBarTests.cs
Labels: wont-backport

#10607 Add new IStorage api - Create, Move, Delete
  samples/ControlCatalog.Android/Properties/AndroidManifest.xml
  src/Android/Avalonia.Android/Avalonia.Android.csproj
  src/Android/Avalonia.Android/Platform/Storage/AndroidStorageItem.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFile.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFolder.cs
  src/Avalonia.Base/Platform/Storage/IStorageFolder.cs
  src/Avalonia.Base/Platform/Storage/IStorageItem.cs
  src/Browser/Avalonia.Browser/Interop/StorageHelper.cs
  src/Browser/Avalonia.Browser/Storage/BrowserStorageProvider.cs
  src/Browser/Avalonia.Browser/webapp/modules/storage/storageItem.ts
  src/iOS/Avalonia.iOS/Storage/IOSStorageItem.cs
Labels: api

#10677 macOS: Fix interaction between ExtendClientAreaToDecorationsHint and SystemDecorations
  native/Avalonia.Native/src/OSX/WindowImpl.mm
  samples/IntegrationTestApp/MainWindow.axaml
  samples/IntegrationTestApp/MainWindow.axaml.cs
  samples/IntegrationTestApp/ShowWindowTest.axaml
  tests/Avalonia.IntegrationTests.Appium/ElementExtensions.cs
  tests/Avalonia.IntegrationTests.Appium/PlatformFactAttribute.cs
  tests/Avalonia.IntegrationTests.Appium/PlatformTheoryAttribute.cs
  tests/Avalonia.IntegrationTests.Appium/WindowTests_MacOS.cs
Labels: bug, os-macos, backport-candidate

#10785 Fix TreeView selection
  src/Avalonia.Controls/TreeView.cs
  src/Avalonia.Controls/TreeViewItem.cs
  tests/Avalonia.Controls.UnitTests/TreeViewTests.cs
Labels: bug

#10775 Downgrade Microsoft.CodeAnalysis.CSharp
  src/tools/Avalonia.Generators/Avalonia.Generators.csproj
Labels: bug, regression

#10801 Fix menu placement
  src/Avalonia.Themes.Fluent/Controls/MenuItem.xaml
  src/Avalonia.Themes.Simple/Controls/MenuItem.xaml
Labels: bug, regression

#10788 Fix inserting at index 0 with VirtualizingStackPanel.
  src/Avalonia.Controls/VirtualizingStackPanel.cs
  tests/Avalonia.Controls.UnitTests/VirtualizingStackPanelTests.cs
Labels: bug

#10858 Fix inherited property change notifications.
  src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs
  src/Avalonia.Base/PropertyStore/ValueStore.cs
  tests/Avalonia.Base.UnitTests/AvaloniaObjectTests_Inheritance.cs
Labels: bug

#10864 Don't layout invisible controls
  src/Avalonia.Base/Layout/LayoutManager.cs
  tests/Avalonia.Base.UnitTests/Layout/LayoutManagerTests.cs
  tests/Avalonia.Controls.UnitTests/MenuItemTests.cs
  tests/Avalonia.Controls.UnitTests/Primitives/PopupTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/ControlThemeTests.cs
Labels: bug
