Repository AvaloniaUI/Avalonia, pull requests merged in 2023-02, with the labels that each got.

#10153 macOS: Sync actual window state after window show, and fix integration tests on macOS 13.1
  native/Avalonia.Native/src/OSX/WindowImpl.mm
  tests/Avalonia.IntegrationTests.Appium/ElementExtensions.cs
Labels: bug, os-macos, backport-candidate

#10105 Make AnonymousObserver public and LightweightObservableBase internal
  src/Avalonia.Base/Reactive/AnonymousObserver.cs
  src/Avalonia.Base/Reactive/LightweightObservableBase.cs
Labels: api

#10196 macOS: Fix window transparency
  samples/IntegrationTestApp/MainWindow.axaml
  samples/IntegrationTestApp/MainWindow.axaml.cs
  src/Avalonia.Native/WindowImplBase.cs
  tests/Avalonia.IntegrationTests.Appium/Avalonia.IntegrationTests.Appium.csproj
  tests/Avalonia.IntegrationTests.Appium/WindowTests.cs
Labels: bug, os-macos, backport-candidate

#10204 Update Angle to 2.1.0.2023020321
  samples/ControlCatalog.NetCore/ControlCatalog.NetCore.csproj
  samples/MobileSandbox.Desktop/MobileSandbox.Desktop.csproj
  src/Windows/Avalonia.Win32/Avalonia.Win32.csproj
  src/tools/Avalonia.Designer.HostApp/Avalonia.Designer.HostApp.csproj
Labels: bug, os-windows

#10238 Make previewer to properly load ALL referenced assemblies
  src/tools/Avalonia.Designer.HostApp/DesignXamlLoader.cs
Labels: area-xaml

#10299 Make all Render overrides sealed
  src/Avalonia.Controls/Border.cs
  src/Avalonia.Controls/ExperimentalAcrylicBorder.cs
  src/Avalonia.Controls/Grid.cs
  src/Avalonia.Controls/Image.cs
  src/Avalonia.Controls/Panel.cs
  src/Avalonia.Controls/Presenters/ContentPresenter.cs
  src/Avalonia.Controls/Presenters/TextPresenter.cs
  src/Avalonia.Controls/Primitives/AccessText.cs
  src/Avalonia.Controls/Remote/RemoteWidget.cs
  src/Avalonia.Controls/Shapes/Shape.cs
  src/Avalonia.Controls/TextBlock.cs
  src/Avalonia.Controls/TickBar.cs
Labels: breaking-change

#8894 Add option to prevent App Nap.
  native/Avalonia.Native/src/OSX/Avalonia.Native.OSX.xcodeproj/project.pbxproj
  native/Avalonia.Native/src/OSX/PlatformBehaviorInhibition.mm
  native/Avalonia.Native/src/OSX/common.h
  native/Avalonia.Native/src/OSX/main.mm
  src/Avalonia.Base/Platform/IPlatformBehaviorInhibition.cs
  src/Avalonia.Controls/PlatformInhibitionType.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.Native/AvaloniaNativePlatform.cs
  src/Avalonia.Native/PlatformBehaviorInhibition.cs
  src/Avalonia.Native/WindowImplBase.cs
  src/Avalonia.Native/avn.idl
Labels: api, os-macos

#10265 Various macOS and win32 fixes
  native/Avalonia.Native/src/OSX/AvnWindow.mm
  native/Avalonia.Native/src/OSX/PopupImpl.mm
  native/Avalonia.Native/src/OSX/WindowBaseImpl.h
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
  native/Avalonia.Native/src/OSX/WindowImpl.h
  native/Avalonia.Native/src/OSX/WindowImpl.mm
  samples/IntegrationTestApp/MainWindow.axaml
  samples/IntegrationTestApp/MainWindow.axaml.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
  tests/Avalonia.IntegrationTests.Appium/WindowTests.cs
  tests/Avalonia.IntegrationTests.Appium/WindowTests_MacOS.cs
Labels: bug, os-macos, os-windows, backport-candidate

#10348 Two ValueStore fixes.
  src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs
  src/Avalonia.Base/PropertyStore/ValueStore.cs
  src/Avalonia.Base/StyledProperty.cs
  tests/Avalonia.Base.UnitTests/AvaloniaObjectTests_Binding.cs
  tests/Avalonia.Base.UnitTests/PropertyStore/ValueStoreTests_Inheritance.cs
Labels: bug

#10343 Browser backend initialization fix and file picker updates
  samples/ControlCatalog.Browser.Blazor/App.razor.cs
  samples/ControlCatalog.Browser.Blazor/Program.cs
  samples/ControlCatalog.Browser/Program.cs
  samples/ControlCatalog.Browser/main.js
  samples/ControlCatalog/Pages/DialogsPage.xaml.cs
  src/Android/Avalonia.Android/Platform/Storage/AndroidStorageItem.cs
  src/Android/Avalonia.Android/Platform/Storage/AndroidStorageProvider.cs
  src/Avalonia.Base/Platform/DefaultPlatformSettings.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFile.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageProvider.cs
  src/Avalonia.Base/Platform/Storage/FilePickerFileType.cs
  src/Avalonia.Base/Platform/Storage/IStorageFile.cs
  src/Avalonia.Base/Platform/Storage/IStorageProvider.cs
  src/Avalonia.Base/Platform/Storage/StorageProviderExtensions.cs
  src/Avalonia.Controls/Platform/Dialogs/SystemDialogImpl.cs
  src/Avalonia.Diagnostics/Diagnostics/Screenshots/FilePickerHandler.cs
  src/Avalonia.Dialogs/Internal/ManagedFileChooserViewModel.cs
  src/Avalonia.Dialogs/ManagedFileDialogExtensions.cs
  src/Avalonia.FreeDesktop/DBusSystemDialog.cs
  src/Avalonia.Native/SystemDialogs.cs
  src/Avalonia.X11/NativeDialogs/CompositeStorageProvider.cs
  src/Avalonia.X11/NativeDialogs/GtkNativeFileDialogs.cs
  src/Browser/Avalonia.Browser.Blazor/AvaloniaView.cs
  src/Browser/Avalonia.Browser.Blazor/BlazorSingleViewLifetime.cs
  src/Browser/Avalonia.Browser/AvaloniaView.cs
  src/Browser/Avalonia.Browser/BrowserAppBuilder.cs
  src/Browser/Avalonia.Browser/BrowserPlatformSettings.cs
  src/Browser/Avalonia.Browser/BrowserSingleViewLifetime.cs
  src/Browser/Avalonia.Browser/Interop/AvaloniaModule.cs
  src/Browser/Avalonia.Browser/Interop/StorageHelper.cs
  src/Browser/Avalonia.Browser/Storage/BrowserStorageProvider.cs
  src/Browser/Avalonia.Browser/webapp/.eslintrc.json
  src/Browser/Avalonia.Browser/webapp/build.js
  src/Browser/Avalonia.Browser/webapp/modules/avalonia.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/caniuse.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/stream.ts
  src/Browser/Avalonia.Browser/webapp/modules/storage/storageItem.ts
  src/Browser/Avalonia.Browser/webapp/modules/storage/storageProvider.ts
  src/Browser/Avalonia.Browser/webapp/package-lock.json
  src/Browser/Avalonia.Browser/webapp/package.json
  src/Browser/Avalonia.Browser/webapp/tsconfig.json
  src/Windows/Avalonia.Win32/Win32StorageProvider.cs
  src/iOS/Avalonia.iOS/Storage/IOSStorageItem.cs
  src/iOS/Avalonia.iOS/Storage/IOSStorageProvider.cs
Labels: bug, breaking-change, os-browser

#10339 Add SliderAutomationPeer
  samples/IntegrationTestApp/MainWindow.axaml
  src/Avalonia.Controls/Automation/Peers/SliderAutomationPeer.cs
  src/Avalonia.Controls/Slider.cs
  src/Windows/Avalonia.Win32/Automation/AutomationNode.cs
  src/Windows/Avalonia.Win32/Automation/RootAutomationNode.cs
  tests/Avalonia.IntegrationTests.Appium/SliderTests.cs
Labels: wont-backport

#9964 [SKIA] UseOpacitySaveLayer feature switch
  src/Avalonia.Base/Media/DrawingContext.cs
  src/Avalonia.Base/Media/DrawingGroup.cs
  src/Avalonia.Base/Media/ImmediateDrawingContext.cs
  src/Avalonia.Base/Platform/IDrawingContextImpl.cs
  src/Avalonia.Base/Rendering/Composition/Drawing/CompositionDrawingContext.cs
  src/Avalonia.Base/Rendering/Composition/Server/DrawingContextProxy.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs
  src/Avalonia.Base/Rendering/ImmediateRenderer.cs
  src/Avalonia.Base/Rendering/SceneGraph/OpacityNode.cs
  src/Avalonia.Headless/HeadlessPlatformRenderInterface.cs
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
  src/Skia/Avalonia.Skia/SkiaOptions.cs
  src/Windows/Avalonia.Direct2D1/Media/DrawingContextImpl.cs
  tests/Avalonia.Benchmarks/NullDrawingContextImpl.cs
  tests/Avalonia.RenderTests/Controls/CustomRenderTests.cs
  tests/Avalonia.RenderTests/Media/BitmapTests.cs
Labels: area-skia, area-rendering

#10149 ThemeVariant property definitions to ThemeVariantScope + fix DataGrid theme variant switch
  src/Avalonia.Base/Controls/ResourceNodeExtensions.cs
  src/Avalonia.Base/StyledElement.cs
  src/Avalonia.Base/Styling/IGlobalThemeVariantProvider.cs
  src/Avalonia.Base/Styling/IThemeVariantHost.cs
  src/Avalonia.Base/Styling/ThemeVariant.cs
  src/Avalonia.Controls.DataGrid/Themes/Fluent.xaml
  src/Avalonia.Controls/Application.cs
  src/Avalonia.Controls/Control.cs
  src/Avalonia.Controls/Primitives/Popup.cs
  src/Avalonia.Controls/ThemeVariantScope.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.Diagnostics/Diagnostics/Controls/Application.cs
  src/Avalonia.Themes.Simple/Controls/SplitButton.xaml
  src/Avalonia.Themes.Simple/Controls/SplitView.xaml
  src/Avalonia.Themes.Simple/Controls/ToggleSwitch.xaml
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/StaticResourceExtension.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/ThemeDictionariesTests.cs
Labels: bug

#10389 Browser drag n drop target support + new DataFormat.Files which returns IStorageItem collection
  samples/ControlCatalog/Pages/DialogsPage.xaml.cs
  samples/ControlCatalog/Pages/DragAndDropPage.xaml
  samples/ControlCatalog/Pages/DragAndDropPage.xaml.cs
  src/Avalonia.Base/Input/DataFormats.cs
  src/Avalonia.Base/Input/DataObject.cs
  src/Avalonia.Base/Input/DataObjectExtensions.cs
  src/Avalonia.Base/Input/IDataObject.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFile.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFolder.cs
  src/Avalonia.Base/Platform/Storage/FileIO/StorageProviderHelpers.cs
  src/Avalonia.Base/Platform/Storage/PickerOptions.cs
  src/Avalonia.Base/Platform/Storage/StorageProviderExtensions.cs
  src/Avalonia.Native/ClipboardImpl.cs
  src/Browser/Avalonia.Browser/AvaloniaView.cs
  src/Browser/Avalonia.Browser/BrowserDataObject.cs
  src/Browser/Avalonia.Browser/BrowserTopLevelImpl.cs
  src/Browser/Avalonia.Browser/ClipboardImpl.cs
  src/Browser/Avalonia.Browser/Interop/AvaloniaModule.cs
  src/Browser/Avalonia.Browser/Interop/GeneralHelpers.cs
  src/Browser/Avalonia.Browser/Interop/InputHelper.cs
  src/Browser/Avalonia.Browser/Interop/StorageHelper.cs
  src/Browser/Avalonia.Browser/Storage/BrowserStorageProvider.cs
  src/Browser/Avalonia.Browser/webapp/modules/avalonia.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/generalHelpers.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/input.ts
  src/Browser/Avalonia.Browser/webapp/modules/storage/storageItem.ts
  src/Browser/Avalonia.Browser/webapp/modules/storage/storageProvider.ts
  src/Windows/Avalonia.Win32/ClipboardFormats.cs
  src/Windows/Avalonia.Win32/DataObject.cs
  src/Windows/Avalonia.Win32/OleDataObject.cs
Labels: api, os-browser

#10427 macOS: Fix window order breaking when closing modal dialog
  native/Avalonia.Native/src/OSX/AvnWindow.mm
  tests/Avalonia.IntegrationTests.Appium/WindowTests_MacOS.cs
Labels: bug, os-macos, backport-candidate

#10055 Fix nth-last-child styles on virtualizing layouts
  samples/ControlCatalog/Pages/ListBoxPage.xaml
  src/Avalonia.Base/LogicalTree/ChildIndexChangedEventArgs.cs
  src/Avalonia.Base/LogicalTree/IChildIndexProvider.cs
  src/Avalonia.Base/Styling/Activators/NthChildActivator.cs
  src/Avalonia.Base/Styling/NthChildSelector.cs
  src/Avalonia.Controls.DataGrid/Primitives/DataGridCellsPresenter.cs
  src/Avalonia.Controls.DataGrid/Primitives/DataGridColumnHeadersPresenter.cs
  src/Avalonia.Controls.DataGrid/Primitives/DataGridRowsPresenter.cs
  src/Avalonia.Controls.ItemsRepeater/Controls/ItemsRepeater.cs
  src/Avalonia.Controls/ItemsControl.cs
  src/Avalonia.Controls/Panel.cs
  src/Avalonia.Controls/VirtualizingStackPanel.cs
  tests/Avalonia.Controls.UnitTests/VirtualizingStackPanelTests.cs
Labels: bug, regression

#10430 Add RadioButtonAutomationPeer
  samples/IntegrationTestApp/MainWindow.axaml
  src/Avalonia.Controls/Automation/Peers/RadioButtonAutomationPeer.cs
  src/Avalonia.Controls/Automation/SelectionItemPatternIdentifiers.cs
  src/Avalonia.Controls/RadioButton.cs
  src/Windows/Avalonia.Win32/Automation/AutomationNode.cs
  tests/Avalonia.IntegrationTests.Appium/RadioButtonTests.cs
Labels: wont-backport

#10470 Don't throw exceptions in carousel panel.
  src/Avalonia.Controls/VirtualizingCarouselPanel.cs
Labels: bug
