Repository AvaloniaUI/Avalonia, pull requests merged in 2023-06, with the labels that each got.

#11667 Text] Fixes
  src/Avalonia.Base/Media/GlyphRun.cs
  src/Avalonia.Base/Media/TextFormatting/TextFormatterImpl.cs
  src/Avalonia.Base/Media/TextFormatting/TextLayout.cs
  src/Avalonia.Base/Media/TextFormatting/TextLineImpl.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextLayoutTests.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextLineTests.cs
Labels: area-textprocessing

#11782 Fix changing selection source in selection changed
  .ncrunch/MobileSandbox.Browser.v3.ncrunchproject
  .ncrunch/WindowsInteropTest.net461.v3.ncrunchproject
  .ncrunch/WindowsInteropTest.net6.0-windows.v3.ncrunchproject
  src/Avalonia.Controls/Selection/SelectionModel.cs
  tests/Avalonia.Controls.UnitTests/Selection/SelectionModelTests_Single.cs
Labels: bug

#11783 Fix ListBox losing selection on container focus lost
  src/Avalonia.Controls/Primitives/SelectingItemsControl.cs
  tests/Avalonia.Controls.UnitTests/VirtualizingStackPanelTests.cs
Labels: bug

#11768 Use double for compositor types
  samples/ControlCatalog/Pages/CompositionPage.axaml.cs
  samples/ControlCatalog/Pages/GesturePage.cs
  samples/GpuInterop/DrawingSurfaceDemoBase.cs
  samples/Sandbox/MainWindow.axaml
  src/Avalonia.Base/Rendering/Composition/Animations/Interpolators.cs
  src/Avalonia.Base/Rendering/Composition/CompositingRenderer.cs
  src/Avalonia.Base/Rendering/Composition/CompositionCustomVisualHandler.cs
  src/Avalonia.Base/Rendering/Composition/CompositionTarget.cs
  src/Avalonia.Base/Rendering/Composition/Expressions/BuiltInExpressionFfi.cs
  src/Avalonia.Base/Rendering/Composition/Expressions/DelegateExpressionFfi.cs
  src/Avalonia.Base/Rendering/Composition/Expressions/ExpressionVariant.cs
  src/Avalonia.Base/Rendering/Composition/MatrixUtils.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs
  src/Avalonia.Base/Rendering/Composition/Visual.cs
  src/Avalonia.Base/Vector.cs
  src/Avalonia.Base/Vector3D.cs
  src/Avalonia.Base/composition-schema.xml
  src/Avalonia.Controls/PullToRefresh/RefreshVisualizer.cs
  src/Avalonia.OpenGL/Controls/OpenGlControlBase.cs
Labels: breaking-change

#11849 Don't set uncoerced value to coerced default value.
  src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs
  tests/Avalonia.Base.UnitTests/AvaloniaObjectTests_Coercion.cs
Labels: bug

#11882 Fix fluent compact theme
  src/Avalonia.Themes.Fluent/DensityStyles/Compact.xaml
  src/Avalonia.Themes.Fluent/FluentTheme.xaml
  src/Avalonia.Themes.Fluent/FluentTheme.xaml.cs
Labels: bug

#11904 Fix DataGridColumn.CellStyleClasses not settable from XAML
  src/Avalonia.Controls.DataGrid/DataGridColumn.cs
Labels: breaking-change

#11843 Fix palette TryGetResource code
  samples/ControlCatalog/App.xaml
  samples/ControlCatalog/App.xaml.cs
  src/Avalonia.Controls/AppBuilder.cs
  src/Avalonia.Themes.Fluent/ColorPaletteResourcesCollection.cs
Labels: bug

#11956 Make TextInputEventArgs.Text settable
  src/Avalonia.Base/Input/TextInputEventArgs.cs
Labels: release-blocker

#11898 Restructure Win32PlatformOptions options
  samples/ControlCatalog.NetCore/Program.cs
  src/Android/Avalonia.Android/AndroidPlatform.cs
  src/Avalonia.Native/AvaloniaNativePlatform.cs
  src/Avalonia.Native/AvaloniaNativePlatformExtensions.cs
  src/Avalonia.Native/PopupImpl.cs
  src/Avalonia.Native/WindowImpl.cs
  src/Avalonia.Native/WindowImplBase.cs
  src/Avalonia.OpenGL/Egl/EglPlatformGraphics.cs
  src/Avalonia.X11/Glx/GlxPlatformFeature.cs
  src/Avalonia.X11/X11Platform.cs
  src/Windows/Avalonia.Win32/DirectX/DxgiConnection.cs
  src/Windows/Avalonia.Win32/Win32GlManager.cs
  src/Windows/Avalonia.Win32/Win32Platform.cs
  src/Windows/Avalonia.Win32/Win32PlatformOptions.cs
  src/Windows/Avalonia.Win32/WinRT/Composition/WinUiCompositedWindowSurface.cs
  src/Windows/Avalonia.Win32/WinRT/Composition/WinUiCompositionShared.cs
  src/Windows/Avalonia.Win32/WinRT/Composition/WinUiCompositorConnection.cs
Labels: breaking-change

#11848 Rework ITextInputMethodClient
  samples/MobileSandbox.Android/MainActivity.cs
  src/Android/Avalonia.Android/AndroidInputMethod.cs
  src/Android/Avalonia.Android/InputEditable.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
  src/Avalonia.Base/Input/TextInput/ITextEditable.cs
  src/Avalonia.Base/Input/TextInput/ITextInputMethodClient.cs
  src/Avalonia.Base/Input/TextInput/ITextInputMethodImpl.cs
  src/Avalonia.Base/Input/TextInput/InputMethodManager.cs
  src/Avalonia.Base/Input/TextInput/TextInputMethodClient.cs
  src/Avalonia.Base/Input/TextInput/TextInputMethodClientRequestedEventArgs.cs
  src/Avalonia.Controls/Presenters/TextPresenter.cs
  src/Avalonia.Controls/TextBox.cs
  src/Avalonia.Controls/TextBoxTextInputMethodClient.cs
  src/Avalonia.FreeDesktop/DBusIme/DBusTextInputMethodBase.cs
  src/Avalonia.Native/AvaloniaNativeTextInputMethod.cs
  src/Avalonia.X11/X11Window.Xim.cs
  src/Browser/Avalonia.Browser/AvaloniaView.cs
  src/Windows/Avalonia.Win32/Input/Imm32InputMethod.cs
  src/iOS/Avalonia.iOS/AvaloniaView.Text.cs
  src/iOS/Avalonia.iOS/AvaloniaView.cs
  src/iOS/Avalonia.iOS/TextInputResponder.cs
Labels: breaking-change, release-blocker
