Repository AvaloniaUI/Avalonia, pull requests merged in 2023-11, with the labels that each got.

#13506 Fix ImageBrush crash when source bitmap gets disposed
  src/Avalonia.Base/Media/Imaging/Bitmap.cs
Labels: backport-candidate-11.0.x

#13312 Make Avalonia.Browser work on .NET 8
  samples/ControlCatalog.Browser/AppBundle/Logo.svg
  samples/ControlCatalog.Browser/AppBundle/app.css
  samples/ControlCatalog.Browser/AppBundle/embed.js
  samples/ControlCatalog.Browser/AppBundle/favicon.ico
  samples/ControlCatalog.Browser/AppBundle/index.html
  samples/ControlCatalog.Browser/AppBundle/main.js
  samples/ControlCatalog.Browser/ControlCatalog.Browser.csproj
  samples/ControlCatalog.Browser/EmbedSample.Browser.cs
  samples/ControlCatalog.Browser/Program.cs
  samples/ControlCatalog.Browser/Roots.xml
  samples/ControlCatalog.Browser/app.css
  samples/ControlCatalog.Browser/index.html
  src/Avalonia.Base/Logging/LogArea.cs
  src/Avalonia.Base/Media/MediaContext.Compositor.cs
  src/Avalonia.Base/Rendering/Composition/CompositingRenderer.cs
  src/Avalonia.Base/Rendering/Composition/Compositor.cs
  src/Browser/Avalonia.Browser/Avalonia.Browser.props
  src/Browser/Avalonia.Browser/Avalonia.Browser.targets
  src/Browser/Avalonia.Browser/AvaloniaView.cs
  src/Browser/Avalonia.Browser/BrowserDispatcherImpl.cs
  src/Browser/Avalonia.Browser/Interop/CanvasHelper.cs
  src/Browser/Avalonia.Browser/WindowingPlatform.cs
Labels: enhancement, os-browser, backport-candidate-11.0.x

#13625 Win32 file picker fixes
  src/Windows/Avalonia.Win32/Win32Com/win32.idl
  src/Windows/Avalonia.Win32/Win32StorageProvider.cs
Labels: os-windows

#13630 fix:Previewer connection fails from VSCode
  src/Avalonia.DesignerSupport/Remote/HtmlTransport/HtmlTransport.cs
Labels: backport-candidate-11.0.x

#13047 Impl auto safe area padding
  samples/SafeAreaDemo.iOS/Info.plist
  samples/SafeAreaDemo/App.xaml
  samples/SafeAreaDemo/App.xaml.cs
  samples/SafeAreaDemo/ViewModels/MainViewModel.cs
  samples/SafeAreaDemo/Views/MainView.xaml
  samples/SafeAreaDemo/Views/MainView.xaml.cs
  src/Avalonia.Controls/TopLevel.cs
  src/iOS/Avalonia.iOS/AvaloniaView.cs
  src/iOS/Avalonia.iOS/InsetsManager.cs
Labels: breaking-change

#13699 Fix Design.IsDesignMode being false in BuildAvaloniaApp method
  src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs
Labels: bug, area-previewer, backport-candidate-11.0.x

#13765 Fix overlapping items in `VirtualizingStackPanel`
  src/Avalonia.Controls/Utils/RealizedStackElements.cs
  tests/Avalonia.Controls.UnitTests/VirtualizingStackPanelTests.cs
Labels: backport-candidate-11.0.x

#13680 Data grid handled events
  src/Avalonia.Controls.DataGrid/DataGridCell.cs
Labels: backport-candidate-11.0.x
