Repository AvaloniaUI/Avalonia, pull requests merged in 2023-10, with the labels that each got.

#13080 Add "EGL_ANGLE_flexible_surface_compatibility" ext check
  src/Avalonia.OpenGL/Egl/EglContext.cs
  src/Avalonia.OpenGL/Egl/EglDisplay.cs
  src/Avalonia.OpenGL/Egl/EglInterface.cs
  src/Windows/Avalonia.Win32/OpenGl/Angle/AngleExternalD3D11Texture2D.cs
  src/Windows/Avalonia.Win32/OpenGl/Angle/AngleWin32EglDisplay.cs
Labels: backport-candidate-11.0.x

#13066 Fix initial logical scrollable state
  src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
  tests/Avalonia.Controls.UnitTests/ItemsControlTests.cs
  tests/Avalonia.Controls.UnitTests/Primitives/SelectingItemsControlTests_Multiple.cs
  tests/Avalonia.Controls.UnitTests/ScrollViewerTests_ILogicalScrollable.cs
Labels: backport-candidate-11.0.x

#13097 Fixed an issue that windows empty Win32 window would show unnecessarily
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: bug, os-windows, backport-candidate-11.0.x

#13106 [nuke] Use a regex to detect a release branch.
  nukebuild/BuildParameters.cs
Labels: infrastructure, backport-candidate-11.0.x

#13109 Update SkiaSharp to 2.88.6 to fix a critical security vulnerability
  build/SkiaSharp.props
  src/Tizen/Avalonia.Tizen/Avalonia.Tizen.csproj
Labels: backport-candidate-0.10.x

#13156 fix parsing the baseline version for api diff.
  nukebuild/BuildParameters.cs
Labels: backport-candidate-11.0.x

#13197 Fix macOS clipboard formats mapping
  native/Avalonia.Native/src/OSX/clipboard.mm
  src/Avalonia.Base/Input/DataFormats.cs
  src/Avalonia.Native/AvaloniaNativeDragSource.cs
  src/Avalonia.Native/ClipboardImpl.cs
  src/Avalonia.Native/avn.idl
Labels: bug, os-macos

#13313 Implement IList on DataGridCollectionView.
  src/Avalonia.Controls.DataGrid/Collections/DataGridCollectionView.cs
  src/Avalonia.Controls.DataGrid/DataGridDataConnection.cs
Labels: enhancement

#13274 Add TextBox.ScrollToLine
  src/Avalonia.Controls/TextBox.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
Labels: backport-candidate-11.0.x, hacktoberfest-accepted
