Repository AvaloniaUI/Avalonia, pull requests merged in 2023-05, with the labels that each got.

#11096 [CRITICAL] [Input] [MacOS] fix timestamp overflow on objC side
  native/Avalonia.Native/src/OSX/AvnView.mm
  native/Avalonia.Native/src/OSX/AvnWindow.mm
  src/Avalonia.Native/WindowImplBase.cs
  src/Avalonia.Native/avn.idl
Labels: backport-candidate

#11233 Fix scrollbar getting stuck in certain situations
  src/Avalonia.Base/Layout/LayoutManager.cs
  tests/Avalonia.Base.UnitTests/Layout/LayoutManagerTests.cs
Labels: bug

#11252 Fix drag delta when moving outside draggable range.
  src/Avalonia.Controls/Primitives/Thumb.cs
  src/Avalonia.Controls/Primitives/Track.cs
  tests/Avalonia.Controls.UnitTests/ScrollViewerTests.cs
  tests/Avalonia.UnitTests/MouseTestHelper.cs
Labels: bug

#11085 WASM save file picker polyfill for Firefox
  src/Avalonia.Base/Platform/Storage/FileIO/StorageProviderHelpers.cs
  src/Browser/Avalonia.Browser/BrowserAppBuilder.cs
  src/Browser/Avalonia.Browser/Interop/AvaloniaModule.cs
  src/Browser/Avalonia.Browser/Interop/StorageHelper.cs
  src/Browser/Avalonia.Browser/Storage/BrowserStorageProvider.cs
  src/Browser/Avalonia.Browser/WindowingPlatform.cs
  src/Browser/Avalonia.Browser/webapp/build.js
  src/Browser/Avalonia.Browser/webapp/modules/avalonia.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/stream.ts
  src/Browser/Avalonia.Browser/webapp/modules/storage/storageProvider.ts
  src/Browser/Avalonia.Browser/webapp/modules/sw.ts
Labels: bug, bug-in-dependency, os-browser

#11265 ResourceDictionary xaml tests
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/GroupTransformers/XamlIncludeGroupTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlThemeVariantProviderTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/ResourceIncludeTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/ResourceDictionaryTests.cs
Labels: bug, area-xaml

#11169 [WIP] Reuse text and geometry related headless mocks in Avalonia unit test and benchmarks
  src/Headless/Avalonia.Headless/Avalonia.Headless.csproj
  src/Headless/Avalonia.Headless/HeadlessPlatformRenderInterface.cs
  src/Headless/Avalonia.Headless/HeadlessPlatformStubs.cs
  tests/Avalonia.Base.UnitTests/Media/FontManagerTests.cs
  tests/Avalonia.Base.UnitTests/Media/GlyphRunTests.cs
  tests/Avalonia.Base.UnitTests/Rendering/CompositorHitTestingTests.cs
  tests/Avalonia.Base.UnitTests/VisualTree/MockRenderInterface.cs
  tests/Avalonia.Benchmarks/Layout/ControlsBenchmark.cs
  tests/Avalonia.Benchmarks/NullCursorFactory.cs
  tests/Avalonia.Benchmarks/NullDrawingContextImpl.cs
  tests/Avalonia.Benchmarks/NullRenderingPlatform.cs
  tests/Avalonia.Benchmarks/NullThreadingPlatform.cs
  tests/Avalonia.Benchmarks/Rendering/ShapeRendering.cs
  tests/Avalonia.Benchmarks/Styling/ControlTheme_Change.cs
  tests/Avalonia.Benchmarks/Styling/ResourceBenchmarks.cs
  tests/Avalonia.Benchmarks/Styling/Style_Apply_Detach_Complex.cs
  tests/Avalonia.Benchmarks/Text/HugeTextLayout.cs
  tests/Avalonia.Benchmarks/Themes/FluentBenchmark.cs
  tests/Avalonia.Controls.UnitTests/DatePickerTests.cs
  tests/Avalonia.Controls.UnitTests/ItemsControlTests.cs
  tests/Avalonia.Controls.UnitTests/MaskedTextBoxTests.cs
  tests/Avalonia.Controls.UnitTests/Primitives/SelectingItemsControlTests_Multiple.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests_DataValidation.cs
  tests/Avalonia.Controls.UnitTests/TimePickerTests.cs
  tests/Avalonia.Controls.UnitTests/TreeViewTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/StyleTests.cs
  tests/Avalonia.Skia.UnitTests/Media/FontManagerTests.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextLayoutTests.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextLineTests.cs
  tests/Avalonia.UnitTests/Avalonia.UnitTests.csproj
  tests/Avalonia.UnitTests/ImmediateDispatcher.cs
  tests/Avalonia.UnitTests/MockFontManagerImpl.cs
  tests/Avalonia.UnitTests/MockGlyphRun.cs
  tests/Avalonia.UnitTests/MockGlyphTypeface.cs
  tests/Avalonia.UnitTests/MockPlatformRenderInterface.cs
  tests/Avalonia.UnitTests/MockStreamGeometryImpl.cs
  tests/Avalonia.UnitTests/MockTextShaperImpl.cs
  tests/Avalonia.UnitTests/TestServices.cs
  tests/Avalonia.UnitTests/TextTestHelper.cs
Labels: area-headless

#11363 Use TypeSystem.String instead of typeof(string) when resolving types from Cecil
  src/Avalonia.Build.Tasks/XamlCompilerTaskExecutor.cs
Labels: area-xaml

#11387 Make some AvaloniaProperty APIs internal.
  src/Avalonia.Base/AttachedProperty.cs
  src/Avalonia.Base/AvaloniaProperty.cs
  src/Avalonia.Base/AvaloniaProperty`1.cs
  src/Avalonia.Base/DirectProperty.cs
  src/Avalonia.Base/DirectPropertyBase.cs
  src/Avalonia.Base/StyledProperty.cs
Labels: breaking-change

#11407 Limit IFocusManager API, extend IInputElement API, remove focus static members from public API
  src/Avalonia.Base/Input/AccessKeyHandler.cs
  src/Avalonia.Base/Input/FocusManager.cs
  src/Avalonia.Base/Input/IFocusManager.cs
  src/Avalonia.Base/Input/IFocusScope.cs
  src/Avalonia.Base/Input/IInputElement.cs
  src/Avalonia.Base/Input/IInputRoot.cs
  src/Avalonia.Base/Input/IKeyboardDevice.cs
  src/Avalonia.Base/Input/InputElement.cs
  src/Avalonia.Base/Input/KeyboardDevice.cs
  src/Avalonia.Base/Input/KeyboardNavigationHandler.cs
  src/Avalonia.Base/Input/MouseDevice.cs
  src/Avalonia.Base/Input/Navigation/TabNavigation.cs
  src/Avalonia.Base/Input/PenDevice.cs
  src/Avalonia.Base/Input/TouchDevice.cs
  src/Avalonia.Controls.DataGrid/DataGrid.cs
  src/Avalonia.Controls.ItemsRepeater/Controls/ViewManager.cs
  src/Avalonia.Controls/AutoCompleteBox/AutoCompleteBox.cs
  src/Avalonia.Controls/Calendar/Calendar.cs
  src/Avalonia.Controls/ComboBox.cs
  src/Avalonia.Controls/ContextMenu.cs
  src/Avalonia.Controls/DateTimePickers/DatePickerPresenter.cs
  src/Avalonia.Controls/DateTimePickers/TimePickerPresenter.cs
  src/Avalonia.Controls/Flyouts/PopupFlyoutBase.cs
  src/Avalonia.Controls/ItemsControl.cs
  src/Avalonia.Controls/Primitives/Popup.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.Controls/TreeView.cs
  src/Avalonia.Controls/TreeViewItem.cs
  src/Avalonia.Controls/WindowBase.cs
  src/Avalonia.Diagnostics/Diagnostics/DevTools.cs
  src/Linux/Avalonia.LinuxFramebuffer/LinuxFramebufferPlatform.cs
  src/Windows/Avalonia.Win32.Interop/WinForms/WinFormsAvaloniaControlHost.cs
  src/Windows/Avalonia.Win32/Input/WindowsKeyboardDevice.cs
  tests/Avalonia.Base.UnitTests/Input/InputElement_Focus.cs
  tests/Avalonia.Base.UnitTests/Input/PointerOverTests.cs
  tests/Avalonia.Controls.UnitTests/FlyoutTests.cs
  tests/Avalonia.Controls.UnitTests/ItemsControlTests.cs
  tests/Avalonia.Controls.UnitTests/ListBoxTests.cs
  tests/Avalonia.Controls.UnitTests/Platform/DefaultMenuInteractionHandlerTests.cs
  tests/Avalonia.Controls.UnitTests/Primitives/PopupTests.cs
  tests/Avalonia.Controls.UnitTests/TabControlTests.cs
  tests/Avalonia.Controls.UnitTests/TreeViewTests.cs
  tests/Avalonia.LeakTests/ControlTests.cs
  tests/Avalonia.UnitTests/TestRoot.cs
Labels: breaking-change

#11443 update buildservices nuget.
  packages/Avalonia/Avalonia.csproj
Labels: backported-0.10.x

#11437 Make miscellaneous Avalonia.Base APIs internal
  samples/GpuInterop/VulkanDemo/VulkanContext.cs
  samples/VirtualizationDemo/ViewModels/PlaygroundPageViewModel.cs
  src/Avalonia.Base/Animation/Animatable.cs
  src/Avalonia.Base/Avalonia.Base.csproj
  src/Avalonia.Base/AvaloniaPropertyExtensions.cs
  src/Avalonia.Base/Collections/Pooled/ClearMode.cs
  src/Avalonia.Base/Collections/Pooled/IReadOnlyPooledList.cs
  src/Avalonia.Base/Collections/Pooled/PooledList.cs
  src/Avalonia.Base/Collections/Pooled/PooledStack.cs
  src/Avalonia.Base/Controls/ChildNameScope.cs
  src/Avalonia.Base/Data/Core/CommonPropertyNames.cs
  src/Avalonia.Base/Data/IndexerBinding.cs
  src/Avalonia.Base/Diagnostics/IAvaloniaObjectDebug.cs
  src/Avalonia.Base/Diagnostics/INotifyCollectionChangedDebug.cs
  src/Avalonia.Base/EnumExtensions.cs
  src/Avalonia.Base/Input/AccessKeyHandler.cs
  src/Avalonia.Base/Input/KeyboardNavigationHandler.cs
  src/Avalonia.Base/Interactivity/Interactive.cs
  src/Avalonia.Base/Logging/TraceLogSink.cs
  src/Avalonia.Base/Media/ArcSegment.cs
  src/Avalonia.Base/Media/BezierSegment .cs
  src/Avalonia.Base/Media/Imaging/Bitmap.cs
  src/Avalonia.Base/Media/Immutable/ImmutableTileBrush.cs
  src/Avalonia.Base/Media/LineSegment.cs
  src/Avalonia.Base/Media/PathSegment.cs
  src/Avalonia.Base/Media/PolyLineSegment.cs
  src/Avalonia.Base/Media/QuadraticBezierSegment .cs
  src/Avalonia.Base/Media/StreamGeometryContext.cs
  src/Avalonia.Base/Media/Transformation/TransformParser.cs
  src/Avalonia.Base/Platform/Storage/NameCollisionOption.cs
  src/Avalonia.Base/Rendering/ManagedDeferredRendererLock.cs
  src/Avalonia.Base/Rendering/RendererBase.cs
  src/Avalonia.Base/Rendering/Utilities/TileBrushCalculator.cs
  src/Avalonia.Base/Rendering/ZIndexComparer.cs
  src/Avalonia.Base/StyledElement.cs
  src/Avalonia.Base/Utilities/DisposableLock.cs
  src/Avalonia.Base/Utilities/NonPumpingLockHelper.cs
  src/Avalonia.Base/Utilities/SingleOrDictionary.cs
  src/Avalonia.Base/Utilities/SingleOrQueue.cs
  src/Avalonia.Base/Utilities/ValueSingleOrList.cs
  src/Avalonia.Base/Utilities/WeakTimer.cs
  src/Avalonia.Base/Visual.cs
  src/Avalonia.Controls.ItemsRepeater/Controls/RepeaterLayoutContext.cs
  src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
  src/Avalonia.Controls/Primitives/AccessText.cs
  src/Avalonia.Controls/Primitives/OverlayPopupHost.cs
  src/Avalonia.Controls/Primitives/PopupRoot.cs
  src/Avalonia.Controls/Primitives/ScrollBar.cs
  src/Avalonia.Controls/Primitives/TemplatedControl.cs
  src/Avalonia.Controls/Primitives/VisualLayerManager.cs
  src/Avalonia.Controls/TextBlock.cs
  src/Avalonia.Controls/Viewbox.cs
  src/Headless/Avalonia.Headless.Vnc/HeadlessVncFramebufferSource.cs
  src/Windows/Avalonia.Win32.Interop/Wpf/WpfTopLevelImpl.cs
  tests/Avalonia.IntegrationTests.Appium/PlatformFactAttribute.cs
  tests/Avalonia.IntegrationTests.Appium/PlatformTheoryAttribute.cs
Labels: breaking-change

#11458 Use `IsEffectivelyEnabled` in automation peers.
  samples/IntegrationTestApp/MainWindow.axaml
  src/Avalonia.Controls/Automation/Peers/ControlAutomationPeer.cs
  tests/Avalonia.IntegrationTests.Appium/ButtonTests.cs
Labels: bug

#11465 Focus first child from no focus.
  src/Avalonia.Base/Input/KeyboardNavigationHandler.cs
  tests/Avalonia.Base.UnitTests/Input/KeyboardNavigationTests_Tab.cs
Labels: bug

#11483 Make miscellaneous Avalonia.Markup and Avalonia.Markup.Xaml APIs internal
  src/Avalonia.Base/Animation/AnimatorKeyFrame.cs
  src/Avalonia.Base/AvaloniaProperty.cs
  src/Avalonia.Base/AvaloniaProperty`1.cs
  src/Avalonia.Base/Collections/AvaloniaListConverter.cs
  src/Avalonia.Base/Data/BindingValue.cs
  src/Avalonia.Base/Data/Converters/DefaultValueConverter.cs
  src/Avalonia.Base/Data/Core/BindingExpression.cs
  src/Avalonia.Base/Data/TemplateBinding.cs
  src/Avalonia.Base/Diagnostics/TrimmingMessages.cs
  src/Avalonia.Base/Properties/AssemblyInfo.cs
  src/Avalonia.Base/PropertyStore/DirectUntypedBindingObserver.cs
  src/Avalonia.Base/PropertyStore/LocalValueBindingObserver.cs
  src/Avalonia.Base/PropertyStore/UntypedValueUtils.cs
  src/Avalonia.Base/StyledProperty.cs
  src/Avalonia.Base/Styling/PropertyEqualsSelector.cs
  src/Avalonia.Base/Styling/Setter.cs
  src/Avalonia.Base/Utilities/TypeUtilities.cs
  src/Markup/Avalonia.Markup.Xaml/Avalonia.Markup.Xaml.csproj
  src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindings/CompiledBindingPath.cs
  src/Markup/Avalonia.Markup/Avalonia.Markup.csproj
  src/Markup/Avalonia.Markup/Data/BindingBase.cs
  src/Markup/Avalonia.Markup/Markup/Data/DelayedBinding.cs
  src/Markup/Avalonia.Markup/Markup/Parsers/ArgumentListParser.cs
  src/Markup/Avalonia.Markup/Markup/Parsers/PropertyPathGrammar.cs
  src/Markup/Avalonia.Markup/Markup/Parsers/SelectorParser.cs
  tests/Avalonia.Markup.Xaml.UnitTests/XamlTestBase.cs
Labels: api, breaking-change

#11455 Fix `ListBox` selection interactions
  src/Avalonia.Controls/ItemsControl.cs
  src/Avalonia.Controls/ListBox.cs
  src/Avalonia.Controls/ListBoxItem.cs
  src/Avalonia.Controls/Primitives/SelectingItemsControl.cs
  src/Avalonia.Controls/VirtualizingStackPanel.cs
  tests/Avalonia.Controls.UnitTests/ListBoxTests.cs
  tests/Avalonia.Controls.UnitTests/ListBoxTests_Multiple.cs
  tests/Avalonia.Controls.UnitTests/ListBoxTests_Single.cs
Labels: bug

#11495 Remove presenter interfaces
  src/Avalonia.Controls/ContentControl.cs
  src/Avalonia.Controls/Presenters/ContentPresenter.cs
  src/Avalonia.Controls/Presenters/IContentPresenter.cs
  src/Avalonia.Controls/Presenters/IContentPresenterHost.cs
  src/Avalonia.Controls/Presenters/IPresenter.cs
  src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
  src/Avalonia.Controls/Primitives/HeaderedContentControl.cs
  src/Avalonia.Controls/Primitives/HeaderedItemsControl.cs
  src/Avalonia.Controls/Primitives/HeaderedSelectingItemsControl.cs
  src/Avalonia.Controls/Primitives/IPopupHost.cs
  src/Avalonia.Controls/ScrollViewer.cs
  src/Avalonia.Controls/SplitView/SplitView.cs
  src/Avalonia.Controls/TabControl.cs
  src/Avalonia.Controls/ToggleSwitch.cs
  src/Avalonia.Controls/TransitioningContentControl.cs
  tests/Avalonia.Controls.UnitTests/ContentControlTests.cs
  tests/Avalonia.Controls.UnitTests/HeaderedItemsControlTests .cs
  tests/Avalonia.Controls.UnitTests/ListBoxTests_Single.cs
  tests/Avalonia.Controls.UnitTests/Presenters/ContentPresenterTests_InTemplate.cs
  tests/Avalonia.Controls.UnitTests/TabControlTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/CompiledBindingExtensionTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/ControlTemplateTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/DataTemplateTests.cs
  tests/Avalonia.ReactiveUI.UnitTests/TransitioningContentControlTest.cs
  tests/Avalonia.UnitTests/TestExtensions.cs
Labels: api, breaking-change

#11552 Media system refactoring
  src/Android/Avalonia.Android/AndroidPlatform.cs
  src/Avalonia.Base/Animation/Easings/IEasing.cs
  src/Avalonia.Base/Layout/LayoutManager.cs
  src/Avalonia.Base/Media/MediaContext.Compositor.cs
  src/Avalonia.Base/Media/MediaContext.cs
  src/Avalonia.Base/Rendering/Composition/Compositor.cs
  src/Avalonia.Base/Rendering/Composition/Drawing/RenderDataDrawingContext.cs
  src/Avalonia.Base/Rendering/Composition/Drawing/ServerResourceHelperExtensions.cs
  src/Browser/Avalonia.Browser/BrowserTopLevelImpl.cs
  src/iOS/Avalonia.iOS/Platform.cs
  tests/Avalonia.Base.UnitTests/Rendering/SceneGraph/DrawOperationTests.cs
Labels: breaking-change

#11557 Mark private apis as private
  nukebuild/RefAssemblyGenerator.cs
  samples/ControlCatalog.NetCore/ControlCatalog.NetCore.csproj
  src/Android/Avalonia.Android/Platform/SkiaPlatform/InvalidationAwareSurfaceView.cs
  src/Avalonia.Base/AvaloniaLocator.cs
  src/Avalonia.Base/Input/DragDropDevice.cs
  src/Avalonia.Base/Input/IInputDevice.cs
  src/Avalonia.Base/Input/IInputManager.cs
  src/Avalonia.Base/Input/IKeyboardNavigationHandler.cs
  src/Avalonia.Base/Input/InputManager.cs
  src/Avalonia.Base/Input/KeyboardNavigationHandler.cs
  src/Avalonia.Base/Input/Raw/RawDragEvent.cs
  src/Avalonia.Base/Input/Raw/RawInputEventArgs.cs
  src/Avalonia.Base/Input/Raw/RawKeyEventArgs.cs
  src/Avalonia.Base/Input/Raw/RawMouseWheelEventArgs.cs
  src/Avalonia.Base/Input/Raw/RawPointerEventArgs.cs
  src/Avalonia.Base/Input/Raw/RawPointerGestureEventArgs.cs
  src/Avalonia.Base/Input/Raw/RawSizeEventArgs.cs
  src/Avalonia.Base/Input/Raw/RawTextInputEventArgs.cs
  src/Avalonia.Base/Input/Raw/RawTouchEventArgs.cs
  src/Avalonia.Base/Media/Brush.cs
  src/Avalonia.Base/Media/DrawingBrush.cs
  src/Avalonia.Base/Media/VisualBrush.cs
  src/Avalonia.Base/Metadata/PrivateApiAttribute.cs
  src/Avalonia.Base/Platform/IModuleEnvironmentChecker.cs
  src/Avalonia.Base/Platform/IPlatformThreadingInterface.cs
  src/Avalonia.Base/Platform/IRenderTarget.cs
  src/Avalonia.Base/Platform/Interop/IDynamicLibraryLoader.cs
  src/Avalonia.Base/Platform/Interop/Utf8Buffer.cs
  src/Avalonia.Base/Rendering/DefaultRenderTimer.cs
  src/Avalonia.Base/Rendering/DirtyRects.cs
  src/Avalonia.Base/Rendering/DirtyVisuals.cs
  src/Avalonia.Base/Rendering/DisplayDirtyRect.cs
  src/Avalonia.Base/Rendering/DisplayDirtyRects.cs
  src/Avalonia.Base/Rendering/IDeferredRendererLock.cs
  src/Avalonia.Base/Rendering/IRenderTimer.cs
  src/Avalonia.Base/Rendering/IVisualBrushInitialize.cs
  src/Avalonia.Base/Rendering/ManagedDeferredRendererLock.cs
  src/Avalonia.Base/Rendering/SceneInvalidatedEventArgs.cs
  src/Avalonia.Base/Rendering/SleepLoopRenderTimer.cs
  src/Avalonia.Base/Rendering/UiThreadRenderTimer.cs
  src/Avalonia.Base/VisualTree/IVisualWithRoundRectClip.cs
  src/Avalonia.Controls/Application.cs
  src/Avalonia.Controls/Platform/INativeApplicationCommands.cs
  src/Avalonia.Controls/Platform/IPlatformNativeSurfaceHandle.cs
  src/Avalonia.Controls/Primitives/PopupPositioning/ManagedPopupPositioner.cs
  src/Avalonia.Controls/Primitives/PopupPositioning/ManagedPopupPositionerPopupImplHelper.cs
  src/Avalonia.Diagnostics/Diagnostics/Controls/Application.cs
  src/Avalonia.X11/X11Window.cs
  src/Linux/Avalonia.LinuxFramebuffer/Output/DrmBindings.cs
  src/Linux/Avalonia.LinuxFramebuffer/Output/DrmOutput.cs
  src/Windows/Avalonia.Direct2D1/Avalonia.Direct2D1.csproj
  src/Windows/Avalonia.Direct2D1/Direct2DChecker.cs
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
  tests/Avalonia.UnitTests/NullRenderer.cs
Labels: breaking-change

#11394 Fix PushOpacity when ClipToBounds is false
  src/Avalonia.Base/Media/DrawingContext.cs
  src/Avalonia.Base/Media/DrawingGroup.cs
  src/Avalonia.Base/Media/PlatformDrawingContext.cs
  src/Avalonia.Base/Platform/IDrawingContextImpl.cs
  src/Avalonia.Base/Rendering/Composition/Drawing/Nodes/RenderDataNodes.cs
  src/Avalonia.Base/Rendering/Composition/Drawing/RenderDataDrawingContext.cs
  src/Avalonia.Base/Rendering/Composition/Server/DrawingContextProxy.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs
  src/Avalonia.Base/Rendering/ImmediateRenderer.cs
  src/Headless/Avalonia.Headless/HeadlessPlatformRenderInterface.cs
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
  src/Windows/Avalonia.Direct2D1/Media/DrawingContextImpl.cs
  tests/Avalonia.RenderTests/Controls/CustomRenderTests.cs
Labels: breaking-change

#11566 Fix devtools after recent XAML compiler changes
  src/Avalonia.Build.Tasks/XamlCompilerTaskExecutor.cs
  src/Avalonia.Controls.ColorPicker/Themes/Fluent/ColorPicker.xaml
  src/Avalonia.Controls.ColorPicker/Themes/Fluent/ColorPreviewer.xaml
  src/Avalonia.Controls.ColorPicker/Themes/Fluent/ColorSlider.xaml
  src/Avalonia.Controls.ColorPicker/Themes/Fluent/ColorSpectrum.xaml
  src/Avalonia.Controls.ColorPicker/Themes/Fluent/ColorView.xaml
  src/Avalonia.Controls.ColorPicker/Themes/Simple/ColorPicker.xaml
  src/Avalonia.Controls.ColorPicker/Themes/Simple/ColorPreviewer.xaml
  src/Avalonia.Controls.ColorPicker/Themes/Simple/ColorSlider.xaml
  src/Avalonia.Controls.ColorPicker/Themes/Simple/ColorSpectrum.xaml
  src/Avalonia.Controls.ColorPicker/Themes/Simple/ColorView.xaml
  src/Avalonia.Diagnostics/Diagnostics/Controls/FilterTextBox.axaml
  src/Avalonia.Diagnostics/Diagnostics/Controls/ThicknessEditor.axaml
Labels: area-xaml

#11488 Updates to WinForms interop
  Avalonia.sln
  dirs.proj
  nukebuild/_build.csproj
  samples/ControlCatalog.Desktop/ControlCatalog.Desktop.csproj
  samples/ControlCatalog.Desktop/Program.cs
  samples/interop/WindowsInteropTest/EmbedToWinFormsDemo.Designer.cs
  samples/interop/WindowsInteropTest/EmbedToWinFormsDemo.cs
  samples/interop/WindowsInteropTest/EmbedToWpfDemo.xaml
  samples/interop/WindowsInteropTest/EmbedToWpfDemo.xaml.cs
  samples/interop/WindowsInteropTest/Program.cs
  samples/interop/WindowsInteropTest/SelectorForm.Designer.cs
  samples/interop/WindowsInteropTest/SelectorForm.cs
  samples/interop/WindowsInteropTest/SelectorForm.resx
  samples/interop/WindowsInteropTest/WindowsInteropTest.csproj
  src/Avalonia.Controls/TopLevel.cs
  src/Windows/Avalonia.Direct2D1/Avalonia.Direct2D1.csproj
  src/Windows/Avalonia.Win32.Interop/WinForms/WinFormsAvaloniaControlHost.cs
  src/Windows/Avalonia.Win32.Interop/Wpf/CursorShim.cs
  src/Windows/Avalonia.Win32.Interop/Wpf/Direct2DImageSurface.cs
  src/Windows/Avalonia.Win32.Interop/Wpf/IntSize.cs
  src/Windows/Avalonia.Win32.Interop/Wpf/WpfAvaloniaHost.cs
  src/Windows/Avalonia.Win32.Interop/Wpf/WpfInteropExtensions.cs
  src/Windows/Avalonia.Win32.Interop/Wpf/WpfMouseDevice.cs
  src/Windows/Avalonia.Win32.Interop/Wpf/WpfTopLevelImpl.cs
  src/Windows/Avalonia.Win32.Interop/Wpf/WritableBitmapSurface.cs
  src/Windows/Avalonia.Win32.Interoperability/Avalonia.Win32.Interoperability.csproj
  src/Windows/Avalonia.Win32.Interoperability/WinForms/WinFormsAvaloniaControlHost.cs
  src/Windows/Avalonia.Win32/Avalonia.Win32.csproj
  src/tools/Avalonia.Designer.HostApp/Program.cs
  tests/Avalonia.UnitTests/InvariantCultureFixture.cs
Labels: os-windows, breaking-change

#11574 Remove IKeyboardDevice/IPointerDevice/IDragDropDevice from public API, as they are not really used anywhere
  src/Avalonia.Base/Input/IKeyboardDevice.cs
  src/Avalonia.Base/Input/IMouseDevice.cs
  src/Avalonia.Base/Input/IPenDevice.cs
  src/Avalonia.Base/Input/IPointerDevice.cs
  src/Avalonia.Base/Input/KeyEventArgs.cs
  src/Avalonia.Base/Input/KeyboardDevice.cs
  src/Avalonia.Base/Input/Raw/IDragDropDevice.cs
  src/Avalonia.Base/Input/TextInputEventArgs.cs
  tests/Avalonia.Controls.UnitTests/Primitives/SelectingItemsControlTests.cs
Labels: breaking-change

#11579 BclStorageFile.OpenWrite should always override file if it exist
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFile.cs
Labels: bug

#11518 Rework GestureRecognizer handling
  src/Avalonia.Base/Input/GestureRecognizers/GestureRecognizer.cs
  src/Avalonia.Base/Input/GestureRecognizers/GestureRecognizerCollection.cs
  src/Avalonia.Base/Input/GestureRecognizers/IGestureRecognizer.cs
  src/Avalonia.Base/Input/GestureRecognizers/PinchGestureRecognizer.cs
  src/Avalonia.Base/Input/GestureRecognizers/PullGestureRecognizer.cs
  src/Avalonia.Base/Input/GestureRecognizers/ScrollGestureRecognizer.cs
  src/Avalonia.Base/Input/IPointer.cs
  src/Avalonia.Base/Input/InputElement.cs
  src/Avalonia.Base/Input/MouseDevice.cs
  src/Avalonia.Base/Input/PenDevice.cs
  src/Avalonia.Base/Input/Pointer.cs
  src/Avalonia.Base/Input/PointerEventArgs.cs
  src/Avalonia.Base/Input/TouchDevice.cs
  src/Avalonia.Controls/Primitives/Thumb.cs
  src/Avalonia.Controls/PullToRefresh/RefreshVisualizer.cs
  tests/Avalonia.Controls.UnitTests/Platform/DefaultMenuInteractionHandlerTests.cs
  tests/Avalonia.UnitTests/TouchTestHelper.cs
Labels: breaking-change
