Repository AvaloniaUI/Avalonia, pull requests merged in 2023-01, with the labels that each got.

#9658 Feature/transparent web canvas
  samples/ControlCatalog.Android/MainActivity.cs
  samples/ControlCatalog.Android/Resources/values/styles.xml
  samples/ControlCatalog.Android/SplashActivity.cs
  samples/ControlCatalog.Browser/Properties/launchSettings.json
  samples/ControlCatalog/MainView.xaml
  samples/ControlCatalog/MainView.xaml.cs
  samples/ControlCatalog/MainWindow.xaml
  samples/ControlCatalog/Pages/WindowCustomizationsPage.xaml
  samples/ControlCatalog/ViewModels/MainWindowViewModel.cs
  src/Android/Avalonia.Android/AvaloniaView.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/InvalidationAwareSurfaceView.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
  src/Browser/Avalonia.Browser.Blazor/Avalonia.Browser.Blazor.csproj
  src/Browser/Avalonia.Browser.Blazor/AvaloniaView.cs
  src/Browser/Avalonia.Browser.Blazor/BlazorSingleViewLifetime.cs
  src/Browser/Avalonia.Browser/AvaloniaView.cs
  src/Browser/Avalonia.Browser/BrowserSingleViewLifetime.cs
  src/Browser/Avalonia.Browser/BrowserTopLevelImpl.cs
  src/Browser/Avalonia.Browser/Interop/CanvasHelper.cs
  src/Browser/Avalonia.Browser/Skia/BrowserSkiaGpuRenderTarget.cs
  src/Browser/Avalonia.Browser/Storage/BlobReadableStream.cs
  src/Browser/Avalonia.Browser/Storage/BrowserStorageProvider.cs
  src/Browser/Avalonia.Browser/Storage/WriteableStream.cs
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/dom.ts
Labels: os-browser, os-android

#9892 [Text] [Rename] ShapeableTextCharacters to UnshapedTextRun and ShapedTextCharacters to ShapedTextRun
  src/Avalonia.Base/Media/TextFormatting/InterWordJustification.cs
  src/Avalonia.Base/Media/TextFormatting/ShapedTextRun.cs
  src/Avalonia.Base/Media/TextFormatting/TextCharacters.cs
  src/Avalonia.Base/Media/TextFormatting/TextEllipsisHelper.cs
  src/Avalonia.Base/Media/TextFormatting/TextFormatterImpl.cs
  src/Avalonia.Base/Media/TextFormatting/TextLeadingPrefixCharacterEllipsis.cs
  src/Avalonia.Base/Media/TextFormatting/TextLineImpl.cs
  src/Avalonia.Base/Media/TextFormatting/UnshapedTextRun.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextFormatterTests.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextLayoutTests.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextLineTests.cs
Labels: area-textprocessing

#9947 [stable] macOS: Set Window appearance to fix missing white border
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
Labels: os-macos

#9913 Accent color and dark mode platform settings
  native/Avalonia.Native/src/OSX/Avalonia.Native.OSX.xcodeproj/project.pbxproj
  native/Avalonia.Native/src/OSX/PlatformSettings.mm
  native/Avalonia.Native/src/OSX/WindowBaseImpl.h
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
  native/Avalonia.Native/src/OSX/common.h
  native/Avalonia.Native/src/OSX/main.mm
  samples/ControlCatalog/MainView.xaml.cs
  src/Android/Avalonia.Android/AndroidPlatform.cs
  src/Android/Avalonia.Android/AvaloniaView.cs
  src/Android/Avalonia.Android/Platform/AndroidPlatformSettings.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
  src/Avalonia.Base/Platform/DefaultPlatformSettings.cs
  src/Avalonia.Base/Platform/IPlatformSettings.cs
  src/Avalonia.Base/Platform/PlatformColorValues.cs
  src/Avalonia.Controls/Embedding/Offscreen/OffscreenTopLevelImpl.cs
  src/Avalonia.Controls/Platform/ITopLevelImpl.cs
  src/Avalonia.DesignerSupport/Remote/Stubs.cs
  src/Avalonia.FreeDesktop/DBusPlatformSettings.cs
  src/Avalonia.FreeDesktop/DBusSettings.cs
  src/Avalonia.Headless/HeadlessWindowImpl.cs
  src/Avalonia.Native/AvaloniaNativePlatform.cs
  src/Avalonia.Native/NativePlatformSettings.cs
  src/Avalonia.Native/WindowImplBase.cs
  src/Avalonia.Native/avn.idl
  src/Avalonia.X11/X11Platform.cs
  src/Avalonia.X11/X11Window.cs
  src/Browser/Avalonia.Browser/BrowserPlatformSettings.cs
  src/Browser/Avalonia.Browser/BrowserTopLevelImpl.cs
  src/Browser/Avalonia.Browser/Interop/DomHelper.cs
  src/Browser/Avalonia.Browser/WindowingPlatform.cs
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/dom.ts
  src/Linux/Avalonia.LinuxFramebuffer/FramebufferToplevelImpl.cs
  src/Windows/Avalonia.Win32.Interop/Wpf/WpfTopLevelImpl.cs
  src/Windows/Avalonia.Win32/Win32Platform.cs
  src/Windows/Avalonia.Win32/Win32PlatformSettings.cs
  src/Windows/Avalonia.Win32/WinRT/NativeWinRTMethods.cs
  src/Windows/Avalonia.Win32/WinRT/WinRTColor.cs
  src/Windows/Avalonia.Win32/WinRT/winrt.idl
  src/Windows/Avalonia.Win32/WindowImpl.cs
  src/iOS/Avalonia.iOS/AvaloniaView.cs
  src/iOS/Avalonia.iOS/Platform.cs
  src/iOS/Avalonia.iOS/PlatformSettings.cs
  tests/Avalonia.Base.UnitTests/Rendering/CompositorTestsBase.cs
  tests/Avalonia.DesignerSupport.Tests/Remote/HtmlTransport/webapp/package-lock.json
Labels: api, os-macos, os-linux, os-windows, os-browser, os-ios, os-android

#9716 macos: Fix child window key handling
  native/Avalonia.Native/src/OSX/AvnWindow.mm
  native/Avalonia.Native/src/OSX/WindowBaseImpl.h
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
  native/Avalonia.Native/src/OSX/WindowImpl.h
  native/Avalonia.Native/src/OSX/WindowImpl.mm
Labels: bug, os-macos, backport-candidate

#10071 Add IsScrollInertiaEnabled attached property to scrollviewer
  samples/ControlCatalog/Pages/ScrollViewerPage.xaml
  samples/ControlCatalog/Pages/ScrollViewerPage.xaml.cs
  src/Avalonia.Base/Input/GestureRecognizers/ScrollGestureRecognizer.cs
  src/Avalonia.Controls/ScrollViewer.cs
  src/Avalonia.Themes.Fluent/Controls/ScrollViewer.xaml
Labels: api

#9960 IStorageProvider API updates
  samples/ControlCatalog/Pages/DialogsPage.xaml
  samples/ControlCatalog/Pages/DialogsPage.xaml.cs
  src/Android/Avalonia.Android/AvaloniaMainActivity.cs
  src/Android/Avalonia.Android/IActivityResultHandler.cs
  src/Android/Avalonia.Android/Platform/PlatformSupport.cs
  src/Android/Avalonia.Android/Platform/Storage/AndroidStorageItem.cs
  src/Android/Avalonia.Android/Platform/Storage/AndroidStorageProvider.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFile.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFolder.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageProvider.cs
  src/Avalonia.Base/Platform/Storage/FileIO/StorageProviderHelpers.cs
  src/Avalonia.Base/Platform/Storage/IStorageItem.cs
  src/Avalonia.Base/Platform/Storage/IStorageProvider.cs
  src/Avalonia.Base/Platform/Storage/NameCollisionOption.cs
  src/Avalonia.Base/Platform/Storage/StorageProviderExtensions.cs
  src/Avalonia.Base/Platform/Storage/WellKnownFolder.cs
  src/Avalonia.Controls/Platform/Dialogs/SystemDialogImpl.cs
  src/Avalonia.Diagnostics/Diagnostics/Screenshots/BaseRenderToStreamHandler.cs
  src/Avalonia.Diagnostics/Diagnostics/Screenshots/FilePickerHandler.cs
  src/Avalonia.Dialogs/Avalonia.Dialogs.csproj
  src/Avalonia.Dialogs/Internal/ManagedFileChooserViewModel.cs
  src/Avalonia.Dialogs/ManagedFileDialogExtensions.cs
  src/Avalonia.Dialogs/ManagedStorageProvider.cs
  src/Avalonia.FreeDesktop/DBusSystemDialog.cs
  src/Avalonia.Native/SystemDialogs.cs
  src/Avalonia.X11/NativeDialogs/CompositeStorageProvider.cs
  src/Avalonia.X11/NativeDialogs/GtkNativeFileDialogs.cs
  src/Browser/Avalonia.Browser/Interop/StorageHelper.cs
  src/Browser/Avalonia.Browser/Storage/BrowserStorageProvider.cs
  src/Browser/Avalonia.Browser/webapp/modules/storage/storageItem.ts
  src/Browser/Avalonia.Browser/webapp/modules/storage/storageProvider.ts
  src/Windows/Avalonia.Win32/Win32StorageProvider.cs
  src/iOS/Avalonia.iOS/Storage/IOSStorageItem.cs
  src/iOS/Avalonia.iOS/Storage/IOSStorageProvider.cs
  tests/Avalonia.Base.UnitTests/Utilities/UriExtensionsTests.cs
Labels: api, os-macos, os-linux, os-windows, os-browser, os-ios, os-android

#10121 Implement support for InheritDataTypeFromItemsAttribute
  samples/ControlCatalog/Pages/DataGridPage.xaml
  samples/ControlCatalog/Pages/DataGridPage.xaml.cs
  src/Avalonia.Base/Metadata/InheritDataTypeFromItemsAttribute.cs
  src/Avalonia.Controls.DataGrid/DataGridBoundColumn.cs
  src/Avalonia.Controls.DataGrid/DataGridTemplateColumn.cs
  src/Avalonia.Controls/ItemsControl.cs
  src/Avalonia.Controls/Repeater/ItemsRepeater.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlDataContextTypeTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/XamlIlBindingPathHelper.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/CompiledBindingExtensionTests.cs
Labels: api, area-xaml

#10127 Fix NET6_0_OR_GREATER msbuild check
  build/Base.props
  build/System.Memory.props
Labels: bug

#10137 Switch TreeViewItem.IsExpanded to a StyledProperty
  src/Avalonia.Controls/TreeViewItem.cs
Labels: breaking-change

#10113 Check for duplicate property setters in styles and control themes
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlCompiler.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlControlThemeTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlDuplicateSettersChecker.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlSelectorTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/XamlIlTests.cs
Labels: area-xaml
