Repository AvaloniaUI/Avalonia, pull requests merged in 2024-12, with the labels that each got.

#17676 #17675 - AfterPlatformServicesSetup callbacks are not called by the A…
  src/Avalonia.Controls/AppBuilder.cs
Labels: bug, backport-candidate-11.1.x, backport-candidate-11.2.x

#17657 Implement Matrix.CreateRotation with center point.
  src/Avalonia.Base/Matrix.cs
  tests/Avalonia.Base.UnitTests/MatrixTests.cs
Labels: feature

#17618 Fix broken pre-edit markedText on iOS and solve #17523
  src/iOS/Avalonia.iOS/CombinedSpan3.cs
  src/iOS/Avalonia.iOS/TextInputResponder.cs
Labels: bug, os-ios, backport-candidate-11.2.x

#17659 Make MarkupExtension.ProvideValue method inlinable for StaticResourceExtension and ResolveByNameExtension
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/ResolveByNameExtension.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/StaticResourceExtension.cs
Labels: enhancement, area-perf, backport-candidate-11.2.x

#17658 BoolConverters.Not should support ConvertBack
  src/Avalonia.Base/Data/Converters/BoolConverters.cs
  tests/Avalonia.Base.UnitTests/Data/BoolConvertersTests.cs
  tests/Avalonia.Base.UnitTests/Data/StringConvertersTests.cs
Labels: enhancement

#17664 DropShadowDirectionEffect: add AffectsRender for ShadowDepthProperty and DirectionProperty
  src/Avalonia.Base/Media/Effects/DropShadowEffect.cs
Labels: bug

#17682 Filepath with space not recognized correctly by xdg-open
  src/Avalonia.Base/Platform/Storage/FileIO/BclLauncher.cs
Labels: bug, os-linux

#17645 Expanding StringTokenizator with ReadOnlySpan.
  src/Avalonia.Base/Media/Fonts/FontCollectionBase.cs
  src/Avalonia.Base/Media/TextDecorationCollection.cs
  src/Avalonia.Base/RelativeRect.cs
  src/Avalonia.Base/Utilities/SpanHelpers.cs
  src/Avalonia.Base/Utilities/StringTokenizer.cs
  tests/Avalonia.Base.UnitTests/Utilities/StringTokenizerTests.cs
Labels: enhancement, area-perf

#17709 Add missing nullcheck in AvnView::mouseEvent
  native/Avalonia.Native/src/OSX/AvnView.mm
Labels: bug, os-macos

#16919 Update Unicode data and algorithms to v. 16.0
  src/Avalonia.Base/Media/TextFormatting/Unicode/BiDi.trie.cs
  src/Avalonia.Base/Media/TextFormatting/Unicode/BiDiData.cs
  src/Avalonia.Base/Media/TextFormatting/Unicode/Codepoint.cs
  src/Avalonia.Base/Media/TextFormatting/Unicode/EastAsianWidth.trie.cs
  src/Avalonia.Base/Media/TextFormatting/Unicode/EastAsianWidthClass.cs
  src/Avalonia.Base/Media/TextFormatting/Unicode/LineBreakClass.cs
  src/Avalonia.Base/Media/TextFormatting/Unicode/LineBreakEnumerator.cs
  src/Avalonia.Base/Media/TextFormatting/Unicode/PropertyValueAliasHelper.cs
  src/Avalonia.Base/Media/TextFormatting/Unicode/Script.cs
  src/Avalonia.Base/Media/TextFormatting/Unicode/UnicodeData.cs
  src/Avalonia.Base/Media/TextFormatting/Unicode/UnicodeData.trie.cs
  tests/Avalonia.Base.UnitTests/Media/TextFormatting/BiDiAlgorithmTests.cs
  tests/Avalonia.Base.UnitTests/Media/TextFormatting/BiDiClassTestDataGenerator.cs
  tests/Avalonia.Base.UnitTests/Media/TextFormatting/BiDiClassTests.cs
  tests/Avalonia.Base.UnitTests/Media/TextFormatting/BiDiTestDataGenerator.cs
  tests/Avalonia.Base.UnitTests/Media/TextFormatting/EastAsianWidthClassTrieGenerator.cs
  tests/Avalonia.Base.UnitTests/Media/TextFormatting/EastAsianWidthClassTrieGeneratorTests.cs
  tests/Avalonia.Base.UnitTests/Media/TextFormatting/GraphemeBreakClassTrieGeneratorTests.cs
  tests/Avalonia.Base.UnitTests/Media/TextFormatting/GraphemeBreakTestDataGenerator.cs
  tests/Avalonia.Base.UnitTests/Media/TextFormatting/LineBreakEnumeratorTests.cs
  tests/Avalonia.Base.UnitTests/Media/TextFormatting/UnicodeDataGenerator.cs
  tests/Avalonia.Base.UnitTests/Media/TextFormatting/UnicodeEnumsGenerator.cs
Labels: enhancement, area-textprocessing

#17727 Use Flat Array Text Blob Cache instead of more expensive ConcurrentDictionary in Avalonia.Skia.GlyphRunImpl
  src/Skia/Avalonia.Skia/GlyphRunImpl.cs
Labels: enhancement, area-perf

#17726 [Win] Fix cursor update on pointer enter
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: bug, os-windows, backport-candidate-11.2.x

#17721 Fix TextAlignment="DetectFromContent"
  src/Avalonia.Base/Media/TextFormatting/TextLayout.cs
  src/Avalonia.Base/Media/TextFormatting/TextLineImpl.cs
  src/Avalonia.Controls/TextBlock.cs
  tests/Avalonia.Controls.UnitTests/TextBlockTests.cs
Labels: backport-candidate-11.2.x

#17729 [Text] Make BreakUnit a readonly struct
  src/Avalonia.Base/Media/TextFormatting/Unicode/LineBreakEnumerator.cs
Labels: enhancement, area-perf

#17753 Fix macOS popup memory leak due to Close not being called
  native/Avalonia.Native/src/OSX/AvnWindow.mm
Labels: bug, os-macos, customer-priority, backport-candidate-11.2.x

#17695 Ignore key modifiers on text editing if field is a password field.
  src/Avalonia.Controls/TextBox.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
Labels: enhancement, backport-candidate-11.2.x

#17683 Made OneTime bindings update on DataContext changes
  src/Avalonia.Base/Data/Core/BindingExpression.cs
  tests/Avalonia.Base.UnitTests/Data/Core/BindingExpressionTests.GetValue.cs
  tests/Avalonia.Base.UnitTests/Data/Core/BindingExpressionTests.Mode.cs
  tests/Avalonia.Markup.UnitTests/Data/BindingTests.cs
Labels: bug, customer-priority, area-bindings, backport-candidate-11.2.x

#17705 Fix KnownFolder for x86 Windows
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageProvider.cs
Labels: bug, os-windows, backport-candidate-11.2.x

#17779 [GLX] Resize the platform render target to compositor-provided size
  src/Avalonia.Base/Platform/IRenderTarget.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionTarget.cs
  src/Avalonia.OpenGL/Surfaces/IGlPlatformSurfaceRenderTarget.cs
  src/Avalonia.X11/Glx/GlxDisplay.cs
  src/Avalonia.X11/Glx/GlxGlPlatformSurface.cs
  src/Avalonia.X11/X11Window.cs
  src/Skia/Avalonia.Skia/FramebufferRenderTarget.cs
  src/Skia/Avalonia.Skia/Gpu/ISkiaGpuRenderTarget.cs
  src/Skia/Avalonia.Skia/Gpu/OpenGl/GlRenderTarget.cs
  src/Skia/Avalonia.Skia/Gpu/SkiaGpuRenderTarget.cs
Labels: enhancement, area-rendering, customer-priority, backport-candidate-11.2.x

#17446 XEmbed client support
  Avalonia.Desktop.slnf
  Avalonia.sln
  samples/XEmbedSample/HarfbuzzWorkaround.cs
  samples/XEmbedSample/Program.cs
  samples/XEmbedSample/SocketEx.cs
  samples/XEmbedSample/XEmbedSample.csproj
  src/Avalonia.X11/Dispatching/GLibDispatcherImpl.cs
  src/Avalonia.X11/Dispatching/IX11PlatformDispatcher.cs
  src/Avalonia.X11/Dispatching/X11PlatformThreading.cs
  src/Avalonia.X11/X11Window.cs
  src/Avalonia.X11/X11WindowModes/DefaultWindowMode.cs
  src/Avalonia.X11/X11WindowModes/InputProxyWindowMode.cs
  src/Avalonia.X11/X11WindowModes/WindowMode.cs
  src/Avalonia.X11/X11WindowModes/XEmbedClientWindowMode.cs
  src/Avalonia.X11/XEmbedPlug.cs
Labels: feature, os-linux, area-x11

#17782 Auto free finished vulkan command buffers in gpu interop feature implementation
  src/Avalonia.Vulkan/Interop/VulkanCommandBufferPool.cs
  src/Avalonia.Vulkan/VulkanExternalObjectsFeature.cs
Labels: bug, backport-candidate-11.2.x

#17783 [MacOS] fix small memory leak when TopLevel closes.
  src/Avalonia.Native/WindowImplBase.cs
Labels: bug, os-macos, backport-candidate-11.2.x

#17774 Align bitmap memory to 4 bytes
  src/Avalonia.Base/Media/Imaging/BitmapMemory.cs
  tests/Avalonia.RenderTests/Media/BitmapMemoryTests.cs
  tests/Avalonia.Skia.RenderTests/Avalonia.Skia.RenderTests.csproj
Labels: enhancement

#17794 [macOS] Prevent popups from stealing focus
  native/Avalonia.Native/src/OSX/PopupImpl.mm
Labels: bug, os-macos, customer-priority, backport-candidate-11.2.x

#17812 Add NonPumpingLockHelper.Use to the SyncCommit
  src/Avalonia.Base/Media/MediaContext.Compositor.cs
Labels: bug, os-windows, area-trimming-aot, backport-candidate-11.2.x

#17813 Fix double build of Avalonia.Build.Tasks
  packages/Avalonia/Avalonia.csproj
  src/Avalonia.Base/Avalonia.Base.csproj
  src/Avalonia.MicroCom/Avalonia.MicroCom.csproj
Labels: bug, area-infrastructure

#17816 Clamp progress bar indicator width and height to never drop below zero when calculating size.
  src/Avalonia.Controls/ProgressBar.cs
Labels: bug, backport-candidate-11.2.x
