Repository AvaloniaUI/Avalonia, pull requests merged in 2024-04, with the labels that each got.

#15185 fix SplitView
  src/Avalonia.Themes.Fluent/Controls/SplitView.xaml
  src/Avalonia.Themes.Simple/Controls/SplitView.xaml
Labels: backport-candidate-11.1.x

#15103 Fix for browser pointer capture not released when pointer up outside of browser
  src/Browser/Avalonia.Browser/BrowserMouseDevice.cs
  src/Browser/Avalonia.Browser/BrowserTopLevelImpl.cs
  src/Browser/Avalonia.Browser/Interop/InputHelper.cs
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/input.ts
Labels: os-browser, backport-candidate-11.1.x

#15030 Add Points collection observability support for Polygon and Polyline
  src/Avalonia.Base/Media/PolylineGeometry.cs
  src/Avalonia.Controls/Shapes/Path.cs
  src/Avalonia.Controls/Shapes/Polygon.cs
  src/Avalonia.Controls/Shapes/Polyline.cs
  src/Avalonia.Controls/Shapes/Shape.cs
  tests/Avalonia.Controls.UnitTests/Shapes/PolygonTests.cs
  tests/Avalonia.Controls.UnitTests/Shapes/PolylineTests.cs
  tests/Avalonia.LeakTests/ControlTests.cs
Labels: backport-candidate-11.1.x

#15190 Fix broken tizen/ios initialization
  samples/MobileSandbox/MobileSandbox.csproj
  samples/SafeAreaDemo.iOS/Info.plist
  samples/SafeAreaDemo.iOS/SafeAreaDemo.iOS.csproj
  src/Tizen/Avalonia.Tizen/NuiTizenApplication.cs
  src/iOS/Avalonia.iOS/AvaloniaAppDelegate.cs
Labels: os-ios, os-tizen, backport-candidate-11.1.x

#15203 Update single project capabilities
  packages/Avalonia/AvaloniaSingleProject.targets
  samples/MobileSandbox/MobileSandbox.csproj
Labels: infrastructure

#15224 Propagate Dispose for ICustomDrawOperation through RenderDataCustomNode.
  src/Avalonia.Base/Rendering/Composition/Drawing/Nodes/RenderDataNodes.cs
Labels: backport-candidate-11.0.x, backport-candidate-11.1.x

#15217 X11 - Apply current_filter extension from dbus save picker
  samples/ControlCatalog/Pages/DialogsPage.xaml.cs
  src/Avalonia.FreeDesktop/DBusSystemDialog.cs
Labels: backport-candidate-11.1.x

#15238 Added WindowManagerAddShadowHint to PopupRoot.
  src/Avalonia.Controls/Primitives/Popup.cs
  src/Avalonia.Controls/Primitives/PopupRoot.cs
  src/Avalonia.Controls/ToolTip.cs
Labels: priority, backport-candidate-11.1.x

#14979 feat: PixelSize TryParse
  src/Avalonia.Base/PixelSize.cs
  tests/Avalonia.Base.UnitTests/PixelSizeTests.cs
Labels: api

#15242 feat (File Picker) add WebP to FilePickerFileTypes
  src/Avalonia.Base/Platform/Storage/FilePickerFileTypes.cs
Labels: backport-candidate-11.1.x

#15277 Clamp reported dirty rect before attempting to merge it
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionTarget.DirtyRects.cs
Labels: backport-candidate-11.1.x

#15278 Mark unstable math utilities
  src/Avalonia.Base/Utilities/MathUtilities.cs
Labels: backport-candidate-11.1.x

#15134 Fix NumericUpDown DataValidationErrors
  src/Avalonia.Themes.Fluent/Controls/NumericUpDown.xaml
  src/Avalonia.Themes.Simple/Controls/NumericUpDown.xaml
Labels: backport-candidate-11.1.x

#15297 fix: Fix the TouchDevice lost the touch Pressure
  src/Avalonia.Base/Input/PointerPoint.cs
  src/Avalonia.Base/Input/TouchDevice.cs
Labels: bug, backport-candidate-11.1.x

#15302 Try to combine AvaloniaResources with the same system path
  src/Avalonia.Base/Utilities/AvaloniaResourcesIndex.cs
  src/Avalonia.Build.Tasks/GenerateAvaloniaResourcesTask.cs
  src/Avalonia.Build.Tasks/XamlCompilerTaskExecutor.Helpers.cs
  tests/Avalonia.Base.UnitTests/Utilities/AvaloniaResourcesIndexTests.cs
Labels: area-xaml

#15259 Added tooltip chaining and `ToolTip.BetweenShowDelay`
  src/Avalonia.Controls/ToolTip.cs
  src/Avalonia.Controls/ToolTipService.cs
  tests/Avalonia.Controls.UnitTests/ToolTipTests.cs
Labels: api, backport-candidate-11.1.x

#15318 Fix __AvaloniaDefaultWindowIcon appreating in IDE
  packages/Avalonia/AvaloniaBuildTasks.targets
Labels: backport-candidate-11.1.x

#15331 Enable nullable on Avalonia.Android project
  src/Android/Avalonia.Android/AndroidInputMethod.cs
  src/Android/Avalonia.Android/AndroidPlatform.cs
  src/Android/Avalonia.Android/AndroidRuntimePlatform.cs
  src/Android/Avalonia.Android/AndroidThreadingInterface.cs
  src/Android/Avalonia.Android/AndroidViewControlHandle.cs
  src/Android/Avalonia.Android/Avalonia.Android.csproj
  src/Android/Avalonia.Android/AvaloniaActivity.cs
  src/Android/Avalonia.Android/AvaloniaMainActivity.App.cs
  src/Android/Avalonia.Android/AvaloniaMainActivity.cs
  src/Android/Avalonia.Android/AvaloniaView.cs
  src/Android/Avalonia.Android/ChoreographerTimer.cs
  src/Android/Avalonia.Android/IActivityResultHandler.cs
  src/Android/Avalonia.Android/IAndroidNavigationService.cs
  src/Android/Avalonia.Android/IAvaloniaActivity.cs
  src/Android/Avalonia.Android/Platform/AndroidActivatableLifetime.cs
  src/Android/Avalonia.Android/Platform/AndroidInsetsManager.cs
  src/Android/Avalonia.Android/Platform/AndroidNativeControlHostImpl.cs
  src/Android/Avalonia.Android/Platform/AndroidPlatformSettings.cs
  src/Android/Avalonia.Android/Platform/AndroidSystemNavigationManager.cs
  src/Android/Avalonia.Android/Platform/ClipboardImpl.cs
  src/Android/Avalonia.Android/Platform/PlatformSupport.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/FramebufferManager.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/InvalidationAwareSurfaceView.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
  src/Android/Avalonia.Android/Platform/Specific/Helpers/AndroidKeyInterop.cs
  src/Android/Avalonia.Android/Platform/Specific/Helpers/AndroidKeyboardEventsHelper.cs
  src/Android/Avalonia.Android/Platform/Specific/Helpers/AndroidMotionEventsHelper.cs
  src/Android/Avalonia.Android/Platform/Storage/AndroidStorageItem.cs
  src/Android/Avalonia.Android/Platform/Storage/AndroidStorageProvider.cs
  src/Android/Avalonia.Android/SingleViewLifetime.cs
  src/Android/Avalonia.Android/Stubs.cs
  src/Headless/Avalonia.Headless/HeadlessWindowImpl.cs
  tests/Avalonia.UnitTests/TestRoot.cs
Labels: infrastructure, os-android, backport-candidate-11.1.x

#15219 Improve debug display of controls and related error messages
  src/Avalonia.Base/Animation/AnimatorKeyFrame.cs
  src/Avalonia.Base/Animation/Animators/TransformOperationsAnimator.cs
  src/Avalonia.Base/Animation/KeyFrame.cs
  src/Avalonia.Base/Animation/TransitionBase.cs
  src/Avalonia.Base/Animation/Transitions.cs
  src/Avalonia.Base/AvaloniaObject.cs
  src/Avalonia.Base/Collections/AvaloniaList.cs
  src/Avalonia.Base/Collections/IAvaloniaListItemValidator.cs
  src/Avalonia.Base/Diagnostics/DebugDisplayHelper.cs
  src/Avalonia.Base/StyledElement.cs
  src/Avalonia.Base/Styling/Styles.cs
  src/Avalonia.Base/Threading/DispatcherOperation.cs
  src/Avalonia.Base/Visual.cs
  src/Avalonia.Controls/ContentControl.cs
  src/Avalonia.Controls/Controls.cs
  src/Avalonia.Controls/NativeMenu.cs
  src/Avalonia.Controls/NativeMenuItem.cs
  src/Avalonia.Controls/Presenters/ContentPresenter.cs
  src/Avalonia.Controls/Primitives/HeaderedContentControl.cs
  src/Avalonia.Controls/Templates/DataTemplates.cs
  src/Avalonia.Controls/TextBlock.cs
Labels: enhancement, backport-candidate-11.1.x

#15348 Fix render mode fallback for Metal
  src/Avalonia.Native/AvaloniaNativePlatform.cs
Labels: os-macos, backport-candidate-11.1.x

#15317 File activation
  src/Android/Avalonia.Android/Avalonia.Android.csproj
  src/Android/Avalonia.Android/AvaloniaActivity.cs
  src/Android/Avalonia.Android/Platform/AndroidActivatableLifetime.cs
  src/Android/Avalonia.Android/Platform/Storage/AndroidStorageItem.cs
  src/Avalonia.Controls/ApplicationLifetimes/ActivatableLifetimeBase.cs
  src/Avalonia.Controls/ApplicationLifetimes/ActivatedEventArgs.cs
  src/Avalonia.Controls/ApplicationLifetimes/ActivationKind.cs
  src/Avalonia.Controls/ApplicationLifetimes/FileActivatedEventArgs.cs
  src/Avalonia.Controls/ApplicationLifetimes/ProtocolActivatedEventArgs.cs
  src/Avalonia.Controls/Platform/IApplicationPlatformEvents.cs
  src/Avalonia.Native/AvaloniaNativeApplicationPlatform.cs
  src/Avalonia.Native/MacOSActivatableLifetime.cs
  src/iOS/Avalonia.iOS/ActivatableLifetime.cs
  src/iOS/Avalonia.iOS/AvaloniaAppDelegate.cs
  src/iOS/Avalonia.iOS/Storage/IOSStorageItem.cs
  src/iOS/Avalonia.iOS/Storage/IOSStorageProvider.cs
Labels: api, os-macos, os-ios, os-android, backport-candidate-11.1.x

#15153 Add locks in GeometryImpl for safe multithreaded access
  src/Skia/Avalonia.Skia/GeometryImpl.cs
Labels: backport-candidate-11.1.x

#15423 Fix ReactiveUI regression, when DataContext type is different
  src/Avalonia.ReactiveUI/ReactiveUserControl.cs
  src/Avalonia.ReactiveUI/ReactiveWindow.cs
  tests/Avalonia.ReactiveUI.UnitTests/ReactiveUserControlTest.cs
Labels: bug

#15406 upgrade `Quamotion.RemoteViewing` to 1.1.211 to work with `RealVNC Viewer`, Add `password` parameter to `StartWithHeadlessVncPlatform`
  src/Avalonia.Base/Logging/LogArea.cs
  src/Headless/Avalonia.Headless.Vnc/Avalonia.Headless.Vnc.csproj
  src/Headless/Avalonia.Headless.Vnc/AvaloniaVncLogger.cs
  src/Headless/Avalonia.Headless.Vnc/HeadlessVncFramebufferSource.cs
  src/Headless/Avalonia.Headless.Vnc/HeadlessVncPlatformExtensions.cs
Labels: backport-candidate-11.0.x

#15424 Make MenuItem check mark visible with Simple theme
  src/Avalonia.Themes.Simple/Controls/MenuItem.xaml
Labels: backport-candidate-11.0.x

#15438 Fix app shutdown cancellation via window
  src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs
  tests/Avalonia.Controls.UnitTests/DesktopStyleApplicationLifetimeTests.cs
Labels: bug, backport-candidate-11.0.x, backport-candidate-11.1.x

#15137 Fix input starvation issues on resource-constrained devices.
  src/Avalonia.Base/Media/MediaContext.Compositor.cs
  src/Avalonia.Base/Media/MediaContext.cs
  src/Avalonia.Base/Threading/DispatcherOptions.cs
Labels: backport-candidate-11.1.x

#15106 Add AvsEnableDevWarningsNotAsErrors prop
  .editorconfig
  Avalonia.sln
  Directory.Build.props
  Settings.StyleCop
  build/WarnAsErrors.props
Labels: infrastructure, backport-candidate-11.0.x, backport-candidate-11.1.x

#15255 SkiaSharp updates, SkiaSharp 3.0 render tests enabled
  build/HarfBuzzSharp.props
  build/SkiaSharp.props
  src/Avalonia.Base/Avalonia.Base.csproj
  src/Avalonia.Controls/Avalonia.Controls.csproj
  src/Skia/Avalonia.Skia/Avalonia.Skia.csproj
  src/Skia/Avalonia.Skia/Compatibility/SkiaCompat.SKCanvas.cs
  src/Skia/Avalonia.Skia/Compatibility/SkiaCompat.SKImageFilter.cs
  src/Skia/Avalonia.Skia/Compatibility/SkiaCompat.SKPath.cs
  src/Skia/Avalonia.Skia/Compatibility/SkiaCompat.cs
  src/Skia/Avalonia.Skia/DrawingContextImpl.Effects.cs
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
  src/Skia/Avalonia.Skia/GlyphRunImpl.cs
  src/Skia/Avalonia.Skia/SurfaceRenderTarget.cs
  src/Skia/Avalonia.Skia/TransformedGeometryImpl.cs
  tests/Avalonia.RenderTests/TestBase.cs
  tests/Avalonia.Skia.RenderTests/Avalonia.Skia.RenderTests.csproj
Labels: area-skia, backport-candidate-11.1.x

#14909 feat: Add API for fetching window Z-order
  native/Avalonia.Native/src/OSX/WindowImpl.h
  native/Avalonia.Native/src/OSX/WindowImpl.mm
  src/Avalonia.Controls/Platform/IWindowImpl.cs
  src/Avalonia.Controls/Window.cs
  src/Avalonia.DesignerSupport/Remote/PreviewerWindowImpl.cs
  src/Avalonia.DesignerSupport/Remote/Stubs.cs
  src/Avalonia.Native/WindowImpl.cs
  src/Avalonia.Native/avn.idl
  src/Avalonia.X11/X11Window.cs
  src/Headless/Avalonia.Headless/HeadlessWindowImpl.cs
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: api, backport-candidate-11.1.x

#15420 ComboBox: support different DataTemplate for selected item.
  samples/ControlCatalog/Pages/ComboBoxPage.xaml
  src/Avalonia.Controls/ComboBox.cs
  src/Avalonia.Themes.Fluent/Controls/ComboBox.xaml
  src/Avalonia.Themes.Simple/Controls/ComboBox.xaml
  tests/Avalonia.Controls.UnitTests/ComboBoxTests.cs
Labels: backport-candidate-11.1.x

#15449 Fix VirtualizingStackPanel ScrollIntoView
  src/Avalonia.Controls/VirtualizingStackPanel.cs
  tests/Avalonia.Controls.UnitTests/VirtualizingStackPanelTests.cs
Labels: backport-candidate-11.0.x, backport-candidate-11.1.x

#15342 Improve AvaloniaObject.GetValue performance
  src/Avalonia.Base/AvaloniaObject.cs
  src/Avalonia.Base/AvaloniaProperty.cs
  src/Avalonia.Base/AvaloniaPropertyMetadata.cs
  src/Avalonia.Base/Compatibility/ReferenceEqualityComparer.cs
  src/Avalonia.Base/Data/BindingOperations.cs
  src/Avalonia.Base/Data/Core/UntypedBindingExpressionBase.cs
  src/Avalonia.Base/Data/Optional.cs
  src/Avalonia.Base/DirectProperty.cs
  src/Avalonia.Base/DirectPropertyBase.cs
  src/Avalonia.Base/DirectPropertyMetadata`1.cs
  src/Avalonia.Base/IDirectPropertyAccessor.cs
  src/Avalonia.Base/IStyledPropertyAccessor.cs
  src/Avalonia.Base/PropertyStore/BindingEntryBase.cs
  src/Avalonia.Base/PropertyStore/DirectBindingObserver.cs
  src/Avalonia.Base/PropertyStore/DirectUntypedBindingObserver.cs
  src/Avalonia.Base/PropertyStore/EffectiveValue.cs
  src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs
  src/Avalonia.Base/PropertyStore/LocalValueBindingObserverBase.cs
  src/Avalonia.Base/PropertyStore/SourceUntypedBindingEntry.cs
  src/Avalonia.Base/PropertyStore/TypedBindingEntry.cs
  src/Avalonia.Base/PropertyStore/ValueStore.cs
  src/Avalonia.Base/StyledProperty.cs
  src/Avalonia.Base/StyledPropertyMetadata`1.cs
  src/Avalonia.Base/Utilities/AvaloniaPropertyDictionary.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindingExtension.cs
  src/Markup/Avalonia.Markup/Data/Binding.cs
  src/Markup/Avalonia.Markup/Data/BindingBase.cs
  src/Markup/Avalonia.Markup/Data/MultiBinding.cs
  src/Shared/StringCompatibilityExtensions.cs
  tests/Avalonia.Base.UnitTests/Utilities/AvaloniaPropertyDictionaryTests.cs
  tests/Avalonia.Benchmarks/ControlHierarchyCreator.cs
Labels: enhancement, perf

#15489 Fix DevTools FiredEvent failing on reused RoutedEventArgs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/FiredEvent.cs
Labels: area-dev-tools, backport-candidate-11.1.x

#15485 Fix binding related memory leaks
  src/Avalonia.Base/Data/Core/ExpressionNodes/AvaloniaPropertyAccessorNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/MethodCommandNode.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindings/PropertyInfoAccessorFactory.cs
  tests/Avalonia.LeakTests/AvaloniaObjectTests.cs
Labels: backport-candidate-11.1.x

#15498 Make `SelectionModel.SelectedItems` and `SelectedIndexes` implement INCC.
  src/Avalonia.Controls/Selection/ReadOnlySelectionListBase.cs
  src/Avalonia.Controls/Selection/SelectedIndexes.cs
  src/Avalonia.Controls/Selection/SelectedItems.cs
  src/Avalonia.Controls/Selection/SelectionModel.cs
  tests/Avalonia.Controls.UnitTests/Selection/SelectionModelTests_Single.cs
Labels: enhancement, priority, backport-candidate-11.1.x

#15013 feat(TabControl): Enable Recognizes AccessKey
  samples/ControlCatalog/Pages/TabControlPage.xaml
  src/Avalonia.Controls/TabItem.cs
  src/Avalonia.Themes.Fluent/Controls/TabItem.xaml
  src/Avalonia.Themes.Simple/Controls/TabItem.xaml
  tests/Avalonia.Controls.UnitTests/TabControlTests.cs
  tests/Avalonia.UnitTests/TestServices.cs
  tests/Avalonia.UnitTests/UnitTestApplication.cs
Labels: enhancement, backport-candidate-11.1.x

#15070 Reduce allocations while loading deferred resources
  src/Avalonia.Base/Controls/IDeferredContent.cs
  src/Avalonia.Base/Controls/ResourceDictionary.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlLanguage.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  src/Markup/Avalonia.Markup.Xaml/Avalonia.Markup.Xaml.csproj
  src/Markup/Avalonia.Markup.Xaml/EagerParentStackEnumerator.cs
  src/Markup/Avalonia.Markup.Xaml/Extensions.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/DynamicResourceExtension.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/StaticResourceExtension.cs
  src/Markup/Avalonia.Markup.Xaml/Templates/TemplateContent.cs
  src/Markup/Avalonia.Markup.Xaml/XamlIl/Runtime/IAvaloniaXamlIlParentStackProvider.cs
  src/Markup/Avalonia.Markup.Xaml/XamlIl/Runtime/XamlIlRuntimeHelpers.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/StyleIncludeTests.cs
Labels: area-xaml, backport-candidate-11.1.x

#15506 Fix `AssemblyDescriptorResolver` assembly matching
  src/Avalonia.Base/Platform/Internal/AssemblyDescriptorResolver.cs
Labels: bug, backport-candidate-11.0.x, backport-candidate-11.1.x

#15505 Fix NativeMenuBar tooltip
  samples/IntegrationTestApp/MainWindow.axaml.cs
  src/Avalonia.Controls/NativeMenuBarPresenter.cs
  tests/Avalonia.IntegrationTests.Appium/NativeMenuTests.cs
Labels: bug, backport-candidate-11.1.x

#15521 Fix Avalonia.Browser running on .NET 9
  src/Browser/Avalonia.Browser/BrowserInputHandler.cs
  src/Browser/Avalonia.Browser/Interop/CanvasHelper.cs
  src/Browser/Avalonia.Browser/Interop/InputHelper.cs
  src/Browser/Avalonia.Browser/Rendering/BrowserSurface.cs
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/input.ts
Labels: bug, os-browser, backport-candidate-11.1.x

#15520 Fixed use of stride in ImmutableBitmap ctor
  src/Skia/Avalonia.Skia/ImmutableBitmap.cs
Labels: backport-candidate-11.0.x, backport-candidate-11.1.x

#15516 Grid fixes
  src/Avalonia.Controls/Grid.cs
Labels: backport-candidate-11.1.x

#12737 Vulkan backend
  Avalonia.Desktop.slnf
  Avalonia.sln
  Avalonia.sln.DotSettings
  build/CoreLibraries.props
  samples/ControlCatalog.NetCore/Program.cs
  samples/GpuInterop/Program.cs
  samples/GpuInterop/VulkanDemo/VulkanContent.cs
  samples/GpuInterop/VulkanDemo/VulkanContext.cs
  samples/GpuInterop/VulkanDemo/VulkanImage.cs
  samples/GpuInterop/VulkanDemo/VulkanSemaphorePair.cs
  samples/GpuInterop/VulkanDemo/VulkanSwapchain.cs
  src/Avalonia.Base/Avalonia.Base.csproj
  src/Avalonia.Base/Platform/Interop/Utf8Buffer.cs
  src/Avalonia.Base/Platform/PlatformGraphicsExternalMemory.cs
  src/Avalonia.Vulkan/Avalonia.Vulkan.csproj
  src/Avalonia.Vulkan/IVulkanContextExternalObjectsFeature.cs
  src/Avalonia.Vulkan/IVulkanDevice.cs
  src/Avalonia.Vulkan/IVulkanPlatformSurface.cs
  src/Avalonia.Vulkan/IVulkanRenderTarget.cs
  src/Avalonia.Vulkan/Interop/VulkanCommandBuffer.cs
  src/Avalonia.Vulkan/Interop/VulkanCommandBufferPool.cs
  src/Avalonia.Vulkan/Interop/VulkanDebugLogger.cs
  src/Avalonia.Vulkan/Interop/VulkanDevice.Create.cs
  src/Avalonia.Vulkan/Interop/VulkanDevice.cs
  src/Avalonia.Vulkan/Interop/VulkanDisplay.cs
  src/Avalonia.Vulkan/Interop/VulkanFence.cs
  src/Avalonia.Vulkan/Interop/VulkanImage.cs
  src/Avalonia.Vulkan/Interop/VulkanInstance.cs
  src/Avalonia.Vulkan/Interop/VulkanKhrSurface.cs
  src/Avalonia.Vulkan/Interop/VulkanMemoryHelper.cs
  src/Avalonia.Vulkan/Interop/VulkanSemaphore.cs
  src/Avalonia.Vulkan/UnmanagedInterop/Utf8BufferArray.cs
  src/Avalonia.Vulkan/UnmanagedInterop/VulkanDeviceApi.cs
  src/Avalonia.Vulkan/UnmanagedInterop/VulkanEnums.cs
  src/Avalonia.Vulkan/UnmanagedInterop/VulkanGlobalApi.cs
  src/Avalonia.Vulkan/UnmanagedInterop/VulkanInstanceApi.cs
  src/Avalonia.Vulkan/UnmanagedInterop/VulkanStructs.cs
  src/Avalonia.Vulkan/VulkanBindings.cs
  src/Avalonia.Vulkan/VulkanContext.cs
  src/Avalonia.Vulkan/VulkanException.cs
  src/Avalonia.Vulkan/VulkanExternalObjectsFeature.cs
  src/Avalonia.Vulkan/VulkanImageInfo.cs
  src/Avalonia.Vulkan/VulkanKhrSurfaceRenderTarget.cs
  src/Avalonia.Vulkan/VulkanOptions.cs
  src/Avalonia.Vulkan/VulkanPlatformGraphics.cs
  src/Avalonia.X11/Vulkan/VulkanNativeInterop.cs
  src/Avalonia.X11/Vulkan/VulkanSupport.cs
  src/Avalonia.X11/X11Platform.cs
  src/Skia/Avalonia.Skia/Gpu/Vulkan/VulkanSkiaExternalObjectsFeature.cs
  src/Skia/Avalonia.Skia/Gpu/Vulkan/VulkanSkiaGpu.cs
  src/Skia/Avalonia.Skia/Gpu/Vulkan/VulkanSkiaRenderTarget.cs
  src/Skia/Avalonia.Skia/PlatformRenderInterface.cs
  src/Windows/Avalonia.Win32/Vulkan/VulkanNativeInterop.cs
  src/Windows/Avalonia.Win32/Vulkan/VulkanSupport.cs
  src/Windows/Avalonia.Win32/Win32GlManager.cs
  src/Windows/Avalonia.Win32/Win32PlatformOptions.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: area-rendering, os-linux

#15430 Add isStroked overload for IGeometryContext
  src/Avalonia.Base/Media/ArcSegment.cs
  src/Avalonia.Base/Media/BezierSegment .cs
  src/Avalonia.Base/Media/LineSegment.cs
  src/Avalonia.Base/Media/PathSegment.cs
  src/Avalonia.Base/Media/QuadraticBezierSegment .cs
  src/Avalonia.Base/Media/StreamGeometryContext.cs
  src/Avalonia.Base/Platform/IGeometryContext2.cs
  src/Skia/Avalonia.Skia/StreamGeometryImpl.cs
  tests/Avalonia.RenderTests.WpfCompare/CrossUI.Wpf.cs
  tests/Avalonia.RenderTests/CrossTests/CrossGeometryTests.cs
  tests/Avalonia.RenderTests/CrossUI/CrossUI.Avalonia.cs
  tests/Avalonia.RenderTests/CrossUI/CrossUI.cs
  tests/Avalonia.Skia.RenderTests/CrossTestBase.cs
  tests/TestFiles/CrossTests/Media/Geometry/Should_Properly_CloseFigure_Flat_Bevel.wpf.png
  tests/TestFiles/CrossTests/Media/Geometry/Should_Properly_CloseFigure_Flat_Miter.wpf.png
  tests/TestFiles/CrossTests/Media/Geometry/Should_Properly_CloseFigure_Flat_Round.wpf.png
  tests/TestFiles/CrossTests/Media/Geometry/Should_Properly_CloseFigure_Round_Bevel.wpf.png
  tests/TestFiles/CrossTests/Media/Geometry/Should_Properly_CloseFigure_Round_Miter.wpf.png
  tests/TestFiles/CrossTests/Media/Geometry/Should_Properly_CloseFigure_Round_Round.wpf.png
  tests/TestFiles/CrossTests/Media/Geometry/Should_Render_Geometry_With_Strokeless_Lines.wpf.png
  tests/TestFiles/CrossTests/Media/Geometry/Should_Render_Stream_Geometry.wpf.png
Labels: enhancement, api, backport-candidate-11.1.x

#15552 Win32 - Fix EntendClient hints not being applied window show
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: os-windows, backport-candidate-11.1.x

#15496 fix: ICommadSource Implemetation
  src/Avalonia.Controls/Button.cs
  src/Avalonia.Controls/MenuItem.cs
  src/Avalonia.Controls/SplitButton/SplitButton.cs
  tests/Avalonia.Base.UnitTests/Input/KeyboardNavigationTests_Tab.cs
  tests/Avalonia.Controls.UnitTests/ButtonTests.cs
  tests/Avalonia.Controls.UnitTests/MenuItemTests.cs
  tests/Avalonia.Controls.UnitTests/SplitButtonTests.cs
  tests/Avalonia.Controls.UnitTests/Utils/TestCommand.cs
Labels: bug, backport-candidate-11.1.x
