Repository AvaloniaUI/Avalonia, pull requests merged in 2024-02, with the labels that each got.

#14400 Fix IActivatableApplicationLifetime definition
  src/Avalonia.Controls/ApplicationLifetimes/IActivatableApplicationLifetime.cs
Labels: backport-candidate-11.0.x

#14406 EnableDataValidation for TimePicker
  src/Avalonia.Controls/DateTimePickers/TimePicker.cs
  tests/Avalonia.Controls.UnitTests/TimePickerTests.cs
Labels: backport-candidate-11.0.x

#14407 [Mac] Make sure emulated text input is generated after key down
  native/Avalonia.Native/src/OSX/AvnView.mm
Labels: os-macos, backport-candidate-11.0.x

#14424 Fix controls not showing up in accessibility when made visibile
  src/Avalonia.Controls/Automation/Peers/ControlAutomationPeer.cs
  tests/Avalonia.Controls.UnitTests/Automation/ControlAutomationPeerTests.cs
Labels: backport-candidate-11.0.x

#14430 EnableDataValidation for DatePicker
  src/Avalonia.Controls/DateTimePickers/DatePicker.cs
  tests/Avalonia.Controls.UnitTests/DatePickerTests.cs
Labels: backport-candidate-11.0.x

#14436 Fix Windows 7 'api-ms-win-core-winrt-string-l1-1-0.dll' error
  src/Windows/Avalonia.Win32/WinRT/WinRTApiInformation.cs
Labels: bug, os-windows, backport-candidate-11.0.x

#14441 Ignore frame extents if window has no decorations
  src/Avalonia.X11/X11Window.cs
Labels: backport-candidate-11.0.x

#13376 Improve NumericUpDown and AutoCompleteBox focusability
  src/Avalonia.Controls/AutoCompleteBox/AutoCompleteBox.cs
  src/Avalonia.Controls/NumericUpDown/NumericUpDown.cs
  src/Avalonia.Themes.Fluent/Controls/ButtonSpinner.xaml
  src/Avalonia.Themes.Fluent/Controls/NumericUpDown.xaml
  src/Avalonia.Themes.Simple/Controls/ButtonSpinner.xaml
  src/Avalonia.Themes.Simple/Controls/NumericUpDown.xaml
Labels: backport-candidate-11.0.x

#14494 fix macos crash at startup by not parsing all app arguments into uris.
  native/Avalonia.Native/src/OSX/app.mm
  src/Avalonia.Native/AvaloniaNativeApplicationPlatform.cs
  src/Avalonia.Native/avn.idl
Labels: backport-candidate-11.0.x

#14229 Prevent random dispatcher deadlocks
  src/Avalonia.Base/Threading/Dispatcher.Queue.cs
Labels: backport-candidate-11.0.x

#14419 Fix horizontal ScrollToView in VirtualizingStackPanel in some cases
  src/Avalonia.Controls/VirtualizingStackPanel.cs
  tests/Avalonia.Controls.UnitTests/VirtualizingStackPanelTests.cs
Labels: backport-candidate-11.0.x

#13947 XY focus
  samples/ControlCatalog.Android/ControlCatalog.Android.csproj
  samples/ControlCatalog.Android/MainActivity.cs
  samples/ControlCatalog/MainView.xaml
  samples/ControlCatalog/Pages/ComboBoxPage.xaml
  samples/ControlCatalog/Pages/FocusPage.xaml
  samples/ControlCatalog/Pages/FocusPage.xaml.cs
  src/Android/Avalonia.Android/Platform/Input/AndroidKeyboardDevice.cs
  src/Android/Avalonia.Android/Platform/Specific/Helpers/AndroidKeyboardEventsHelper.cs
  src/Avalonia.Base/Controls/IInternalScroller.cs
  src/Avalonia.Base/Input/FocusManager.cs
  src/Avalonia.Base/Input/IPointer.cs
  src/Avalonia.Base/Input/KeyDeviceType.cs
  src/Avalonia.Base/Input/KeyboardNavigationHandler.cs
  src/Avalonia.Base/Input/Navigation/FocusExtensions.cs
  src/Avalonia.Base/Input/Navigation/XYFocus.Bubbling.cs
  src/Avalonia.Base/Input/Navigation/XYFocus.FindElements.cs
  src/Avalonia.Base/Input/Navigation/XYFocus.Impl.cs
  src/Avalonia.Base/Input/Navigation/XYFocus.Properties.cs
  src/Avalonia.Base/Input/Navigation/XYFocusAlgorithms.cs
  src/Avalonia.Base/Input/Navigation/XYFocusHelpers.cs
  src/Avalonia.Base/Input/Navigation/XYFocusNavigationModes.cs
  src/Avalonia.Base/Input/Navigation/XYFocusNavigationStrategy.cs
  src/Avalonia.Base/Input/Navigation/XYFocusOptions.cs
  src/Avalonia.Base/Utilities/MathUtilities.cs
  src/Avalonia.Base/VisualTree/VisualExtensions.cs
  src/Avalonia.Controls/AutoCompleteBox/AutoCompleteBox.cs
  src/Avalonia.Controls/ButtonSpinner.cs
  src/Avalonia.Controls/CalendarDatePicker/CalendarDatePicker.cs
  src/Avalonia.Controls/ComboBox.cs
  src/Avalonia.Controls/GridSplitter.cs
  src/Avalonia.Controls/ScrollViewer.cs
  src/Avalonia.Controls/Slider.cs
  src/Avalonia.Controls/SplitButton/SplitButton.cs
  src/Avalonia.Controls/TextBox.cs
  src/Tizen/Avalonia.Tizen/Platform/Input/TizenKeyboardDevice.cs
  tests/Avalonia.Base.UnitTests/Input/KeyboardNavigationTests_XY.cs
  tests/Avalonia.Controls.UnitTests/ItemsControlTests.cs
  tests/Avalonia.Controls.UnitTests/MaskedTextBoxTests.cs
  tests/Avalonia.Controls.UnitTests/Primitives/SelectingItemsControlTests_Multiple.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
  tests/Avalonia.Controls.UnitTests/TreeViewTests.cs
  tests/Avalonia.UnitTests/TestServices.cs
  tests/Avalonia.UnitTests/UnitTestApplication.cs
Labels: area-focus

#14514 Fix CompiledBinding with RelativeSource/ElementName but no Path
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlBindingPathParser.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/CompiledBindingExtensionTests.cs
Labels: bug, backport-candidate-11.0.x

#14320 Implement TopLevel.Launcher
  samples/ControlCatalog/Pages/DialogsPage.xaml
  samples/ControlCatalog/Pages/DialogsPage.xaml.cs
  src/Android/Avalonia.Android/Platform/AndroidLauncher.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclLauncher.cs
  src/Avalonia.Base/Platform/Storage/ILauncher.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.Dialogs/AboutAvaloniaDialog.xaml.cs
  src/Avalonia.Native/WindowImplBase.cs
  src/Avalonia.X11/X11Window.cs
  src/Browser/Avalonia.Browser/Interop/NavigationHelper.cs
  src/Browser/Avalonia.Browser/Storage/BrowserLauncher.cs
  src/Tizen/Avalonia.Tizen/Platform/Permissions.cs
  src/Tizen/Avalonia.Tizen/Platform/TizenLauncher.cs
  src/Tizen/Avalonia.Tizen/TopLevelImpl.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
  src/iOS/Avalonia.iOS/AvaloniaView.cs
  src/iOS/Avalonia.iOS/IOSLauncher.cs
Labels: api, os-macos, os-linux, os-windows, os-ios, os-android, os-tizen

#14462 Fix DevTools popup freezing
  src/Avalonia.Diagnostics/Diagnostics/Views/MainWindow.xaml.cs
Labels: bug, area-dev-tools, backport-candidate-11.0.x

#14530 Avoid NRE from GetGlyphPath
  src/Skia/Avalonia.Skia/PlatformRenderInterface.cs
Labels: backport-candidate-11.0.x

#14533 fix(Browser): Handle mouse wheel coordinates.
  src/Browser/Avalonia.Browser/AvaloniaView.cs
Labels: os-browser, backport-candidate-11.0.x

#14173 Discard additional lines upon inserting when AcceptsReturn=false
  src/Avalonia.Controls/TextBox.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
Labels: backport-candidate-11.0.x

#14552 Fix previewer sometimes not finding deps file
  src/tools/Avalonia.Designer.HostApp/DesignXamlLoader.cs
Labels: backport-candidate-11.0.x

#14553 Fix not handling first window creation
  src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs
Labels: backport-candidate-11.0.x

#14538 Move `ScrollIntoView` into `ItemsControl`.
  src/Avalonia.Controls/ItemsControl.cs
  src/Avalonia.Controls/Primitives/SelectingItemsControl.cs
Labels: enhancement, backport-candidate-11.0.x, priority

#14566 Fix TextBlock MeasureOverride visual child handling
  src/Avalonia.Controls/TextBlock.cs
Labels: backport-candidate-11.0.x

#14465 DataGrid add property to specify Number Format of items count
  src/Avalonia.Controls.DataGrid/DataGridRowGroupHeader.cs
Labels: area-datagrid

#14225 Browser StaticWebAssets sdk support
  .gitignore
  samples/ControlCatalog.Browser.Blazor/ControlCatalog.Browser.Blazor.csproj
  samples/ControlCatalog.Browser/ControlCatalog.Browser.csproj
  samples/MobileSandbox.Browser/MobileSandbox.Browser.csproj
  samples/MobileSandbox.Browser/Roots.xml
  src/Browser/Avalonia.Browser.Blazor/Avalonia.Browser.Blazor.csproj
  src/Browser/Avalonia.Browser.Blazor/BlazorSingleViewLifetime.cs
  src/Browser/Avalonia.Browser/Avalonia.Browser.csproj
  src/Browser/Avalonia.Browser/Avalonia.Browser.props
  src/Browser/Avalonia.Browser/AvaloniaView.cs
  src/Browser/Avalonia.Browser/BrowserSingleViewLifetime.cs
  src/Browser/Avalonia.Browser/WebEmbeddableControlRoot.cs
  src/Browser/Avalonia.Browser/build/Avalonia.Browser.props
  src/Browser/Avalonia.Browser/build/Avalonia.Browser.targets
  src/Browser/Avalonia.Browser/build/Microsoft.AspNetCore.StaticWebAssets.props
  src/Browser/Avalonia.Browser/build/interop.js
  src/Browser/Avalonia.Browser/webapp/build.js
Labels: breaking-change, os-browser

#14509 Add HyperlinkButton
  samples/ControlCatalog/Pages/ButtonsPage.xaml
  src/Avalonia.Controls/HyperlinkButton.cs
  src/Avalonia.Themes.Fluent/Accents/FluentControlResources.xaml
  src/Avalonia.Themes.Fluent/Controls/FluentControls.xaml
  src/Avalonia.Themes.Fluent/Controls/HyperlinkButton.xaml
  src/Avalonia.Themes.Simple/Accents/Base.xaml
  src/Avalonia.Themes.Simple/Controls/HyperlinkButton.xaml
  src/Avalonia.Themes.Simple/Controls/SimpleControls.xaml
Labels: api

#11441 Introduce MenuItem.ToggleType
  samples/ControlCatalog/App.xaml
  samples/ControlCatalog/MainWindow.xaml
  samples/ControlCatalog/Pages/MenuPage.xaml
  samples/ControlCatalog/ViewModels/ApplicationViewModel.cs
  samples/ControlCatalog/ViewModels/MainWindowViewModel.cs
  src/Avalonia.Controls/Avalonia.Controls.csproj
  src/Avalonia.Controls/IMenuItem.cs
  src/Avalonia.Controls/MenuBase.cs
  src/Avalonia.Controls/MenuItem.cs
  src/Avalonia.Controls/MenuItemToggleType.cs
  src/Avalonia.Controls/NativeMenuBar.cs
  src/Avalonia.Controls/NativeMenuBarPresenter.cs
  src/Avalonia.Controls/NativeMenuItem.cs
  src/Avalonia.Controls/Platform/DefaultMenuInteractionHandler.cs
  src/Avalonia.Controls/RadioButton.cs
  src/Avalonia.Controls/RadioButtonGroupManager.cs
  src/Avalonia.Themes.Fluent/Controls/CheckBox.xaml
  src/Avalonia.Themes.Fluent/Controls/FluentControls.xaml
  src/Avalonia.Themes.Fluent/Controls/MenuItem.xaml
  src/Avalonia.Themes.Fluent/Controls/NativeMenuBar.xaml
  src/Avalonia.Themes.Fluent/IBitmapToImageConverter.cs
  src/Avalonia.Themes.Simple/Controls/MenuItem.xaml
  src/Avalonia.Themes.Simple/Controls/NativeMenuBar.xaml
  src/Avalonia.Themes.Simple/Controls/SimpleControls.xaml
  src/Avalonia.Themes.Simple/IBitmapToImageConverter.cs
  src/Windows/Avalonia.Win32/TrayIconImpl.cs
  src/Windows/Avalonia.Win32/Win32NativeToManagedMenuExporter.cs
  tests/Avalonia.Controls.UnitTests/MenuItemTests.cs
Labels: api

#14593 Make integration tests catch issues with Icon Loading
  samples/IntegrationTestApp/App.axaml
  samples/IntegrationTestApp/Assets/icon.ico
  samples/IntegrationTestApp/IntegrationTestApp.csproj
  samples/IntegrationTestApp/MainWindow.axaml
Labels: backport-candidate-11.0.x

#14467 feat(DevTools): Add to Events View visual feedback
  src/Avalonia.Diagnostics/Diagnostics/Controls/ControlHighlightAdorner.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/EventsPageViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/EventsPageView.xaml
  src/Avalonia.Diagnostics/Diagnostics/Views/EventsPageView.xaml.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/TreePageView.xaml.cs
Labels: area-dev-tools

#14627 Fix TextBlock wrong caret position
  src/Avalonia.Controls/TextBox.cs
Labels: backport-candidate-11.0.x

#14649 added _windowProperties override to Win32.EmbeddedWindowImpl
  src/Windows/Avalonia.Win32/EmbeddedWindowImpl.cs
Labels: os-windows, backport-candidate-11.0.x

#14348 Implement MacOSProperties.IsTemplateIcon attached property on TrayIcon
  native/Avalonia.Native/src/OSX/trayicon.h
  native/Avalonia.Native/src/OSX/trayicon.mm
  samples/ControlCatalog/App.xaml
  src/Avalonia.Controls/Platform/ITrayIconImpl.cs
  src/Avalonia.Controls/Platform/MacOSProperties.cs
  src/Avalonia.Controls/TrayIcon.cs
  src/Avalonia.Native/TrayIconImpl.cs
  src/Avalonia.Native/avn.idl
  src/Windows/Avalonia.Win32/TrayIconImpl.cs
Labels: os-macos, backport-candidate-11.0.x, priority

#14664 [Win32] Fixes improper IME composition ignorance
  src/Windows/Avalonia.Win32/Input/Imm32InputMethod.cs
Labels: os-windows

#14470 Allow a win32 window's restored size to be defined even when it is maximised or minimised
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/Windows/Avalonia.Win32/PlatformConstants.cs
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: os-windows

#14542 Use dynamic resources in Expander button theme.
  src/Avalonia.Themes.Fluent/Controls/Expander.xaml
Labels: bug, backport-candidate-11.0.x

#13398 Disable close, move, resize, maximize and minimize functions for parent of modal window on Linux.
  src/Avalonia.X11/X11Window.cs
Labels: os-linux, priority

#13840 Fix "original.dll" file permission errors during build
  Avalonia.Desktop.slnf
  packages/Avalonia/AvaloniaBuildTasks.targets
  src/Avalonia.Build.Tasks/Avalonia.Build.Tasks.csproj
  src/Avalonia.Build.Tasks/CompileAvaloniaXamlTask.cs
  src/Avalonia.Build.Tasks/Program.cs
  tests/Avalonia.Build.Tasks.UnitTest/Avalonia.Build.Tasks.UnitTest.csproj
  tests/Avalonia.Build.Tasks.UnitTest/CompileAvaloniaXamlTaskTest.cs
Labels: priority

#14705 Recreate TextLayout on measure to make sure constraint is updated
  src/Avalonia.Controls/TextBlock.cs
  tests/Avalonia.Controls.UnitTests/TextBlockTests.cs
Labels: backport-candidate-11.0.x

#14722 Fix dev tools property value converter
  src/Avalonia.Diagnostics/Diagnostics/Views/PropertyValueEditorView.cs
Labels: area-dev-tools

#14180 TemplatePart XAML diagnostics
  .editorconfig
  samples/ControlCatalog/Pages/TransitioningContentControlPage.axaml
  src/Avalonia.Base/Controls/Metadata/TemplatePartAttribute.cs
  src/Avalonia.Controls.DataGrid/Themes/Fluent.xaml
  src/Avalonia.Controls.DataGrid/Themes/Simple.xaml
  src/Avalonia.Controls/Chrome/CaptionButtons.cs
  src/Avalonia.Controls/Chrome/TitleBar.cs
  src/Avalonia.Controls/ComboBox.cs
  src/Avalonia.Controls/DateTimePickers/DatePickerPresenter.cs
  src/Avalonia.Controls/DateTimePickers/TimePickerPresenter.cs
  src/Avalonia.Controls/NumericUpDown/NumericUpDown.cs
  src/Avalonia.Controls/Primitives/HeaderedItemsControl.cs
  src/Avalonia.Controls/ProgressBar.cs
  src/Avalonia.Controls/Slider.cs
  src/Avalonia.Controls/TabControl.cs
  src/Avalonia.Controls/TextBox.cs
  src/Avalonia.Controls/ToggleSwitch.cs
  src/Avalonia.Dialogs/ManagedFileChooser.cs
  src/Avalonia.Themes.Fluent/Controls/CalendarButton.xaml
  src/Avalonia.Themes.Fluent/Controls/CalendarDayButton.xaml
  src/Avalonia.Themes.Fluent/Controls/CalendarItem.xaml
  src/Avalonia.Themes.Fluent/Controls/CheckBox.xaml
  src/Avalonia.Themes.Fluent/Controls/DateTimePickerShared.xaml
  src/Avalonia.Themes.Fluent/Controls/FlyoutPresenter.xaml
  src/Avalonia.Themes.Fluent/Controls/NotificationCard.xaml
  src/Avalonia.Themes.Fluent/Controls/ScrollBar.xaml
  src/Avalonia.Themes.Simple/Controls/CalendarButton.xaml
  src/Avalonia.Themes.Simple/Controls/CalendarDayButton.xaml
  src/Avalonia.Themes.Simple/Controls/DateTimePickerShared.xaml
  src/Avalonia.Themes.Simple/Controls/FlyoutPresenter.xaml
  src/Avalonia.Themes.Simple/Controls/NotificationCard.xaml
  src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlDiagnosticCodes.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlCompiler.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlControlTemplatePartsChecker.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlControlTemplatePriorityTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlControlTemplateTargetTypeMetadataTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  src/Markup/Avalonia.Markup.Xaml/RuntimeXamlLoaderConfiguration.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/ControlTemplateTests.cs
Labels: enhancement, area-xaml, area-analyzers

#14677 Some iOS/Android file picker fixes
  src/Android/Avalonia.Android/Platform/Storage/AndroidStorageProvider.cs
  src/iOS/Avalonia.iOS/Storage/IOSStorageItem.cs
  src/iOS/Avalonia.iOS/Storage/IOSStorageProvider.cs
Labels: bug, os-ios, os-android

#14641 Fix for bugg when move window between screens with different DPI
  src/Browser/Avalonia.Browser/AvaloniaView.cs
  src/Browser/Avalonia.Browser/BrowserTopLevelImpl.cs
  src/Browser/Avalonia.Browser/Interop/DomHelper.cs
  src/Browser/Avalonia.Browser/Skia/BrowserSkiaGpuRenderTarget.cs
  src/Browser/Avalonia.Browser/Skia/BrowserSkiaSurface.cs
  src/Browser/Avalonia.Browser/webapp/modules/avalonia.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/canvas.ts
Labels: os-browser

#14744 feat(DataGrid): make IDataGridCollectionViewFactory and IDataGridCollectionView, Add DP CollectionView
  src/Avalonia.Controls.DataGrid/Collections/DataGridCollectionView.cs
  src/Avalonia.Controls.DataGrid/Collections/IDataGridCollectionView.cs
  src/Avalonia.Controls.DataGrid/DataGrid.cs
Labels: area-datagrid
