Repository AvaloniaUI/Avalonia, pull requests merged in 2024-10, with the labels that each got.

#17178 Fix SplitView :closed pseudoclass not being added on control initialization #17176
  src/Avalonia.Controls/SplitView/SplitView.cs
  tests/Avalonia.Controls.UnitTests/SplitViewTests.cs
Labels: bug

#17180 Warning fixes: fall wave
  samples/ControlCatalog/Pages/OpenGlPage.xaml.cs
  samples/IntegrationTestApp/IntegrationTestApp.csproj
  samples/IntegrationTestApp/MacOSIntegration.cs
  src/Avalonia.Base/Rendering/UiThreadRenderTimer.cs
  src/Avalonia.Controls/Embedding/Offscreen/OffscreenTopLevelImpl.cs
  src/Avalonia.Controls/Primitives/OverlayPopupHost.cs
  src/Avalonia.DesignerSupport/Remote/PreviewerWindowImpl.cs
  src/Avalonia.Native/StorageProviderApi.cs
  src/Avalonia.Native/TopLevelImpl.cs
  src/Avalonia.X11/NativeDialogs/GtkNativeFileDialogs.cs
  src/Avalonia.X11/X11Window.cs
  src/Linux/Avalonia.LinuxFramebuffer/EpollDispatcherImpl.cs
  src/Windows/Avalonia.Win32/ScreenImpl.cs
  tests/Avalonia.Controls.UnitTests/Platform/ScreensTests.cs
Labels: enhancement

#17181 Don't apply our weird window positioning hacks for clicks on traffic lights
  native/Avalonia.Native/src/OSX/AvnWindow.mm
Labels: bug, os-macos, backport-candidate-11.2.x

#16886 Avoid Select when no boxing required
  src/Avalonia.Base/AvaloniaObjectExtensions.cs
Labels: enhancement, area-bindings

#16498 feat: Support ContactRect in X11 and Windows platform
  src/Avalonia.Base/Input/PenDevice.cs
  src/Avalonia.Base/Input/PointerPoint.cs
  src/Avalonia.Base/Input/Raw/RawPointerEventArgs.cs
  src/Avalonia.X11/X11Platform.cs
  src/Avalonia.X11/XI2Manager.cs
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
Labels: enhancement, feature, os-linux

#16938 feat: Allow use of (Classes.`classname`) syntax on Style and ControlThe…
  src/Avalonia.Base/ClassBindingManager.cs
  src/Avalonia.Base/StyledElementExtensions.cs
  src/Avalonia.Base/Styling/Setter.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlSetterTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/XamlIlAvaloniaPropertyHelper.cs
  tests/Avalonia.Markup.Xaml.UnitTests/TestViewModel.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/ControlThemeTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/StyleTests.cs
Labels: feature, area-xaml

#16940 fix: `SplitButton.Click` is not fired when `SplitButton` is not in focused
  src/Avalonia.Controls/SplitButton/SplitButton.cs
  tests/Avalonia.Controls.UnitTests/SplitButtonTests.cs
Labels: backport-candidate-11.2.x

#16748 ComboBox Empty Selection should not Generate a TextBlock as SelectionBoxItem
  src/Avalonia.Controls/ComboBox.cs
  tests/Avalonia.Controls.UnitTests/ComboBoxTests.cs
Labels: bug, backport-candidate-11.2.x

#17196 Fix LayoutUpdated and EffectiveViewportChanged double registration
  src/Avalonia.Base/Layout/Layoutable.cs
  tests/Avalonia.Base.UnitTests/Layout/LayoutableTests.cs
  tests/Avalonia.Base.UnitTests/Layout/LayoutableTests_EffectiveViewportChanged.cs
Labels: bug, backport-candidate-11.2.x

#17218 macOS: Prevent crash with popups
  native/Avalonia.Native/src/OSX/WindowBaseImpl.h
Labels: bug, os-macos, priority, backport-candidate-11.2.x

#17234 Introduce font family mapping
  src/Avalonia.Base/Media/FontManager.cs
  src/Avalonia.Base/Media/FontManagerOptions.cs
  tests/Avalonia.Skia.UnitTests/Media/FontManagerTests.cs
Labels: feature

#17209 Fixed an issue RTL wrapped text calculates an extra line for the control desired size
  src/Avalonia.Base/Media/TextFormatting/BidiReorderer.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextFormatterTests.cs
Labels: bug, area-textprocessing, backport-candidate-11.2.x

#14153 Add `ItemsControl.PreparingContainer` event
  src/Avalonia.Controls/ItemsControl.cs
Labels: feature

#16158 Considering scaling when centering windows
  src/Avalonia.Controls/Window.cs
  src/Avalonia.Controls/WindowBase.cs
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
  tests/Avalonia.Base.UnitTests/Input/PointerTestsBase.cs
  tests/Avalonia.Controls.UnitTests/DesktopStyleApplicationLifetimeTests.cs
  tests/Avalonia.Controls.UnitTests/WindowTests.cs
  tests/Avalonia.IntegrationTests.Appium/SliderTests.cs
  tests/Avalonia.IntegrationTests.Appium/WindowTests_MacOS.cs
  tests/Avalonia.LeakTests/ControlTests.cs
Labels: bug, os-linux

#16668 feat(DevTools): Allow configure DevTools HotKey
  src/Avalonia.Diagnostics/Diagnostics/DevToolsOptions.cs
  src/Avalonia.Diagnostics/Diagnostics/HotKeyConfiguration.cs
Labels: feature, area-dev-tools

#17204 Try to infer DataContext type from the $parent and #named compiled binding path parts
  src/Avalonia.Diagnostics/Diagnostics/Views/ControlDetailsView.xaml
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/XamlIlBindingPathHelper.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/CompiledBindingExtensionTests.cs
Labels: enhancement, area-xaml, area-bindings

#17059 Fix desktop lifetime non-mainwindow cancellation
  src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs
  src/Avalonia.Controls/Window.cs
  tests/Avalonia.Controls.UnitTests/DesktopStyleApplicationLifetimeTests.cs
  tests/Avalonia.Controls.UnitTests/WindowTests.cs
Labels: bug, backport-candidate-11.2.x

#17257 Fix ThemeVariant equality
  src/Avalonia.Base/Styling/ThemeVariant.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/ThemeDictionariesTests.cs
Labels: bug, backport-candidate-11.2.x

#17248 Fix DataGrid native aot crash when sorting.
  src/Avalonia.Controls.DataGrid/Collections/DataGridSortDescription.cs
  tests/Avalonia.Controls.DataGrid.UnitTests/Collections/ComparerTests.cs
Labels: bug, area-datagrid, area-trimming-aot

#16850 Use the himetric location instead of the pixel location.
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: enhancement, os-windows

#17251 Set TimePicker.Time seconds to zero when UseSeconds is False
  src/Avalonia.Controls/DateTimePickers/TimePickerPresenter.cs
  tests/Avalonia.Controls.UnitTests/TimePickerTests.cs
Labels: bug, backport-candidate-11.2.x

#17285 Restore the progress bar page
  samples/ControlCatalog/Pages/ProgressBarPage.xaml
Labels: enhancement

#17281 Implemented GLib-based dispatcher
  samples/ControlCatalog.NetCore/ControlCatalog.NetCore.csproj
  samples/ControlCatalog.NetCore/NativeControls/Gtk/GtkHelper.cs
  src/Avalonia.X11/Dispatching/GLibDispatcherImpl.cs
  src/Avalonia.X11/Dispatching/X11EventDispatcher.cs
  src/Avalonia.X11/Dispatching/X11PlatformThreading.cs
  src/Avalonia.X11/Interop/Glib.cs
  src/Avalonia.X11/Interop/GtkInteropHelper.cs
  src/Avalonia.X11/NativeDialogs/Gtk.cs
  src/Avalonia.X11/NativeDialogs/GtkNativeFileDialogs.cs
  src/Avalonia.X11/X11FocusProxy.cs
  src/Avalonia.X11/X11Platform.cs
  src/Avalonia.X11/XLib.cs
Labels: feature, priority, backport-candidate-11.1.x, backport-candidate-11.2.x

#17259 Integration tests: add retries to OpenWindowWithClick
  tests/Avalonia.IntegrationTests.Appium/ElementExtensions.cs
Labels: enhancement, area-infrastructure

#17322 Fix PopupRoot.ConfigurePosition being called unnecessary
  src/Avalonia.Controls/Primitives/Popup.cs
  tests/Avalonia.Controls.UnitTests/Primitives/PopupTests.cs
Labels: enhancement

#17195 Do not reset text selection when the TextBox loses focus
  samples/ControlCatalog/Pages/TextBoxPage.xaml
  src/Avalonia.Controls/Presenters/TextPresenter.cs
  src/Avalonia.Controls/TextBox.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
Labels: bug, backport-candidate-11.2.x

#17362 Fix .NET 9 WASM incompatibility by updating SkiaSharp.WASM package
  build/HarfBuzzSharp.props
  build/SkiaSharp.props
  src/Browser/Avalonia.Browser/build/Avalonia.Browser.props
  src/Browser/Avalonia.Browser/build/Avalonia.Browser.targets
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/XamlIlBindingPathHelper.cs
Labels: bug, os-browser, backported-11.2.x

#17374 Fix xml-test error message being not culture-invariant
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/StyleTests.cs
Labels: bug

#17194 Fix InlineUIContainer clipping in text when ArrangeOverride called. (#17183)
  src/Avalonia.Controls/TextBlock.cs
Labels: bug, backport-candidate-11.2.x

#17370 Fix InlineDictionary Behavior for Single Item Reassignment
  src/Avalonia.Base/Utilities/SmallDictionary.cs
  tests/Avalonia.Base.UnitTests/Utilities/InlineDictionaryTests.cs
Labels: bug, backport-candidate-11.2.x

#17389 Updated PackageProjectUrl with UTM tags
  build/SharedVersion.props
Labels: enhancement, backport-candidate-11.1.x, backport-candidate-11.2.x

#17391 Updated Avalonia.Desktop.slnf
  Avalonia.Desktop.slnf
Labels: bug

#17392 Don't use GLib helper functions introduced in 2.74
  src/Avalonia.X11/Interop/Glib.cs
Labels: bug, backport-candidate-11.2.x
