Repository AvaloniaUI/Avalonia, pull requests merged in 2024-08, with the labels that each got.

#16520 Allow binding `DataGridRow.IsSelected`
  src/Avalonia.Controls.DataGrid/DataGrid.cs
  src/Avalonia.Controls.DataGrid/DataGridRow.cs
  src/Avalonia.Controls.DataGrid/DataGridRows.cs
  tests/Avalonia.Controls.DataGrid.UnitTests/Avalonia.Controls.DataGrid.UnitTests.csproj
  tests/Avalonia.Controls.DataGrid.UnitTests/Collections/DataGridSortDescriptionTests.cs
  tests/Avalonia.Controls.DataGrid.UnitTests/DataGridRowTests.cs
  tests/Avalonia.Controls.DataGrid.UnitTests/Utils/ReflectionHelperTests.cs
  tests/Avalonia.UnitTests/TestRoot.cs
Labels: enhancement, area-datagrid, priority

#16568 Remove System.Linq.Expressions usages in ReflectionClrPropertyInfo
  src/Avalonia.Base/Data/Core/ClrPropertyInfo.cs
Labels: enhancement, area-trimming-aot

#16490 Android - Refactor AvaloniaInputConnection
  src/Android/Avalonia.Android/Platform/Input/AndroidInputMethod.cs
  src/Android/Avalonia.Android/Platform/Input/AvaloniaInputConnection.cs
  src/Android/Avalonia.Android/Platform/Input/EditCommand.cs
  src/Android/Avalonia.Android/Platform/Input/TextEditBuffer.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
Labels: enhancement, os-android, backport-candidate-11.1.x

#16398 Forward pointer wheel event from scrollbar to scrollviewer
  src/Avalonia.Controls/Primitives/ScrollBar.cs
Labels: bug, backport-candidate-11.1.x

#16575 Apply NumericUpDown.FormatString changes immediately.
  src/Avalonia.Controls/NumericUpDown/NumericUpDown.cs
  tests/Avalonia.Controls.UnitTests/NumericUpDownTests.cs
Labels: bug, backport-candidate-11.1.x

#16583 Increase LayoutTransformControl.DecimalsAfterRound from 4 to 8
  src/Avalonia.Controls/LayoutTransformControl.cs
Labels: enhancement, wont-backport

#16562 Remove internal access modifier from IWindowImpl.GetWindowsZOrder
  src/Avalonia.Controls/Platform/IWindowImpl.cs
Labels: bug, backport-candidate-11.1.x

#16539 [OpenGL] Fix #13807 - lingering glGetError from Avalonia
  src/Avalonia.OpenGL/GlBasicInfoInterface.cs
  src/Avalonia.OpenGL/GlInterface.cs
Labels: bug, area-rendering, backport-candidate-11.1.x

#16546 Record video for failing win32 integration tests on CI.
  azure-pipelines-integrationtests.yml
  tests/Avalonia.IntegrationTests.Appium/record-video.runsettings
Labels: area-infrastructure

#16564 Fixed overlay popups not automatically closing
  src/Avalonia.Controls/ToolTipService.cs
  tests/Avalonia.Controls.UnitTests/ToolTipTests.cs
Labels: bug, backport-candidate-11.1.x

#15542 Add basic integration tests for NativeControlHost and improve its automation/a11y support.
  native/Avalonia.Native/src/OSX/automation.mm
  samples/IntegrationTestApp/Embedding/INativeControlFactory.cs
  samples/IntegrationTestApp/Embedding/MacHelper.cs
  samples/IntegrationTestApp/Embedding/MacOSTextBoxFactory.cs
  samples/IntegrationTestApp/Embedding/MacOSViewHandle.cs
  samples/IntegrationTestApp/Embedding/NativeTextBox.cs
  samples/IntegrationTestApp/Embedding/Win32TextBoxFactory.cs
  samples/IntegrationTestApp/Embedding/Win32WindowControlHandle.cs
  samples/IntegrationTestApp/Embedding/WinApi.cs
  samples/IntegrationTestApp/IntegrationTestApp.csproj
  samples/IntegrationTestApp/MainWindow.axaml.cs
  samples/IntegrationTestApp/Pages/EmbeddingPage.axaml
  samples/IntegrationTestApp/Pages/EmbeddingPage.axaml.cs
  samples/IntegrationTestApp/Program.cs
  samples/IntegrationTestApp/app.manifest
  src/Avalonia.Controls/Automation/Peers/InteropAutomationPeer.cs
  src/Avalonia.Controls/Automation/Peers/NativeControlHostPeer.cs
  src/Avalonia.Controls/NativeControlHost.cs
  src/Avalonia.Native/AvnAutomationPeer.cs
  src/Avalonia.Native/avn.idl
  src/Windows/Avalonia.Win32/Automation/AutomationNode.cs
  src/Windows/Avalonia.Win32/Automation/InteropAutomationNode.cs
  tests/Avalonia.IntegrationTests.Appium/EmbeddingTests.cs
Labels: enhancement

#16597 Try to fix flaky window decorations tests on Windows.
  samples/IntegrationTestApp/MainWindow.axaml.cs
Labels: area-infrastructure

#16599 Added Compositor.CreateCompositionVisualSnapshot API
  api/Avalonia.Skia.nupkg.xml
  samples/ControlCatalog/Pages/OpenGlPage.xaml
  samples/ControlCatalog/Pages/OpenGlPage.xaml.cs
  src/Avalonia.Base/Platform/IDrawingContextImpl.cs
  src/Avalonia.Base/Platform/IPlatformRenderInterface.cs
  src/Avalonia.Base/Platform/IScopedResource.cs
  src/Avalonia.Base/Rendering/Composition/Compositor.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionDrawListVisual.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionExperimentalAcrylicVisual.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionSolidColorVisual.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionSurfaceVisual.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionTarget.DirtyRects.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionTarget.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositor.UserApis.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositor.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCustomCompositionVisual.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerVisualRenderContext.cs
  src/Avalonia.Controls/BorderVisual.cs
  src/Headless/Avalonia.Headless/HeadlessPlatformRenderInterface.cs
  src/Skia/Avalonia.Skia/Gpu/ISkiaGpu.cs
  src/Skia/Avalonia.Skia/Gpu/Metal/SkiaMetalGpu.cs
  src/Skia/Avalonia.Skia/Gpu/OpenGl/GlSkiaGpu.cs
  src/Skia/Avalonia.Skia/SkiaBackendContext.cs
  src/Skia/Avalonia.Skia/SurfaceRenderTarget.cs
  src/Windows/Avalonia.Direct2D1/Direct2D1Platform.cs
Labels: feature, area-rendering, priority, backport-candidate-11.1.x

#16594 Fixes ShapedTextRun background rendering
  src/Avalonia.Base/Media/TextFormatting/ShapedTextRun.cs
  tests/Avalonia.RenderTests/Controls/TextBlockTests.cs
  tests/TestFiles/Direct2D1/Controls/TextBlock/Should_Draw_Run_With_Background.expected.png
  tests/TestFiles/Skia/Controls/TextBlock/Should_Draw_Run_With_Background.expected.png
Labels: bug, area-rendering, backport-candidate-11.1.x

#16540 Fixup `GlxDisplay.CreateContext`
  src/Avalonia.X11/Glx/GlxDisplay.cs
Labels: bug, backport-candidate-11.1.x

#15994 Switch to Metal by default
  src/iOS/Avalonia.iOS/Platform.cs
Labels: os-ios, backported-11.1.x

#16219 Implemented `MultiBindingExpression`
  src/Avalonia.Base/AvaloniaObjectExtensions.cs
  src/Avalonia.Base/Data/Core/IBinding2.cs
  src/Avalonia.Base/Data/Core/MultiBindingExpression.cs
  src/Avalonia.Base/Data/Core/UntypedBindingExpressionBase.cs
  src/Avalonia.Base/Data/IndexerBinding.cs
  src/Avalonia.Base/Data/TemplateBinding.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindingExtension.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/DynamicResourceExtension.cs
  src/Markup/Avalonia.Markup/Data/Binding.cs
  src/Markup/Avalonia.Markup/Data/BindingBase.cs
  src/Markup/Avalonia.Markup/Data/MultiBinding.cs
  tests/Avalonia.Markup.UnitTests/Data/MultiBindingTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Converters/MultiValueConverterTests.cs
Labels: bug, enhancement, backport-candidate-11.1.x

#16620 fix: SixLabors ImageSharp Out-of-bounds Write `CVE-2024-41131`
  build/ImageSharp.props
Labels: area-infrastructure

#16649 feat(XamlX): Trim text before invoke Color.Parse
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlLanguageParseIntrinsics.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/AvaloniaIntrinsicsTests.cs
Labels: bug, area-xaml

#16633 Switch to a HashSet<T> as backing for SafeEnumerableList
  src/Avalonia.Base/Controls/Classes.cs
  src/Avalonia.Base/Utilities/SafeEnumerableHashSet.cs
  src/Avalonia.Base/Utilities/SafeEnumerableList.cs
  tests/Avalonia.Controls.UnitTests/Utils/SafeEnumerableHashSetTests.cs
Labels: enhancement, wont-backport

#16616 Android - Defer rendering till surface is created
  src/Android/Avalonia.Android/AvaloniaActivity.cs
  src/Android/Avalonia.Android/AvaloniaMainActivity.cs
  src/Android/Avalonia.Android/AvaloniaView.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/InvalidationAwareSurfaceView.cs
Labels: os-android

#16557 UWP/WinUI style XYFocus subtree restrictions
  src/Avalonia.Base/Input/Navigation/XYFocus.Impl.cs
  src/Avalonia.Base/Input/Navigation/XYFocusHelpers.cs
  tests/Avalonia.Base.UnitTests/Input/KeyboardNavigationTests_XY.cs
Labels: feature, wont-backport, area-focus

#16647 Screens api refactor mobile
  api/Avalonia.Android.nupkg.xml
  api/Avalonia.Browser.nupkg.xml
  api/Avalonia.iOS.nupkg.xml
  src/Android/Avalonia.Android/AndroidViewControlHandle.cs
  src/Android/Avalonia.Android/AvaloniaView.cs
  src/Android/Avalonia.Android/Platform/AndroidNativeControlHostImpl.cs
  src/Android/Avalonia.Android/Platform/AndroidScreens.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
  src/Browser/Avalonia.Browser/BrowserScreens.cs
  src/Browser/Avalonia.Browser/BrowserTopLevelImpl.cs
  src/Browser/Avalonia.Browser/Interop/DomHelper.cs
  src/Browser/Avalonia.Browser/Interop/ScreenHelper.cs
  src/Browser/Avalonia.Browser/JSObjectControlHandle.cs
  src/Browser/Avalonia.Browser/WindowingPlatform.cs
  src/Browser/Avalonia.Browser/webapp/modules/avalonia.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/screens.ts
  src/Browser/Avalonia.Browser/webapp/package-lock.json
  src/Browser/Avalonia.Browser/webapp/package.json
  src/Tizen/Avalonia.Tizen/NuiScreens.cs
  src/Tizen/Avalonia.Tizen/TizenRuntimePlatform.cs
  src/Tizen/Avalonia.Tizen/TopLevelImpl.cs
  src/iOS/Avalonia.iOS/AvaloniaView.cs
  src/iOS/Avalonia.iOS/NativeControlHostImpl.cs
  src/iOS/Avalonia.iOS/Platform.cs
  src/iOS/Avalonia.iOS/iOSScreens.cs
Labels: feature, os-browser, os-ios, os-android, os-tizen

#16701 Fix typos in build messages when waiting to attach a debugger
  src/Avalonia.Build.Tasks/XamlCompilerTaskExecutor.cs
Labels: area-infrastructure

#16666 Android - Input Connection fixes
  src/Android/Avalonia.Android/Platform/Input/AndroidInputMethod.cs
  src/Android/Avalonia.Android/Platform/Input/AvaloniaInputConnection.cs
  src/Android/Avalonia.Android/Platform/Input/EditCommand.cs
  src/Android/Avalonia.Android/Platform/Input/TextEditBuffer.cs
Labels: bug, os-android

#16664 feat(Geometries): PolyBezierSegment
  src/Avalonia.Base/Media/PolyBezierSegment.cs
  src/Avalonia.Base/Points.cs
  tests/Avalonia.RenderTests.WpfCompare/CrossUI.Wpf.cs
  tests/Avalonia.RenderTests/CrossTests/CrossGeometryTests.cs
  tests/Avalonia.RenderTests/CrossUI/CrossUI.Avalonia.cs
  tests/Avalonia.RenderTests/CrossUI/CrossUI.cs
  tests/TestFiles/CrossTests/Media/Geometry/Should_Render_PolyBezierSegment_With_Strokeless_Lines.wpf.png
Labels: feature

#16643 Only add the text selection canvas when the textbox is focused
  src/Avalonia.Controls/Presenters/TextPresenter.cs
  src/Avalonia.Controls/Primitives/TextSelectionCanvas.cs
Labels: enhancement

#16654 ColorPicker Simple Theme Fixes
  src/Avalonia.Controls.ColorPicker/Themes/Simple/ColorPicker.xaml
  src/Avalonia.Controls.ColorPicker/Themes/Simple/ColorView.xaml
  src/Avalonia.Themes.Simple/Controls/NumericUpDown.xaml
Labels: enhancement

#16619 fix: Button should not fire the click event on the space key when it is not active
  src/Avalonia.Controls/Button.cs
  tests/Avalonia.Controls.UnitTests/ButtonTests.cs
Labels: bug

#16644 feat: x:Shared
  src/Avalonia.Base/Controls/ResourceDictionary.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlDeferredResourceTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/XSharedDirectiveTests.cs
Labels: feature, area-xaml

#16593 Extend the client area when a Win32 window is opened in maximised state
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
Labels: bug, os-windows, backport-candidate-11.1.x

#16608 Win32 - Fix Window Frame Size and Position issues.
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
  tests/Avalonia.IntegrationTests.Appium/WindowDecorationsTests.cs
  tests/Avalonia.IntegrationTests.Appium/WindowTests.cs
Labels: os-windows

#16712 Fix caret position after backspace
  src/Avalonia.Controls/TextBox.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
Labels: bug, regression, area-textprocessing

#16710 Ensure SurroundingText is empty for empty line
  src/Avalonia.Controls/TextBoxTextInputMethodClient.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
Labels: bug

#15685 Bump DBus stack take 2
  api/Avalonia.FreeDesktop.nupkg.xml
  src/Avalonia.FreeDesktop/Avalonia.FreeDesktop.csproj
  src/Avalonia.FreeDesktop/DBusIme/Fcitx/FcitxICWrapper.cs
  src/Avalonia.FreeDesktop/DBusIme/Fcitx/FcitxX11TextInputMethod.cs
  src/Avalonia.FreeDesktop/DBusIme/IBus/IBusX11TextInputMethod.cs
  src/Avalonia.FreeDesktop/DBusMenuExporter.cs
  src/Avalonia.FreeDesktop/DBusPlatformSettings.cs
  src/Avalonia.FreeDesktop/DBusSystemDialog.cs
  src/Avalonia.FreeDesktop/DBusTrayIconImpl.cs
  src/Avalonia.X11/X11Window.cs
Labels: os-linux

#16527 Fix - Grow datagrid height if there's available space
  src/Avalonia.Controls.DataGrid/DataGrid.cs
  src/Avalonia.Controls.DataGrid/DataGridRows.cs
  src/Avalonia.Controls.DataGrid/Primitives/DataGridRowsPresenter.cs
Labels: bug, area-datagrid, priority, backport-candidate-11.1.x

#16626 Changed modifiers for injected non-client implementable method
  nukebuild/RefAssemblyGenerator.cs
Labels: area-infrastructure, backport-candidate-11.0.x, priority, backport-candidate-11.1.x

#15753 Validate all width/height properties of Layoutable when they are set
  src/Avalonia.Base/Layout/Layoutable.cs
  tests/Avalonia.Base.UnitTests/Layout/LayoutableTests.cs
Labels: enhancement, wont-backport

#15667 Custom popup placement callback
  api/Avalonia.nupkg.xml
  samples/ControlCatalog/Pages/FlyoutsPage.axaml
  samples/ControlCatalog/Pages/FlyoutsPage.axaml.cs
  samples/ControlCatalog/Pages/ToolTipPage.xaml
  samples/ControlCatalog/Pages/ToolTipPage.xaml.cs
  src/Avalonia.Controls/ContextMenu.cs
  src/Avalonia.Controls/ContextRequestedEventArgs.cs
  src/Avalonia.Controls/Flyouts/PopupFlyoutBase.cs
  src/Avalonia.Controls/PlacementMode.cs
  src/Avalonia.Controls/Primitives/IPopupHost.cs
  src/Avalonia.Controls/Primitives/OverlayPopupHost.cs
  src/Avalonia.Controls/Primitives/Popup.cs
  src/Avalonia.Controls/Primitives/PopupPositioning/CustomPopupPlacement.cs
  src/Avalonia.Controls/Primitives/PopupPositioning/CustomPopupPlacementCallback.cs
  src/Avalonia.Controls/Primitives/PopupPositioning/IPopupPositioner.cs
  src/Avalonia.Controls/Primitives/PopupPositioning/PopupPositionRequest.cs
  src/Avalonia.Controls/Primitives/PopupRoot.cs
  src/Avalonia.Controls/ToolTip.cs
  tests/Avalonia.Controls.UnitTests/Primitives/PopupRootTests.cs
  tests/Avalonia.Controls.UnitTests/Primitives/PopupTests.cs
Labels: feature

#16733 11.2.x Private/PublicAPI adjustments
  api/Avalonia.Skia.nupkg.xml
  api/Avalonia.nupkg.xml
  src/Avalonia.Base/Diagnostics/IValueFrameDiagnostic.cs
  src/Avalonia.Base/Diagnostics/StyleDiagnostics.cs
  src/Avalonia.Base/Diagnostics/StyleValueFrameDiagnostic.cs
  src/Avalonia.Base/Diagnostics/StyledElementExtensions.cs
  src/Avalonia.Base/Diagnostics/ValueStoreDiagnostic.cs
  src/Avalonia.Base/Media/Fonts/Tables/InvalidFontTableException.cs
  src/Avalonia.Base/Media/Fonts/Tables/KnownNameIds.cs
  src/Avalonia.Base/Media/Fonts/Tables/MissingFontTableException.cs
  src/Browser/Avalonia.Browser/Rendering/RenderWorker.cs
Labels: enhancement

#16705 X11 - Refactor x11 Screen API
  src/Avalonia.X11/Screens/X11Screen.Providers.cs
  src/Avalonia.X11/Screens/X11Screens.Scaling.cs
  src/Avalonia.X11/Screens/X11Screens.cs
Labels: feature, area-x11

#16735 TitleBar.Height setter crashes integrational tests app
  src/Avalonia.Controls/Chrome/TitleBar.cs
Labels: os-macos, regression, priority

#16719 Housekeeping Update ReactiveUI and Rx base version
  build/ReactiveUI.props
  build/Rx.props
Labels: area-infrastructure

#16780 fix: NativeMethods.txt
  src/Windows/Avalonia.Win32/NativeMethods.txt
Labels: bug, os-windows

#16794 Reduced memory alloc for combined binding subjects
  src/Avalonia.Base/Data/InstancedBinding.cs
Labels: enhancement

#16844 Add TypographicFamilyName to GlyphTypeface and use it for FontCollection
  src/Avalonia.Base/Media/Fonts/EmbeddedFontCollection.cs
  src/Avalonia.Base/Media/Fonts/SystemFontCollection.cs
  src/Avalonia.Base/Media/IGlyphTypeface2.cs
  src/Skia/Avalonia.Skia/GlyphTypefaceImpl.cs
  tests/Avalonia.Skia.UnitTests/Avalonia.Skia.UnitTests.csproj
  tests/Avalonia.Skia.UnitTests/Fonts/Manrope-Light.ttf
  tests/Avalonia.Skia.UnitTests/Media/EmbeddedFontCollectionTests.cs
Labels: bug, priority, backport-candidate-11.1.x

#16347 Fixes #16346
  src/Avalonia.Controls/VirtualizingStackPanel.cs
Labels: bug, backport-candidate-11.1.x
