Repository AvaloniaUI/Avalonia, pull requests merged in 2024-11, with the labels that each got.

#17398 Fix DateTimePickerPanelType enum backward compatibility
  src/Avalonia.Controls/DateTimePickers/DateTimePickerPanel.cs
Labels: bug, regression, backport-candidate-11.2.x

#17414 Create an autorelease pool for every render timer tick
  native/Avalonia.Native/src/OSX/PlatformRenderTimer.mm
Labels: bug, backport-candidate-11.1.x, backport-candidate-11.2.x

#17413 Added generate-headers.sh for convenience purposes
  native/Avalonia.Native/generate-headers.sh
Labels: area-infrastructure

#17411 fix Expander.cs for transition broken
  src/Avalonia.Controls/Expander.cs
Labels: bug, backport-candidate-11.2.x

#17409 Implement TryGetFeature on secondary previewer windows
  src/Avalonia.DesignerSupport/Remote/Stubs.cs
Labels: bug, regression, area-previewer, backport-candidate-11.2.x

#17405 Improve automation XML docs.
  src/Avalonia.Controls/Automation/AutomationProperties.cs
  src/Avalonia.Controls/Automation/Peers/AutomationPeer.cs
  src/Avalonia.Controls/Automation/Provider/IEmbeddedRootProvider.cs
  src/Avalonia.Controls/Automation/Provider/IExpandCollapseProvider.cs
  src/Avalonia.Controls/Automation/Provider/IInvokeProvider.cs
  src/Avalonia.Controls/Automation/Provider/IRangeValueProvider.cs
  src/Avalonia.Controls/Automation/Provider/IRootProvider.cs
  src/Avalonia.Controls/Automation/Provider/IScrollProvider.cs
  src/Avalonia.Controls/Automation/Provider/ISelectionItemProvider .cs
  src/Avalonia.Controls/Automation/Provider/ISelectionProvider.cs
  src/Avalonia.Controls/Automation/Provider/IToggleProvider.cs
  src/Avalonia.Controls/Automation/Provider/IValueProvider.cs
Labels: enhancement

#17428 Update pipelines to macOS 13
  azure-pipelines.yml
Labels: area-infrastructure

#17399 Typeface simulation fixes
  src/Avalonia.Base/Media/FontManager.cs
  src/Avalonia.Base/Media/Fonts/EmbeddedFontCollection.cs
  src/Avalonia.Base/Media/Fonts/SystemFontCollection.cs
Labels: bug, backport-candidate-11.2.x

#17422 Optimization for Process.GetCurrentProcess() in Avalonia.Win32.Automation
  src/Windows/Avalonia.Win32.Automation/AutomationNode.cs
Labels: enhancement, area-accessibility

#17427 Fix TemplateBinding in custom IControlTemplate implementations
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlControlTemplateTargetTypeMetadataTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/ControlTemplateTests.cs
Labels: bug, area-xaml, customer-priority, backport-candidate-11.2.x

#17442 Fix adapter selection in Vulkan demo
  samples/GpuInterop/VulkanDemo/D3DMemoryHelper.cs
Labels: bug

#17454 Handle previously missing event types in PenDevice
  src/Avalonia.Base/Input/PenDevice.cs
Labels: bug, os-windows, backport-candidate-11.2.x

#17452 Bring back ".net 8" target for Avalonia.Browser
  src/Browser/Avalonia.Browser/Avalonia.Browser.csproj
Labels: enhancement, os-browser, backport-candidate-11.2.x

#17426 Added basic date/time picker automation peers.
  src/Avalonia.Controls/Automation/Peers/DatePickerAutomationPeer.cs
  src/Avalonia.Controls/Automation/Peers/TimePickerAutomationPeer.cs
  src/Avalonia.Controls/DateTimePickers/DatePicker.cs
  src/Avalonia.Controls/DateTimePickers/TimePicker.cs
Labels: enhancement, customer-priority, backport-candidate-11.2.x

#17292 Fixes and improves several access key (accelerator) related issues
  api/Avalonia.nupkg.xml
  samples/ControlCatalog/MainView.xaml
  samples/ControlCatalog/Pages/AcceleratorPage.xaml
  samples/ControlCatalog/Pages/AcceleratorPage.xaml.cs
  src/Avalonia.Base/Input/AccessKeyHandler.cs
  src/Avalonia.Base/Input/InputElement.cs
  src/Avalonia.Controls/Button.cs
  src/Avalonia.Controls/Label.cs
  src/Avalonia.Controls/Menu.cs
  src/Avalonia.Controls/MenuItem.cs
  src/Avalonia.Controls/MenuItemAccessKeyHandler.cs
  src/Avalonia.Controls/Platform/DefaultMenuInteractionHandler.cs
  src/Avalonia.Controls/TabItem.cs
  tests/Avalonia.Base.UnitTests/Input/AccessKeyHandlerTests.cs
  tests/Avalonia.Base.UnitTests/Input/InputElement_Focus.cs
  tests/Avalonia.Controls.UnitTests/ButtonTests.cs
  tests/Avalonia.Controls.UnitTests/TabControlTests.cs
  tests/Avalonia.Markup.UnitTests/Data/BindingTests_Method.cs
Labels: enhancement

#17402 Fix TextBlock TextAlignment issues when a HorizontalAlignment is defined
  src/Avalonia.Controls/TextBlock.cs
  tests/Avalonia.Controls.UnitTests/TextBlockTests.cs
  tests/Avalonia.RenderTests/Controls/TextBlockTests.cs
  tests/Avalonia.RenderTests/TestSkip.cs
  tests/TestFiles/Direct2D1/Controls/TextBlock/Should_Measure_Arrange_TextBlock_150_NoWrap.expected.png
  tests/TestFiles/Direct2D1/Controls/TextBlock/Should_Measure_Arrange_TextBlock_44_NoWrap.expected.png
  tests/TestFiles/Direct2D1/Controls/TextBlock/Should_Measure_Arrange_TextBlock_44_Wrap.expected.png
  tests/TestFiles/Skia/Controls/TextBlock/Should_Measure_Arrange_TextBlock_150_NoWrap.expected.png
  tests/TestFiles/Skia/Controls/TextBlock/Should_Measure_Arrange_TextBlock_44_NoWrap.expected.png
  tests/TestFiles/Skia/Controls/TextBlock/Should_Measure_Arrange_TextBlock_44_Wrap.expected.png
Labels: customer-priority, backport-candidate-11.1.x, backport-candidate-11.2.x

#17462 AutoCompleteBox don't lose text selection when contextmenu opens
  src/Avalonia.Controls/AutoCompleteBox/AutoCompleteBox.cs
  tests/Avalonia.Controls.UnitTests/AutoCompleteBoxTests.cs
Labels: bug, area-textprocessing

#17468 Update IInsetsManager.cs
  src/Avalonia.Controls/Platform/IInsetsManager.cs
Labels: spelling

#17489 Nullable annotations for LinuxFramebuffer
  src/Linux/Avalonia.LinuxFramebuffer/Avalonia.LinuxFramebuffer.csproj
  src/Linux/Avalonia.LinuxFramebuffer/EpollDispatcherImpl.cs
  src/Linux/Avalonia.LinuxFramebuffer/FramebufferToplevelImpl.cs
  src/Linux/Avalonia.LinuxFramebuffer/Input/EvDev/EvDevBackend.cs
  src/Linux/Avalonia.LinuxFramebuffer/Input/EvDev/EvDevDevice.cs
  src/Linux/Avalonia.LinuxFramebuffer/Input/EvDev/EvDevDeviceDescription.cs
  src/Linux/Avalonia.LinuxFramebuffer/Input/EvDev/EvDevTouchScreen.cs
  src/Linux/Avalonia.LinuxFramebuffer/Input/LibInput/LibInputBackend.Pointer.cs
  src/Linux/Avalonia.LinuxFramebuffer/Input/LibInput/LibInputBackend.Touch.cs
  src/Linux/Avalonia.LinuxFramebuffer/Input/LibInput/LibInputBackend.cs
  src/Linux/Avalonia.LinuxFramebuffer/Input/LibInput/LibInputNativeUnsafeMethods.cs
  src/Linux/Avalonia.LinuxFramebuffer/LinuxFramebufferPlatform.cs
  src/Linux/Avalonia.LinuxFramebuffer/Output/DrmBindings.cs
  src/Linux/Avalonia.LinuxFramebuffer/Output/DrmOutput.cs
  src/Linux/Avalonia.LinuxFramebuffer/Output/FbDevBackBuffer.cs
  src/Linux/Avalonia.LinuxFramebuffer/Output/FbDevOutputOptions.cs
  src/Linux/Avalonia.LinuxFramebuffer/Output/FbdevOutput.cs
  src/Linux/Avalonia.LinuxFramebuffer/Output/IGlOutputBackend.cs
Labels: enhancement, os-linux

#17480 add automation peer for UserControl
  src/Avalonia.Controls/Automation/Peers/UserControlAutomationPeer.cs
  src/Avalonia.Controls/UserControl.cs
Labels: enhancement, area-accessibility

#17499 Revert "Fixed publishing multi-architecture Android builds"
  packages/Avalonia/AvaloniaBuildTasks.targets
Labels: area-infrastructure, regression, backport-candidate-11.2.x

#17500 Fix Gtk open file dialog returns folder
  src/Avalonia.X11/NativeDialogs/GtkNativeFileDialogs.cs
Labels: bug, os-linux, backport-candidate-11.2.x

#17507 [Browser] Add dotnet/runtime#109289 workaround
  src/Browser/Avalonia.Browser/build/Avalonia.Browser.targets
Labels: bug, os-browser, backport-candidate-11.2.x

#17380 Properly handle nc hittest for caption buttons
  src/Avalonia.Controls/Chrome/CaptionButtons.cs
  src/Avalonia.Controls/Platform/Win32Properties.cs
  src/Avalonia.Themes.Fluent/Controls/CaptionButtons.xaml
  src/Avalonia.Themes.Fluent/Controls/TitleBar.xaml
  src/Avalonia.Themes.Simple/Controls/CaptionButtons.xaml
  src/Avalonia.Themes.Simple/Controls/TitleBar.xaml
  src/Windows/Avalonia.Win32/WindowImpl.CustomCaptionProc.cs
Labels: enhancement, os-windows

#17508 Disable Metal as a default rendering mode for 11.2
  src/Avalonia.Native/AvaloniaNativePlatformExtensions.cs
Labels: bug, os-macos, backported-11.2.x

#17011 Enhance OpenGlControlBase.cs
  src/Avalonia.OpenGL/Controls/OpenGlControlBase.cs
Labels: bug, area-rendering

#17171 Fix INotifyCollectionChanged Move and Replace handling
  src/Avalonia.Base/Collections/AvaloniaDictionaryExtensions.cs
  src/Avalonia.Base/Collections/AvaloniaList.cs
  src/Avalonia.Base/Collections/AvaloniaListExtensions.cs
  src/Avalonia.Controls/Presenters/PanelContainerGenerator.cs
  src/Avalonia.Controls/Selection/SelectionNodeBase.cs
  src/Avalonia.Controls/VirtualizingCarouselPanel.cs
  src/Avalonia.Controls/VirtualizingStackPanel.cs
  tests/Avalonia.Base.UnitTests/Collections/AvaloniaListTests.cs
  tests/Avalonia.Controls.UnitTests/Presenters/ItemsPresenterTests.cs
  tests/Avalonia.Controls.UnitTests/VirtualizingCarouselPanelTests.cs
  tests/Avalonia.Controls.UnitTests/VirtualizingStackPanelTests.cs
Labels: enhancement

#17465 CalendarDatePicker - use CustomDateFormatString for parsing the text input
  src/Avalonia.Controls/CalendarDatePicker/CalendarDatePicker.cs
  tests/Avalonia.Controls.UnitTests/CalendarDatePickerTests.cs
Labels: bug, backport-candidate-11.2.x

#17483 Enable TemplateBinding inside ItemsPanelTemplate
  src/Avalonia.Base/Metadata/ControlTemplateScopeAttribute.cs
  src/Avalonia.Controls/Templates/IControlTemplate.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlControlTemplateTargetTypeMetadataTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  src/Markup/Avalonia.Markup.Xaml/Templates/ItemsPanelTemplate.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/ItemsPanelTemplateTests.cs
Labels: feature, area-xaml, customer-priority, area-bindings, backport-candidate-11.2.x

#17516 Fix TimePicker breaking change, when using pre-11.2 styles
  src/Avalonia.Controls/DateTimePickers/TimePicker.cs
  src/Avalonia.Controls/DateTimePickers/TimePickerPresenter.cs
Labels: bug, backport-candidate-11.2.x

#17505 Backport TextBlock fixes
  src/Avalonia.Controls/TextBlock.cs
  tests/Avalonia.Controls.UnitTests/TextBlockTests.cs
  tests/Avalonia.RenderTests/Controls/TextBlockTests.cs
  tests/Avalonia.RenderTests/TestSkip.cs
  tests/TestFiles/Direct2D1/Controls/TextBlock/Should_Measure_Arrange_TextBlock_150_NoWrap.expected.png
  tests/TestFiles/Direct2D1/Controls/TextBlock/Should_Measure_Arrange_TextBlock_44_NoWrap.expected.png
  tests/TestFiles/Direct2D1/Controls/TextBlock/Should_Measure_Arrange_TextBlock_44_Wrap.expected.png
  tests/TestFiles/Skia/Controls/TextBlock/Should_Measure_Arrange_TextBlock_150_NoWrap.expected.png
  tests/TestFiles/Skia/Controls/TextBlock/Should_Measure_Arrange_TextBlock_44_NoWrap.expected.png
  tests/TestFiles/Skia/Controls/TextBlock/Should_Measure_Arrange_TextBlock_44_Wrap.expected.png
Labels: bug

#17532 Fix npm install for parallel builds
  src/Browser/Avalonia.Browser/Avalonia.Browser.csproj
Labels: bug, area-infrastructure

#17550 Remove Tizen workload; use the Tizen SDK package directly instead
  azure-pipelines.yml
  build/TargetFrameworks.props
  global.json
  samples/ControlCatalog.Tizen/ControlCatalog.Tizen.csproj
  src/Tizen/Avalonia.Tizen/Avalonia.Tizen.csproj
Labels: enhancement, area-infrastructure, os-tizen

#17531 Fix build Clean target
  nukebuild/Build.cs
  nukebuild/BuildParameters.cs
Labels: bug, area-infrastructure

#17524 Fix crashing after opening a uri on browser
  src/Browser/Avalonia.Browser/Interop/NavigationHelper.cs
  src/Browser/Avalonia.Browser/Storage/BrowserLauncher.cs
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/navigationHelper.ts
Labels: bug, os-browser, backport-candidate-11.2.x

#17519 Fix FontCollection glyph typeface caching
  src/Avalonia.Base/Media/Fonts/EmbeddedFontCollection.cs
  src/Avalonia.Base/Media/Fonts/SystemFontCollection.cs
  tests/Avalonia.Skia.UnitTests/Media/EmbeddedFontCollectionTests.cs
  tests/Avalonia.Skia.UnitTests/Media/FontCollectionTests.cs
Labels: bug, backport-candidate-11.2.x

#17565 Fix visual snapshot on headless
  src/Avalonia.Base/Rendering/Composition/Compositor.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionContainerVisual.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionTarget.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositor.UserApis.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerVisualRenderContext.cs
  tests/Avalonia.Headless.UnitTests/RenderingTests.cs
Labels: bug, area-headless, backport-candidate-11.2.x

#17559 Win32: fix position being changed on Resize while minimized
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: bug, os-windows, customer-priority, backport-candidate-11.2.x

#17571 Don't check if intent is declared by app before launch
  src/Android/Avalonia.Android/Platform/AndroidLauncher.cs
Labels: bug, os-android, backport-candidate-11.2.x

#17573 call proper method on hide
  src/Avalonia.Native/AvaloniaNativeApplicationPlatform.cs
Labels: bug, os-macos, backport-candidate-11.2.x

#17595 Update SkiaSharp
  build/HarfBuzzSharp.props
  build/SkiaSharp.props
Labels: enhancement, backport-candidate-11.2.x

#17594 Use URLWithString for pickers
  native/Avalonia.Native/src/OSX/StorageProvider.mm
Labels: bug, os-macos, regression, backport-candidate-11.2.x

#17321 Fix the known valuator do not update.
  src/Avalonia.X11/XI2Manager.cs
Labels: enhancement, os-linux

#17605 Optimize SKRoundRectCache Clear Method for .NET 6+
  src/Skia/Avalonia.Skia/SKRoundRectCache.cs
Labels: enhancement, area-perf

#17570 Raise the `EffectiveViewPortChanged` when a control is added to the tree that has already has a valid layout
  src/Avalonia.Base/Layout/LayoutManager.cs
  tests/Avalonia.Base.UnitTests/Layout/LayoutableTests_EffectiveViewportChanged.cs
Labels: bug, backport-candidate-11.0.x, backport-candidate-11.1.x, backport-candidate-11.2.x

#17608 Fix macOS ActivatableLifetime events
  native/Avalonia.Native/src/OSX/app.mm
  src/Avalonia.Native/AvaloniaNativeApplicationPlatform.cs
  src/Avalonia.Native/avn.idl
Labels: bug, os-macos, customer-priority

#17630 Add missing ItemGroup to build tasks
  packages/Avalonia/AvaloniaBuildTasks.targets
Labels: bug, area-infrastructure

#17628 Fix random test failures and add empty dispatcher verification to tests
  Avalonia.sln.DotSettings
  build/XUnit.props
  src/Avalonia.Base/Threading/Dispatcher.Queue.cs
  src/Avalonia.Base/Threading/DispatcherOperation.cs
  src/Avalonia.Base/Threading/DispatcherPriorityQueue.cs
  tests/Avalonia.Base.UnitTests/Composition/CompositionAnimationTests.cs
  tests/Avalonia.Base.UnitTests/Input/AccessKeyHandlerTests.cs
  tests/Avalonia.Base.UnitTests/Input/PointerTestsBase.cs
  tests/Avalonia.Base.UnitTests/Layout/LayoutableTests_EffectiveViewportChanged.cs
  tests/Avalonia.Base.UnitTests/Layout/LayoutableTests_LayoutRounding.cs
  tests/Avalonia.Base.UnitTests/Properties/AssemblyInfo.cs
  tests/Avalonia.Controls.UnitTests/ComboBoxTests.cs
  tests/Avalonia.Controls.UnitTests/Properties/AssemblyInfo.cs
  tests/Avalonia.Controls.UnitTests/TabControlTests.cs
  tests/Avalonia.Headless.UnitTests/InputTests.cs
  tests/Avalonia.Headless.UnitTests/RenderingTests.cs
  tests/Avalonia.Headless.UnitTests/ServicesTests.cs
  tests/Avalonia.Headless.UnitTests/ThreadingTests.cs
  tests/Avalonia.IntegrationTests.Appium/WindowTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Avalonia.Markup.Xaml.UnitTests.csproj
  tests/Avalonia.ReactiveUI.UnitTests/Attributes.cs
  tests/Avalonia.ReactiveUI.UnitTests/ReactiveUserControlTest.cs
  tests/Avalonia.UnitTests/InvariantCultureAttribute.cs
  tests/Avalonia.UnitTests/VerifyEmptyDispatcherAfterTestAttribute.cs
Labels: bug, area-infrastructure

#17638 Fix TextBlock re-measure in infinite container
  src/Avalonia.Controls/SelectableTextBlock.cs
  src/Avalonia.Controls/TextBlock.cs
  tests/Avalonia.Controls.UnitTests/TextBlockTests.cs
Labels: bug, regression, backport-candidate-11.1.x, backport-candidate-11.2.x
