Repository AvaloniaUI/Avalonia, pull requests merged in 2024-06, with the labels that each got.

#15828 Implementing IFormattable on KeyGesture
  src/Android/Avalonia.Android/AndroidPlatform.cs
  src/Avalonia.Base/Input/KeyGesture.cs
  src/Avalonia.Base/Input/Platform/KeyGestureFormatInfo.cs
  src/Avalonia.Controls/Converters/PlatformKeyGestureConverter.cs
  src/Avalonia.Native/AvaloniaNativePlatform.cs
  src/Avalonia.X11/X11Platform.cs
  src/Browser/Avalonia.Browser/WindowingPlatform.cs
  src/Headless/Avalonia.Headless/AvaloniaHeadlessPlatform.cs
  src/Linux/Avalonia.LinuxFramebuffer/LinuxFramebufferPlatform.cs
  src/Tizen/Avalonia.Tizen/TizenPlatform.cs
  src/Windows/Avalonia.Win32/Win32Platform.cs
  src/iOS/Avalonia.iOS/Platform.cs
Labels: enhancement, api

#15907 [Win] Fix composition on focus change
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
Labels: backport-candidate-11.0.x, backport-candidate-11.1.x

#15910 Use the owner window's screen as the constraint.
  src/Avalonia.Controls/Window.cs
Labels: bug, backport-candidate-11.0.x, backport-candidate-11.1.x

#15815 More trimming fixes, enable analyzers unconditionally
  build/TrimmingEnable.props
  src/Avalonia.Base/Data/Core/Plugins/BindingPlugins.cs
  src/Avalonia.Base/Data/Core/TargetTypeConverter.cs
  src/Avalonia.Base/Diagnostics/TrimmingMessages.cs
  src/Avalonia.Base/Rendering/Composition/Expressions/Expression.cs
  src/Browser/Avalonia.Browser/Rendering/RenderWorker.cs
  src/Windows/Avalonia.Win32/WinRT/WinRTInspectable.cs
Labels: bug, area-trimming-aot, backport-candidate-11.1.x

#15274 feat: Every RoutedEvent should be usable as Attached Event
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlCompiler.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlTransformRoutedEvent.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Avalonia.Markup.Xaml.UnitTests.csproj
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/EventTests.cs
Labels: enhancement, area-xaml

#15929 Gracefully fall back to the next storage provider
  src/Avalonia.Base/Platform/Storage/FallbackStorageProvider.cs
  src/Avalonia.Dialogs/Avalonia.Dialogs.csproj
  src/Avalonia.X11/NativeDialogs/CompositeStorageProvider.cs
  src/Avalonia.X11/X11Window.cs
Labels: os-linux, backport-candidate-11.1.x

#15909 DataGrid: expose row index
  samples/ControlCatalog/Pages/DataGridPage.xaml
  samples/ControlCatalog/Pages/DataGridPage.xaml.cs
  src/Avalonia.Controls.DataGrid/DataGridRow.cs
Labels: enhancement, area-datagrid

#15849 Refactor WASM input and dom-callbacks to work with multithreading
  samples/ControlCatalog.Browser/ControlCatalog.Browser.csproj
  samples/ControlCatalog.Browser/EmbedSample.Browser.cs
  samples/ControlCatalog.Browser/Program.cs
  src/Browser/Avalonia.Browser/Avalonia.Browser.csproj
  src/Browser/Avalonia.Browser/AvaloniaView.cs
  src/Browser/Avalonia.Browser/BrowserActivatableLifetime.cs
  src/Browser/Avalonia.Browser/BrowserAppBuilder.cs
  src/Browser/Avalonia.Browser/BrowserInputHandler.cs
  src/Browser/Avalonia.Browser/BrowserInputPane.cs
  src/Browser/Avalonia.Browser/BrowserInsetsManager.cs
  src/Browser/Avalonia.Browser/BrowserPlatformSettings.cs
  src/Browser/Avalonia.Browser/BrowserSystemNavigationManager.cs
  src/Browser/Avalonia.Browser/BrowserTextInputMethod.cs
  src/Browser/Avalonia.Browser/BrowserTopLevelImpl.cs
  src/Browser/Avalonia.Browser/ClipboardImpl.cs
  src/Browser/Avalonia.Browser/Interop/CanvasHelper.cs
  src/Browser/Avalonia.Browser/Interop/DomHelper.cs
  src/Browser/Avalonia.Browser/Interop/InputHelper.cs
  src/Browser/Avalonia.Browser/Interop/NavigationHelper.cs
  src/Browser/Avalonia.Browser/ManualTriggerRenderTimer.cs
  src/Browser/Avalonia.Browser/Rendering/BrowserSurface.cs
  src/Browser/Avalonia.Browser/Rendering/RenderTargetBrowserSurface.cs
  src/Browser/Avalonia.Browser/WindowingPlatform.cs
  src/Browser/Avalonia.Browser/webapp/build.js
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/dom.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/input.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/jsExports.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/rendering/canvasSurface.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/timer.ts
  src/Browser/Avalonia.Browser/webapp/tsconfig.json
Labels: enhancement, wont-backport, os-browser

#15936 Implemented VulkanDevice.Dispose
  src/Avalonia.Vulkan/Interop/VulkanDevice.Create.cs
  src/Avalonia.Vulkan/Interop/VulkanDevice.cs
  src/Avalonia.Vulkan/UnmanagedInterop/VulkanInstanceApi.cs
Labels: bug, area-rendering, backport-candidate-11.1.x

#15952 [X11] Ensure XSync before calling CreateNativeControlCore
  src/Avalonia.X11/X11NativeControlHost.cs
Labels: bug, area-x11, backport-candidate-11.1.x

#15931 Fix gesture event names
  src/Avalonia.Base/Input/Gestures.cs
Labels: bug

#15997 Fixed UIA pattern matching for IExpandCollapseProvider.
  src/Windows/Avalonia.Win32/Automation/AutomationNode.cs
Labels: bug, backport-candidate-11.0.x, backport-candidate-11.1.x

#15998 Fixed memory leak in Switch class
  src/Avalonia.Base/Reactive/Operators/Switch.cs
Labels: bug, backport-candidate-11.0.x, backport-candidate-11.1.x

#16019 Fix some issues with strokeless geometry segments
  src/Avalonia.Base/Media/PolyLineSegment.cs
  src/Skia/Avalonia.Skia/CombinedGeometryImpl.cs
  src/Skia/Avalonia.Skia/GeometryImpl.cs
  src/Skia/Avalonia.Skia/StreamGeometryImpl.cs
  tests/Avalonia.RenderTests.WpfCompare/CrossUI.Wpf.cs
  tests/Avalonia.RenderTests/CrossTests/CrossGeometryTests.cs
  tests/Avalonia.RenderTests/CrossUI/CrossUI.Avalonia.cs
  tests/Avalonia.RenderTests/CrossUI/CrossUI.cs
  tests/Avalonia.Skia.UnitTests/CombinedGeometryImplTests.cs
  tests/TestFiles/CrossTests/Media/Geometry/Should_Render_PolyLineSegment_With_Strokeless_Lines.wpf.png
Labels: bug, backport-candidate-11.1.x

#16005 Fix #15955
  src/Avalonia.Controls/VirtualizingStackPanel.cs
Labels: bug, backport-candidate-11.1.x

#15848 [Text] Fix glyph offsets
  src/Skia/Avalonia.Skia/TextShaperImpl.cs
  src/Windows/Avalonia.Direct2D1/Media/TextShaperImpl.cs
Labels: backport-candidate-11.0.x, backport-candidate-11.1.x

#16035 Improved: D3D11 Adapter Creation Speed by Manually Selecting Hardware Type
  src/Avalonia.OpenGL/OpenGlException.cs
  src/Windows/Avalonia.Win32/OpenGl/Angle/AngleWin32EglDisplay.cs
Labels: enhancement, area-perf, area-rendering

#16028 Convert IAvaloniaXamlIlParentStackProvider to eager one if needed
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlLanguage.cs
  src/Markup/Avalonia.Markup.Xaml/Avalonia.Markup.Xaml.csproj
  src/Markup/Avalonia.Markup.Xaml/XamlIl/Runtime/XamlIlParentStackProviderWrapper.cs
  src/Markup/Avalonia.Markup.Xaml/XamlIl/Runtime/XamlIlRuntimeHelpers.cs
Labels: bug, area-xaml, backport-candidate-11.1.x

#16058 Fix headless window transparency
  src/Headless/Avalonia.Headless/HeadlessWindowImpl.cs
Labels: bug, area-headless, backport-candidate-11.1.x

#16053 [Text] Use CultureInfo.Name instead of ISOLanguageName for character matching
  src/Skia/Avalonia.Skia/FontManagerImpl.cs
Labels: area-textprocessing, backport-candidate-11.0.x, backport-candidate-11.1.x

#15932 Avalonia.Native TopLevel embedding
  Avalonia.sln
  Avalonia.sln.DotSettings
  native/Avalonia.Native/src/OSX/Avalonia.Native.OSX.xcodeproj/project.pbxproj
  native/Avalonia.Native/src/OSX/Avalonia.Native.OSX.xcodeproj/xcshareddata/xcschemes/Avalonia.Native.OSX.xcscheme
  native/Avalonia.Native/src/OSX/AvnView.h
  native/Avalonia.Native/src/OSX/AvnView.mm
  native/Avalonia.Native/src/OSX/AvnWindow.mm
  native/Avalonia.Native/src/OSX/INSWindowHolder.h
  native/Avalonia.Native/src/OSX/PopupImpl.h
  native/Avalonia.Native/src/OSX/PopupImpl.mm
  native/Avalonia.Native/src/OSX/TopLevelImpl.h
  native/Avalonia.Native/src/OSX/TopLevelImpl.mm
  native/Avalonia.Native/src/OSX/WindowBaseImpl.h
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
  native/Avalonia.Native/src/OSX/WindowImpl.h
  native/Avalonia.Native/src/OSX/WindowImpl.mm
  native/Avalonia.Native/src/OSX/automation.mm
  native/Avalonia.Native/src/OSX/common.h
  native/Avalonia.Native/src/OSX/main.mm
  nukebuild/_build.csproj.DotSettings
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
  src/Android/Avalonia.Android/Stubs.cs
  src/Avalonia.Controls/Embedding/EmbeddableControlRoot.cs
  src/Avalonia.Controls/Embedding/Offscreen/OffscreenTopLevelImpl.cs
  src/Avalonia.Controls/Platform/ITopLevelImpl.cs
  src/Avalonia.Controls/Platform/IWindowBaseImpl.cs
  src/Avalonia.Controls/Platform/IWindowingPlatform.cs
  src/Avalonia.Controls/Platform/PlatformManager.cs
  src/Avalonia.Controls/Primitives/PopupPositioning/ManagedPopupPositionerPopupImplHelper.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.Controls/WindowBase.cs
  src/Avalonia.DesignerSupport/Remote/PreviewerWindowingPlatform.cs
  src/Avalonia.Native/AvaloniaNativeGlPlatformGraphics.cs
  src/Avalonia.Native/AvaloniaNativePlatform.cs
  src/Avalonia.Native/AvaloniaNativeTextInputMethod.cs
  src/Avalonia.Native/DeferredFramebuffer.cs
  src/Avalonia.Native/EmbeddableTopLevelImpl.cs
  src/Avalonia.Native/Metal.cs
  src/Avalonia.Native/PopupImpl.cs
  src/Avalonia.Native/SystemDialogs.cs
  src/Avalonia.Native/TopLevelImpl.cs
  src/Avalonia.Native/WindowImpl.cs
  src/Avalonia.Native/WindowImplBase.cs
  src/Avalonia.Native/avn.idl
  src/Avalonia.X11/X11Platform.cs
  src/Browser/Avalonia.Browser/BrowserTopLevelImpl.cs
  src/Browser/Avalonia.Browser/WindowingPlatform.cs
  src/Headless/Avalonia.Headless/AvaloniaHeadlessPlatform.cs
  src/Linux/Avalonia.LinuxFramebuffer/FramebufferToplevelImpl.cs
  src/Tizen/Avalonia.Tizen/Stubs.cs
  src/Tizen/Avalonia.Tizen/TopLevelImpl.cs
  src/Windows/Avalonia.Win32/Automation/RootAutomationNode.cs
  src/Windows/Avalonia.Win32/PopupImpl.cs
  src/Windows/Avalonia.Win32/ScreenImpl.cs
  src/Windows/Avalonia.Win32/Win32Platform.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
  src/iOS/Avalonia.iOS/AvaloniaView.cs
  src/iOS/Avalonia.iOS/Stubs.cs
  tests/Avalonia.UnitTests/CompositorTestServices.cs
  tests/Avalonia.UnitTests/MockWindowingPlatform.cs
Labels: enhancement, api, os-macos

#16102 Fix BindingNotification handling in MultiBinding
  src/Avalonia.Base/Data/Core/UntypedObservableBindingExpression.cs
  tests/Avalonia.Markup.UnitTests/Data/MultiBindingTests.cs
Labels: bug, regression, priority

#15899 macOS: Don't include two windows in a11y tree.
  native/Avalonia.Native/src/OSX/Avalonia.Native.OSX.xcodeproj/project.pbxproj
  native/Avalonia.Native/src/OSX/AvnAccessibility.h
  native/Avalonia.Native/src/OSX/AvnAutomationNode.h
  native/Avalonia.Native/src/OSX/AvnView.h
  native/Avalonia.Native/src/OSX/AvnView.mm
  native/Avalonia.Native/src/OSX/AvnWindow.mm
  native/Avalonia.Native/src/OSX/WindowInterfaces.h
  native/Avalonia.Native/src/OSX/WindowProtocol.h
  native/Avalonia.Native/src/OSX/automation.h
  native/Avalonia.Native/src/OSX/automation.mm
  tests/Avalonia.IntegrationTests.Appium/WindowTests.cs
  tests/Avalonia.IntegrationTests.Appium/WindowTests_MacOS.cs
Labels: bug

#16064 Fix HorizontalHeadTable usage
  src/Avalonia.Base/Media/Fonts/Tables/HorizontalHeadTable.cs
  src/Skia/Avalonia.Skia/GlyphTypefaceImpl.cs
Labels: bug, backport-candidate-11.1.x

#16109 Fix compiled binding indexer always forcing integer boxing
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/XamlIlClrPropertyInfoHelper.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/CompiledBindingExtensionTests.cs
Labels: bug, area-xaml, backport-candidate-11.0.x, backport-candidate-11.1.x, area-bindings

#15706 Respect global packages folder in BuildToNuGetCache
  nukebuild/Build.cs
Labels: area-infrastructure

#15855 Remove from logical children and clear item container on reset
  src/Avalonia.Controls/Presenters/PanelContainerGenerator.cs
  tests/Avalonia.Controls.UnitTests/ItemsControlTests.cs
Labels: bug, backport-candidate-11.1.x

#16119 DBus init and usage fixes
  src/Avalonia.FreeDesktop/DBusHelper.cs
  src/Avalonia.FreeDesktop/DBusIme/X11DBusImeHelper.cs
  src/Avalonia.FreeDesktop/DBusMenuExporter.cs
  src/Avalonia.FreeDesktop/DBusPlatformSettings.cs
  src/Avalonia.FreeDesktop/DBusSystemDialog.cs
  src/Avalonia.FreeDesktop/DBusTrayIconImpl.cs
  src/Avalonia.X11/X11Platform.cs
Labels: bug, os-linux

#15770 Don't show text selector when no text is ready
  src/Avalonia.Controls/Primitives/TextSelectionCanvas.cs
  src/Avalonia.Controls/Primitives/TextSelectionHandle.cs
Labels: bug, backport-candidate-11.1.x

#15251 Notify window on mouseEntered (mac only)
  native/Avalonia.Native/src/OSX/AvnView.mm
Labels: bug, os-macos

#16122 Fix `ICommand` bindings in style setters
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/XamlIlBindingPathHelper.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/CompiledBindingExtensionTests.cs
Labels: bug, regression, priority

#16101 Fix negation of null values.
  src/Avalonia.Base/Data/BindingNotification.cs
  src/Avalonia.Base/Data/Core/BindingExpression.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/ArrayIndexerNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/AvaloniaPropertyAccessorNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/CollectionNodeBase.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/DataContextNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/ExpressionNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/FuncTransformNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/LogicalAncestorElementNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/LogicalNotNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/MethodCommandNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/NamedElementNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/ParentDataContextNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/PropertyAccessorNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/Reflection/DynamicPluginPropertyAccessorNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/Reflection/DynamicPluginStreamNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/Reflection/ReflectionIndexerNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/Reflection/ReflectionTypeCastNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/StreamNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/TemplatedParentNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/VisualAncestorElementNode.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/BindingTests.cs
Labels: bug, regression, priority

#16134 Update Appium tests readme.md
  tests/Avalonia.IntegrationTests.Appium/readme.md
Labels: area-infrastructure

#15493 New ToolTipClosing, ToolTipOpening attached events and ToolTip.Opened, ToolTip.Closed
  samples/ControlCatalog/Pages/ToolTipPage.xaml
  samples/ControlCatalog/Pages/ToolTipPage.xaml.cs
  src/Avalonia.Controls/ToolTip.cs
  src/Avalonia.Controls/ToolTipService.cs
  tests/Avalonia.Controls.UnitTests/ToolTipTests.cs
Labels: api, backport-candidate-11.1.x

#16120 [Text] Fix some text layout issues with ligatures that are being formed
  src/Avalonia.Base/Media/GlyphRun.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextLayoutTests.cs
Labels: backport-candidate-11.0.x, backport-candidate-11.1.x

#16135 [Text] Use GetBackspaceCaretCharacterHit for backspace delete handling
  src/Avalonia.Controls/TextBox.cs
Labels: backport-candidate-11.1.x

#16143 win32: Fix edge-case bug with DPI scaling
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: bug, os-windows

#16148 Patch Win32.TrayIconImpl DPI check for Win7/8
  src/Windows/Avalonia.Win32/TrayIconImpl.cs
Labels: bug, os-windows, backport-candidate-11.1.x

#16024 Fix TrayIcon menu crash
  samples/IntegrationTestApp/App.axaml
  samples/IntegrationTestApp/App.axaml.cs
  samples/IntegrationTestApp/IntegrationTestApp.csproj
  src/Avalonia.Controls/NativeMenuItem.cs
Labels: bug

#16061 Set isDirectory:true explicitly to help [NSURL fileURLWithPath] method
  native/Avalonia.Native/src/OSX/SystemDialogs.mm
Labels: bug, os-macos, backport-candidate-11.1.x

#15561 [Windows] WindowDecorations related integration tests
  samples/IntegrationTestApp/IntegrationTestApp.csproj
  samples/IntegrationTestApp/MainWindow.axaml
  samples/IntegrationTestApp/MainWindow.axaml.cs
  samples/IntegrationTestApp/ShowWindowTest.axaml
  samples/IntegrationTestApp/ShowWindowTest.axaml.cs
  samples/IntegrationTestApp/TopmostWindowTest.axaml.cs
  src/Avalonia.Controls/Automation/Peers/TitleBarAutomationPeer.cs
  src/Avalonia.Controls/Chrome/TitleBar.cs
  tests/Avalonia.IntegrationTests.Appium/AppiumDriverEx.cs
  tests/Avalonia.IntegrationTests.Appium/CollectionDefinitions.cs
  tests/Avalonia.IntegrationTests.Appium/ElementExtensions.cs
  tests/Avalonia.IntegrationTests.Appium/WindowDecorationsTests.cs
  tests/Avalonia.IntegrationTests.Appium/WindowTests.cs
  tests/Avalonia.IntegrationTests.Appium/WindowTests_MacOS.cs
Labels: enhancement, os-macos, os-windows, backport-candidate-11.1.x

#16150 Make bindings react to PropertyChanged even if property hasn't changed
  src/Avalonia.Base/Data/Core/ExpressionNodes/ExpressionNode.cs
  tests/Avalonia.Base.UnitTests/Data/Core/BindingExpressionTests.Property.cs
  tests/Avalonia.Base.UnitTests/Data/Core/BindingExpressionTests.cs
Labels: regression, priority

#16159 Toplevel - Fix system theme not being applied at launch on some platforms
  src/Android/Avalonia.Android/Platform/AndroidInsetsManager.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.Controls/WindowBase.cs
Labels: bug, os-android, backport-candidate-11.1.x

#16110 Fix Linux X11 Atoms lost: Before the window was mapped, only the first atom was set.
  src/Avalonia.X11/X11Window.cs
Labels: os-linux, area-x11, backport-candidate-11.1.x
