Repository AvaloniaUI/Avalonia, pull requests merged in 2024-05, with the labels that each got.

#15578 Update TargetFrameworks in Avalonia.Vulkan.csproj
  src/Avalonia.Vulkan/Avalonia.Vulkan.csproj
Labels: backport-candidate-11.1.x

#15509 CompileAvaloniaXamlTask - handle no-pdb compilations
  src/Avalonia.Build.Tasks/CompileAvaloniaXamlTask.cs
Labels: bug, backport-candidate-11.0.x, backport-candidate-11.1.x

#15312 Fix tooltips not closing when the pointer leaves the window
  src/Avalonia.Controls/ToolTipService.cs
  tests/Avalonia.Controls.UnitTests/ToolTipTests.cs
Labels: bug, regression, backport-candidate-11.1.x

#15594 fix(Themes.Fluent): MenuItem Chevron position
  src/Avalonia.Themes.Fluent/Controls/MenuItem.xaml
Labels: backport-candidate-11.1.x

#15601 Fix android launcher return values
  src/Android/Avalonia.Android/Platform/AndroidLauncher.cs
  src/Avalonia.Controls/Platform/IInputPane.cs
Labels: bug, backport-candidate-11.1.x

#15606 [TextBox] fix double click on TextBox cannot select word on touch device
  src/Avalonia.Controls/TextBox.cs
Labels: backport-candidate-11.1.x

#15596 More Tooltip edge case fixes
  src/Avalonia.Controls/IToolTipService.cs
  src/Avalonia.Controls/ToolTipService.cs
  src/Avalonia.Controls/TopLevel.cs
Labels: backport-candidate-11.1.x

#15659 Suspend selection updates in TextBoxTextInputMethodClient until all changes are completed
  src/Android/Avalonia.Android/AndroidInputMethod.cs
  src/Avalonia.Controls/TextBox.cs
  src/Avalonia.Controls/TextBoxTextInputMethodClient.cs
Labels: bug, area-textprocessing, backport-candidate-11.1.x

#15517 Update popups and flyouts to properly support OverlayDismissEventPassThrough
  src/Avalonia.Controls/Button.cs
  src/Avalonia.Controls/CalendarDatePicker/CalendarDatePicker.cs
  src/Avalonia.Controls/ComboBox.cs
  src/Avalonia.Controls/Flyouts/PopupFlyoutBase.cs
  src/Avalonia.Controls/Primitives/Popup.cs
  src/Avalonia.Controls/SplitButton/SplitButton.cs
  tests/Avalonia.Controls.UnitTests/ComboBoxTests.cs
  tests/Avalonia.Controls.UnitTests/FlyoutTests.cs
Labels: backport-candidate-11.1.x

#13802 Improve DevTools previewer of setter values by including all value priorities
  api/Avalonia.nupkg.xml
  src/Avalonia.Base/Diagnostics/AppliedStyle.cs
  src/Avalonia.Base/Diagnostics/IValueFrameDiagnostic.cs
  src/Avalonia.Base/Diagnostics/LocalValueFrameDiagnostic.cs
  src/Avalonia.Base/Diagnostics/StyleDiagnostics.cs
  src/Avalonia.Base/Diagnostics/StyleValueFrameDiagnostic.cs
  src/Avalonia.Base/Diagnostics/StyledElementExtensions.cs
  src/Avalonia.Base/Diagnostics/ValueFrameDiagnostic.cs
  src/Avalonia.Base/Diagnostics/ValueStoreDiagnostic.cs
  src/Avalonia.Base/PropertyStore/FramePriority.cs
  src/Avalonia.Base/PropertyStore/ValueStore.cs
  src/Avalonia.Base/StyledElement.cs
  src/Avalonia.Diagnostics/Diagnostics/Controls/BrushEditor.axaml.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ControlDetailsViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/MainViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/StyleViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ValueFrameViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/ControlDetailsView.xaml
Labels: enhancement, breaking-change, area-dev-tools

#15670 Fixed DeferredContent parents order
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlLanguage.cs
  src/Markup/Avalonia.Markup.Xaml/EagerParentStackEnumerator.cs
  src/Markup/Avalonia.Markup.Xaml/XamlIl/Runtime/IAvaloniaXamlIlParentStackProvider.cs
  src/Markup/Avalonia.Markup.Xaml/XamlIl/Runtime/XamlIlRuntimeHelpers.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/StaticResourceExtensionTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/ParentStackProviderTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/StyleIncludeTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/XamlIlTests.cs
Labels: area-xaml, backport-candidate-11.1.x

#15686 X11Window should probably ignore X11 grab focus events
  src/Avalonia.X11/X11Window.cs
Labels: bug, os-linux

#15676 Hack to enable subpixel rendering by default.
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionTarget.cs
Labels: bug, backport-candidate-11.1.x

#15701 Implement missing browser stream methods
  samples/ControlCatalog/Pages/DialogsPage.xaml.cs
  src/Browser/Avalonia.Browser/Interop/StreamHelper.cs
  src/Browser/Avalonia.Browser/Storage/BlobReadableStream.cs
  src/Browser/Avalonia.Browser/Storage/WriteableStream.cs
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/stream.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/surfaces/softwareSurface.ts
Labels: bug, os-browser, backport-candidate-11.1.x

#15482 Fix nth child selector in data grid header
  src/Avalonia.Controls.DataGrid/DataGridColumnCollection.cs
  src/Avalonia.Controls.DataGrid/Primitives/DataGridCellsPresenter.cs
  src/Avalonia.Controls.DataGrid/Primitives/DataGridColumnHeadersPresenter.cs
Labels: bug, area-datagrid

#15716 Fixes spurious DataGrid data validation error
  src/Avalonia.Base/Data/Core/BindingExpression.cs
  src/Avalonia.Base/Data/Core/UntypedBindingExpressionBase.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindingExtension.cs
  src/Markup/Avalonia.Markup/Data/Binding.cs
  tests/Avalonia.Base.UnitTests/Data/Core/BindingExpressionTests.Obsolete.cs
  tests/Avalonia.Base.UnitTests/Data/Core/BindingExpressionTests.cs
Labels: bug, backport-candidate-11.1.x

#15700 Add HotKeys Page to DevTools
  src/Avalonia.Diagnostics/Diagnostics/DevToolsOptions.cs
  src/Avalonia.Diagnostics/Diagnostics/HotKeyConfiguration.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/HotKeyPageViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/MainViewModel.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/HotKeyPageView.axaml
  src/Avalonia.Diagnostics/Diagnostics/Views/HotKeyPageView.axaml.cs
  src/Avalonia.Diagnostics/Diagnostics/Views/MainView.xaml
  src/Avalonia.Diagnostics/Diagnostics/Views/MainWindow.xaml
  src/Avalonia.Diagnostics/Diagnostics/Views/MainWindow.xaml.cs
Labels: enhancement, area-dev-tools, backport-candidate-11.1.x

#15710 Fix DrmOutputOptions.ConnectorTypeId naming
  src/Linux/Avalonia.LinuxFramebuffer/DrmOutputOptions.cs
  src/Linux/Avalonia.LinuxFramebuffer/Output/DrmBindings.cs
  src/Linux/Avalonia.LinuxFramebuffer/Output/DrmOutput.cs
Labels: api, backport-candidate-11.1.x

#15709 Refactored WASM rendering, added MT support for dispatcher
  samples/ControlCatalog.Browser/ControlCatalog.Browser.csproj
  src/Avalonia.Base/Platform/IPlatformGpu.cs
  src/Avalonia.Base/Platform/Internal/UnmanagedBlob.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionTarget.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositor.cs
  src/Avalonia.Base/Rendering/PlatformRenderInterfaceContextManager.cs
  src/Browser/Avalonia.Browser/BrowserAppBuilder.cs
  src/Browser/Avalonia.Browser/BrowserDispatcherImpl.cs
  src/Browser/Avalonia.Browser/BrowserTopLevelImpl.cs
  src/Browser/Avalonia.Browser/Interop/AvaloniaModule.cs
  src/Browser/Avalonia.Browser/Interop/CanvasHelper.cs
  src/Browser/Avalonia.Browser/Interop/TimerHelper.cs
  src/Browser/Avalonia.Browser/Rendering/BrowserCompositor.cs
  src/Browser/Avalonia.Browser/Rendering/BrowserGlSurface.cs
  src/Browser/Avalonia.Browser/Rendering/BrowserRasterSurface.cs
  src/Browser/Avalonia.Browser/Rendering/BrowserRenderTimer.cs
  src/Browser/Avalonia.Browser/Rendering/BrowserSharedRenderLoop.cs
  src/Browser/Avalonia.Browser/Rendering/BrowserSoftwareRenderTarget.cs
  src/Browser/Avalonia.Browser/Rendering/BrowserSurface.cs
  src/Browser/Avalonia.Browser/Rendering/BrowserWebGlRenderTarget.cs
  src/Browser/Avalonia.Browser/Rendering/RenderTargetBrowserSurface.cs
  src/Browser/Avalonia.Browser/Rendering/RenderWorker.cs
  src/Browser/Avalonia.Browser/Rendering/WebRenderTarget.cs
  src/Browser/Avalonia.Browser/Skia/BrowserSkiaGpu.cs
  src/Browser/Avalonia.Browser/Skia/BrowserSkiaGpuRenderSession.cs
  src/Browser/Avalonia.Browser/Skia/BrowserSkiaGpuRenderTarget.cs
  src/Browser/Avalonia.Browser/WindowingPlatform.cs
  src/Browser/Avalonia.Browser/build/Avalonia.Browser.targets
  src/Browser/Avalonia.Browser/webapp/modules/avalonia.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/jsExports.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/rendering/canvasSurface.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/rendering/renderingMode.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/rendering/resizeHandler.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/rendering/softwareRenderTarget.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/rendering/webGlRenderTarget.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/rendering/webRenderTarget.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/rendering/webRenderTargetRegistry.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/surfaces/htmlSurfaceBase.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/surfaces/softwareSurface.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/surfaces/surfaceBase.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/surfaces/surfaceFactory.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/surfaces/webGlSurface.ts
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/timer.ts
  src/Browser/Avalonia.Browser/webapp/package-lock.json
  src/Browser/Avalonia.Browser/webapp/package.json
  src/Skia/Avalonia.Skia/Gpu/OpenGl/GlSkiaGpu.cs
  src/Skia/Avalonia.Skia/Gpu/OpenGl/IGlSkiaSpecificOptionsFeature.cs
Labels: enhancement, area-rendering, os-browser

#15722 Allow nested BindingNotifications.
  src/Avalonia.Base/Data/BindingNotification.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/ExpressionNode.cs
  tests/Avalonia.Base.UnitTests/Data/Core/BindingExpressionTests.DataValidation.cs
Labels: bug, backport-candidate-11.1.x

#15742 [X11] Blacklist SVGA3D gpu driver
  src/Avalonia.X11/X11Platform.cs
Labels: area-rendering, area-x11, backport-candidate-11.0.x, backport-candidate-11.1.x

#15734 Fix for #7284
  src/Windows/Avalonia.Win32/FramebufferManager.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: bug, os-windows, backport-candidate-11.1.x

#15747 Warning fixes: spring wave
  build/Base.props
  build/ImageSharp.props
  build/SampleApp.props
  samples/ControlCatalog.Desktop/Program.cs
  samples/ControlCatalog/Pages/OpenGl/OpenGlContent.cs
  samples/ControlCatalog/Pages/OpenGl/OpenGlLeasePage.xaml.cs
  samples/ControlCatalog/Pages/OpenGlPage.xaml.cs
  samples/GpuInterop/VulkanDemo/VulkanImage.cs
  samples/UnloadableAssemblyLoadContext/UnloadableAssemblyLoadContext/AssemblyLoadContextH.cs
  samples/UnloadableAssemblyLoadContext/UnloadableAssemblyLoadContext/MainWindow.axaml.cs
  samples/UnloadableAssemblyLoadContext/UnloadableAssemblyLoadContext/PlugTool.cs
  samples/UnloadableAssemblyLoadContext/UnloadableAssemblyLoadContext/UnloadableAssemblyLoadContext.csproj
  samples/UnloadableAssemblyLoadContext/UnloadableAssemblyLoadContextPlug/Program.cs
  samples/UnloadableAssemblyLoadContext/UnloadableAssemblyLoadContextPlug/Window1.axaml
  samples/UnloadableAssemblyLoadContext/UnloadableAssemblyLoadContextPlug/Window1.axaml.cs
  src/Avalonia.Base/Compatibility/TrimmingAttributes.cs
  src/Avalonia.Base/Platform/RenderTargetProperties.cs
  src/Avalonia.Base/PropertyStore/ValueStore.cs
  src/Avalonia.Base/Rendering/Composition/Server/DrawingContextProxy.cs
  src/Avalonia.FreeDesktop/DBusTrayIconImpl.cs
  src/Avalonia.Vulkan/Avalonia.Vulkan.csproj
  src/Avalonia.Vulkan/VulkanImageInfo.cs
  src/Avalonia.X11/Vulkan/VulkanSupport.cs
  src/Avalonia.X11/X11FramebufferSurface.cs
  src/Browser/Avalonia.Browser/Rendering/RenderWorker.cs
  src/Browser/Avalonia.Browser/build/Avalonia.Browser.targets
  src/Linux/Avalonia.LinuxFramebuffer/Input/LibInput/LibInputBackend.cs
  src/Linux/Avalonia.LinuxFramebuffer/NativeUnsafeMethods.cs
  src/Linux/Avalonia.LinuxFramebuffer/Output/DrmOutput.cs
  src/Linux/Avalonia.LinuxFramebuffer/Output/FbDevBackBuffer.cs
  src/Linux/Avalonia.LinuxFramebuffer/Output/FbDevOutputOptions.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/IncludeXamlIlSre.props
  src/tools/Avalonia.Designer.HostApp/Avalonia.Designer.HostApp.csproj
  tests/Avalonia.RenderTests.WpfCompare/CrossTestBase.cs
  tests/Avalonia.RenderTests.WpfCompare/CrossUI.Wpf.cs
  tests/Avalonia.RenderTests/CrossTests/CrossGeometryTests.cs
  tests/Avalonia.RenderTests/CrossUI/CrossUI.Avalonia.cs
  tests/Avalonia.RenderTests/CrossUI/CrossUI.cs
  tests/Avalonia.Skia.RenderTests/CrossTestBase.cs
Labels: enhancement

#15703 Try to normalize family names for embedded fonts
  src/Avalonia.Base/Media/FontManager.cs
  src/Avalonia.Base/Media/FontWeight.cs
  src/Avalonia.Base/Media/Fonts/EmbeddedFontCollection.cs
  src/Avalonia.Base/Media/Fonts/FontCollectionBase.cs
  src/Avalonia.Base/Media/Fonts/SystemFontCollection.cs
  src/Skia/Avalonia.Skia/GlyphTypefaceImpl.cs
  tests/Avalonia.Skia.UnitTests/Media/EmbeddedFontCollectionTests.cs
  tests/Avalonia.Skia.UnitTests/Media/FontManagerTests.cs
Labels: backport-candidate-11.0.x, backport-candidate-11.1.x

#15810 Fix Android app randomly hangs
  src/Android/Avalonia.Android/AvaloniaActivity.cs
  src/Android/Avalonia.Android/AvaloniaView.cs
Labels: bug, os-android, backport-candidate-11.1.x

#15603 [Android] [TextBox] fix a bug which cause cannot call out the soft keyboard again after closing it
  src/Avalonia.Base/Input/TextInput/TextInputMethodClient.cs
  src/Avalonia.Controls/TextBox.cs
  src/Avalonia.Controls/TextBoxTextInputMethodClient.cs
Labels: bug, os-android, backport-candidate-11.1.x

#15827 Fix OnColorValuesChanged not executed on the UI thread
  src/Avalonia.FreeDesktop/DBusPlatformSettings.cs
Labels: bug, os-linux, backport-candidate-11.0.x, backport-candidate-11.1.x

#15839 Translate glyphRun bounds by the baseline origin
  src/Avalonia.Base/Media/GlyphRun.cs
  src/Skia/Avalonia.Skia/GlyphRunImpl.cs
Labels: backport-candidate-11.0.x, backport-candidate-11.1.x

#15819 FontManager adjustments
  src/Avalonia.Base/Media/FontManager.cs
  src/Avalonia.Base/Media/Fonts/EmbeddedFontCollection.cs
  src/Avalonia.Base/Media/Fonts/FontCollectionBase.cs
  src/Avalonia.Base/Media/Fonts/SystemFontCollection.cs
  src/Headless/Avalonia.Headless/HeadlessPlatformStubs.cs
  tests/Avalonia.Base.UnitTests/Media/GlyphRunTests.cs
  tests/Avalonia.Skia.UnitTests/Media/EmbeddedFontCollectionTests.cs
  tests/Avalonia.Skia.UnitTests/Media/FontCollectionTests.cs
  tests/Avalonia.Skia.UnitTests/Media/FontManagerTests.cs
Labels: backport-candidate-11.0.x, backport-candidate-11.1.x

#15852 Handle case when TaskBarList could not be created
  src/Windows/Avalonia.Win32/Interop/TaskBarList.cs
Labels: bug, os-windows, backport-candidate-11.0.x, backport-candidate-11.1.x

#15838 Restore 0.10.x behavior for re-creating visual brush content on property change
  src/Avalonia.Base/Media/Brush.cs
  src/Avalonia.Base/Media/DrawingBrush.cs
  src/Avalonia.Base/Media/VisualBrush.cs
  src/Avalonia.Base/Rendering/Composition/Brushes/ServerSimpleContentBrush.cs
  src/Avalonia.Base/Rendering/Composition/Drawing/CompositionRenderDataSceneBrushContent.cs
  src/Avalonia.Base/Utilities/SmallDictionary.cs
Labels: bug, area-rendering, backport-candidate-11.0.x, backport-candidate-11.1.x
