Repository AvaloniaUI/Avalonia, pull requests merged in 2024-07, with the labels that each got.

#16051 Restores WS_CHILD style for Embedded Windows
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: bug, os-windows, backport-candidate-11.1.x

#16183 Fix typos
  src/Android/Avalonia.Android/SingleViewLifetime.cs
  src/Avalonia.Desktop/AppBuilderDesktopExtensions.cs
Labels: enhancement

#16182 Merge same case branches
  src/Avalonia.Base/AvaloniaObject.cs
Labels: enhancement

#16185 Reset scroller valuators on XI2Manager.cs
  src/Avalonia.X11/XI2Manager.cs
Labels: bug, area-x11, backport-candidate-11.1.x, backport-candidate-0.10.x

#16201 Android - Add workaround for android 11 ime insets being weird
  src/Android/Avalonia.Android/Platform/AndroidInsetsManager.cs
Labels: bug, os-android, backport-candidate-11.1.x

#16205 [macOS][X11] Release mouse capture when dialog shown
  samples/IntegrationTestApp/DelegateCommand.cs
  samples/IntegrationTestApp/MainWindow.axaml
  samples/IntegrationTestApp/MainWindow.axaml.cs
  src/Avalonia.Base/Input/MouseDevice.cs
  src/Avalonia.Base/Input/TouchDevice.cs
  src/Avalonia.Native/WindowImpl.cs
  src/Avalonia.X11/X11Window.cs
  tests/Avalonia.IntegrationTests.Appium/PointerTests.cs
Labels: bug, os-macos, os-linux, area-x11

#16220 Remove obsolete API usage from `SelectingItemsControl`.
  src/Avalonia.Controls/Primitives/SelectingItemsControl.cs
Labels: enhancement, backport-candidate-11.1.x

#16041 Fix crash in TreeView when removing a node.
  samples/ControlCatalog/ViewModels/TreeViewPageViewModel.cs
Labels: bug

#16079 Adds support for Seconds to TimePicker
  samples/ControlCatalog/Pages/DateTimePickerPage.xaml
  samples/ControlCatalog/Pages/DateTimePickerPage.xaml.cs
  src/Avalonia.Controls/DateTimePickers/DateTimePickerPanel.cs
  src/Avalonia.Controls/DateTimePickers/TimePicker.cs
  src/Avalonia.Controls/DateTimePickers/TimePickerPresenter.cs
  src/Avalonia.Themes.Fluent/Controls/TimePicker.xaml
  src/Avalonia.Themes.Fluent/Strings/InvariantResources.xaml
  src/Avalonia.Themes.Simple/Controls/TimePicker.xaml
  tests/Avalonia.Controls.UnitTests/DatePickerTests.cs
  tests/Avalonia.Controls.UnitTests/TimePickerTests.cs
Labels: enhancement, api

#16214 Implement `BindingOperations.GetBindingExpressionBase`
  src/Avalonia.Base/Data/BindingOperations.cs
  src/Avalonia.Base/PropertyStore/ValueStore.cs
  tests/Avalonia.Base.UnitTests/Data/BindingOperationsTests.cs
Labels: enhancement, backport-candidate-11.1.x

#16258 Fixed a typo
  src/Avalonia.Base/Data/BindingValue.cs
Labels: enhancement

#16140 Fix datagrid performance on attached to tree
  src/Avalonia.Controls.DataGrid/DataGrid.cs
Labels: bug, area-datagrid

#16168 Make VirtualizingStackPanel better handle container size changes
  src/Avalonia.Controls/Utils/RealizedStackElements.cs
  src/Avalonia.Controls/VirtualizingPanel.cs
  src/Avalonia.Controls/VirtualizingStackPanel.cs
  tests/Avalonia.Controls.UnitTests/VirtualizingStackPanelTests.cs
Labels: bug, backport-candidate-11.0.x, backport-candidate-11.1.x

#16154 TrayIcon integration tests
  samples/IntegrationTestApp/App.axaml
  samples/IntegrationTestApp/App.axaml.cs
  samples/IntegrationTestApp/MainWindow.axaml
  samples/IntegrationTestApp/MainWindow.axaml.cs
  src/Windows/Avalonia.Win32/TrayIconImpl.cs
  tests/Avalonia.IntegrationTests.Appium/DefaultAppFixture.cs
  tests/Avalonia.IntegrationTests.Appium/OverlayPopupsAppFixture.cs
  tests/Avalonia.IntegrationTests.Appium/TrayIconTests.cs
Labels: enhancement, os-macos, os-windows, area-accessibility

#16174 Fixed build error: SourceRoot paths are required to end with a slash or backslash
  build/SourceLink.props
Labels: enhancement, area-infrastructure

#16167 Add an overload for ClassicDesktopStyleApplicationLifetime
  src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs
Labels: api

#16244 Set InheritsTransform on ComboBox Popup in Simple theme
  src/Avalonia.Themes.Simple/Controls/ComboBox.xaml
Labels: bug, backport-candidate-11.0.x, backport-candidate-11.1.x

#16265 TrayIcon tests are flacky, disable them
  tests/Avalonia.IntegrationTests.Appium/SliderTests.cs
  tests/Avalonia.IntegrationTests.Appium/TrayIconTests.cs
Labels: area-infrastructure

#16271 Fix launcher on browser
  src/Browser/Avalonia.Browser/BrowserTopLevelImpl.cs
  src/Browser/Avalonia.Browser/Interop/NavigationHelper.cs
Labels: os-browser, backport-candidate-11.1.x

#16054 Enhance SplitPropertyPath to conditionally handle parentheses in prop…
  src/Avalonia.Controls.DataGrid/Utils/ReflectionHelper.cs
  tests/Avalonia.Controls.DataGrid.UnitTests/Utils/ReflectionHelperTests.cs
Labels: bug, area-datagrid

#16296 Disable WinFormsAvaloniaControlHost in design mode
  src/Windows/Avalonia.Win32.Interoperability/WinForms/WinFormsAvaloniaControlHost.cs
Labels: bug, os-windows, backport-candidate-11.1.x

#16303 "About Avalonia" native menu item crashes app when main window is not visible
  src/Avalonia.Native/AvaloniaNativeMenuExporter.cs
Labels: bug, os-macos, backport-candidate-11.1.x

#16305 Remove old API compat baseline files
  src/Avalonia.Base/ApiCompatBaseline.txt
  src/Avalonia.Controls.DataGrid/ApiCompatBaseline.txt
  src/Avalonia.Controls/ApiCompatBaseline.txt
  src/Avalonia.DesignerSupport/ApiCompatBaseline.txt
  src/Avalonia.Dialogs/ApiCompatBaseline.txt
  src/Avalonia.Remote.Protocol/ApiCompatBaseline.txt
  src/Avalonia.Themes.Fluent/ApiCompatBaseline.txt
  src/Avalonia.Themes.Simple/ApiCompatBaseline.txt
  src/Markup/Avalonia.Markup.Xaml/ApiCompatBaseline.txt
  src/Markup/Avalonia.Markup/ApiCompatBaseline.txt
Labels: area-infrastructure

#16276 Fix BaselineAlignment
  src/Avalonia.Base/Media/TextDecoration.cs
  src/Avalonia.Base/Media/TextFormatting/ShapedTextRun.cs
  src/Avalonia.Base/Media/TextFormatting/TextLineImpl.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextLayoutTests.cs
Labels: area-textprocessing, backport-candidate-11.1.x

#15896 fix #15873, prevent FontFamily Property was null and crash the whole application
  src/Avalonia.Base/Media/Typeface.cs
Labels: bug, backport-candidate-11.1.x

#16295 Screens API refactor
  api/Avalonia.nupkg.xml
  native/Avalonia.Native/src/OSX/Screens.mm
  native/Avalonia.Native/src/OSX/TopLevelImpl.h
  native/Avalonia.Native/src/OSX/TopLevelImpl.mm
  native/Avalonia.Native/src/OSX/common.h
  native/Avalonia.Native/src/OSX/main.mm
  native/Avalonia.Native/src/OSX/menu.mm
  samples/ControlCatalog/MainView.xaml
  samples/ControlCatalog/MainView.xaml.cs
  samples/ControlCatalog/Pages/ScreenPage.cs
  samples/IntegrationTestApp/MainWindow.axaml
  samples/IntegrationTestApp/MainWindow.axaml.cs
  src/Avalonia.Base/Platform/PlatformHandle.cs
  src/Avalonia.Controls/Embedding/Offscreen/OffscreenTopLevelImpl.cs
  src/Avalonia.Controls/Platform/IScreenImpl.cs
  src/Avalonia.Controls/Platform/ITopLevelImpl.cs
  src/Avalonia.Controls/Platform/Screen.cs
  src/Avalonia.Controls/Primitives/PopupPositioning/ManagedPopupPositionerPopupImplHelper.cs
  src/Avalonia.Controls/Screens.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.Controls/WindowBase.cs
  src/Avalonia.DesignerSupport/Remote/PreviewerWindowImpl.cs
  src/Avalonia.DesignerSupport/Remote/Stubs.cs
  src/Avalonia.Native/AvaloniaNativePlatform.cs
  src/Avalonia.Native/EmbeddableTopLevelImpl.cs
  src/Avalonia.Native/PopupImpl.cs
  src/Avalonia.Native/ScreenImpl.cs
  src/Avalonia.Native/TopLevelImpl.cs
  src/Avalonia.Native/WindowImpl.cs
  src/Avalonia.Native/WindowImplBase.cs
  src/Avalonia.Native/avn.idl
  src/Avalonia.X11/Screens/X11Screens.cs
  src/Avalonia.X11/X11Window.cs
  src/Browser/Avalonia.Browser/WinStubs.cs
  src/Headless/Avalonia.Headless/HeadlessPlatformStubs.cs
  src/Windows/Avalonia.Win32/Avalonia.Win32.csproj
  src/Windows/Avalonia.Win32/DirectX/DirectXStructs.cs
  src/Windows/Avalonia.Win32/DirectX/DirectXUnmanagedMethods.cs
  src/Windows/Avalonia.Win32/DirectX/DxgiConnection.cs
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/Windows/Avalonia.Win32/NativeMethods.txt
  src/Windows/Avalonia.Win32/PopupImpl.cs
  src/Windows/Avalonia.Win32/ScreenImpl.cs
  src/Windows/Avalonia.Win32/Win32Platform.cs
  src/Windows/Avalonia.Win32/Win32TypeExtensions.cs
  src/Windows/Avalonia.Win32/WinScreen.cs
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
  tests/Avalonia.Controls.UnitTests/ContextMenuTests.cs
  tests/Avalonia.Controls.UnitTests/MenuItemTests.cs
  tests/Avalonia.Controls.UnitTests/Platform/ScreensTests.cs
  tests/Avalonia.Controls.UnitTests/WindowTests.cs
  tests/Avalonia.IntegrationTests.Appium/ScreenTests.cs
  tests/Avalonia.UnitTests/MockWindowingPlatform.cs
Labels: enhancement, api, os-macos, os-windows

#16339 Don't BringIntoViewOnFocusChange in Carousel.
  src/Avalonia.Themes.Fluent/Controls/Carousel.xaml
  src/Avalonia.Themes.Simple/Controls/Carousel.xaml
Labels: bug, backport-candidate-11.1.x

#16310 Use culture identifier instead of CultureInfo in NameTable
  src/Avalonia.Base/Media/Fonts/Tables/Name/NameTable.cs
  src/Avalonia.Base/Media/IGlyphTypeface2.cs
  src/Skia/Avalonia.Skia/GlyphTypefaceImpl.cs
Labels: bug, area-trimming-aot, backport-candidate-11.1.x

#16297 Win32 - Fix window size and position for border only window when maximized through OS means
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
Labels: bug, backport-candidate-11.1.x

#16341 macOS WindowState call on Show crash fix
  src/Avalonia.Native/WindowImpl.cs
Labels: bug, os-macos, backport-candidate-11.1.x

#16157 Fix nunit tests adapter losing async locals
  src/Headless/Avalonia.Headless.NUnit/AvaloniaTestMethodCommand.cs
  src/Headless/Avalonia.Headless/Avalonia.Headless.csproj
  src/Headless/Avalonia.Headless/HeadlessUnitTestSession.cs
  tests/Avalonia.Headless.UnitTests/ThreadingTests.cs
Labels: bug, area-headless, backport-candidate-11.1.x

#16338 Only update selection on focus in TabControl if focus comes from TabItem.
  src/Avalonia.Controls/TabControl.cs
Labels: bug, backport-candidate-11.1.x

#16090 MacOS sandboxing feature
  native/Avalonia.Native/src/OSX/Avalonia.Native.OSX.xcodeproj/project.pbxproj
  native/Avalonia.Native/src/OSX/StorageProvider.mm
  native/Avalonia.Native/src/OSX/common.h
  native/Avalonia.Native/src/OSX/main.mm
  samples/ControlCatalog/Pages/DialogsPage.xaml.cs
  src/Android/Avalonia.Android/Platform/Storage/AndroidStorageItem.cs
  src/Android/Avalonia.Android/Platform/Storage/AndroidStorageProvider.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFile.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFolder.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageItem.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageProvider.cs
  src/Avalonia.Base/Platform/Storage/FileIO/SecurityScopedStream.cs
  src/Avalonia.Base/Platform/Storage/FileIO/StorageBookmarkHelper.cs
  src/Avalonia.Base/Platform/Storage/FileIO/StorageProviderHelpers.cs
  src/Avalonia.Base/Platform/Storage/IStorageBookmarkItem.cs
  src/Avalonia.Base/Platform/Storage/StorageProviderExtensions.cs
  src/Avalonia.Diagnostics/Diagnostics/Conventions.cs
  src/Avalonia.Diagnostics/Diagnostics/Screenshots/FilePickerHandler.cs
  src/Avalonia.Native/AvaloniaNativeApplicationPlatform.cs
  src/Avalonia.Native/AvaloniaNativePlatform.cs
  src/Avalonia.Native/AvaloniaNativePlatformExtensions.cs
  src/Avalonia.Native/ClipboardImpl.cs
  src/Avalonia.Native/StorageItem.cs
  src/Avalonia.Native/StorageProviderApi.cs
  src/Avalonia.Native/StorageProviderImpl.cs
  src/Avalonia.Native/SystemDialogs.cs
  src/Avalonia.Native/TopLevelImpl.cs
  src/Avalonia.Native/avn.idl
  src/Browser/Avalonia.Browser/Storage/BrowserStorageProvider.cs
  src/iOS/Avalonia.iOS/Storage/IOSSecurityScopedStream.cs
  src/iOS/Avalonia.iOS/Storage/IOSStorageItem.cs
  src/iOS/Avalonia.iOS/Storage/IOSStorageProvider.cs
  tests/Avalonia.Base.UnitTests/Utilities/UriExtensionsTests.cs
  tests/Avalonia.Controls.UnitTests/Platform/StorageProviderHelperTests.cs
Labels: enhancement, os-macos, breaking-change

#16354 Fix context menu keyboard selection.
  samples/IntegrationTestApp/MainWindow.axaml
  src/Avalonia.Themes.Fluent/Controls/ContextMenu.xaml
  src/Avalonia.Themes.Simple/Controls/ContextMenu.xaml
  tests/Avalonia.IntegrationTests.Appium/ContextMenuTests.cs
  tests/Avalonia.IntegrationTests.Appium/ElementExtensions.cs
Labels: bug, priority, backport-candidate-11.1.x

#16373 Fix - return (0,0) as size for text selector layer on MeasureOverride
  src/Avalonia.Controls/Primitives/TextSelectorLayer.cs
Labels: bug, backport-candidate-11.1.x

#16434 Compatible with "fcitx5" envrionment variable
  src/Avalonia.FreeDesktop/DBusIme/X11DBusImeHelper.cs
Labels: bug, os-linux, backport-candidate-11.1.x

#16393 [WinRT] Added watchdog for ICompositor5::RequestCommitAsync
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/Windows/Avalonia.Win32/OffscreenParentWindow.cs
  src/Windows/Avalonia.Win32/SimpleWindow.cs
  src/Windows/Avalonia.Win32/WinRT/Composition/WinUiCompositorConnection.cs
Labels: bug, area-rendering, os-windows, backport-candidate-11.1.x

#16427 Fix Avalonia/references generation
  packages/Avalonia/AvaloniaBuildTasks.targets
Labels: bug, priority

#16306 [Text] Fix infinite loop hang on selection of bidi text
  src/Avalonia.Base/Media/TextFormatting/TextLineImpl.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextLineTests.cs
Labels: bug, area-textprocessing, backport-candidate-11.1.x

#16453 Win32.PlatformConstants uses buildNumber instead of version
  src/Windows/Avalonia.Win32/PlatformConstants.cs
Labels: bug, os-windows, backport-candidate-11.1.x

#16470 Reset API validation baseline
  api/Avalonia.Android.nupkg.xml
  api/Avalonia.Browser.nupkg.xml
  api/Avalonia.Controls.ColorPicker.nupkg.xml
  api/Avalonia.Controls.DataGrid.nupkg.xml
  api/Avalonia.Diagnostics.nupkg.xml
  api/Avalonia.Skia.nupkg.xml
  api/Avalonia.Themes.Fluent.nupkg.xml
  api/Avalonia.Themes.Simple.nupkg.xml
  api/Avalonia.nupkg.xml
  build/SharedVersion.props
  nukebuild/BuildParameters.cs
Labels: area-infrastructure, backport-candidate-11.1.x

#16477 Fix android uri activation
  samples/ControlCatalog.Android/MainActivity.cs
  src/Android/Avalonia.Android/AvaloniaActivity.cs
  src/Android/Avalonia.Android/AvaloniaMainActivity.cs
  src/Android/Avalonia.Android/Platform/AndroidActivatableLifetime.cs
Labels: bug, os-android, backport-candidate-11.1.x

#16153 Fix XML child-value syntax in Setters
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlSetterTransformer.cs
  tests/Avalonia.Markup.Xaml.UnitTests/StyleTests.cs
Labels: bug, area-xaml, backport-candidate-11.1.x

#16256 Move IsDirect = true into DirectPropertyBase
  src/Avalonia.Base/DirectProperty.cs
  src/Avalonia.Base/DirectPropertyBase.cs
Labels: enhancement

#16505 Obsolete CompiledBindingPathBuilder.SetRawSource
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlBindingPathParser.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/XamlIlBindingPathHelper.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindings/CompiledBindingPath.cs
Labels: enhancement, area-xaml, backport-candidate-11.1.x, area-bindings

#16489 Always use the matched typeface's weight, style and stretch
  src/Skia/Avalonia.Skia/FontManagerImpl.cs
Labels: bug, backport-candidate-11.1.x

#16481 Fix TextLayout invalidation
  src/Avalonia.Controls/Presenters/TextPresenter.cs
  src/Avalonia.Controls/TextBlock.cs
Labels: bug, area-textprocessing, backport-candidate-11.1.x

#16011 chore: update comimpl.h
  native/Avalonia.Native/inc/comimpl.h
Labels: enhancement, area-infrastructure

#16538 Fix typeface font simulations
  src/Avalonia.Base/Media/Fonts/EmbeddedFontCollection.cs
  src/Avalonia.Base/Media/Fonts/SystemFontCollection.cs
Labels: bug, area-textprocessing, backport-candidate-11.1.x
