Repository AvaloniaUI/Avalonia, pull requests merged in 2024-03, with the labels that each got.

#14703 Do not defer resources with name registration on them
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlCompiler.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlControlTemplatePartsChecker.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlDeferredResourceTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Visitors/NameScopeRegistrationVisitor.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/ResourceDictionaryTests.cs
Labels: bug, area-xaml

#14556 Add Application.TryGetFeature, re-add new feature - IActivatableLifetime
  Avalonia.sln.DotSettings
  samples/ControlCatalog/App.xaml.cs
  samples/ControlCatalog/Pages/DialogsPage.xaml.cs
  src/Android/Avalonia.Android/AndroidPlatform.cs
  src/Android/Avalonia.Android/AvaloniaMainActivity.App.cs
  src/Android/Avalonia.Android/Platform/AndroidActivatableLifetime.cs
  src/Android/Avalonia.Android/SingleViewLifetime.cs
  src/Avalonia.Base/Platform/IOptionalFeatureProvider.cs
  src/Avalonia.Controls/AppBuilder.cs
  src/Avalonia.Controls/Application.cs
  src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs
  src/Avalonia.Controls/ApplicationLifetimes/IActivatableApplicationLifetime.cs
  src/Avalonia.Native/AvaloniaNativeApplicationPlatform.cs
  src/Avalonia.Native/AvaloniaNativePlatform.cs
  src/Avalonia.Native/AvaloniaNativePlatformExtensions.cs
  src/Avalonia.Native/MacOSActivatableLifetime.cs
  src/Browser/Avalonia.Browser/BrowserActivatableLifetime.cs
  src/Browser/Avalonia.Browser/BrowserSingleViewLifetime.cs
  src/Browser/Avalonia.Browser/WindowingPlatform.cs
  src/iOS/Avalonia.iOS/ActivatableLifetime.cs
  src/iOS/Avalonia.iOS/AvaloniaAppDelegate.cs
  src/iOS/Avalonia.iOS/Platform.cs
  src/iOS/Avalonia.iOS/SingleViewLifetime.cs
Labels: wont-backport, priority

#14812 Use actual infinite timeout instead of zero timeout in Dispatcher.Send
  src/Avalonia.Base/Threading/Dispatcher.Invoke.cs
Labels: backport-candidate-11.0.x

#14782 CanResize does not work on Windows
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: backport-candidate-11.0.x

#14111 Read all pixels then write all pixels to avoid virtual call overhead
  src/Avalonia.Base/Media/Imaging/PixelFormatReaders.cs
  src/Avalonia.Base/Media/Imaging/PixelFormatTranscoder.cs
  src/Avalonia.Base/Media/Imaging/PixelFormatWriter.cs
  src/Avalonia.Base/Platform/Internal/UnmanagedBlob.cs
  tests/Avalonia.Base.UnitTests/Media/Imaging/PixelFormatTranscoderTests.cs
Labels: backport-candidate-11.0.x

#14830 Seek stream before loading icon
  src/Windows/Avalonia.Win32/Win32Platform.cs
Labels: backport-candidate-11.0.x

#14761 CAMetalLayer should not be opaque
  native/Avalonia.Native/src/OSX/metal.mm
  src/iOS/Avalonia.iOS/AvaloniaView.cs
Labels: os-macos

#14833 Add browser packages migration to the ApiDiffHelper
  nukebuild/ApiDiffHelper.cs
Labels: infrastructure

#14838 Fix parsing type cast of attached property.
  src/Markup/Avalonia.Markup/Markup/Parsers/BindingExpressionGrammar.cs
  tests/Avalonia.Markup.UnitTests/Parsers/ExpressionObserverBuilderTests_AttachedProperty.cs
Labels: area-xaml, backport-candidate-11.0.x

#14843 Fix `XcursorImageDestroy` interop signature
  src/Avalonia.X11/X11CursorFactory.cs
  src/Avalonia.X11/XLib.cs
Labels: os-linux, backport-candidate-11.0.x

#14866 Fix DataGrid TextBox Cursor blinking
  src/Avalonia.Controls/Presenters/TextPresenter.cs
Labels: backport-candidate-11.0.x

#14861 TextBox: Make watermark invisible when IME preedit.
  src/Avalonia.Themes.Fluent/Controls/TextBox.xaml
  src/Avalonia.Themes.Simple/Controls/TextBox.xaml
Labels: backport-candidate-11.0.x

#14872 Don't defer strings in resource dictionaries
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlDeferredResourceTransformer.cs
Labels: area-xaml, backport-candidate-11.1.x

#14439 Fixed positioning of popups attached to adorners
  src/Avalonia.Controls/Primitives/PopupPositioning/IPopupPositioner.cs
  tests/Avalonia.Controls.UnitTests/Primitives/PopupTests.cs
Labels: backport-candidate-11.1.x

#14873 Fix PopupPositionerConstraintAdjustment.ResizeY value
  src/Avalonia.Controls/Primitives/PopupPositioning/IPopupPositioner.cs
Labels: backport-candidate-11.1.x

#14882 Fix THICKFRAME style being applied on maximized when border is removed
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: backport-candidate-11.1.x

#14883 Fix Dev Tools adorner highlight
  src/Avalonia.Diagnostics/Diagnostics/Views/TreePageView.xaml
  src/Avalonia.Diagnostics/Diagnostics/Views/TreePageView.xaml.cs
Labels: area-dev-tools, backport-candidate-11.1.x

#14762 Enable Metal rendering by default for iOS and macOS
  src/Avalonia.Native/AvaloniaNativePlatformExtensions.cs
  src/iOS/Avalonia.iOS/Platform.cs
Labels: os-macos

#14896 Add Android version checks where necessary
  src/Android/Avalonia.Android/AvaloniaMainActivity.cs
  src/Android/Avalonia.Android/Platform/Specific/Helpers/AndroidKeyboardEventsHelper.cs
  src/Android/Avalonia.Android/Platform/Specific/Helpers/AndroidMotionEventsHelper.cs
  src/Android/Avalonia.Android/Platform/Storage/AndroidStorageItem.cs
  src/Android/Avalonia.Android/Platform/Storage/AndroidStorageProvider.cs
Labels: backport-candidate-11.1.x

#14899 Fix for canvas height on mobile browsers
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/dom.ts
Labels: backport-candidate-11.1.x

#14900 Fix ScrollContentPresenter incorrectly handling BringIntoView without changing its offset
  src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
  src/Avalonia.Controls/VirtualizingStackPanel.cs
  tests/Avalonia.Controls.UnitTests/Presenters/ScrollContentPresenterTests.cs
Labels: backport-candidate-11.1.x

#14913 Fix ScrollContentPresenter incorrectly handling BringIntoView when offset is coerced
  src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
  tests/Avalonia.Controls.UnitTests/Presenters/ScrollContentPresenterTests.cs
Labels: backport-candidate-11.1.x

#14921 Fix silly bug in AndroidActivatableLifetime
  src/Android/Avalonia.Android/Platform/AndroidActivatableLifetime.cs
Labels: backport-candidate-11.1.x

#14943 Fix font fallback for composite keys containing relative URIs
  src/Avalonia.Base/Media/FontManager.cs
  tests/Avalonia.Skia.UnitTests/Media/FontManagerTests.cs
Labels: backport-candidate-11.1.x

#14952 Revert "Fix TextBlock wrong caret position"
  src/Avalonia.Controls/TextBox.cs
Labels: backport-candidate-11.0.x, backport-candidate-11.1.x

#14961 Fall back to linear initial velocity if there's not enough samples for inertia
  src/Avalonia.Base/Input/GestureRecognizers/ScrollGestureRecognizer.cs
  src/Avalonia.Base/Input/GestureRecognizers/VelocityTracker.cs
Labels: backport-candidate-11.1.x

#14966 Fix NativeAOT not using the XAML compilation output
  packages/Avalonia/AvaloniaBuildTasks.targets
Labels: backport-candidate-11.1.x

#14973 Select all input for double-clicks in `TextBox` with `PasswordChar`
  src/Avalonia.Controls/TextBox.cs
Labels: backport-candidate-11.1.x

#14974 Made PART_Track optional for Slider
  src/Avalonia.Controls/Slider.cs
Labels: backport-candidate-11.1.x

#14960 Fix TextBox sync issues
  src/Avalonia.Controls/TextBox.cs
Labels: backport-candidate-11.0.x, backport-candidate-11.1.x

#14982 Constrain CenterOwner window to screen.
  src/Avalonia.Controls/Window.cs
Labels: bug, priority

#14993 Switch version -beta to -alpha for nightly builds
  nukebuild/BuildParameters.cs
Labels: infrastructure, wont-backport

#14989 Move ItemsRepeater to a dedicated repository
  Avalonia.Desktop.slnf
  Avalonia.sln
  samples/ControlCatalog/ControlCatalog.csproj
  samples/ControlCatalog/MainView.xaml
  samples/ControlCatalog/Pages/ItemsRepeaterPage.xaml
  samples/ControlCatalog/Pages/ItemsRepeaterPage.xaml.cs
  samples/ControlCatalog/ViewModels/ItemsRepeaterPageViewModel.cs
  src/Avalonia.Controls.ItemsRepeater/Avalonia.Controls.ItemsRepeater.csproj
  src/Avalonia.Controls.ItemsRepeater/Controls/ElementFactory.cs
  src/Avalonia.Controls.ItemsRepeater/Controls/IElementFactory.cs
  src/Avalonia.Controls.ItemsRepeater/Controls/ItemTemplateWrapper.cs
  src/Avalonia.Controls.ItemsRepeater/Controls/ItemsRepeater.cs
  src/Avalonia.Controls.ItemsRepeater/Controls/ItemsRepeaterElementClearingEventArgs.cs
  src/Avalonia.Controls.ItemsRepeater/Controls/ItemsRepeaterElementIndexChangedEventArgs.cs
  src/Avalonia.Controls.ItemsRepeater/Controls/ItemsRepeaterElementPreparedEventArgs.cs
  src/Avalonia.Controls.ItemsRepeater/Controls/RecyclePool.cs
  src/Avalonia.Controls.ItemsRepeater/Controls/RecyclingElementFactory.cs
  src/Avalonia.Controls.ItemsRepeater/Controls/RepeaterLayoutContext.cs
  src/Avalonia.Controls.ItemsRepeater/Controls/UniqueIdElementPool.cs
  src/Avalonia.Controls.ItemsRepeater/Controls/ViewManager.cs
  src/Avalonia.Controls.ItemsRepeater/Controls/ViewportManager.cs
  src/Avalonia.Controls.ItemsRepeater/Controls/VirtualizationInfo.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/AttachedLayout.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/ElementManager.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/FlowLayoutAlgorithm.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/IFlowLayoutAlgorithmDelegates.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/LayoutContext.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/LayoutContextAdapter.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/NonVirtualizingLayout.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/NonVirtualizingLayoutContext.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/NonVirtualizingStackLayout.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/OrientationBasedMeasures.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/StackLayout.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/StackLayoutState.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/UniformGridLayout.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/UniformGridLayoutState.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/Utils/ListUtils.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/UvBounds.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/UvMeasure.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/VirtualLayoutContextAdapter.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/VirtualizingLayout.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/VirtualizingLayoutContext.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/WrapItem.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/WrapLayout.cs
  src/Avalonia.Controls.ItemsRepeater/Layout/WrapLayoutState.cs
  src/Avalonia.Controls.ItemsRepeater/Properties/AssemblyInfo.cs
  tests/Avalonia.Controls.ItemsRepeater.UnitTests/Avalonia.Controls.ItemsRepeater.UnitTests.csproj
  tests/Avalonia.Controls.ItemsRepeater.UnitTests/ItemsRepeaterTests.cs
  tests/Avalonia.Controls.ItemsRepeater.UnitTests/NonVirtualizingStackLayoutTests.cs
  tests/Avalonia.LeakTests/Avalonia.LeakTests.csproj
  tests/Avalonia.LeakTests/ControlTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Avalonia.Markup.Xaml.UnitTests.csproj
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/StyleTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/XamlTestBase.cs
Labels: wont-backport

#14935 Handle $self in compiled binding in multibinding.
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlBindingPathTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/CompiledBindingExtensionTests.cs
Labels: area-xaml, backport-candidate-11.1.x

#14954 Win32 - Only update window position on extended client changed when window is visible
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: bug, os-windows, backport-candidate-11.1.x

#15029 Implement check for inhertiance before calling method
  src/Avalonia.Controls/NativeControlHost.cs
Labels: bug, backport-candidate-11.0.x, backport-candidate-11.1.x

#15037 Fix TransformOrigin for brushes
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
  src/Windows/Avalonia.Direct2D1/Media/DrawingContextImpl.cs
  tests/Avalonia.RenderTests/Media/ImageBrushTests.cs
  tests/TestFiles/Direct2D1/Media/ImageBrush/ImageBrush_Should_Render_With_TransformOrigin.expected.png
  tests/TestFiles/Skia/Media/ImageBrush/ImageBrush_Should_Render_With_TransformOrigin.expected.png
Labels: backport-candidate-11.1.x

#15039 Fix incorrect comment for CanVerticallyScroll
  src/Avalonia.Base/Input/GestureRecognizers/ScrollGestureRecognizer.cs
Labels: backport-candidate-11.1.x

#15035 Use ShowWindowCommand.Hide when positioning an unshown win32 window
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: bug, os-windows, backport-candidate-11.1.x

#15061 iOS some pointer/keyboard fixes
  src/Avalonia.Base/Input/GestureRecognizers/ScrollGestureRecognizer.cs
  src/Avalonia.Base/Input/PenDevice.cs
  src/iOS/Avalonia.iOS/InputHandler.cs
Labels: bug, os-ios, backport-candidate-11.1.x

#15079 Fix IsInRange and added unit tests.
  src/Avalonia.Base/Media/UnicodeRange.cs
  tests/Avalonia.Base.UnitTests/Media/UnicodeRangeSegmentTests.cs
Labels: backport-candidate-11.1.x

#15108 Actually dispose PooledList
  src/Avalonia.Base/Rendering/Composition/CompositingRenderer.cs
Labels: backport-candidate-11.1.x

#15069 Set capacity of XAML resource dictionaries
  src/Avalonia.Base/Controls/ResourceDictionary.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlCompiler.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/GroupTransformers/XamlMergeResourceGroupTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlEnsureResourceDictionaryCapacityTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
Labels: area-xaml

#15109 Added a separate diagnostics graph to track Update method timing
  src/Avalonia.Base/Rendering/Composition/Server/CompositionTargetOverlays.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionTarget.cs
Labels: backport-candidate-11.0.x, backport-candidate-11.1.x

#15074 Avoid allocations for Unicode data tries
  src/Avalonia.Base/Media/TextFormatting/Unicode/BiDi.trie.cs
  src/Avalonia.Base/Media/TextFormatting/Unicode/GraphemeBreak.trie.cs
  src/Avalonia.Base/Media/TextFormatting/Unicode/UnicodeData.cs
  src/Avalonia.Base/Media/TextFormatting/Unicode/UnicodeData.trie.cs
  src/Avalonia.Base/Media/TextFormatting/Unicode/UnicodeTrie.cs
  src/Avalonia.Base/Media/TextFormatting/Unicode/UnicodeTrieBuilder.cs
  tests/Avalonia.Base.UnitTests/Media/TextFormatting/GraphemeBreakClassTrieGeneratorTests.cs
  tests/Avalonia.Base.UnitTests/Media/TextFormatting/UnicodeDataGenerator.cs
Labels: perf, backport-candidate-11.1.x

#15177 Fix popups disappearing when resized after opening
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: backport-candidate-11.1.x
