Repository AvaloniaUI/Avalonia, pull requests merged in 2024-01, with the labels that each got.

#14080 Fix regression in rendering of non-clear type text
  src/Skia/Avalonia.Skia/GlyphRunImpl.cs
Labels: backport-candidate-11.0.x

#14089 Do not crash on IsCurrent checks
  src/Avalonia.OpenGL/Egl/EglContext.cs
Labels: bug, os-windows, backport-candidate-11.0.x

#14090 Implement ApiInformation checks
  src/Windows/Avalonia.Win32/Input/WindowsInputPane.cs
  src/Windows/Avalonia.Win32/Win32PlatformSettings.cs
  src/Windows/Avalonia.Win32/WinRT/WinRTApiInformation.cs
  src/Windows/Avalonia.Win32/WinRT/winrt.idl
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: bug, os-windows, backport-candidate-11.0.x

#14088 Avoid hardcoded font properties
  src/Avalonia.Themes.Fluent/Accents/FluentControlResources.xaml
  src/Avalonia.Themes.Fluent/Controls/AutoCompleteBox.xaml
  src/Avalonia.Themes.Fluent/Controls/ButtonSpinner.xaml
  src/Avalonia.Themes.Fluent/Controls/Calendar.xaml
  src/Avalonia.Themes.Fluent/Controls/CalendarButton.xaml
  src/Avalonia.Themes.Fluent/Controls/CalendarDayButton.xaml
  src/Avalonia.Themes.Fluent/Controls/CalendarItem.xaml
  src/Avalonia.Themes.Fluent/Controls/CheckBox.xaml
  src/Avalonia.Themes.Fluent/Controls/ComboBox.xaml
  src/Avalonia.Themes.Fluent/Controls/ContextMenu.xaml
  src/Avalonia.Themes.Fluent/Controls/DatePicker.xaml
  src/Avalonia.Themes.Fluent/Controls/HeaderedContentControl.xaml
  src/Avalonia.Themes.Fluent/Controls/ListBox.xaml
  src/Avalonia.Themes.Fluent/Controls/ListBoxItem.xaml
  src/Avalonia.Themes.Fluent/Controls/Menu.xaml
  src/Avalonia.Themes.Fluent/Controls/MenuItem.xaml
  src/Avalonia.Themes.Fluent/Controls/NotificationCard.xaml
  src/Avalonia.Themes.Fluent/Controls/NumericUpDown.xaml
  src/Avalonia.Themes.Fluent/Controls/OverlayPopupHost.xaml
  src/Avalonia.Themes.Fluent/Controls/PopupRoot.xaml
  src/Avalonia.Themes.Fluent/Controls/RadioButton.xaml
  src/Avalonia.Themes.Fluent/Controls/RepeatButton.xaml
  src/Avalonia.Themes.Fluent/Controls/Slider.xaml
  src/Avalonia.Themes.Fluent/Controls/SplitButton.xaml
  src/Avalonia.Themes.Fluent/Controls/TabItem.xaml
  src/Avalonia.Themes.Fluent/Controls/TabStripItem.xaml
  src/Avalonia.Themes.Fluent/Controls/TextBox.xaml
  src/Avalonia.Themes.Fluent/Controls/ThemeVariantScope.xaml
  src/Avalonia.Themes.Fluent/Controls/TimePicker.xaml
  src/Avalonia.Themes.Fluent/Controls/ToggleButton.xaml
  src/Avalonia.Themes.Fluent/Controls/ToggleSwitch.xaml
  src/Avalonia.Themes.Fluent/DensityStyles/Compact.xaml
  src/Avalonia.Themes.Simple/Controls/NotificationCard.xaml
  src/Avalonia.Themes.Simple/Controls/ThemeVariantScope.xaml
Labels: enhancement, wont-backport

#14140 Only clear held pointer reference if pointer event is raised
  src/Avalonia.Base/Input/Gestures.cs
Labels: backport-candidate-11.0.x

#14093 fix(XML Docs): Rename inheritdocs to inheritdoc
  src/Avalonia.Base/Animation/Animators/BoolAnimator.cs
  src/Avalonia.Base/Animation/Animators/ByteAnimator.cs
  src/Avalonia.Base/Animation/Animators/DecimalAnimator.cs
  src/Avalonia.Base/Animation/Animators/DoubleAnimator.cs
  src/Avalonia.Base/Animation/Animators/FloatAnimator.cs
  src/Avalonia.Base/Animation/Animators/Int16Animator.cs
  src/Avalonia.Base/Animation/Animators/Int32Animator.cs
  src/Avalonia.Base/Animation/Animators/Int64Animator.cs
  src/Avalonia.Base/Animation/Animators/TransformAnimator.cs
  src/Avalonia.Base/Animation/Animators/UInt16Animator.cs
  src/Avalonia.Base/Animation/Animators/UInt32Animator.cs
  src/Avalonia.Base/Animation/Animators/UInt64Animator.cs
  src/Avalonia.Base/Animation/TransitionBase.cs
Labels: backport-candidate-11.0.x

#14138 Improving TextBox behaviour on Ctrl+Backspace down event
  src/Avalonia.Controls/TextBox.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
Labels: backport-candidate-11.0.x

#14106 Add an event so that users can detect when an Application icon is clicked
  native/Avalonia.Native/src/OSX/app.mm
  native/Avalonia.Native/src/OSX/common.h
  samples/ControlCatalog.Android/MainActivity.cs
  samples/ControlCatalog/App.xaml.cs
  src/Android/Avalonia.Android/AvaloniaMainActivity.App.cs
  src/Android/Avalonia.Android/AvaloniaMainActivity.cs
  src/Android/Avalonia.Android/IAndroidNavigationService.cs
  src/Android/Avalonia.Android/IAvaloniaActivity.cs
  src/Android/Avalonia.Android/SingleViewLifetime.cs
  src/Avalonia.Controls/ApplicationLifetimes/ActivatedEventArgs.cs
  src/Avalonia.Controls/ApplicationLifetimes/ActivationKind.cs
  src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs
  src/Avalonia.Controls/ApplicationLifetimes/IActivatableApplicationLifetime.cs
  src/Avalonia.Controls/ApplicationLifetimes/ProtocolActivatedEventArgs.cs
  src/Avalonia.Controls/Platform/INativeApplicationCommands.cs
  src/Avalonia.Native/AvaloniaNativeApplicationPlatform.cs
  src/Avalonia.Native/AvaloniaNativePlatformExtensions.cs
  src/Avalonia.Native/MacOSClassicDesktopStyleApplicationLifetime.cs
  src/Avalonia.Native/MacOSNativeMenuCommands.cs
  src/Avalonia.Native/avn.idl
  src/Browser/Avalonia.Browser/BrowserAppBuilder.cs
  src/Browser/Avalonia.Browser/BrowserSingleViewLifetime.cs
  src/Browser/Avalonia.Browser/Interop/InputHelper.cs
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/input.ts
  src/iOS/Avalonia.iOS/AvaloniaAppDelegate.cs
  src/iOS/Avalonia.iOS/SingleViewLifetime.cs
Labels: api, os-macos, os-browser, os-ios, os-android, backport-candidate-11.0.x

#14171 Fix exception when `SelectedValueBinding` evaluates to null
  src/Avalonia.Controls/Primitives/SelectingItemsControl.cs
  tests/Avalonia.Controls.UnitTests/Primitives/SelectingItemsControlTests_SelectedValue.cs
Labels: backport-candidate-11.0.x

#14162 Add InheritDataTypeFromItems for AutoCompleteBox.ValueMemberBinding
  src/Avalonia.Controls/AutoCompleteBox/AutoCompleteBox.Properties.cs
Labels: backport-candidate-11.0.x

#14186 Port DragMove logic from WPF
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: backport-candidate-11.0.x, priority

#14013 fix(Geometries): Relative line drawing
  src/Avalonia.Base/Media/PathMarkupParser.cs
  tests/Avalonia.Base.UnitTests/Media/PathMarkupParserTests.cs
Labels: backport-candidate-11.0.x

#13921 Fix Adorner Layer Clipping
  samples/ControlCatalog/Pages/AdornerLayerPage.xaml
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs
  src/Avalonia.Controls/GridSplitter.cs
  src/Avalonia.Controls/Primitives/AdornerLayer.cs
Labels: bug, backport-candidate-11.0.x

#14266 Fix segmentation fault error when using Linux Framebuffer DRM mode with AOT compilation
  src/Linux/Avalonia.LinuxFramebuffer/Output/DrmOutput.cs
Labels: os-linux, backport-candidate-11.0.x

#14268 Remove "netcoreapp2.0" target from the Avalonia. Make previewer use netstandard2.0
  Directory.Build.props
  nukebuild/ApiDiffHelper.cs
  packages/Avalonia/Avalonia.csproj
  packages/Avalonia/Avalonia.props
  samples/Directory.Build.props
  src/Markup/Avalonia.Markup.Xaml.Loader/Avalonia.Markup.Xaml.Loader.csproj
  src/Markup/Avalonia.Markup.Xaml.Loader/IncludeXamlIlSre.props
  src/tools/Avalonia.Designer.HostApp/Avalonia.Designer.HostApp.csproj
  src/tools/Avalonia.Designer.HostApp/DesignXamlLoader.cs
  src/tools/Avalonia.Designer.HostApp/Program.cs
  tests/Avalonia.DesignerSupport.Tests/DesignerSupportTests.cs
Labels: wont-backport

#14267 Make Classic ApplicationLifetime API a bit more reliable
  src/Avalonia.Controls/AppBuilder.cs
  src/Avalonia.Controls/Application.cs
  src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs
  src/Avalonia.Native/AvaloniaNativePlatformExtensions.cs
  tests/Avalonia.Controls.UnitTests/DesktopStyleApplicationLifetimeTests.cs
Labels: backport-candidate-11.0.x

#14276 Allow binding container IsVisible with virtualization.
  src/Avalonia.Controls/VirtualizingStackPanel.cs
  tests/Avalonia.Controls.UnitTests/VirtualizingStackPanelTests.cs
Labels: backport-candidate-11.0.x

#14196 AppleTV support + improvements for iOS backend
  azure-pipelines.yml
  samples/ControlCatalog.iOS/ControlCatalog.iOS.csproj
  samples/ControlCatalog.iOS/EmbedSample.iOS.cs
  samples/ControlCatalog.iOS/Info.plist
  src/Avalonia.Base/Compatibility/OperatingSystem.cs
  src/Avalonia.Base/Platform/StandardRuntimePlatform.cs
  src/Avalonia.Controls/ApplicationLifetimes/IActivatableApplicationLifetime.cs
  src/Skia/Avalonia.Skia/Gpu/Metal/SkiaMetalApi.cs
  src/iOS/Avalonia.iOS/Avalonia.iOS.csproj
  src/iOS/Avalonia.iOS/AvaloniaAppDelegate.cs
  src/iOS/Avalonia.iOS/AvaloniaView.Text.cs
  src/iOS/Avalonia.iOS/AvaloniaView.cs
  src/iOS/Avalonia.iOS/ClipboardImpl.cs
  src/iOS/Avalonia.iOS/DispatcherImpl.cs
  src/iOS/Avalonia.iOS/DisplayLinkTimer.cs
  src/iOS/Avalonia.iOS/Eagl/EaglDisplay.cs
  src/iOS/Avalonia.iOS/Eagl/EaglLayerSurface.cs
  src/iOS/Avalonia.iOS/Eagl/LayerFbo.cs
  src/iOS/Avalonia.iOS/InputHandler.cs
  src/iOS/Avalonia.iOS/InsetsManager.cs
  src/iOS/Avalonia.iOS/Metal/MetalDevice.cs
  src/iOS/Avalonia.iOS/Metal/MetalDrawingSession.cs
  src/iOS/Avalonia.iOS/Metal/MetalPlatformGraphics.cs
  src/iOS/Avalonia.iOS/Metal/MetalPlatformSurface.cs
  src/iOS/Avalonia.iOS/Metal/MetalRenderTarget.cs
  src/iOS/Avalonia.iOS/NativeControlHostImpl.cs
  src/iOS/Avalonia.iOS/Platform.cs
  src/iOS/Avalonia.iOS/PlatformSettings.cs
  src/iOS/Avalonia.iOS/SingleViewLifetime.cs
  src/iOS/Avalonia.iOS/Storage/IOSStorageItem.cs
  src/iOS/Avalonia.iOS/Storage/IOSStorageProvider.cs
  src/iOS/Avalonia.iOS/Stubs.cs
  src/iOS/Avalonia.iOS/TextInputResponder.Properties.cs
  src/iOS/Avalonia.iOS/TextInputResponder.cs
  src/iOS/Avalonia.iOS/TouchHandler.cs
  src/iOS/Avalonia.iOS/UIKitInputPane.cs
  src/iOS/Avalonia.iOS/ViewController.cs
Labels: enhancement, os-ios

#14287 Use embed JSON parser instead of Regex while parsing Deps file
  src/Markup/Avalonia.Markup.Xaml/RuntimeXamlLoaderConfiguration.cs
  src/tools/Avalonia.Designer.HostApp/DesignXamlLoader.cs
  src/tools/Avalonia.Designer.HostApp/TinyJson.cs
Labels: backport-candidate-11.0.x

#14301 Fix Previewer crash from Refit reflection (#14282)
  src/Avalonia.DesignerSupport/DesignWindowLoader.cs
  src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs
Labels: backport-candidate-11.0.x

#14329 Fix - Use root visual to calculate offsets is scroll gesture
  src/Avalonia.Base/Input/GestureRecognizers/ScrollGestureRecognizer.cs
Labels: backport-candidate-11.0.x

#14341 Dispose layout manager when embeddable control root is disposed.
  src/Android/Avalonia.Android/AvaloniaView.cs
  src/Android/Avalonia.Android/SingleViewLifetime.cs
  src/Avalonia.Controls/Embedding/EmbeddableControlRoot.cs
Labels: backport-candidate-11.0.x

#14247 Fix Inlines clear handling
  src/Avalonia.Controls/TextBlock.cs
  tests/Avalonia.Controls.UnitTests/TextBlockTests.cs
Labels: backport-candidate-11.0.x

#14181 Avoid WriteableBitmap misuse in several places, avoid UnmanagedBlod disposal from finalizer
  src/Avalonia.Base/Media/Imaging/WriteableBitmap.cs
  src/Avalonia.Controls.ColorPicker/Avalonia.Controls.ColorPicker.csproj
  src/Avalonia.Controls.ColorPicker/ColorSlider/ColorSlider.cs
  src/Avalonia.Controls.ColorPicker/ColorSpectrum/ColorSpectrum.cs
  src/Avalonia.Controls.ColorPicker/Helpers/ArrayList.cs
  src/Avalonia.Controls.ColorPicker/Helpers/ColorPickerHelpers.cs
  src/Windows/Avalonia.Win32/TrayIconImpl.cs
Labels: backport-candidate-11.0.x

#14366 Use popupParent as X11 parent window
  src/Avalonia.X11/X11Window.cs
Labels: backport-candidate-11.0.x

#14399 Remove Unstable attribute from IThemeVariantProvider.cs
  src/Avalonia.Base/Controls/IThemeVariantProvider.cs
Labels: area-xaml, backport-candidate-11.0.x
