Repository AvaloniaUI/Avalonia, pull requests merged in 2024-09, with the labels that each got.

#16835 Fix --no-build publishing when axaml compiler is used
  packages/Avalonia/AvaloniaBuildTasks.targets
Labels: bug, priority, backport-candidate-11.1.x

#16941 Add BoolTransition
  src/Avalonia.Base/Animation/Transitions/BoolTransition.cs
Labels: feature

#16758 Fix SimpleTheme for TimePicker
  src/Avalonia.Controls/DateTimePickers/TimePicker.cs
  src/Avalonia.Themes.Simple/Controls/TimePicker.xaml
Labels: bug

#16788 Fix stuck internal macOS modifier keys
  native/Avalonia.Native/src/OSX/AvnView.h
  native/Avalonia.Native/src/OSX/AvnView.mm
  native/Avalonia.Native/src/OSX/AvnWindow.mm
Labels: bug, os-macos, priority

#16970 Android - fix selection bounds in TextEditBuffer
  src/Android/Avalonia.Android/Platform/Input/TextEditBuffer.cs
Labels: bug, os-android

#16993 fix(ToggleSwitch): only remove knob transitions when dragging
  src/Avalonia.Controls/ToggleSwitch.cs
Labels: bug

#16981 Sync CaretIndex directly
  src/Avalonia.Controls/TextBox.cs
Labels: bug

#16955 Remove invalid Properties folder reference in project
  src/Skia/Avalonia.Skia/Avalonia.Skia.csproj
  src/Windows/Avalonia.Direct2D1/Avalonia.Direct2D1.csproj
  tests/Avalonia.DesignerSupport.Tests/Avalonia.DesignerSupport.Tests.csproj
Labels: area-infrastructure

#16796 Fixed nearest font matching not working
  src/Avalonia.Base/Media/Fonts/SystemFontCollection.cs
Labels: bug, area-textprocessing, backport-candidate-11.1.x

#16363 Fix transform desync
  src/Avalonia.Base/Rendering/Composition/Server/DrawingContextProxy.PendingCommands.cs
  tests/Avalonia.RenderTests.WpfCompare/CrossUI.Wpf.cs
  tests/Avalonia.RenderTests/CrossTests/Media/DrawingContextTests.cs
  tests/Avalonia.RenderTests/CrossUI/CrossUI.Avalonia.cs
  tests/Avalonia.RenderTests/CrossUI/CrossUI.cs
  tests/Avalonia.RenderTests/Media/DrawingContextTests.cs
  tests/TestFiles/CrossTests/Media/DrawingContext/Transform_Should_Work_As_Expected.wpf.png
  tests/TestFiles/Skia/Media/DrawingContext/Should_Render_LinesAndText.expected.png
Labels: bug

#16476 Fix IME not working in some scenarios.
  src/Avalonia.FreeDesktop/DBusIme/DBusTextInputMethodBase.cs
Labels: bug, os-linux, backport-candidate-11.1.x

#16677 fix #12190, the name of FontFamily is null will cause crash
  src/Avalonia.Base/Media/Typeface.cs
Labels: bug, backport-candidate-11.1.x

#16861 feat: add UpdateSourceTrigger support for ReflectionBindingExtension
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/ReflectionBindingExtension.cs
Labels: feature

#16984 feat: expose TreeViewItem expansion status to root event.
  src/Avalonia.Controls/TreeViewItem.cs
Labels: feature

#16969 Android - call base dispatch key event before called toplevel's override
  src/Android/Avalonia.Android/AvaloniaView.cs
  src/Android/Avalonia.Android/Platform/Specific/Helpers/AndroidKeyboardEventsHelper.cs
Labels: os-android

#16756 Fixes geometry render bounds when curves are present
  src/Skia/Avalonia.Skia/GeometryImpl.cs
  tests/Avalonia.Skia.UnitTests/RenderBoundsTests.cs
Labels: bug, area-rendering, backport-candidate-11.1.x

#16928 ResourceProvider upgrade
  api/Avalonia.Themes.Fluent.nupkg.xml
  src/Avalonia.Base/Controls/ResourceProvider.cs
  src/Avalonia.Themes.Fluent/ColorPaletteResources.cs
  src/Avalonia.Themes.Fluent/ColorPaletteResourcesCollection.cs
  src/Avalonia.Themes.Fluent/FluentTheme.xaml.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/DynamicResourceExtensionTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/ResourceIncludeTests.cs
Labels: enhancement

#16601 Make sure GlyphRunImpl.InkBounds are always at a positive location
  src/Skia/Avalonia.Skia/GlyphRunImpl.cs
Labels: bug, area-textprocessing, backport-candidate-11.1.x

#15536 Fix SelectableTextBlock Selection
  src/Avalonia.Controls/SelectableTextBlock.cs
Labels: bug

#17004 [Text] Convert control codepoints into zero width space during shaping
  src/Skia/Avalonia.Skia/TextShaperImpl.cs
Labels: bug, area-textprocessing

#17022 Adjust diagnostic apis
  src/Avalonia.Base/Avalonia.Base.csproj
  src/Avalonia.Base/Data/Core/MultiBindingExpression.cs
  src/Avalonia.Base/Diagnostics/AvaloniaObjectExtensions.cs
  src/Avalonia.Base/Diagnostics/IValueFrameDiagnostic.cs
  src/Avalonia.Base/Diagnostics/LocalValueFrameDiagnostic.cs
  src/Avalonia.Base/Diagnostics/StyleValueFrameDiagnostic.cs
  src/Avalonia.Base/Diagnostics/StyledElementExtensions.cs
  src/Avalonia.Base/Diagnostics/ValueFrameDiagnostic.cs
  src/Avalonia.Controls/Avalonia.Controls.csproj
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/ValueFrameViewModel.cs
Labels: area-infrastructure, area-dev-tools

#16729 Fix bindings without property path
  src/Avalonia.Base/Data/Core/BindingExpression.cs
  tests/Avalonia.Base.UnitTests/Data/Core/BindingExpressionTests.GetValue.cs
  tests/Avalonia.Base.UnitTests/Data/Core/BindingExpressionTests.Mode.cs
  tests/Avalonia.Base.UnitTests/Data/Core/BindingExpressionTests.cs
  tests/Avalonia.Markup.UnitTests/Data/BindingTests_Logging.cs
Labels: bug, regression, backport-candidate-11.1.x, area-bindings

#16585 Extract non-generic members from frequently used generic types
  src/Avalonia.Base/AvaloniaObject.cs
  src/Avalonia.Base/AvaloniaPropertyRegistry.cs
  src/Avalonia.Base/PropertyStore/BindingEntryBase.cs
  src/Avalonia.Base/PropertyStore/BindingEntryBaseNonGenericHelper.cs
  src/Avalonia.Base/PropertyStore/EffectiveValue`1.cs
  src/Avalonia.Base/PropertyStore/PropertyNotifying.cs
  src/Avalonia.Base/Reactive/AnonymousObserver.cs
  src/Avalonia.Base/Reactive/AnonymousObserverNonGenericHelper.cs
  src/Avalonia.Base/StyledProperty.cs
  src/Avalonia.Base/StyledPropertyNonGenericHelper.cs
  src/Avalonia.Base/Threading/Dispatcher.cs
Labels: enhancement, area-trimming-aot

#17045 Delete nuget.config from IntegrationTestApp
  samples/IntegrationTestApp/nuget.config
Labels: area-infrastructure

#17044 Fix parsing of XAML setters when the child isn't a text node
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlSetterTransformer.cs
  tests/Avalonia.Markup.Xaml.UnitTests/StyleTests.cs
Labels: bug, area-xaml, regression

#17049 Validate visual parent on attaching to the tree
  src/Avalonia.Base/Visual.cs
Labels: enhancement, backport-candidate-11.1.x

#17035 [macOS] Fixes stuck mouse buttons after drag
  native/Avalonia.Native/src/OSX/AvnView.h
  native/Avalonia.Native/src/OSX/AvnView.mm
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
  samples/ControlCatalog/Pages/DragAndDropPage.xaml
Labels: bug, os-macos

#17030 fix Automation.HelpText on windows
  src/Avalonia.Controls/Automation/AutomationElementIdentifiers.cs
  src/Avalonia.Controls/Automation/Peers/AutomationPeer.cs
  src/Avalonia.Controls/Automation/Peers/ControlAutomationPeer.cs
  src/Avalonia.Controls/Automation/Peers/InteropAutomationPeer.cs
  src/Avalonia.Controls/Automation/Peers/UnrealizedElementAutomationPeer.cs
  src/Windows/Avalonia.Win32/Automation/AutomationNode.cs
Labels: enhancement, area-accessibility

#17072 Enable VisualBrush to be used as Visual's OpacityMask
  src/Avalonia.Base/Rendering/Composition/Visual.cs
  src/Avalonia.Base/Visual.Composition.cs
  src/Avalonia.Base/composition-schema.xml
  src/tools/DevGenerators/CompositionGenerator/Config.cs
  src/tools/DevGenerators/CompositionGenerator/Generator.cs
  tests/Avalonia.RenderTests/Media/VisualBrushTests.cs
  tests/TestFiles/Direct2D1/Media/VisualBrush/VisualBrush_Should_Be_Usable_As_Opacity_Mask.expected.png
  tests/TestFiles/Skia/Media/VisualBrush/VisualBrush_Should_Be_Usable_As_Opacity_Mask.expected.png
Labels: enhancement, feature

#17096 [macOS]: Call layer.setNeedsDisplay on show.
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
Labels: bug, priority, backport-candidate-11.1.x

#17079 Added Win32PlatformOptions.GraphicsAdapterSelectionCallback
  src/Avalonia.Base/Platform/PlatformGraphicsDeviceAdapterDescription.cs
  src/Windows/Avalonia.Win32/OpenGl/Angle/AngleWin32EglDisplay.cs
  src/Windows/Avalonia.Win32/Win32PlatformOptions.cs
Labels: enhancement, os-windows

#17101 Properly fixed DrawingContextProxy transform tracking
  src/Avalonia.Base/Rendering/Composition/Server/DrawingContextProxy.PendingCommands.cs
  src/Avalonia.Base/Rendering/Composition/Server/DrawingContextProxy.cs
Labels: bug, backport-candidate-11.1.x

#17041 [AVN] Introduced ComObjectWeakPtr
  native/Avalonia.Native/inc/comimpl.h
  native/Avalonia.Native/src/OSX/AvnView.mm
  native/Avalonia.Native/src/OSX/AvnWindow.mm
  native/Avalonia.Native/src/OSX/IWindowStateChanged.h
Labels: enhancement, os-macos

#17046 Fix AutomationProperties.HelpText on macos
  native/Avalonia.Native/src/OSX/automation.mm
  src/Avalonia.Native/AvnAutomationPeer.cs
  src/Avalonia.Native/avn.idl
Labels: enhancement, area-accessibility

#17107 Fix WellKnownFolder.Downloads on Windows
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageProvider.cs
Labels: bug, os-windows

#17074 Prevent AutoCompleteBox getting stuck in a state where it can't drop down.
  src/Avalonia.Controls/AutoCompleteBox/AutoCompleteBox.cs
  tests/Avalonia.Controls.UnitTests/AutoCompleteBoxTests.cs
Labels: bug, priority

#17112 Add missing Screen.Equals/GetHashCode overrides
  src/Avalonia.Controls/Platform/IScreenImpl.cs
  src/Avalonia.Controls/Platform/Screen.cs
Labels: bug

#17073 Prevent stack overflow in two-way bindings.
  src/Avalonia.Base/Data/Core/BindingExpression.cs
  tests/Avalonia.Markup.UnitTests/Data/BindingTests.cs
Labels: bug, priority, backport-candidate-11.1.x, area-bindings

#17122 Unsubscribe the same handler with subscribed with in Dispatcher::ShutdownImpl
  src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs
Labels: bug, backport-candidate-11.1.x

#17141 Fixed TabItem.ContentTemplate being reused for the next tab item
  src/Avalonia.Controls/TabControl.cs
  tests/Avalonia.Controls.UnitTests/TabControlTests.cs
Labels: bug

#17145 Fixed publishing multi-architecture Android builds
  packages/Avalonia/AvaloniaBuildTasks.targets
Labels: bug, area-infrastructure

#17140 Execute Dispatcher.RunJobs after each headless NUnit test
  src/Headless/Avalonia.Headless.NUnit/AvaloniaTestMethodCommand.cs
Labels: bug, area-headless

#17103 Fix HeadlessWindowImpl.Position does not persist new value
  src/Headless/Avalonia.Headless/HeadlessWindowImpl.cs
  tests/Avalonia.Headless.UnitTests/InputTests.cs
Labels: bug, area-headless

#17121 Make UiThreadRenderTimer to calculate the next tick time based on expected FPS
  src/Avalonia.Base/Rendering/UiThreadRenderTimer.cs
Labels: enhancement, backport-candidate-11.1.x

#16779 feat: Enable Rule CA1851
  .editorconfig
  src/Avalonia.Controls/NumericUpDown/NumericUpDown.cs
  src/Avalonia.Controls/Primitives/TextSelectionCanvas.cs
  src/Avalonia.Controls/TreeView.cs
Labels: enhancement, area-infrastructure

#16642 Make popup focus stealing configurable.
  api/Avalonia.nupkg.xml
  samples/IntegrationTestApp/Embedding/INativeControlFactory.cs
  samples/IntegrationTestApp/Embedding/INativeTextBoxFactory.cs
  samples/IntegrationTestApp/Embedding/MacOSTextBoxFactory.cs
  samples/IntegrationTestApp/Embedding/NativeTextBox.cs
  samples/IntegrationTestApp/Embedding/Win32TextBoxFactory.cs
  samples/IntegrationTestApp/Embedding/WinApi.cs
  samples/IntegrationTestApp/Pages/EmbeddingPage.axaml
  samples/IntegrationTestApp/Pages/EmbeddingPage.axaml.cs
  src/Avalonia.Controls/ContextMenu.cs
  src/Avalonia.Controls/Platform/IPopupImpl.cs
  src/Avalonia.Controls/Primitives/IPopupHost.cs
  src/Avalonia.Controls/Primitives/OverlayPopupHost.cs
  src/Avalonia.Controls/Primitives/Popup.cs
  src/Avalonia.Controls/Primitives/PopupRoot.cs
  src/Avalonia.Controls/ToolTip.cs
  src/Avalonia.DesignerSupport/Remote/Stubs.cs
  src/Avalonia.Native/PopupImpl.cs
  src/Avalonia.X11/X11Window.cs
  src/Headless/Avalonia.Headless/HeadlessWindowImpl.cs
  src/Windows/Avalonia.Win32/PopupImpl.cs
  tests/Avalonia.IntegrationTests.Appium/ElementExtensions.cs
  tests/Avalonia.IntegrationTests.Appium/EmbeddingTests.cs
Labels: bug, enhancement, priority

#17136 Disable runtime marshalling for getprocaddress
  src/Android/Avalonia.Android/Avalonia.Android.csproj
  src/Avalonia.OpenGL/Avalonia.OpenGL.csproj
  src/Avalonia.Vulkan/Avalonia.Vulkan.csproj
  src/tools/DevGenerators/GetProcAddressInitialization.cs
Labels: enhancement, area-trimming-aot

#17124 [fbdev] Added a mode that should not waste time in FBIO_WAITFORVSYNC
  src/Linux/Avalonia.LinuxFramebuffer/Output/FbDevBackBuffer.cs
  src/Linux/Avalonia.LinuxFramebuffer/Output/FbDevOutputOptions.cs
  src/Linux/Avalonia.LinuxFramebuffer/Output/FbdevOutput.cs
Labels: enhancement, backport-candidate-11.1.x

#17123 Use epoll for dispatcher loop since it's more accurate with wait timeouts
  src/Linux/Avalonia.LinuxFramebuffer/EpollDispatcherImpl.cs
  src/Linux/Avalonia.LinuxFramebuffer/LinuxFramebufferPlatform.cs
Labels: enhancement, backport-candidate-11.1.x

#17143 Use coercion for MaskedTextBox.Text
  src/Avalonia.Controls/MaskedTextBox.cs
  src/Avalonia.Controls/TextBox.cs
  tests/Avalonia.Controls.UnitTests/MaskedTextBoxTests.cs
Labels: enhancement, feature
