Repository AvaloniaUI/Avalonia, pull requests merged in 2025-05, with the labels that each got.

#18767 Invoke ScalingChanged when scaling changed on iOS
  src/iOS/Avalonia.iOS/AvaloniaView.cs
Labels: bug, regression, os-ios, backport-candidate-11.3.x

#18793 Fix crash with samsung keyboard when using password textboxes
  src/Android/Avalonia.Android/Platform/Input/AvaloniaInputConnection.cs
  src/Android/Avalonia.Android/Platform/Input/TextEditBuffer.cs
Labels: bug, os-android, backport-candidate-11.3.x

#18753 Invalidate ScrollContentPresenter measure on Can...Scroll
  src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
  tests/Avalonia.Controls.UnitTests/ScrollViewerTests.cs
Labels: bug, backport-candidate-11.3.x

#18816 Fix an issue where input controls initialized with `InputMethod.IsInputMethodEnable=false` could still use IME in their initial state.
  src/Windows/Avalonia.Win32/Input/Imm32InputMethod.cs
Labels: bug, os-windows, backport-candidate-11.3.x

#18759 Fix incorrect CandidateWindow position when using Pinyin IMEs in Windows
  src/Windows/Avalonia.Win32/Input/Imm32InputMethod.cs
Labels: bug, os-windows, backport-candidate-11.3.x

#18794 Fix caret handles not updating to the latest caret points
  src/Avalonia.Controls/Presenters/TextPresenter.cs
  src/Avalonia.Controls/Primitives/TextSelectionCanvas.cs
Labels: bug, area-textprocessing, backport-candidate-11.3.x

#18832 [Issue 18806] Prevent children of UniformGrid from having negative dimensions when row/col spacing exceeds available space
  src/Avalonia.Controls/Primitives/UniformGrid.cs
  tests/Avalonia.Controls.UnitTests/Primitives/UniformGridTests.cs
Labels: bug, backport-candidate-11.3.x

#18869 Improved inline documentation of class event handler methods
  src/Avalonia.Base/Input/InputElement.cs
  src/Avalonia.Controls.ColorPicker/ColorPreviewer/ColorPreviewer.cs
  src/Avalonia.Controls.ColorPicker/ColorSlider/ColorSlider.cs
  src/Avalonia.Controls.ColorPicker/ColorView/ColorView.cs
  src/Avalonia.Controls/Control.cs
  src/Avalonia.Controls/Expander.cs
  src/Avalonia.Controls/MenuItem.cs
  src/Avalonia.Controls/Primitives/Thumb.cs
Labels: enhancement, backport-candidate-11.3.x

#18722 Limit use of deprecated Android display API
  src/Android/Avalonia.Android/Avalonia.Android.csproj
  src/Android/Avalonia.Android/Platform/AndroidScreens.cs
Labels: enhancement, os-android

#18876 Update azure ubuntu version
  azure-pipelines.yml
Labels: area-infrastructure, backport-candidate-11.0.x, backport-candidate-11.1.x, backport-candidate-11.2.x, backport-candidate-11.3.x

#18766 Improve pen secondary button handling on list box
  samples/ControlCatalog/Pages/ListBoxPage.xaml
  src/Avalonia.Base/Input/GestureRecognizers/ScrollGestureRecognizer.cs
  src/Avalonia.Controls/ListBox.cs
  src/Avalonia.Controls/ListBoxItem.cs
  tests/Avalonia.Controls.UnitTests/ListBoxTests.cs
  tests/Avalonia.Controls.UnitTests/ListBoxTests_Single.cs
  tests/Avalonia.UnitTests/MouseTestHelper.cs
  tests/Avalonia.UnitTests/TouchTestHelper.cs
Labels: bug, backport-candidate-11.2.x, backport-candidate-11.3.x

#18868 Fixed core `GotFocus` and `LostFocus` handling being skippable
  src/Avalonia.Base/Input/InputElement.cs
Labels: bug, wont-backport

#18571 Update SkiaSharp and HarfBuzzSharp version to support LA64 and RV64
  build/HarfBuzzSharp.props
  build/SkiaSharp.props
Labels: enhancement, area-skia, backport-candidate-11.3.x

#18901 Fixed rare soft-"freezes" with OnRender(c) { ...; InvalidateVisual(); … } pattern
  src/Avalonia.Base/Media/MediaContext.Compositor.cs
Labels: bug, customer-priority, backport-candidate-11.3.x

#18746 fix TextBox multiline selection with up/down keys till start/end of text
  src/Avalonia.Controls/TextBox.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
Labels: bug, backport-candidate-11.3.x

#18907 Fix RadialGradientBrush GradientStop reordering
  src/Avalonia.Base/Media/GradientStops.cs
  src/Avalonia.Base/Media/Immutable/ImmutableGradientStop.cs
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
Labels: bug, backport-candidate-11.3.x

#18922 Remove Keyboard Theme Override
  src/iOS/Avalonia.iOS/TextInputResponder.Properties.cs
Labels: bug, backport-candidate-11.3.x

#18456 Don't round size in TextBlock when UseLayoutRounding is false
  src/Avalonia.Controls/TextBlock.cs
  tests/Avalonia.Controls.UnitTests/TextBlockTests.cs
Labels: bug

#18462 Fix MeasureCore when there's a size constraint and there's a negative…
  src/Avalonia.Base/Layout/Layoutable.cs
  tests/Avalonia.Base.UnitTests/Layout/LayoutableTests.cs
Labels: bug

#18892 [Performance] Reduce allocations in `TextShaperImpl` by reusing HarfBuzz Buffer
  src/Skia/Avalonia.Skia/TextShaperImpl.cs
Labels: enhancement, area-perf, backport-candidate-11.3.x

#18947 Don't expect WasmRuntimeAssetsLocation to be always set
  samples/ControlCatalog/Pages/TabControlPage.xaml
  src/Browser/Avalonia.Browser/Rendering/RenderWorker.cs
  src/Browser/Avalonia.Browser/build/Avalonia.Browser.props
  src/Browser/Avalonia.Browser/build/Avalonia.Browser.targets
  src/Browser/Avalonia.Browser/build/Microsoft.AspNetCore.StaticWebAssets.props
Labels: enhancement, os-browser, backport-candidate-11.3.x
