Repository AvaloniaUI/Avalonia, pull requests merged in 2025-10, with the labels that each got.

#19739 Add Add/Remove event handler methods to DragDrop.
  src/Avalonia.Base/Input/DragDrop.cs
Labels: enhancement, api-approved, backport-candidate-11.3.x

#19744 Remove Microsoft.SourceLink.GitHub PackageReference
  build/SourceLink.props
Labels: bug, area-infrastructure, backport-candidate-11.3.x

#19750 Make sure inlines properly inherit text run properties from their parent
  src/Avalonia.Controls/Documents/Bold.cs
  src/Avalonia.Controls/Documents/Inline.cs
  src/Avalonia.Controls/Documents/Italic.cs
  src/Avalonia.Controls/Documents/Underline.cs
  tests/Avalonia.Controls.UnitTests/InlineTests.cs
Labels: bug, backport-candidate-11.3.x

#19757 Update Avalonia.BuildServices package version
  packages/Avalonia/Avalonia.csproj
Labels: enhancement, area-infrastructure, backport-candidate-11.2.x, backport-candidate-11.3.x

#18791 [OSX] Implemented IOSurface/MTLSharedEvent interop APIs
  api/Avalonia.nupkg.xml
  azure-pipelines-integrationtests.yml
  azure-pipelines.yml
  native/Avalonia.Native/inc/noarc.h
  native/Avalonia.Native/src/OSX/Avalonia.Native.OSX.xcodeproj/project.pbxproj
  native/Avalonia.Native/src/OSX/cgl.mm
  native/Avalonia.Native/src/OSX/common.h
  native/Avalonia.Native/src/OSX/crapium.h
  native/Avalonia.Native/src/OSX/crapium.mm
  native/Avalonia.Native/src/OSX/main.mm
  native/Avalonia.Native/src/OSX/memhelp.mm
  native/Avalonia.Native/src/OSX/metal.mm
  native/Avalonia.Native/src/OSX/noarc.mm
  samples/GpuInterop/NativeMethods.cs
  samples/GpuInterop/VulkanDemo/VulkanCommandBufferPool.cs
  samples/GpuInterop/VulkanDemo/VulkanContext.cs
  samples/GpuInterop/VulkanDemo/VulkanImage.cs
  samples/GpuInterop/VulkanDemo/VulkanSwapchain.cs
  samples/GpuInterop/VulkanDemo/VulkanTimelineSemaphore.cs
  src/Avalonia.Base/Platform/IExternalObjectsRenderInterfaceContextFeature.cs
  src/Avalonia.Base/Platform/PlatformGraphicsExternalMemory.cs
  src/Avalonia.Base/Rendering/Composition/CompositionDrawingSurface.cs
  src/Avalonia.Base/Rendering/Composition/CompositionExternalMemory.cs
  src/Avalonia.Base/Rendering/Composition/CompositionInterop.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionDrawingSurface.cs
  src/Avalonia.Metal/IMetalExternalObjectsFeature.cs
  src/Avalonia.Native/AvaloniaNativeGlPlatformGraphics.cs
  src/Avalonia.Native/AvaloniaNativePlatform.cs
  src/Avalonia.Native/GpuHandleWrapFeature.cs
  src/Avalonia.Native/Metal.cs
  src/Avalonia.Native/avn.idl
  src/Avalonia.OpenGL/Features/ExternalObjectsOpenGlExtensionFeature.cs
  src/Avalonia.OpenGL/GlConsts.cs
  src/Avalonia.OpenGL/IGlContextExternalObjectsFeature.cs
  src/Skia/Avalonia.Skia/Gpu/Metal/SkiaMetalExternalObjectsFeature.cs
  src/Skia/Avalonia.Skia/Gpu/Metal/SkiaMetalGpu.cs
  src/Skia/Avalonia.Skia/Gpu/OpenGl/GlSkiaExternalObjectsFeature.cs
  src/Skia/Avalonia.Skia/Gpu/OpenGl/GlSkiaGpu.cs
  src/Skia/Avalonia.Skia/Gpu/Vulkan/VulkanSkiaExternalObjectsFeature.cs
  src/Skia/Avalonia.Skia/ImmutableBitmap.cs
  src/Windows/Avalonia.Win32/OpenGl/Angle/AngleExternalD3D11Texture2D.cs
Labels: feature, os-macos, backport-candidate-11.3.x

#19722 Remove Tizen
  Avalonia.sln
  build/DevSingleProject.targets
  build/TargetFrameworks.props
  dirs.proj
  packages/Avalonia/AvaloniaSingleProject.targets
  samples/ControlCatalog.Tizen/ControlCatalog.Tizen.csproj
  samples/ControlCatalog.Tizen/EmbedSampleNuiTizen.cs
  samples/ControlCatalog.Tizen/Main.cs
  samples/ControlCatalog.Tizen/shared/res/Avalonia.png
  samples/ControlCatalog.Tizen/tizen-manifest.xml
  samples/SingleProjectSandbox/Platforms/Tizen/Main.cs
  samples/SingleProjectSandbox/Platforms/Tizen/shared/res/Avalonia.png
  samples/SingleProjectSandbox/Platforms/Tizen/tizen-manifest.xml
  samples/SingleProjectSandbox/SingleProjectSandbox.csproj
  src/Tizen/Avalonia.Tizen/Avalonia.Tizen.csproj
  src/Tizen/Avalonia.Tizen/ITizenView.cs
  src/Tizen/Avalonia.Tizen/NuiAvaloniaView.cs
  src/Tizen/Avalonia.Tizen/NuiAvaloniaViewTextEditable.cs
  src/Tizen/Avalonia.Tizen/NuiClipboardImpl.cs
  src/Tizen/Avalonia.Tizen/NuiGlLayerSurface.cs
  src/Tizen/Avalonia.Tizen/NuiGlPlatform.cs
  src/Tizen/Avalonia.Tizen/NuiKeyboardHandler.cs
  src/Tizen/Avalonia.Tizen/NuiNativeControlHostImpl.cs
  src/Tizen/Avalonia.Tizen/NuiScreens.cs
  src/Tizen/Avalonia.Tizen/NuiTizenApplication.cs
  src/Tizen/Avalonia.Tizen/NuiTouchHandler.cs
  src/Tizen/Avalonia.Tizen/NuiViewControlHandle.cs
  src/Tizen/Avalonia.Tizen/Platform/Consts.cs
  src/Tizen/Avalonia.Tizen/Platform/Input/TizenKeyboardDevice.cs
  src/Tizen/Avalonia.Tizen/Platform/Interop/Strucs.cs
  src/Tizen/Avalonia.Tizen/Platform/Permissions.cs
  src/Tizen/Avalonia.Tizen/Platform/TizenLauncher.cs
  src/Tizen/Avalonia.Tizen/Platform/TizenPlatformSettings.cs
  src/Tizen/Avalonia.Tizen/Stubs.cs
  src/Tizen/Avalonia.Tizen/TizenApplicationExtensions.cs
  src/Tizen/Avalonia.Tizen/TizenPlatform.cs
  src/Tizen/Avalonia.Tizen/TizenRenderTimer.cs
  src/Tizen/Avalonia.Tizen/TizenRuntimePlatform.cs
  src/Tizen/Avalonia.Tizen/TizenStorageProvider.cs
  src/Tizen/Avalonia.Tizen/TizenThreadingInterface.cs
  src/Tizen/Avalonia.Tizen/TopLevelImpl.cs
Labels: enhancement, os-tizen

#19762 Make ScreenBase impl more reliable
  src/Avalonia.Controls/Platform/IScreenImpl.cs
Labels: bug, os-windows, backport-candidate-11.3.x
