Repository AvaloniaUI/Avalonia, pull requests merged in 2025-09, with the labels that each got.

#19598 Fix SkiaSharp3 Metal interop signature
  src/Skia/Avalonia.Skia/Gpu/Metal/SkiaMetalApi.cs
Labels: bug, os-macos, backported-11.3.x

#19595 Ignore empty preeditText when no composition was active before
  src/Avalonia.FreeDesktop/DBusIme/IBus/IBusX11TextInputMethod.cs
Labels: bug, os-linux, area-x11, customer-priority, backport-candidate-11.3.x

#19602 TextLine.GetTextBounds zero width run fixes
  src/Avalonia.Base/Media/TextFormatting/TextLineImpl.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextLineTests.cs
Labels: bug, area-textprocessing, backport-candidate-11.3.x

#19615 Backport GRContext bugfix from 12.0 branch
  src/iOS/Avalonia.iOS/Metal/MetalPlatformGraphics.cs
Labels: bug, os-ios, backported-11.3.x

#19643 Fix: ChoreographerTimer should check for Android version correctly.
  src/Android/Avalonia.Android/ChoreographerTimer.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/AndroidFramebuffer.cs
Labels: bug, os-android, backport-candidate-11.3.x

#19644 Add Boxshadow(s) Documentation Comments
  src/Avalonia.Base/Media/BoxShadow.cs
  src/Avalonia.Base/Media/BoxShadows.cs
Labels: enhancement, backport-candidate-11.3.x, area-documentation

#19651 Limit InlineUIContainer to available width
  src/Avalonia.Controls/Documents/Inline.cs
  src/Avalonia.Controls/Documents/InlineCollection.cs
  src/Avalonia.Controls/Documents/InlineUIContainer.cs
  src/Avalonia.Controls/Documents/LineBreak.cs
  src/Avalonia.Controls/Documents/Run.cs
  src/Avalonia.Controls/Documents/Span.cs
  src/Avalonia.Controls/TextBlock.cs
  tests/Avalonia.Controls.UnitTests/TextBlockTests.cs
Labels: area-textprocessing, backport-candidate-11.3.x

#19705 Added resource for TextControlPlaceholderOpacity
  src/Avalonia.Themes.Fluent/Accents/FluentControlResources.xaml
  src/Avalonia.Themes.Fluent/Controls/TextBox.xaml
  src/Avalonia.Themes.Simple/Accents/Base.xaml
  src/Avalonia.Themes.Simple/Controls/TextBox.xaml
Labels: enhancement, area-fluent, backport-candidate-11.3.x

#19712 Enable compiled bindings by default in Avalonia.props
  packages/Avalonia/Avalonia.props
Labels: enhancement, area-xaml, breaking-change, wont-backport

#19727 Fixed TypeConverterAttribute for avalonia properties
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/XamlIlAvaloniaPropertyHelper.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/XamlIlTests.cs
Labels: bug, backport-candidate-11.3.x

#19735 Add FindAssembliesGrantingInternalAccess to AvaloniaXamlIlRuntimeCompiler
  src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs
Labels: enhancement, area-xaml, backport-candidate-11.3.x

#19709 Move ControlCatalog.MacCatalyst/tvOS to their own folders
  Avalonia.sln
  dirs.proj
  samples/ControlCatalog.MacCatalyst/ControlCatalog.MacCatalyst.csproj
  samples/ControlCatalog.MacCatalyst/Entitlements.plist
  samples/ControlCatalog.MacCatalyst/Info.plist
  samples/ControlCatalog.iOS/ControlCatalog.iOS.csproj
  samples/ControlCatalog.iOS/Info.plist
  samples/ControlCatalog.tvOS/ControlCatalog.tvOS.csproj
  samples/ControlCatalog.tvOS/Entitlements.plist
  samples/ControlCatalog.tvOS/Info.plist
Labels: enhancement, os-macos
