Repository AvaloniaUI/Avalonia, pull requests merged in 2025-07, with the labels that each got.

#19167 Fix memory leak by clearing shared array pool references in LightweightObservableBase
  src/Avalonia.Base/Reactive/LightweightObservableBase.cs
Labels: bug, backport-candidate-11.3.x

#19188 Add OpenGlControlBase XML docs
  src/Avalonia.OpenGL/Controls/OpenGlControlBase.cs
  src/Avalonia.OpenGL/GlInterface.cs
Labels: enhancement, backport-candidate-11.3.x

#19189 Rename "Documentation" subfolder into "docs"
  docs/api-compat.md
  docs/build.md
  docs/debug-xaml-compiler.md
  docs/images/xcode-product-path.png
  docs/index.md
  docs/macos-native.md
  docs/porting-code-from-3rd-party-sources.md
  docs/release.md
  readme.md
Labels: area-infrastructure

#18981 [12.0] Target SkiaSharp 3.0. Drop 2.88 support
  api/Avalonia.Skia.nupkg.xml
  build/SkiaSharp.props
  src/Skia/Avalonia.Skia/Avalonia.Skia.csproj
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
  src/Skia/Avalonia.Skia/Gpu/Metal/SkiaMetalApi.cs
  src/Skia/Avalonia.Skia/Gpu/Metal/SkiaMetalGpu.cs
  src/Skia/Avalonia.Skia/Gpu/Vulkan/VulkanSkiaExternalObjectsFeature.cs
  src/Skia/Avalonia.Skia/Gpu/Vulkan/VulkanSkiaRenderTarget.cs
  src/Skia/Avalonia.Skia/IDrawableBitmapImpl.cs
  src/Skia/Avalonia.Skia/ImmutableBitmap.cs
  src/Skia/Avalonia.Skia/SkiaSharpExtensions.cs
  src/Skia/Avalonia.Skia/SurfaceRenderTarget.cs
  src/Skia/Avalonia.Skia/WriteableBitmapImpl.cs
  src/iOS/Avalonia.iOS/Metal/MetalPlatformGraphics.cs
  tests/Avalonia.RenderTests/TestBase.cs
  tests/Avalonia.Skia.RenderTests/Avalonia.Skia.RenderTests.csproj
Labels: area-skia, breaking-change

#19208 Fix TextLineIImpl.GetTextBounds for clustered trailing zero width characters
  src/Avalonia.Base/Media/TextFormatting/TextLineImpl.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextFormatterTests.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextLineTests.cs
Labels: bug, customer-priority, backport-candidate-11.3.x

#19225 Revert 15603, add InputPaneActivationRequested in TextInputMethodClient
  src/Android/Avalonia.Android/Platform/Input/AndroidInputMethod.cs
  src/Avalonia.Base/Input/TextInput/TextInputMethodClient.cs
  src/Avalonia.Controls/TextBox.cs
  src/Avalonia.Controls/TextBoxTextInputMethodClient.cs
  src/Browser/Avalonia.Browser/BrowserTextInputMethod.cs
  src/Tizen/Avalonia.Tizen/NuiAvaloniaViewTextEditable.cs
Labels: enhancement, api-approved

#19251 [11.3] [Backport] #19208
  src/Avalonia.Base/Media/TextFormatting/TextLineImpl.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextFormatterTests.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextLineTests.cs
Labels: bug

#19100 Explicit dispose of GRBackendRenderTarget and SKSurfaceProperties
  src/Skia/Avalonia.Skia/Gpu/OpenGl/FboSkiaSurface.cs
Labels: bug, area-skia, backport-candidate-11.3.x

#18428 [X11] Added INCR support
  src/Avalonia.X11/Clipboard/ClipboardReadSession.cs
  src/Avalonia.X11/Clipboard/EventStreamWindow.cs
  src/Avalonia.X11/Clipboard/X11Clipboard.cs
  src/Avalonia.X11/X11Platform.cs
  src/Avalonia.X11/XLib.cs
Labels: feature, os-linux, area-x11

#19222 Use captured element if available as source for tap gestures
  src/Avalonia.Base/Input/Gestures.cs
  tests/Avalonia.Base.UnitTests/Input/GesturesTests.cs
  tests/Avalonia.UnitTests/MouseTestHelper.cs
Labels: bug, backport-candidate-11.3.x

#19227 [Grid] Fix inner size calculation when Row/ColumnDefinition is not set but spacing is set
  src/Avalonia.Controls/Grid.cs
  tests/Avalonia.Controls.UnitTests/GridTests.cs
Labels: bug, backport-candidate-11.3.x

#19245 Fix typo in XML documentation for ExtendClientAreaChromeHints enum
  src/Avalonia.Controls/Platform/ExtendClientAreaChromeHints.cs
Labels: enhancement

#19257 Typos fix
  samples/GpuInterop/VulkanDemo/VulkanContent.cs
  tests/Avalonia.Base.UnitTests/Data/ObjectConvertersTests_Equal.cs
  tests/Avalonia.Base.UnitTests/Data/ObjectConvertersTests_NotEqual.cs
Labels: enhancement

#19262 Fix X11Screen info update incorrectly when screen changed.
  src/Avalonia.X11/Screens/X11Screen.Providers.cs
  src/Avalonia.X11/Screens/X11Screens.cs
Labels: bug, area-x11, backport-candidate-11.3.x

#19320 Fixes/osx thick titlebar pointer events streaming, (tabs interface) #15696
  native/Avalonia.Native/src/OSX/AvnWindow.mm
  samples/IntegrationTestApp/Pages/WindowDecorationsPage.axaml
  samples/IntegrationTestApp/Pages/WindowDecorationsPage.axaml.cs
  samples/IntegrationTestApp/ShowWindowTest.axaml
  samples/IntegrationTestApp/ShowWindowTest.axaml.cs
  tests/Avalonia.IntegrationTests.Appium/PointerTests_MacOS.cs
Labels: bug, os-macos, backport-candidate-11.3.x

#19366 Add GroupBox
  samples/ControlCatalog/Pages/HeaderedContentPage.axaml
  src/Avalonia.Controls/GroupBox.cs
  src/Avalonia.Themes.Fluent/Accents/FluentControlResources.xaml
  src/Avalonia.Themes.Fluent/Controls/FluentControls.xaml
  src/Avalonia.Themes.Fluent/Controls/GroupBox.xaml
  src/Avalonia.Themes.Simple/Controls/GroupBox.xaml
  src/Avalonia.Themes.Simple/Controls/SimpleControls.xaml
Labels: feature, needs-api-review
