Repository AvaloniaUI/Avalonia, pull requests merged in 2025-06, with the labels that each got.

#18975 Implement IDispatcherImpl for Android based on Looper and MessageQueue
  src/Android/Avalonia.Android/AndroidDispatcherImpl.cs
  src/Android/Avalonia.Android/AndroidPlatform.cs
  src/Android/Avalonia.Android/AndroidThreadingInterface.cs
Labels: enhancement, os-android

#18980 Fix infinite animation memory leak.
  src/Avalonia.Base/Styling/StyleInstance.cs
Labels: bug, area-animations

#18989 Remove old linux hack
  src/Skia/Avalonia.Skia/Helpers/PixelFormatHelper.cs
Labels: enhancement

#18973 [Android] Do not underutilize CPU/GPU when can't keep up with refresh rate
  src/Android/Avalonia.Android/ChoreographerTimer.cs
Labels: enhancement, area-perf, os-android

#18991 Fix DirectX signatures
  src/Windows/Avalonia.Win32/DirectX/directx.idl
Labels: bug, os-windows, backport-candidate-11.3.x

#18990 Fix LostFocus not raised on macOS
  native/Avalonia.Native/src/OSX/AvnView.mm
Labels: bug, os-macos, customer-priority, backport-candidate-11.3.x

#18993 More IDL uint fixes
  src/Windows/Avalonia.Win32/DComposition/dcomp.idl
  src/Windows/Avalonia.Win32/Win32Com/win32.idl
Labels: bug, os-windows, backport-candidate-11.3.x

#18844 Fix insets on android 15
  api/Avalonia.nupkg.xml
  samples/ControlCatalog/MainView.xaml.cs
  samples/SafeAreaDemo/ViewModels/MainViewModel.cs
  src/Android/Avalonia.Android/Platform/AndroidInsetsManager.cs
  src/Avalonia.Controls/Platform/IInsetsManager.cs
  src/Browser/Avalonia.Browser/BrowserInsetsManager.cs
  src/iOS/Avalonia.iOS/InsetsManager.cs
Labels: bug, os-android, backport-candidate-11.3.x

#18511 Extend dirty rect when UseLayoutRounding=false
  src/Avalonia.Base/Layout/Layoutable.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionVisual.cs
  src/Avalonia.Base/composition-schema.xml
Labels: bug, customer-priority

#18373 Add ability to cancel focus change
  src/Avalonia.Base/Input/FocusChangingEventArgs.cs
  src/Avalonia.Base/Input/FocusManager.cs
  src/Avalonia.Base/Input/InputElement.cs
  src/Avalonia.Base/Input/KeyboardDevice.cs
  src/Avalonia.Controls/TopLevel.cs
  tests/Avalonia.Base.UnitTests/Input/KeyboardDeviceTests.cs
Labels: feature, api-approved

#19034 android: better api level detection for display edge to edge and ignore system bar color changes if on api level 35
  src/Android/Avalonia.Android/Platform/AndroidInsetsManager.cs
Labels: bug, os-android, backported-11.3.x

#18970 fix: Prevent DXGI from intercepting Alt+Enter and PrintScreen
  src/Windows/Avalonia.Win32/DirectX/DirectXEnums.cs
  src/Windows/Avalonia.Win32/DirectX/DxgiRenderTarget.cs
Labels: bug, os-windows

#19066 [Avalonia.Native] Respect info.plist values for setActivationPolicy
  native/Avalonia.Native/src/OSX/app.mm
  native/Avalonia.Native/src/OSX/main.mm
Labels: bug, os-macos, customer-priority, backport-candidate-11.3.x

#19075 [Avalonia.Controls] feature: Remove the need for MenuItem Icon to be a ILogical
  src/Avalonia.Controls/MenuItem.cs
Labels: enhancement, backport-candidate-11.3.x

#19076 Android - Revert changes preventing status bar theme from being updated
  src/Android/Avalonia.Android/Platform/AndroidInsetsManager.cs
Labels: bug, os-android, backport-candidate-11.3.x

#18718 feat: add TreeViewItemIndentConverter for dynamic margin calculation
  src/Avalonia.Controls/Converters/TreeViewItemIndentConverter.cs
  src/Avalonia.Themes.Fluent/Controls/TreeViewItem.xaml
  src/Avalonia.Themes.Simple/Controls/TreeViewItem.xaml
Labels: feature, api-approved

#19083 Android - Reset android input method focus and connection state when text input focus is removed
  src/Android/Avalonia.Android/Platform/Input/AndroidInputMethod.cs
Labels: bug, os-android, backport-candidate-11.3.x

#18837 Added missing class event handler methods
  src/Avalonia.Base/Input/InputElement.cs
  src/Avalonia.Controls/Control.cs
Labels: enhancement, api-approved

#19045 Cleanup InvalidationAwareSurfaceView related code
  src/Android/Avalonia.Android/ChoreographerTimer.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/AndroidFramebuffer.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/InvalidationAwareSurfaceView.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
  src/Android/Avalonia.Android/Platform/Specific/IAndroidView.cs
Labels: bug, area-perf, os-android

#19096 fix: reverse TickBar when Slider direction is reversed
  samples/ControlCatalog/Pages/SliderPage.xaml
  src/Avalonia.Themes.Fluent/Controls/Slider.xaml
Labels: bug, area-fluent, backport-candidate-11.3.x

#19106 feat: expose Popup property in PopupFlyoutBase for external access.
  src/Avalonia.Controls/Flyouts/PopupFlyoutBase.cs
Labels: enhancement, api-approved

#19090 Properly handle in cluster ShapedBuffer split
  src/Avalonia.Base/Media/TextFormatting/ShapedBuffer.cs
  src/Avalonia.Base/Media/TextFormatting/ShapedTextRun.cs
  src/Avalonia.Base/Media/TextFormatting/TextFormatterImpl.cs
  tests/Avalonia.Skia.UnitTests/Fonts/CascadiaCode.ttf
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextShaperTests.cs
Labels: bug, customer-priority, backport-candidate-11.2.x, backport-candidate-11.3.x

#18893 Add IActivityApplicationLifetime for android
  samples/ControlCatalog/App.xaml.cs
  samples/SafeAreaDemo/App.xaml.cs
  samples/SingleProjectSandbox/App.axaml.cs
  src/Android/Avalonia.Android/ApplicationLifetime.cs
  src/Android/Avalonia.Android/AvaloniaAndroidApplication.cs
  src/Android/Avalonia.Android/AvaloniaMainActivity.cs
  src/Android/Avalonia.Android/SingleViewLifetime.cs
  src/Avalonia.Controls/ApplicationLifetimes/IActivityApplicationLifetime.cs
Labels: feature, breaking-change, wont-backport, os-android, api-approved

#19128 Fix typo: `ExternalGLibMainLoopExceptionLogger`
  samples/XEmbedSample/Program.cs
  src/Avalonia.X11/Dispatching/GLibDispatcherImpl.cs
  src/Avalonia.X11/X11Platform.cs
Labels: enhancement, breaking-change, area-x11

#19140 remove Settings.StyleCop from sln
  Avalonia.sln
Labels: enhancement

#19133 Remove `PropertyPath`.
  api/Avalonia.nupkg.xml
  src/Avalonia.Base/Data/Core/PropertyPath.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlCompiler.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlPropertyPathTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlSetterTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/XamlPropertyPathException.cs
Labels: enhancement, breaking-change, area-bindings

#19137 remove some redundant returns
  src/Avalonia.Base/Animation/Animators/BoolAnimator.cs
  src/Avalonia.Controls/Automation/Peers/SelectingItemsControlAutomationPeer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlLanguageParseIntrinsics.cs
Labels: enhancement

#19147 Fixed failing to match the focus state in ComboBox
  src/Avalonia.Themes.Fluent/Controls/ComboBox.xaml
Labels: bug, backport-candidate-11.2.x, backport-candidate-11.3.x

#19146 remove some un-used code
  src/Avalonia.X11/X11Window.cs
  src/Headless/Avalonia.Headless/AvaloniaHeadlessPlatform.cs
  src/Headless/Avalonia.Headless/HeadlessPlatformRenderInterface.cs
  src/Headless/Avalonia.Headless/HeadlessWindowImpl.cs
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
  src/tools/Avalonia.Generators/NameGenerator/Options.cs
  src/tools/DevGenerators/CompositionGenerator/Generator.Utils.cs
  src/tools/DevGenerators/CompositionGenerator/Generator.cs
Labels: enhancement
