Repository AvaloniaUI/Avalonia, pull requests merged in 2025-02, with the labels that each got.

#17680 Try fix Korean IME on iOS
  src/iOS/Avalonia.iOS/TextInputResponder.cs
Labels: bug, backport-candidate-11.2.x

#18092 Enable light dismiss on CalendarDatePicker popup in simple theme
  src/Avalonia.Themes.Simple/Controls/CalendarDatePicker.xaml
Labels: bug, regression

#18004 Fixed unnecessary window displacement on resize
  samples/IntegrationTestApp/ShowWindowTest.axaml
  samples/IntegrationTestApp/ShowWindowTest.axaml.cs
  src/Windows/Avalonia.Win32/WindowImpl.cs
  tests/Avalonia.IntegrationTests.Appium/WindowTests.cs
Labels: bug, os-windows

#17714 [ScrollViewerPresenter] Fix rtl scroll (#16667)
  src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
Labels: bug

#18082 feat: Support pressure and tilt on macos
  native/Avalonia.Native/src/OSX/AvnView.mm
  native/Avalonia.Native/src/OSX/AvnWindow.mm
  src/Avalonia.Native/TopLevelImpl.cs
  src/Avalonia.Native/avn.idl
Labels: feature, os-macos

#17977 [DockPanel] Add Spacing properties
  src/Avalonia.Controls/DockPanel.cs
  tests/Avalonia.Controls.UnitTests/DockPanelTests.cs
Labels: feature, api-approved

#18049 Fix SelectableTextBlock selection
  src/Avalonia.Controls/SelectableTextBlock.cs
Labels: bug, backport-candidate-11.2.x

#18126 Fix NSEvent.subType assertion
  native/Avalonia.Native/src/OSX/AvnView.mm
Labels: bug, os-macos

#18047 Fix - Complete window dialog task when dialog is hidden
  src/Avalonia.Controls/Window.cs
  tests/Avalonia.Controls.UnitTests/WindowTests.cs
Labels: bug

#18113 FontFamily.FamilyTypefaces support
  src/Avalonia.Base/Media/FontFamily.cs
  src/Avalonia.Base/Media/FontManager.cs
  src/Avalonia.Base/Media/Fonts/EmbeddedFontCollection.cs
  src/Avalonia.Base/Media/Fonts/IFontCollection.cs
  src/Avalonia.Base/Media/Fonts/SystemFontCollection.cs
  src/Avalonia.Base/Media/Fonts/Tables/OS2Table.cs
  src/Avalonia.Base/Platform/IFontManagerImpl.cs
  src/Avalonia.Fonts.Inter/Assets/Inter-ExtraLight.ttf
  src/Skia/Avalonia.Skia/FontManagerImpl.cs
  src/Skia/Avalonia.Skia/GlyphTypefaceImpl.cs
  tests/Avalonia.Skia.UnitTests/Media/FontManagerTests.cs
Labels: feature

#18069 make _lastKnownPosition trackable at dragging
  src/Avalonia.Base/Input/PointerOverPreProcessor.cs
Labels: bug, backport-candidate-11.2.x

#18125 Fix DevTools bindings
  src/Avalonia.Diagnostics/Diagnostics/Views/ControlDetailsView.xaml
Labels: bug, area-dev-tools, backport-candidate-11.2.x

#18132 Warning AVLN2208: Item container in the data template
  .editorconfig
  build/WarnAsErrors.props
  src/Avalonia.Diagnostics/Diagnostics/Views/EventsPageView.xaml
  src/Avalonia.Diagnostics/Diagnostics/Views/EventsPageView.xaml.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlDiagnosticCodes.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlCompiler.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlDataTemplateWarningsTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/XamlIlTests.cs
Labels: enhancement, area-xaml

#18166 Correct which types receive `CompilerGeneratedAttribute`
  src/Avalonia.Build.Tasks/XamlCompilerTaskExecutor.cs
Labels: enhancement, area-xaml

#18164 [SKIA] Don't re-create SKImage on every WriteableBitmap draw call
  src/Skia/Avalonia.Skia/WriteableBitmapImpl.cs
Labels: bug, backport-candidate-11.2.x

#18197 Fix typo in SetValue validation exception message
  src/Avalonia.Base/PropertyStore/ValueStore.cs
Labels: bug, backport-candidate-11.2.x

#18198 Add FontSize property validation
  src/Avalonia.Controls/Documents/TextElement.cs
Labels: enhancement

#18154 DataGrd: Use VisualBrush to generate DragIndicator if Header is a Control.
  src/Avalonia.Controls.DataGrid/DataGridColumnHeader.cs
Labels: bug, area-datagrid, backport-candidate-11.2.x

#18103 Warning fixes: '25 winter wave
  samples/UnloadableAssemblyLoadContext/UnloadableAssemblyLoadContext/UnloadableAssemblyLoadContext.csproj
  samples/UnloadableAssemblyLoadContext/UnloadableAssemblyLoadContextPlug/UnloadableAssemblyLoadContextPlug.csproj
  samples/XEmbedSample/HarfbuzzWorkaround.cs
  samples/XEmbedSample/Program.cs
  samples/XEmbedSample/SocketEx.cs
  src/Avalonia.Base/Media/TextFormatting/Unicode/PropertyValueAliasHelper.cs
  src/Avalonia.Controls/TextBox.cs
  src/Headless/Avalonia.Headless/HeadlessPlatformStubs.cs
  src/Windows/Avalonia.Win32.Automation/GlobalSuppressions.cs
  tests/Avalonia.Base.UnitTests/Animation/AnimationIterationTests.cs
  tests/Avalonia.Base.UnitTests/Collections/AvaloniaListTests.cs
  tests/Avalonia.Base.UnitTests/DispatcherTests.cs
  tests/Avalonia.Base.UnitTests/Media/TextFormatting/BiDiClassTests.cs
  tests/Avalonia.Base.UnitTests/Media/TextFormatting/UnicodeEnumsGenerator.cs
  tests/Avalonia.Base.UnitTests/Utilities/StringTokenizerTests.cs
  tests/Avalonia.Build.Tasks.UnitTest/CompileAvaloniaXamlTaskTest.cs
  tests/Avalonia.Controls.DataGrid.UnitTests/Collections/ComparerTests.cs
  tests/Avalonia.Controls.UnitTests/GridLengthTests.cs
  tests/Avalonia.Controls.UnitTests/MaskedTextBoxTests.cs
  tests/Avalonia.Controls.UnitTests/Platform/ScreensTests.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
  tests/Avalonia.Controls.UnitTests/WindowTests.cs
  tests/Avalonia.DesignerSupport.Tests/RemoteProtocolTests.cs
  tests/Avalonia.Generators.Tests/XamlXNameResolverTests.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/CompiledBindingExtensionTests.cs
  tests/Avalonia.RenderTests/TestBase.cs
  tests/Avalonia.RenderTests/TestRenderHelper.cs
  tests/Avalonia.Skia.UnitTests/Media/EmbeddedFontCollectionTests.cs
  tests/Avalonia.Skia.UnitTests/Media/FontCollectionTests.cs
Labels: enhancement

#18206 #18192 Fix Implicit x:DataType defining for InheritDataTypeFromItems …
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlDataContextTypeTransformer.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/CompiledBindingExtensionTests.cs
Labels: bug, area-xaml, backport-candidate-11.2.x

#18150 Add Analyzer and CodeFixProvider for Initializing Bitmap with a "avares" scheme argument.
  src/tools/Avalonia.Analyzers/Avalonia.Analyzers.csproj
  src/tools/Avalonia.Analyzers/BitmapAnalyzer.cs
  src/tools/Avalonia.Analyzers/BitmapAnalyzerCSCodeFixProvider.cs
Labels: feature, area-analyzers

#18261 Fix DockPanel index out of range
  src/Avalonia.Controls/DockPanel.cs
  tests/Avalonia.Controls.UnitTests/DockPanelTests.cs
Labels: bug

#18255 TextBox: clear selection when moving the caret horizontally
  src/Avalonia.Controls/TextBox.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
Labels: bug, backport-candidate-11.2.x

#18285 Fix Win32 MonitorFromRect
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/Windows/Avalonia.Win32/ScreenImpl.cs
Labels: bug, os-windows, backport-candidate-11.2.x

#18290 Root assemblies for SRE XAML loader
  src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs
  tests/Avalonia.Markup.Xaml.UnitTests/XamlTestBase.cs
Labels: bug, backport-candidate-11.2.x

#18286 [X11] Use XcursorLibraryLoadCursor for dnd cursors
  src/Avalonia.X11/X11CursorFactory.cs
  src/Avalonia.X11/XLib.cs
Labels: bug, area-x11, backport-candidate-11.2.x

#18287 In-process dnd should always handle pointermoved for consistency withactual dnd
  src/Avalonia.Controls/Platform/InProcessDragSource.cs
Labels: enhancement, backport-candidate-11.2.x

#18288 Don't alter any InputElement properties from in-process dnd handler
  src/Avalonia.Controls/Platform/InProcessDragSource.cs
  src/Avalonia.Controls/TopLevel.cs
Labels: bug, backport-candidate-11.2.x

#18310 Fix TextLayout.Width calculation (#18305)
  src/Avalonia.Base/Media/TextFormatting/TextLayout.cs
  tests/Avalonia.Skia.UnitTests/Avalonia.Skia.UnitTests.csproj
  tests/Avalonia.Skia.UnitTests/Fonts/WinSymbols3.ttf
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextLayoutTests.cs
Labels: bug, backport-candidate-11.2.x

#18313 Fix SlicedStream.Seek(offset, SeekOrigin.End)
  src/Avalonia.Base/Platform/Internal/SlicedStream.cs
  tests/Avalonia.Base.UnitTests/Platform/SlicedStreamTests.cs
Labels: bug, backport-candidate-11.1.x, backport-candidate-11.2.x

#18338 Fix Window.MeasureOverride measuring with the old ClientSize
  src/Avalonia.Controls/Window.cs
  tests/Avalonia.Controls.UnitTests/WindowTests.cs
Labels: bug, customer-priority, backport-candidate-11.2.x
