Repository AvaloniaUI/Avalonia, pull requests merged in 2025-01, with the labels that each got.

#16805 Added `Binding.Delay` feature
  src/Avalonia.Base/Data/Core/BindingExpression.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindingExtension.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/ReflectionBindingExtension.cs
  src/Markup/Avalonia.Markup/Data/Binding.cs
  src/Markup/Avalonia.Markup/Data/BindingBase.cs
  tests/Avalonia.Markup.UnitTests/Data/BindingTests_Delay.cs
Labels: feature

#17895 Add ISkiaGpuWithPlatformGraphicsContext interface to vulkan skia gpu
  src/Skia/Avalonia.Skia/Gpu/Vulkan/VulkanSkiaGpu.cs
Labels: enhancement, area-rendering, backport-candidate-11.2.x

#17814 Nullable annotations for X11
  src/Avalonia.X11/Avalonia.X11.csproj
  src/Avalonia.X11/Dispatching/GLibDispatcherImpl.cs
  src/Avalonia.X11/Dispatching/X11PlatformThreading.cs
  src/Avalonia.X11/Glx/Glx.cs
  src/Avalonia.X11/Glx/GlxContext.cs
  src/Avalonia.X11/Glx/GlxDisplay.cs
  src/Avalonia.X11/Glx/GlxGlPlatformSurface.cs
  src/Avalonia.X11/Glx/GlxPlatformFeature.cs
  src/Avalonia.X11/Interop/Glib.cs
  src/Avalonia.X11/NativeDialogs/Gtk.cs
  src/Avalonia.X11/NativeDialogs/GtkNativeFileDialogs.cs
  src/Avalonia.X11/SMLib.cs
  src/Avalonia.X11/Screens/X11Screen.Providers.cs
  src/Avalonia.X11/Screens/X11Screens.Scaling.cs
  src/Avalonia.X11/Screens/X11Screens.cs
  src/Avalonia.X11/TransparencyHelper.cs
  src/Avalonia.X11/Vulkan/VulkanSupport.cs
  src/Avalonia.X11/X11Atoms.cs
  src/Avalonia.X11/X11Clipboard.cs
  src/Avalonia.X11/X11CursorFactory.cs
  src/Avalonia.X11/X11FramebufferSurface.cs
  src/Avalonia.X11/X11Globals.cs
  src/Avalonia.X11/X11IconLoader.cs
  src/Avalonia.X11/X11Info.cs
  src/Avalonia.X11/X11NativeControlHost.cs
  src/Avalonia.X11/X11Platform.cs
  src/Avalonia.X11/X11PlatformLifetimeEvents.cs
  src/Avalonia.X11/X11Structs.cs
  src/Avalonia.X11/X11Window.Ime.cs
  src/Avalonia.X11/X11Window.Xim.cs
  src/Avalonia.X11/X11Window.cs
  src/Avalonia.X11/X11WindowModes/InputProxyWindowMode.cs
  src/Avalonia.X11/X11WindowModes/WindowMode.cs
  src/Avalonia.X11/X11WindowModes/XEmbedClientWindowMode.cs
  src/Avalonia.X11/XEmbedPlug.cs
  src/Avalonia.X11/XEmbedTrayIconImpl.cs
  src/Avalonia.X11/XI2Manager.cs
  src/Avalonia.X11/XLib.cs
  src/Avalonia.X11/XResources.cs
Labels: enhancement, os-linux

#17932 Respect TextBox.VerticalContentAlignment for inner contents in fluent theme
  src/Avalonia.Themes.Fluent/Controls/TextBox.xaml
Labels: bug, area-fluent

#17924 Reset bidi levels of trailing whitespace after text wrapping (According to TR9 guidelines)
  src/Avalonia.Base/Media/TextFormatting/ShapedBuffer.cs
  src/Avalonia.Base/Media/TextFormatting/TextFormatterImpl.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextFormatterTests.cs
Labels: bug, area-textprocessing

#17948 Update compat dispatcher priorities
  src/Avalonia.Base/Threading/DispatcherPriority.cs
Labels: bug, backport-candidate-11.1.x, backport-candidate-11.2.x

#17968 End/close AppKit sheets attached on window when we hide it
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
Labels: bug, customer-priority, backport-candidate-11.2.x

#17986 Fix wrong horizontal snap point parameter.
  src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
Labels: bug, backport-candidate-11.2.x

#18001 Fixes/skia dash array
  tests/Avalonia.RenderTests/Shapes/LineTests.cs
  tests/TestFiles/Direct2D1/Shapes/Line/Lines_With_DashArray.expected.png
  tests/TestFiles/Skia/Shapes/Line/Lines_With_DashArray.expected.png
Labels: bug, backport-candidate-11.2.x

#17704 Implement support for Android TalkBack
  src/Android/Avalonia.Android/Automation/ExpandCollapseNodeInfoProvider.cs
  src/Android/Avalonia.Android/Automation/INodeInfoProvider.cs
  src/Android/Avalonia.Android/Automation/InvokeNodeInfoProvider.cs
  src/Android/Avalonia.Android/Automation/NodeInfoProvider.cs
  src/Android/Avalonia.Android/Automation/RangeValueNodeInfoProvider.cs
  src/Android/Avalonia.Android/Automation/ScrollNodeInfoProvider.cs
  src/Android/Avalonia.Android/Automation/SelectionItemNodeInfoProvider.cs
  src/Android/Avalonia.Android/Automation/ToggleNodeInfoProvider.cs
  src/Android/Avalonia.Android/Automation/ValueNodeInfoProvider.cs
  src/Android/Avalonia.Android/AvaloniaAccessHelper.cs
  src/Android/Avalonia.Android/AvaloniaView.cs
  src/Avalonia.Controls/Automation/Peers/EmbeddableControlRootAutomationPeer.cs
  src/Avalonia.Controls/Automation/Peers/TextBoxAutomationPeer.cs
  src/Avalonia.Controls/Automation/ValuePatternIdentifiers.cs
  src/Avalonia.Controls/Embedding/EmbeddableControlRoot.cs
Labels: feature, os-android, area-accessibility

#17925 [Skia] Fix RadialGradientBrush for non center origin
  src/Skia/Avalonia.Skia/DrawingContextImpl.cs
  tests/Avalonia.RenderTests/Media/RadialGradientBrushTests.cs
  tests/TestFiles/Direct2D1/Media/RadialGradientBrush/RadialGradientBrush_Partial_Cover.expected.png
  tests/TestFiles/Skia/Media/RadialGradientBrush/RadialGradientBrush_Partial_Cover.expected.png
Labels: bug, customer-priority, backport-candidate-11.2.x

#17815 feat: add hidesuggestions property to textbox
  samples/ControlCatalog/Pages/TextBoxPage.xaml
  src/Android/Avalonia.Android/Platform/Input/AndroidInputMethod.cs
  src/Avalonia.Base/Input/TextInput/TextInputOptions.cs
  src/iOS/Avalonia.iOS/TextInputResponder.Properties.cs
Labels: enhancement, api-change-requested

#18008 Fix in HeadlessClipboardStub.GetDataAsync where format is not considered
  src/Headless/Avalonia.Headless/HeadlessPlatformStubs.cs
Labels: bug, area-headless, backport-candidate-11.2.x

#17656 [TextBox] Add readonly property: LineCount.
  src/Avalonia.Controls/TextBox.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
Labels: feature, api-change-requested

#17993 add spacing to uniform grid - issue 8406
  src/Avalonia.Controls/Primitives/UniformGrid.cs
  tests/Avalonia.Controls.UnitTests/Primitives/UniformGridTests.cs
Labels: enhancement, api-approved

#18005 Support activation with universal links
  src/iOS/Avalonia.iOS/AvaloniaAppDelegate.cs
Labels: enhancement, os-ios

#18029 Bump Avalonia.BuildServices
  packages/Avalonia/Avalonia.csproj
Labels: area-infrastructure, backport-candidate-11.2.x

#17771 Access single file or folder from IStorageFolder by name
  api/Avalonia.nupkg.xml
  src/Android/Avalonia.Android/Platform/Storage/AndroidStorageItem.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageFolder.cs
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageItem.cs
  src/Avalonia.Base/Platform/Storage/IStorageFolder.cs
  src/Avalonia.Native/StorageItem.cs
  src/Browser/Avalonia.Browser/Interop/StorageHelper.cs
  src/Browser/Avalonia.Browser/Storage/BrowserStorageProvider.cs
  src/Browser/Avalonia.Browser/webapp/modules/storage/storageItem.ts
  src/iOS/Avalonia.iOS/Storage/IOSStorageItem.cs
Labels: enhancement, api-approved

#17312 Add new constructor to AvaloniaDictionary and include unit tests #17311
  src/Avalonia.Base/Collections/AvaloniaDictionary.cs
  tests/Avalonia.Base.UnitTests/Collections/AvaloniaDictionaryTests.cs
Labels: enhancement, api-approved

#18034 Clear `Imm32InputMethod.Composition` after receiving `cancel` message (`WM_IME_COMPOSITION` with `lParam` set to `0`)
  src/Windows/Avalonia.Win32/Input/Imm32InputMethod.cs
Labels: bug, os-windows, backport-candidate-11.2.x

#17960 [Refactor] Get trailing whitespace length from the glyph run metrics
  src/Avalonia.Base/Media/TextFormatting/TextFormatterImpl.cs
Labels: enhancement, area-textprocessing

#18026 Fix style without selector not finding target type
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlSelectorTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/StyleTests.cs
Labels: bug, area-xaml, backport-candidate-11.2.x

#18062 Make sure MacOS uses the cached value for render scaling.
  src/Avalonia.Native/TopLevelImpl.cs
Labels: enhancement, area-perf, backport-candidate-11.2.x

#17792 Added `WrapPanel` item alignment
  src/Avalonia.Controls/WrapPanel.cs
  tests/Avalonia.Controls.UnitTests/WrapPanelTests.cs
Labels: feature, api-approved

#5629 Add Popup.ShouldUseOverlayLayer property
  src/Avalonia.Controls/Primitives/OverlayPopupHost.cs
  src/Avalonia.Controls/Primitives/Popup.cs
  tests/Avalonia.Controls.UnitTests/Primitives/PopupTests.cs
Labels: feature

#18025 Path Geometry update fix for 4748 bug rerender on change for paths segments
  src/Avalonia.Base/Media/PathGeometry.cs
  tests/Avalonia.Base.UnitTests/Media/PathGeometryTests.cs
Labels: bug, backport-candidate-11.2.x

#18030 Fix Korean IME on Android
  src/Android/Avalonia.Android/Platform/Input/AndroidInputMethod.cs
Labels: backport-candidate-11.2.x

#17998 [TextTrimming] Fixed some text trimming bugs
  src/Avalonia.Base/Media/TextFormatting/LogicalTextRunEnumerator.cs
  src/Avalonia.Base/Media/TextFormatting/TextCollapsingProperties.cs
  src/Avalonia.Base/Media/TextFormatting/TextEllipsisHelper.cs
  src/Avalonia.Base/Media/TextFormatting/TextLeadingPrefixCharacterEllipsis.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextFormatterTests.cs
Labels: backport-candidate-11.2.x

#17922 TextLayout: TextStyleOverrides aren't applied correctly
  src/Avalonia.Base/Media/TextFormatting/FormattedTextSource.cs
  tests/Avalonia.Base.UnitTests/Media/TextFormatting/FormattedTextSourceTests.cs
Labels: bug, area-textprocessing, backport-candidate-11.2.x

#18076 Fix ManagedStorageProvider OverwritePrompt behaviour
  src/Avalonia.Dialogs/ManagedStorageProvider.cs
Labels: bug, backport-candidate-11.2.x
