Repository AvaloniaUI/Avalonia, pull requests merged in 2025-04, with the labels that each got.

#18405 Implement TextSearch.TextBinding
  samples/ControlCatalog/Pages/ComboBoxPage.xaml
  samples/ControlCatalog/ViewModels/ComboBoxPageViewModel.cs
  src/Avalonia.Controls/AutoCompleteBox/AutoCompleteBox.cs
  src/Avalonia.Controls/Presenters/ItemsPresenter.cs
  src/Avalonia.Controls/Primitives/SelectingItemsControl.cs
  src/Avalonia.Controls/Primitives/TextSearch.cs
  src/Avalonia.Controls/Utils/BindingEvaluator.cs
  src/Avalonia.Controls/VirtualizingPanel.cs
  tests/Avalonia.Controls.UnitTests/ComboBoxTests.cs
Labels: feature, api-approved

#16846 Feature - Container Queries
  Avalonia.sln
  samples/ControlCatalog/Assets/image1.jpg
  samples/ControlCatalog/Assets/image2.jpg
  samples/ControlCatalog/Assets/image3.jpg
  samples/ControlCatalog/Assets/image4.jpg
  samples/ControlCatalog/Assets/image5.jpg
  samples/ControlCatalog/Assets/image6.jpg
  samples/ControlCatalog/Assets/image7.jpg
  samples/ControlCatalog/ControlCatalog.csproj
  samples/ControlCatalog/MainView.xaml
  samples/ControlCatalog/Pages/ContainerQueryPage.xaml
  samples/ControlCatalog/Pages/ContainerQueryPage.xaml.cs
  src/Avalonia.Base/Layout/Layoutable.cs
  src/Avalonia.Base/Platform/VisualQueryProvider.cs
  src/Avalonia.Base/StyledElement.cs
  src/Avalonia.Base/Styling/Activators/AndQueryActivator.cs
  src/Avalonia.Base/Styling/Activators/AndQueryActivatorBuilder.cs
  src/Avalonia.Base/Styling/Activators/ContainerQueryActivatorBase.cs
  src/Avalonia.Base/Styling/Activators/OrQueryActivator.cs
  src/Avalonia.Base/Styling/Activators/OrQueryActivatorBuilder.cs
  src/Avalonia.Base/Styling/Activators/ScreenActivator.cs
  src/Avalonia.Base/Styling/AndQuery.cs
  src/Avalonia.Base/Styling/Container.cs
  src/Avalonia.Base/Styling/ContainerQuery.cs
  src/Avalonia.Base/Styling/ContainerSizing.cs
  src/Avalonia.Base/Styling/OrQuery.cs
  src/Avalonia.Base/Styling/ScreenQueries.cs
  src/Avalonia.Base/Styling/Selector.cs
  src/Avalonia.Base/Styling/Style.cs
  src/Avalonia.Base/Styling/StyleQueries.cs
  src/Avalonia.Base/Styling/StyleQuery.cs
  src/Avalonia.Base/Styling/StyleQueryComparisonOperator.cs
  src/Avalonia.Base/Styling/ValueStyleQuery.cs
  src/Avalonia.Base/Utilities/IdentifierParser.cs
  src/Avalonia.Build.Tasks/Avalonia.Build.Tasks.csproj
  src/Avalonia.Controls/Border.cs
  src/Avalonia.Controls/ContentControl.cs
  src/Avalonia.Controls/Decorator.cs
  src/Avalonia.Controls/Presenters/ContentPresenter.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Avalonia.Controls/WindowBase.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/AvaloniaXamlIlCompiler.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlControlTemplateTargetTypeMetadataTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlQueryTransformer.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs
  src/Markup/Avalonia.Markup/Markup/Parsers/ContainerQueryGrammar.cs
  src/Markup/Avalonia.Markup/Markup/Parsers/ContainerQueryParser.cs
  src/Markup/Avalonia.Markup/Markup/Parsers/SelectorGrammar.cs
  tests/Avalonia.Base.UnitTests/Styling/ContainerTests.cs
Labels: feature, api-approved

#18583 Fix binding null conditional operator not working with AvaloniaProperty
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/XamlIlBindingPathHelper.cs
  tests/Avalonia.Base.UnitTests/Data/Core/NullConditionalBindingTests.cs
Labels: bug, area-bindings, backport-candidate-11.3.x

#18584 Fix DateTimePickerPanel scrolling exception
  src/Avalonia.Controls/DateTimePickers/DateTimePickerPanel.cs
  tests/Avalonia.Controls.UnitTests/DatePickerTests.cs
  tests/Avalonia.Controls.UnitTests/TimePickerTests.cs
Labels: bug, backport-candidate-11.3.x

#18438 Fix issue with OverhangLeading
  src/Avalonia.Base/Media/TextFormatting/TextLayout.cs
  src/Avalonia.Controls/Presenters/TextPresenter.cs
  src/Avalonia.Controls/TextBlock.cs
  src/Skia/Avalonia.Skia/GlyphRunImpl.cs
  src/Windows/Avalonia.Direct2D1/Media/GlyphRunImpl.cs
  tests/Avalonia.Controls.UnitTests/TextBlockTests.cs
  tests/Avalonia.RenderTests/Assets/SourceSerif4_36pt-Italic.ttf
  tests/Avalonia.RenderTests/Controls/TextBlockTests.cs
  tests/Avalonia.Skia.UnitTests/Avalonia.Skia.UnitTests.csproj
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextLayoutTests.cs
  tests/TestFiles/Direct2D1/Controls/TextBlock/RestrictedHeight_VerticalAlign.expected.png
  tests/TestFiles/Direct2D1/Controls/TextBlock/Should_Account_For_Overhang_Leading_And_Trailing.expected.png
  tests/TestFiles/Direct2D1/Controls/TextBlock/Should_Draw_MultiLineText_WithOverHandLeadingTrailing.expected.png
  tests/TestFiles/Direct2D1/Controls/TextBlock/Should_Draw_Run_With_Background.expected.png
  tests/TestFiles/Direct2D1/Controls/TextBlock/Should_Draw_TextDecorations.expected.png
  tests/TestFiles/Direct2D1/Controls/TextBlock/Should_Keep_TrailingWhiteSpace.expected.png
  tests/TestFiles/Direct2D1/Controls/TextBlock/Should_Measure_Arrange_TextBlock_150_NoWrap.expected.png
  tests/TestFiles/Direct2D1/Controls/TextBlock/Should_Measure_Arrange_TextBlock_44_NoWrap.expected.png
  tests/TestFiles/Direct2D1/Controls/TextBlock/Should_Measure_Arrange_TextBlock_44_Wrap.expected.png
  tests/TestFiles/Direct2D1/Controls/TextBlock/Wrapping_NoWrap.expected.png
  tests/TestFiles/Skia/Controls/TextBlock/Should_Account_For_Overhang_Leading_And_Trailing.expected.png
  tests/TestFiles/Skia/Controls/TextBlock/Should_Draw_MultiLineText_WithOverHandLeadingTrailing.expected.png
  tests/TestFiles/Skia/Controls/TextBlock/Should_Keep_TrailingWhiteSpace.expected.png
Labels: bug, area-textprocessing, backport-candidate-11.2.x, backport-candidate-11.3.x

#18603 [Grid] Fix ColumnSpacing property name
  src/Avalonia.Controls/Grid.cs
Labels: bug, backport-candidate-11.3.x

#18605 Disable Metal by default on macOS for 11.3
  src/Avalonia.Native/AvaloniaNativePlatformExtensions.cs
Labels: bug, os-macos, backport-candidate-11.3.x

#18604 Fix Window.Show when MinWidth > MaxWidth
  src/Avalonia.Controls/Window.cs
  src/Avalonia.Dialogs/AboutAvaloniaDialog.xaml
  tests/Avalonia.Controls.UnitTests/WindowTests.cs
Labels: bug, regression, backport-candidate-11.3.x

#18624 Fix Windows Alt codes
  src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs
Labels: bug, os-windows, backport-candidate-11.2.x, backport-candidate-11.3.x

#18599 Fix datepicker not refreshing format when date format changes
  src/Avalonia.Controls/DateTimePickers/DatePicker.cs
  src/Avalonia.Controls/DateTimePickers/DatePickerPresenter.cs
Labels: bug, backport-candidate-11.2.x, backport-candidate-11.3.x

#18621 [Grid] Fix size calculation for ranges
  src/Avalonia.Controls/Grid.cs
  tests/Avalonia.Controls.UnitTests/GridTests.cs
Labels: bug, backport-candidate-11.3.x

#18651 Fix crash when creating documents in an opened folder on android
  src/Android/Avalonia.Android/Platform/Storage/AndroidStorageItem.cs
Labels: bug, os-android, backport-candidate-11.3.x

#18659 Fix height queries not matching when container name is set, remove unused query grammer and allow nesting selector in container styles
  src/Avalonia.Base/Styling/NestingSelector.cs
  src/Avalonia.Base/Styling/ScreenQueries.cs
  src/Markup/Avalonia.Markup/Markup/Parsers/ContainerQueryGrammar.cs
  tests/Avalonia.Base.UnitTests/Styling/ContainerTests.cs
Labels: bug, backport-candidate-11.3.x

#18679 Fix `MenuItem` enabled state in the presence of sub-items.
  src/Avalonia.Controls/MenuItem.cs
  tests/Avalonia.Controls.UnitTests/MenuItemTests.cs
Labels: bug, customer-priority, backport-candidate-11.2.x, backport-candidate-11.3.x

#18711 Update bug_report.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: area-infrastructure

#18719 Add XML doc comments to RegisterDirect warning about unsetValue and d…
  src/Avalonia.Base/AvaloniaProperty.cs
Labels: enhancement, backport-candidate-11.3.x

#18723 Added small banner about accelerate.
  src/Avalonia.Diagnostics/Diagnostics/Views/MainView.xaml
Labels: enhancement, backport-candidate-11.3.x

#18760 Fix null reference crash when window is closed during drag-and-drop
  native/Avalonia.Native/src/OSX/AvnView.mm
Labels: customer-priority

#18694 Fixes for DataValidationErrors not working correctly with Bindings (issue #18693)
  src/Avalonia.Controls/DataValidationErrors.cs
  tests/Avalonia.Controls.UnitTests/AutoCompleteBoxTests.cs
Labels: bug, area-bindings, backport-candidate-11.3.x
