Repository AvaloniaUI/Avalonia, pull requests merged in 2025-03, with the labels that each got.

#16778 feat(Window): Allow to persist content of Clipboard after App close
  api/Avalonia.nupkg.xml
  src/Android/Avalonia.Android/Platform/ClipboardImpl.cs
  src/Avalonia.Base/Input/Platform/IClipboard.cs
  src/Avalonia.DesignerSupport/Remote/Stubs.cs
  src/Avalonia.Native/ClipboardImpl.cs
  src/Avalonia.X11/X11Clipboard.cs
  src/Browser/Avalonia.Browser/ClipboardImpl.cs
  src/Headless/Avalonia.Headless/HeadlessPlatformStubs.cs
  src/Tizen/Avalonia.Tizen/NuiClipboardImpl.cs
  src/Windows/Avalonia.Win32/ClipboardImpl.cs
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/iOS/Avalonia.iOS/ClipboardImpl.cs
  tests/Avalonia.Controls.UnitTests/MaskedTextBoxTests.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
Labels: feature, api-approved

#18343 Bump DBus stack
  src/Avalonia.FreeDesktop/Avalonia.FreeDesktop.csproj
  src/Avalonia.FreeDesktop/DBusIme/DBusTextInputMethodBase.cs
  src/Avalonia.FreeDesktop/DBusIme/Fcitx/FcitxICWrapper.cs
  src/Avalonia.FreeDesktop/DBusIme/Fcitx/FcitxX11TextInputMethod.cs
  src/Avalonia.FreeDesktop/DBusIme/IBus/IBusX11TextInputMethod.cs
  src/Avalonia.FreeDesktop/DBusMenuExporter.cs
  src/Avalonia.FreeDesktop/DBusPlatformSettings.cs
  src/Avalonia.FreeDesktop/DBusSystemDialog.cs
  src/Avalonia.FreeDesktop/DBusTrayIconImpl.cs
Labels: enhancement, os-linux

#18361 Add ContentTemplate property to flyout
  src/Avalonia.Controls/Flyouts/Flyout.cs
Labels: enhancement, api-approved

#18314 Add diagnostic metrics/activities
  Avalonia.sln
  build/Base.props
  build/System.Memory.props
  src/Avalonia.Base/Avalonia.Base.csproj
  src/Avalonia.Base/Controls/ResourceNodeExtensions.cs
  src/Avalonia.Base/Diagnostics/Diagnostic.Activities.cs
  src/Avalonia.Base/Diagnostics/Diagnostic.Consts.cs
  src/Avalonia.Base/Diagnostics/Diagnostic.Metrics.cs
  src/Avalonia.Base/Diagnostics/Diagnostic.cs
  src/Avalonia.Base/Interactivity/EventRoute.cs
  src/Avalonia.Base/Interactivity/Interactive.cs
  src/Avalonia.Base/Interactivity/RoutedEvent.cs
  src/Avalonia.Base/Layout/LayoutManager.cs
  src/Avalonia.Base/Layout/Layoutable.cs
  src/Avalonia.Base/Rendering/Composition/CompositingRenderer.cs
  src/Avalonia.Base/Rendering/Composition/Server/ServerCompositionTarget.cs
  src/Avalonia.Base/Styling/ControlTheme.cs
  src/Avalonia.Base/Styling/Style.cs
  src/Avalonia.Base/Styling/StyleInstance.cs
  src/Avalonia.Base/Threading/DispatcherTimer.cs
  src/Avalonia.Base/Utilities/StopwatchHelper.cs
  src/Avalonia.Base/Visual.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/StaticResourceExtension.cs
  src/Markup/Avalonia.Markup/Avalonia.Markup.csproj
  tests/Avalonia.Controls.DataGrid.UnitTests/Avalonia.Controls.DataGrid.UnitTests.csproj
Labels: feature

#18077 [Grid] Add RowSpacing and ColumnSpacing
  src/Avalonia.Controls/Grid.cs
  tests/Avalonia.Controls.UnitTests/GridTests.cs
Labels: feature, api-approved

#18359 Bring control into view only if control isn't properly visible in viewport
  src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
  tests/Avalonia.Controls.UnitTests/Presenters/ScrollContentPresenterTests.cs
Labels: enhancement

#18385 Fix: TextBox having selection and pressing up / down arrows
  src/Avalonia.Controls/TextBox.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
Labels: bug, backport-candidate-11.2.x

#18379 Support complex types in datatype
  samples/BindingDemo/BindingDemo.csproj
  samples/BindingDemo/MainWindow.xaml
  samples/BindingDemo/MainWindow.xaml.cs
  samples/BindingDemo/TestItemView.xaml
  samples/BindingDemo/ViewModels/MainWindowViewModel.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlDataContextTypeTransformer.cs
  tests/Avalonia.Markup.Xaml.UnitTests/MarkupExtensions/CompiledBindingExtensionTests.cs
Labels: bug, area-xaml, backport-candidate-11.2.x

#18353 Improve KeyGesture.ToString() output in case when Key is set to Key.None
  src/Avalonia.Base/Input/KeyGesture.cs
  tests/Avalonia.Base.UnitTests/Input/KeyGestureTests.cs
Labels: enhancement

#18392 Introduce GlyphTypeface.FaceNames
  src/Avalonia.Base/Media/Fonts/Tables/Name/NameTable.cs
  src/Avalonia.Base/Media/IGlyphTypeface2.cs
  src/Skia/Avalonia.Skia/GlyphTypefaceImpl.cs
Labels: feature, customer-priority

#18349 Improve input behavior for Browser
  src/Browser/Avalonia.Browser/Interop/InputHelper.cs
  src/Browser/Avalonia.Browser/webapp/modules/avalonia/input.ts
Labels: bug, os-browser, backport-candidate-11.2.x

#18354 Implement SetItems method in ResourceDictionary
  src/Avalonia.Base/Controls/ResourceDictionary.cs
Labels: feature, api-approved

#18414 InputMethod should remove handler when remove handler
  src/Avalonia.Base/Input/InputMethod.cs
Labels: bug, backport-candidate-11.2.x

#18412 Added surface dispose to DrawingSurfaceDemoBase
  samples/GpuInterop/DrawingSurfaceDemoBase.cs
Labels: bug

#18416 Fix - Search for visual parents when hittesting for pointer events
  src/Avalonia.Controls/TopLevel.cs
  tests/Avalonia.Base.UnitTests/Input/PointerOverTests.cs
Labels: bug, customer-priority, backport-candidate-11.2.x

#18420 Raise pointer events on captured element
  src/Avalonia.Base/Input/PointerOverPreProcessor.cs
  tests/Avalonia.Base.UnitTests/Input/PointerOverTests.cs
Labels: bug

#18340 Added IClipboard:TryGetInProcessDataObjectAsyns
  api/Avalonia.nupkg.xml
  native/Avalonia.Native/src/OSX/clipboard.mm
  samples/ControlCatalog/Pages/ClipboardPage.xaml
  samples/ControlCatalog/Pages/ClipboardPage.xaml.cs
  src/Android/Avalonia.Android/Platform/ClipboardImpl.cs
  src/Avalonia.Base/Input/Platform/IClipboard.cs
  src/Avalonia.DesignerSupport/Remote/Stubs.cs
  src/Avalonia.Native/ClipboardImpl.cs
  src/Avalonia.Native/avn.idl
  src/Avalonia.X11/X11Clipboard.cs
  src/Browser/Avalonia.Browser/ClipboardImpl.cs
  src/Headless/Avalonia.Headless/HeadlessPlatformStubs.cs
  src/Tizen/Avalonia.Tizen/NuiClipboardImpl.cs
  src/Windows/Avalonia.Win32/ClipboardImpl.cs
  src/Windows/Avalonia.Win32/DataObject.cs
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/iOS/Avalonia.iOS/ClipboardImpl.cs
  tests/Avalonia.Controls.UnitTests/MaskedTextBoxTests.cs
  tests/Avalonia.Controls.UnitTests/TextBoxTests.cs
Labels: feature

#18270 Null conditional operator in bindings
  .ncrunch/XEmbedSample.net8.0.v3.ncrunchproject
  .ncrunch/XEmbedSample.netstandard2.0.v3.ncrunchproject
  src/Avalonia.Base/Data/Core/ExpressionNodes/PropertyAccessorNode.cs
  src/Avalonia.Base/Data/Core/ExpressionNodes/Reflection/DynamicPluginPropertyAccessorNode.cs
  src/Avalonia.Base/Data/Core/Parsers/BindingExpressionVisitor.cs
  src/Avalonia.Base/Utilities/CharacterReader.cs
  src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/XamlIlBindingPathHelper.cs
  src/Markup/Avalonia.Markup.Xaml/MarkupExtensions/CompiledBindings/CompiledBindingPath.cs
  src/Markup/Avalonia.Markup/Markup/Parsers/BindingExpressionGrammar.cs
  src/Markup/Avalonia.Markup/Markup/Parsers/ExpressionNodeFactory.cs
  tests/Avalonia.Base.UnitTests/Data/Core/ErrorCollectingTextBox.cs
  tests/Avalonia.Base.UnitTests/Data/Core/NullConditionalBindingTests.cs
  tests/Avalonia.Markup.UnitTests/Parsers/BindingExpressionGrammarTests.cs
  tests/Avalonia.Markup.UnitTests/Parsers/BindingExpressionGrammarTests_Errors.cs
  tests/Avalonia.Markup.UnitTests/Parsers/ExpressionNodeFactoryTests.cs
Labels: feature, area-bindings

#18430 Extend diagnostic TreeNode features to more types
  src/Avalonia.Base/StyledElement.cs
  src/Avalonia.Diagnostics/Diagnostics/ViewModels/TreeNode.cs
Labels: enhancement, area-dev-tools, backport-candidate-11.2.x

#18450 Fix DBus type in exported menu
  src/Avalonia.FreeDesktop/DBusMenuExporter.cs
Labels: bug, os-linux

#18464 [X11] attempt to use _NET_WM_STATE_FOCUSED or _NET_ACTIVE_WINDOW for tracking window activation, if available
  src/Avalonia.X11/ActivityTrackingHelper.cs
  src/Avalonia.X11/X11Atoms.cs
  src/Avalonia.X11/X11Globals.cs
  src/Avalonia.X11/X11Window.cs
  src/Avalonia.X11/XLib.Helpers.cs
  src/Avalonia.X11/XLib.cs
Labels: bug, os-linux, customer-priority

#18483 Make mobile TryGetPlatformHandle consistent
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
  src/Browser/Avalonia.Browser/BrowserTopLevelImpl.cs
  src/iOS/Avalonia.iOS/AvaloniaView.cs
Labels: enhancement, os-browser, os-ios, os-android, backport-candidate-11.1.x, backport-candidate-11.2.x

#18487 Fix file modified time in storage item properties
  src/Avalonia.Base/Platform/Storage/FileIO/BclStorageItem.cs
Labels: bug, backport-candidate-11.2.x

#18471 Fix Loaded being incorrectly raised for unloaded controls
  src/Avalonia.Controls/Control.cs
  tests/Avalonia.Controls.UnitTests/LoadedTests.cs
Labels: bug, backport-candidate-11.2.x

#18472 Added LogToDelegate and LogToTextWriter APIs
  src/Avalonia.Base/Logging/StringLogSink.cs
  src/Avalonia.Controls/LoggingExtensions.cs
Labels: feature

#18484 Default button should not fire Click event when button is not effectively visible
  src/Avalonia.Controls/Button.cs
  tests/Avalonia.Controls.UnitTests/ButtonTests.cs
Labels: bug, backport-candidate-11.2.x

#18473 Fix grid spacing messure issue
  src/Avalonia.Controls/Grid.cs
  tests/Avalonia.Controls.UnitTests/GridTests.cs
Labels: bug

#18507 Fix grid desired size error
  src/Avalonia.Controls/Grid.cs
  tests/Avalonia.Controls.UnitTests/GridTests.cs
Labels: bug

#18516 Prevented setting 0 to ColumnSpan or RowSpan.
  src/Avalonia.Controls/Grid.cs
Labels: enhancement

#18527 Dismiss popups when toplevel deactivates in embedded scenarios
  src/Avalonia.Controls/Primitives/Popup.cs
Labels: bug, customer-priority, backport-candidate-11.2.x

#18488 Avoid multiple resource change notifications
  src/Avalonia.Base/Controls/IResourceHost.cs
  src/Avalonia.Base/Controls/ResourceDictionary.cs
  src/Avalonia.Base/Controls/ResourceNodeExtensions.cs
  src/Avalonia.Base/Controls/ResourceProvider.cs
  src/Avalonia.Base/Controls/ResourcesChangedEventArgs.cs
  src/Avalonia.Base/Controls/ResourcesChangedHelper.cs
  src/Avalonia.Base/Controls/ResourcesChangedToken.cs
  src/Avalonia.Base/StyledElement.cs
  src/Avalonia.Base/Styling/StyleBase.cs
  src/Avalonia.Base/Utilities/IWeakEventSubscriber.cs
  src/Avalonia.Base/Utilities/WeakEvent.cs
  src/Avalonia.Controls/Application.cs
  src/Avalonia.Controls/Primitives/TemplatedControl.cs
  src/Avalonia.Controls/Primitives/VisualLayerManager.cs
  src/Avalonia.Controls/TopLevel.cs
  src/Markup/Avalonia.Markup.Xaml/Data/DynamicResourceExpression.cs
Labels: enhancement, area-perf, customer-priority, backport-candidate-11.2.x

#18079 [WrapPanel] Add Spacing Properties
  src/Avalonia.Controls/WrapPanel.cs
  tests/Avalonia.Controls.UnitTests/WrapPanelTests.cs
Labels: feature, api-approved

#18315 Layout performance improvements
  src/Avalonia.Base/Layout/LayoutHelper.cs
  src/Avalonia.Base/Layout/Layoutable.cs
  src/Avalonia.Base/Layout/MinMax.cs
  src/Avalonia.Base/Size.cs
  src/Avalonia.Base/StyledElement.cs
  src/Avalonia.Base/Threading/Dispatcher.cs
  src/Avalonia.Base/Utilities/MathUtilities.cs
  src/Avalonia.Base/Visual.cs
  src/Avalonia.Controls/Border.cs
  src/Avalonia.Controls/Presenters/ContentPresenter.cs
  src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
  src/Avalonia.Controls/Primitives/TemplatedControl.cs
  src/Avalonia.Controls/TextBlock.cs
  src/Avalonia.Controls/TopLevel.cs
  tests/Avalonia.Benchmarks/Layout/Measure.cs
  tests/Avalonia.Controls.UnitTests/Presenters/ScrollContentPresenterTests.cs
  tests/Avalonia.Controls.UnitTests/TextBlockTests.cs
  tests/Avalonia.Controls.UnitTests/WindowBaseTests.cs
  tests/Avalonia.Controls.UnitTests/WindowTests.cs
Labels: enhancement, area-perf

#18223 Optimization: Add an optimized path for notifying property changes for inherited va…
  src/Avalonia.Base/AvaloniaObject.cs
  src/Avalonia.Base/AvaloniaPropertyChangedEventArgs.cs
  src/Avalonia.Base/PropertyStore/ValueStore.cs
  tests/Avalonia.Benchmarks/Data/InheritedProperties.cs
Labels: enhancement, area-perf

#18538 Set build number to version on CI
  nukebuild/Build.cs
  nukebuild/BuildParameters.cs
Labels: enhancement, area-infrastructure

#18562 Fixed invalid monitor detection when changing window position
  src/Windows/Avalonia.Win32/WindowImpl.cs
Labels: bug, os-windows
