Repository AvaloniaUI/Avalonia, pull requests merged in 2025-08, with the labels that each got.

#19372 Use VisualBrush for GroupBox Border
  src/Avalonia.Themes.Fluent/Controls/GroupBox.xaml
  src/Avalonia.Themes.Simple/Controls/GroupBox.xaml
Labels: bug

#19364 [iOS] Implement Save File Picker Support
  samples/ControlCatalog.iOS/Info.plist
  src/iOS/Avalonia.iOS/Storage/IOSStorageProvider.cs
Labels: feature, os-ios, backport-candidate-11.3.x

#19289 Android - Restrict souce of input events to avalonia view
  src/Android/Avalonia.Android/AvaloniaActivity.cs
  src/Android/Avalonia.Android/AvaloniaView.Input.cs
  src/Android/Avalonia.Android/AvaloniaView.cs
  src/Android/Avalonia.Android/Platform/Input/AndroidInputMethod.cs
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
Labels: bug, os-android, backport-candidate-11.3.x

#19370 Implemented Dispatcher.Yield / Dispatcher.Resume
  api/Avalonia.nupkg.xml
  src/Avalonia.Base/Threading/Dispatcher.Invoke.cs
  src/Avalonia.Base/Threading/DispatcherPriorityAwaitable.cs
  tests/Avalonia.Base.UnitTests/DispatcherTests.cs
Labels: feature, breaking-change, wont-backport

#18646 Add a buffer cache to containers in VirtualizingStackPanel
  samples/ControlCatalog/Pages/ListBoxPage.xaml
  src/Avalonia.Controls/VirtualizingStackPanel.cs
  tests/Avalonia.Controls.UnitTests/VirtualizingStackPanelTests.cs
Labels: enhancement, area-perf, api-approved, backport-candidate-11.3.x

#19382 Enable tray icon creation in all circumstances when running as an admin
  src/Windows/Avalonia.Win32/Interop/UnmanagedMethods.cs
  src/Windows/Avalonia.Win32/TrayIconImpl.cs
  src/Windows/Avalonia.Win32/Win32Platform.cs
Labels: bug, os-windows, backport-candidate-11.3.x

#18094 IsEditable combox box
  samples/ControlCatalog/Pages/ComboBoxPage.xaml
  samples/ControlCatalog/ViewModels/ComboBoxPageViewModel.cs
  src/Avalonia.Controls/ComboBox.cs
  src/Avalonia.Controls/Utils/BindingEvaluator.cs
  src/Avalonia.Themes.Fluent/Controls/ComboBox.xaml
  src/Avalonia.Themes.Simple/Controls/ComboBox.xaml
  tests/Avalonia.Controls.UnitTests/ComboBoxTests.cs
Labels: feature, api-approved

#19383 WeakEvent subscription management thread race condition fix
  src/Avalonia.Base/Utilities/WeakEvent.cs
  src/Avalonia.Controls/Utils/CollectionChangedEventManager.cs
Labels: bug, backport-candidate-11.3.x

#19241 Removed all nullability overrides from `TimePickerPresenter` and `DatePickerPresenter`
  src/Avalonia.Controls/DateTimePickers/DatePickerPresenter.cs
  src/Avalonia.Controls/DateTimePickers/TimePickerPresenter.cs
Labels: bug, backport-candidate-11.3.x

#19440 Fix Android duplicated pointer events
  src/Android/Avalonia.Android/Platform/SkiaPlatform/TopLevelImpl.cs
Labels: bug, regression, os-android, backported-11.3.x

#19196 Improved NuGet package creation docs.
  docs/build.md
  docs/index.md
  docs/nuget.md
Labels: area-infrastructure

#19460 Fix SplitView incorrectly closing when the user changes DisplayMode to inline when IsPaneOpen is already true
  src/Avalonia.Controls/SplitView/SplitView.cs
  tests/Avalonia.Controls.UnitTests/SplitViewTests.cs
Labels: bug, backport-candidate-11.3.x

#19455 Text API sample app
  Avalonia.Desktop.slnf
  Avalonia.sln
  samples/TextTestApp/App.axaml
  samples/TextTestApp/App.axaml.cs
  samples/TextTestApp/GridRow.cs
  samples/TextTestApp/InteractiveLineControl.cs
  samples/TextTestApp/MainWindow.axaml
  samples/TextTestApp/MainWindow.axaml.cs
  samples/TextTestApp/Program.cs
  samples/TextTestApp/SelectionAdorner.cs
  samples/TextTestApp/TextTestApp.csproj
  samples/TextTestApp/app.manifest
  src/Avalonia.Base/Media/CharacterHit.cs
  src/Avalonia.Base/Media/TextFormatting/GenericTextParagraphProperties.cs
  src/Avalonia.Base/Media/TextFormatting/TextParagraphProperties.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextFormatterTests.cs
  tests/Avalonia.Skia.UnitTests/Media/TextFormatting/TextLayoutTests.cs
Labels: enhancement

#19226 Add Window.IsDialog Property
  src/Avalonia.Controls/Window.cs
Labels: feature, api-approved, backport-candidate-11.3.x

#19461 Increase RemoteProtocolTests timeout
  tests/Avalonia.DesignerSupport.Tests/RemoteProtocolTests.cs
Labels: enhancement, area-infrastructure

#19163 Capture ExecutionContext for Dispatcher.InvokeAsync
  src/Avalonia.Base/Threading/CulturePreservingExecutionContext.cs
  src/Avalonia.Base/Threading/DispatcherOperation.cs
  tests/Avalonia.Base.UnitTests/DispatcherTests.cs
Labels: enhancement

#19445 Remove non implemented message AvnView.resetPressedMouseButtons
  native/Avalonia.Native/src/OSX/AvnView.h
  native/Avalonia.Native/src/OSX/WindowBaseImpl.mm
Labels: bug, os-macos, backport-candidate-11.3.x

#19447 Fix macOS thick titlebar mouse event duplication
  native/Avalonia.Native/src/OSX/AvnWindow.mm
  samples/IntegrationTestApp/ShowWindowTest.axaml
  samples/IntegrationTestApp/ShowWindowTest.axaml.cs
  tests/Avalonia.IntegrationTests.Appium/ElementExtensions.cs
  tests/Avalonia.IntegrationTests.Appium/PointerTests_MacOS.cs
Labels: bug, os-macos, regression, backport-candidate-11.3.x

#19477 Fix validation error not being cleared on valid input
  src/Avalonia.Base/Data/Core/BindingExpression.cs
  tests/Avalonia.Base.UnitTests/Data/Core/BindingExpressionTests.DataValidation.cs
Labels: bug, backport-candidate-11.3.x

#19474 Fix: RelativePanel calculation error with extensible and aligned child
  src/Avalonia.Controls/RelativePanel.cs
  tests/Avalonia.Markup.Xaml.UnitTests/Xaml/RelativePanelTests.cs
Labels: bug, backport-candidate-11.3.x

#19526 Update Brush.Parse() to Handle all Color Formats
  samples/ControlCatalog/Pages/BorderPage.xaml
  src/Avalonia.Base/Media/Brush.cs
  src/Avalonia.Base/Media/KnownColors.cs
  tests/Avalonia.Base.UnitTests/Media/BrushTests.cs
Labels: enhancement, backport-candidate-11.3.x

#19529 Update Nuke to v9 and fix ValidateApiDiff
  .nuke/build.schema.json
  nukebuild/ApiDiffHelper.cs
  nukebuild/Build.cs
  nukebuild/BuildParameters.cs
  nukebuild/BuildTasksPatcher.cs
  nukebuild/_build.csproj
Labels: bug, area-infrastructure

#19540 Fix selected files filename
  src/Avalonia.Dialogs/Internal/ManagedFileChooserViewModel.cs
Labels: bug, backport-candidate-11.3.x

#19544 Fix BringDescendantIntoView with respect to margins
  src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs
  tests/Avalonia.Controls.UnitTests/Presenters/ScrollContentPresenterTests.cs
  tests/Avalonia.Controls.UnitTests/VirtualizingStackPanelTests.cs
Labels: bug, backport-candidate-11.3.x

#19558 Fixes duplicate class property registration
  src/Avalonia.Base/ClassBindingManager.cs
  tests/Avalonia.Base.UnitTests/ClassBindingManagerTests.cs
Labels: bug, area-bindings, backport-candidate-11.3.x

#19493 Font features in test app
  samples/TextTestApp/FontFeatureCollectionConverter.cs
  samples/TextTestApp/InteractiveLineControl.cs
  samples/TextTestApp/MainWindow.axaml
  samples/TextTestApp/Program.cs
  src/Avalonia.Base/Media/FontFeatureCollection.cs
Labels: enhancement, api-approved
